// libs/vue/draggable/src/components/draggable/item-sidebar.vue
<script lang="ts">
export default {
  name: 'DraggableItemSideBar',
};
</script>
<script setup lang="ts">
import { inject, ref, Ref } from 'vue';
import {
  useInitAction,
  useShow,
  withExpandEmit,
  withShareComponent,
  withShareProps,
  withShowEmit,
  withShowProps,
} from '../../hook';
import { useInitSidebar } from '../../hook/useInitSidebar';
import { LocationSideBar } from '../../types';
import SidebarModule from './sidebar/sidebar-module.vue';
const props = defineProps({
  ...withShowProps,
  ...withShareComponent,
  ...withShareProps,
  componentMapSidebarToggle: { type: [String, Object] },
  width: { type: [Number, String], default: 'auto' },
  right: Boolean,
  location: { type: [String] },
});
const emit = defineEmits({ ...withShowEmit, ...withExpandEmit });
const containerId = inject<Ref<string>>(
  'containerId',
  ref(props.containerId || ''),
);
if (!containerId.value) {
  throw 'Not set container id';
}
const { show, open, close } = useShow(props, emit);
const c_location =
  props.location != null
    ? (props.location as LocationSideBar)
    : props.right
      ? 'right'
      : 'left';
const { location, itemId } = useInitSidebar(containerId.value, show, {
  title: props.title,
  type: 'item-sidebar',
  location: c_location,
});
useInitAction(containerId.value, itemId.value, {
  open,
  close,
});
</script>

<template>
  <SidebarModule
    :container-id="containerId"
    :location="location"
    :item-id="itemId"
  >
    <template #title>
      <slot name="title">
        {{ title }}
      </slot>
    </template>
    <slot></slot>
  </SidebarModule>
</template>

// libs/react/draggable/src/components/draggable/item-sidebar.tsx
import { ComponentType, ReactNode } from 'react';
import { useContainerId } from '../../context/ContainerContext';
import { useInitAction, useInitSidebar, useShow } from '../../hook';
import { LocationSideBar } from '../../types';
import { SidebarModule } from './sidebar/sidebar-module';

export interface DraggableItemSideBarProps {
  show?: boolean;
  title?: string;
  containerId?: string;
  componentCard?: ComponentType<any>;
  componentCardHeader?: ComponentType<any>;
  componentMapSidebarToggle?: ComponentType<any>;
  width?: number | string;
  right?: boolean;
  location?: LocationSideBar;
  onUpdateShow?: (value: boolean) => void;
  onClose?: () => void;
  children?: ReactNode;
}

export function DraggableItemSideBar({
  show: propShow,
  title = '',
  containerId: propContainerId,
  componentCard,
  componentCardHeader,
  componentMapSidebarToggle,
  width = 'auto',
  right = false,
  location: propLocation,
  onUpdateShow,
  onClose,
  children,
}: DraggableItemSideBarProps) {
  const containerId = useContainerId(propContainerId);
  const { show, setShow, open, close } = useShow(
    { show: propShow },
    {
      'update:show': onUpdateShow,
      close: onClose,
    },
  );
  const c_location =
    propLocation != null ? propLocation : right ? 'right' : 'left';
  const { location, itemId } = useInitSidebar(containerId, show, setShow, {
    title,
    type: 'item-sidebar',
    location: c_location,
  });
  useInitAction(containerId, itemId, {
    open,
    close,
  });

  return (
    <SidebarModule
      containerId={containerId}
      location={location}
      itemId={itemId}
      title={title}
    >
      {children}
    </SidebarModule>
  );
}
