// libs/draggable/src/components/draggable/item-float.vue
<script lang="ts">
export default {
  name: 'DraggableItemFloat',
};
</script>
<script setup lang="ts">
import { computed, inject, ref, Ref, StyleValue } from 'vue';
import {
  useComponent,
  useContainerOrder,
  useExpand,
  useHighlight,
  useIcon,
  useInitAction,
  useInitItem,
  useShow,
  withExpandEmit,
  withExpandProps,
  withShareProps,
  withShowEmit,
  withShowProps,
} from '../../hook';
import MapButton from '../parts/MapButton.vue';
const { CloseIcon, ToBackIcon, ToFrontIcon, ExpandedIcon, CloseExpandedIcon } =
  useIcon();
const props = defineProps({
  ...withShowProps,
  ...withExpandProps,
  ...withShareProps,
  top: { type: Number, default: undefined },
  left: { type: Number, default: undefined },
  bottom: { type: Number, default: undefined },
  right: { type: Number, default: undefined },
  width: { type: [Number, String], default: 'auto' },
  maxHeight: { type: Number, default: 500 },
  headerLocation: {
    type: String,
    default: 'top',
    validator: function (value: string) {
      // The value must match one of these strings
      return ['top', 'bottom'].includes(value);
    },
  },
});
const emit = defineEmits({ ...withShowEmit, ...withExpandEmit });
const containerId = inject<Ref<string>>(
  'containerId',
  ref(props.containerId || ''),
);
if (!containerId.value) {
  throw 'Not set container id';
}
const { show, open, close } = useShow(props, emit);
const { zIndex, itemId } = useInitItem(containerId.value, show, {
  title: props.title,
  type: 'item-float',
});
const { isHighlight, setHighLight } = useHighlight();
useInitAction(containerId.value, itemId.value, {
  setHighLight,
  open,
  close,
});
const { isLast, isFirst, isHasItems, onToBack, onToFront } = useContainerOrder(
  containerId.value,
  itemId.value,
);
const { expand, toggle: onToggleExpand } = useExpand(props, emit, true);
const { componentCard, componentCardHeader } = useComponent({
  ...props,
  containerId: containerId.value,
});
function onClose() {
  show.value = false;
}
const c_style = computed(() => {
  let style: StyleValue = {};
  style.zIndex = zIndex.value;
  if (props.top) {
    style.top = props.top + 'px';
  }
  if (props.left) {
    style.left = props.left + 'px';
  }
  if (props.right) {
    style.right = props.right + 'px';
  }
  if (props.bottom) {
    style.bottom = props.bottom + 'px';
  }
  if (props.width && props.width != 'auto') {
    if (props.width && !isNaN(+props.width)) style.width = props.width + 'px';
    else {
      style.width = props.width;
    }
  }
  return style;
});
const c_styleContent = computed(() => {
  let style: StyleValue = {};
  style.maxHeight = props.maxHeight + 'px';
  return style;
});
const isAutoWidth = computed(() => {
  return !props.width || props.width == 'auto';
});
</script>

<template>
  <div
    class="float-container"
    v-if="show"
    :class="{
      'auto-float-container': isAutoWidth,
    }"
    :style="c_style"
  >
    <component :is="componentCard" :highlight="isHighlight">
      <div class="draggable-float">
        <template v-if="!disabledHeader && headerLocation === 'top'">
          <component :is="componentCardHeader">
            <template #title>
              <slot name="title">
                {{ title }}
              </slot>
            </template>

            <template #extra-btn>
              <slot name="extra-btn"></slot>

              <map-button @click="onToggleExpand">
                <ExpandedIcon v-if="expand" :size="16" />
                <CloseExpandedIcon v-else :size="16" />
              </map-button>
              <template v-if="isHasItems && !disabledOrder">
                <map-button :disabled="isFirst" @click="onToBack()">
                  <ToBackIcon :size="16" />
                </map-button>
                <map-button :disabled="isLast" @click="onToFront()">
                  <ToFrontIcon :size="16" />
                </map-button>
              </template>
              <map-button v-if="!disabledClose" @click="onClose">
                <CloseIcon :size="16" />
              </map-button>
            </template>
          </component>
        </template>
        <div
          class="draggable-float-content"
          v-show="expand"
          :style="c_styleContent"
        >
          <slot></slot>
        </div>
        <template v-if="!disabledHeader && headerLocation === 'bottom'">
          <component :is="componentCardHeader">
            <template #title>
              <slot name="title">
                {{ title }}
              </slot>
            </template>

            <template #extra-btn>
              <slot name="extra-btn"></slot>
              <map-button @click="onToggleExpand">
                <ExpandedIcon v-if="expand" :size="16" />
                <CloseExpandedIcon v-else :size="16" />
              </map-button>
              <template v-if="isHasItems && !disabledOrder">
                <map-button :disabled="isFirst" @click="onToBack()">
                  <ToBackIcon :size="16" />
                </map-button>
                <map-button :disabled="isLast" @click="onToFront()">
                  <ToFrontIcon :size="16" />
                </map-button>
              </template>
              <map-button v-if="!disabledClose" @click="onClose">
                <CloseIcon :size="16" />
              </map-button>
            </template>
          </component>
        </template>
      </div>
    </component>
  </div>
</template>

<style scoped>
.draggable-float .map-divider {
  flex-grow: 0;
}

.draggable-float .map-spacer {
  flex-grow: 1;
}

.draggable-float {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
}

.draggable-float-content {
  flex-grow: 1;
  overflow: auto;
}
</style>

<style scoped lang="scss">
.float-container {
  position: absolute;
  pointer-events: all;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.float-container > .float-container--content {
  display: none;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.float-container > .float-container--content {
  display: block;
}

.float-container {
  transition: all 0.2s ease;
}
</style>

<style scoped lang="scss">
@media only screen and (max-width: 600px) {
  .auto-float-container {
    width: 100%;
  }
}

@media only screen and (min-width: 600px) and (max-width: 1264px) {
  .auto-float-container {
    width: 320px;
  }
}

@media only screen and (min-width: 1264px) {
  .auto-float-container {
    width: 400px;
  }
}
</style>

// libs/react/draggable/src/components/draggable/item-float.tsx
import {
  ComponentType,
  CSSProperties,
  ReactNode,
  useMemo,
} from 'react';
import { useContainerId } from '../../context/ContainerContext';
import {
  useComponent,
  useContainerOrder,
  useExpand,
  useHighlight,
  useIcon,
  useInitAction,
  useInitItem,
  useShow,
} from '../../hook';
import { MapButton } from '../parts/MapButton';
import './item-float.css';

export interface DraggableItemFloatProps {
  show?: boolean;
  expand?: boolean;
  title?: string;
  containerId?: string;
  componentCard?: ComponentType<any>;
  componentCardHeader?: ComponentType<any>;
  disabledExpand?: boolean;
  disabledHeader?: boolean;
  disabledClose?: boolean;
  disabledOrder?: boolean;
  top?: number;
  left?: number;
  bottom?: number;
  right?: number;
  width?: number | string;
  maxHeight?: number;
  headerLocation?: 'top' | 'bottom';
  onUpdateShow?: (value: boolean) => void;
  onClose?: () => void;
  onUpdateExpand?: (value: boolean) => void;
  children?: ReactNode;
  extraBtn?: ReactNode;
}

export function DraggableItemFloat({
  show: propShow,
  expand: propExpand,
  title = '',
  containerId: propContainerId,
  componentCard,
  componentCardHeader,
  disabledExpand,
  disabledHeader,
  disabledClose,
  disabledOrder,
  top,
  left,
  bottom,
  right,
  width = 'auto',
  maxHeight = 500,
  headerLocation = 'top',
  onUpdateShow,
  onClose,
  onUpdateExpand,
  children,
  extraBtn,
}: DraggableItemFloatProps) {
  const containerId = useContainerId(propContainerId);
  const { show, setShow, open, close } = useShow(
    { show: propShow },
    {
      'update:show': onUpdateShow,
      close: onClose,
    },
  );
  const { zIndex, itemId } = useInitItem(containerId, show, setShow, {
    title,
    type: 'item-float',
  });
  const { isHighlight, setHighLight } = useHighlight();
  useInitAction(containerId, itemId, {
    setHighLight,
    open,
    close,
  });
  const { isLast, isFirst, isHasItems, onToBack, onToFront } =
    useContainerOrder(containerId, itemId);
  const { expand, toggle: onToggleExpand } = useExpand(
    { expand: propExpand },
    {
      'update:expand': onUpdateExpand,
    },
    true,
  );
  const { componentCard: Card, componentCardHeader: Header } = useComponent({
    componentCard,
    componentCardHeader,
    containerId,
  });

  const {
    CloseIcon,
    ToBackIcon,
    ToFrontIcon,
    ExpandedIcon,
    CloseExpandedIcon,
  } = useIcon();

  function handleClose() {
    setShow(false);
  }

  const style = useMemo(() => {
    const s: CSSProperties = { zIndex };
    if (top !== undefined) s.top = `${top}px`;
    if (left !== undefined) s.left = `${left}px`;
    if (right !== undefined) s.right = `${right}px`;
    if (bottom !== undefined) s.bottom = `${bottom}px`;
    if (width && width !== 'auto') {
      if (typeof width === 'number') {
        s.width = `${width}px`;
      } else {
        s.width = width;
      }
    }
    return s;
  }, [zIndex, top, left, right, bottom, width]);

  const contentStyle = useMemo(() => {
    return { maxHeight: `${maxHeight}px` };
  }, [maxHeight]);

  const isAutoWidth = !width || width == 'auto';

  if (!show) return null;

  return (
    <div
      className={`float-container ${isAutoWidth ? 'auto-float-container' : ''}`}
      style={style}
    >
      <Card highlight={isHighlight}>
        <div className="draggable-float">
          {!disabledHeader && headerLocation === 'top' && (
            <Header
              title={title}
              extraBtn={
                <>
                  {extraBtn}
                  <MapButton onClick={onToggleExpand}>
                    {expand ? (
                      <ExpandedIcon size={'16px'} />
                    ) : (
                      <CloseExpandedIcon size={'16px'} />
                    )}
                  </MapButton>
                  {isHasItems && !disabledOrder && (
                    <>
                      <MapButton disabled={isFirst} onClick={onToBack}>
                        <ToBackIcon size={'16px'} />
                      </MapButton>
                      <MapButton disabled={isLast} onClick={onToFront}>
                        <ToFrontIcon size={'16px'} />
                      </MapButton>
                    </>
                  )}
                  {!disabledClose && (
                    <MapButton onClick={handleClose}>
                      <CloseIcon size={'16px'} />
                    </MapButton>
                  )}
                </>
              }
            />
          )}
          {expand && (
            <div className="draggable-float-content" style={contentStyle}>
              {children}
            </div>
          )}
          {!disabledHeader && headerLocation === 'bottom' && (
            <Header
              title={title}
              extraBtn={
                <>
                  {extraBtn}
                  <MapButton onClick={onToggleExpand}>
                    {expand ? (
                      <ExpandedIcon size={'16px'} />
                    ) : (
                      <CloseExpandedIcon size={'16px'} />
                    )}
                  </MapButton>
                  {isHasItems && !disabledOrder && (
                    <>
                      <MapButton disabled={isFirst} onClick={onToBack}>
                        <ToBackIcon size={'16px'} />
                      </MapButton>
                      <MapButton disabled={isLast} onClick={onToFront}>
                        <ToFrontIcon size={'16px'} />
                      </MapButton>
                    </>
                  )}
                  {!disabledClose && (
                    <MapButton onClick={handleClose}>
                      <CloseIcon size={'16px'} />
                    </MapButton>
                  )}
                </>
              }
            />
          )}
        </div>
      </Card>
    </div>
  );
}
