// libs/react/draggable/src/components/draggable/draggable-container.tsx
import { getUUIDv4 } from '@hungpvq/shared';
import debounce from 'lodash/debounce';
import {
  CSSProperties,
  ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { ContainerProvider } from '../../context/ContainerContext';
import { useDragContainer, useDragStore } from '../../store';
import { useStoreReactive } from '../../store/useStoreReactive';
import { SidebarContainer } from './sidebar/sidebar-container';
import { BottomContainer } from './bottom/bottom-container';

type ResultShow = {
  sidebar?: {
    leftCount: number;
    rightCount: number;
  };
  [key: string]: number | Record<string, number> | undefined;
};

export interface DraggableContainerProps {
  containerId?: string;
  className?: string;
  mobileBreakpoint?: number;
  /** `plain` drops map-heavy card chrome (transparent/inherit). */
  variant?: 'default' | 'plain';
  children?: ReactNode;
  onInit?: (id: string) => void;
  onDestroy?: (id: string) => void;
  onChangeShow?: (options: { show: ResultShow; idsShow: string[] }) => void;
}

export function DraggableContainer({
  containerId: propContainerId,
  className,
  mobileBreakpoint = 600,
  variant = 'default',
  children,
  onInit,
  onDestroy,
  onChangeShow,
}: DraggableContainerProps) {
  const boxRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const [containerId] = useState(
    propContainerId || `draggable-container-${getUUIDv4()}`,
  );
  const [initDone, setInitDone] = useState(false);
  const store = useDragContainer(containerId);
  const storeRef = useRef(store);
  storeRef.current = store;
  const onInitRef = useRef(onInit);
  onInitRef.current = onInit;
  const onDestroyRef = useRef(onDestroy);
  onDestroyRef.current = onDestroy;
  const onChangeShowRef = useRef(onChangeShow);
  onChangeShowRef.current = onChangeShow;
  const mobileBreakpointRef = useRef(mobileBreakpoint);
  mobileBreakpointRef.current = mobileBreakpoint;

  useStoreReactive();
  const dragStore = useDragStore();
  const drawer = dragStore.container[containerId]?.drawer;
  const itemShows = store.getItemShows();

  const drawerStyle = useMemo(() => {
    const style: CSSProperties & Record<string, string> = {
      '--drawer-left-size': `${drawer?.left.size || 0}px`,
      '--drawer-right-size': `${drawer?.right.size || 0}px`,
      '--drawer-top-size': `${drawer?.top.size || 0}px`,
      '--drawer-bottom-size': `${drawer?.bottom.size || 0}px`,
    };
    return style;
  }, [
    drawer?.left.size,
    drawer?.right.size,
    drawer?.top.size,
    drawer?.bottom.size,
  ]);

  const onResize = useCallback(() => {
    const clientWidth = boxRef.current?.clientWidth || 0;
    const layoutWidth = rootRef.current?.clientWidth || clientWidth;
    storeRef.current.setParentProps({
      width: clientWidth,
      height: boxRef.current?.clientHeight || 0,
      isMobile: layoutWidth < mobileBreakpointRef.current,
    });
  }, []);

  const handleResize = useMemo(
    () =>
      debounce(() => {
        onResize();
      }, 200),
    [onResize],
  );

  useEffect(() => {
    const options = itemShows;
    const show = options.reduce<ResultShow>((acc, id) => {
      const item = storeRef.current.getItemAction(id);
      if (!item?.type) return acc;
      const baseType = item.type.replace(/^item-/, '');

      if ('location' in item && typeof item.location === 'string') {
        const key = `${item.location}Count`;
        const group =
          (acc[baseType] as Record<string, number> | undefined) ?? {};
        group[key] = (group[key] || 0) + 1;
        acc[baseType] = group;
      } else {
        const key = `${baseType}Count`;
        acc[key] = ((acc[key] as number | undefined) || 0) + 1;
      }

      return acc;
    }, {});
    onChangeShowRef.current?.({ show, idsShow: options });
  }, [itemShows]);

  useEffect(() => {
    const box = boxRef.current;
    const root = rootRef.current;
    storeRef.current.initContainer();
    window.addEventListener('resize', onResize);
    onResize();

    let observer: ResizeObserver | null = null;
    if (typeof ResizeObserver !== 'undefined') {
      observer = new ResizeObserver(() => {
        handleResize();
      });
      if (root) observer.observe(root);
      if (box) observer.observe(box);
    }

    setInitDone(true);
    onInitRef.current?.(containerId);

    return () => {
      storeRef.current.removeContainer();
      window.removeEventListener('resize', onResize);
      onDestroyRef.current?.(containerId);
      handleResize.cancel();
      observer?.disconnect();
    };
  }, [containerId, handleResize, onResize]);

  useEffect(() => {
    onResize();
  }, [mobileBreakpoint, onResize]);

  return (
    <ContainerProvider containerId={containerId}>
      <div
        ref={rootRef}
        className={[
          'draggable-root',
          variant === 'plain' ? 'draggable-variant-plain' : '',
          className,
        ]
          .filter(Boolean)
          .join(' ')}
        style={drawerStyle}
      >
        <div
          className="drawer-slot drawer-slot-top"
          id={`drawer-top-${containerId}`}
        />
        <div
          className="drawer-slot drawer-slot-left"
          id={`drawer-left-${containerId}`}
        />
        <div className="draggable-container" ref={boxRef} id={containerId}>
          {initDone && (
            <>
              <SidebarContainer location="left" />
              <SidebarContainer location="right" />
              <SidebarContainer location="top" />
              <SidebarContainer location="bottom" />
              <BottomContainer />
              {children}
            </>
          )}
        </div>
        <div
          className="drawer-slot drawer-slot-right"
          id={`drawer-right-${containerId}`}
        />
        <div
          className="drawer-slot drawer-slot-bottom"
          id={`drawer-bottom-${containerId}`}
        />
        <div
          className="draggable-modal-layer"
          id={`modal-layer-${containerId}`}
        />
      </div>
    </ContainerProvider>
  );
}

// libs/draggable/src/components/draggable/draggable-container.vue
<script setup lang="ts">
import { getUUIDv4 } from '@hungpvq/shared';
import { debounce } from 'lodash';
import { nextTick, onMounted, onUnmounted, provide, ref, watch } from 'vue';
import { useDragContainer } from '../../store';
import SidebarContainer from './sidebar/sidebar-container.vue';
type ResultShow = {
  sidebar?: {
    leftCount: number;
    rightCount: number;
  };
  [key: string]: any;
};

const emit = defineEmits({
  init: (id: string) => {
    return true;
  },
  destroy: (id: string) => {
    return true;
  },
  changeShow: (options: { show: ResultShow; idsShow: string[] }) => {
    return true;
  },
});
const box = ref<HTMLDivElement>();
const { containerId } = defineProps<{ containerId?: string }>();
const p_container_id = ref(containerId || `draggable-container-${getUUIDv4()}`);
const init_done = ref(false);
const store = useDragContainer(p_container_id.value);
let resizeObserver: any;

const handleResize = debounce(() => {
  nextTick(() => {
    onResize();
  });
}, 200);
watch(
  () => store.getItemShows(),
  (options) => {
    const show = options.reduce<ResultShow>((acc, id) => {
      const item = store.getItemAction(id);
      // Bỏ tiền tố 'item-'
      const baseType = item.type.replace(/^item-/, '');

      // Nếu có location → gom theo leftCount/rightCount
      if ('location' in item && typeof item.location === 'string') {
        const key = `${item.location}Count`;

        // Khởi tạo nếu chưa có
        acc[baseType] ??= {};
        acc[baseType][key] = (acc[baseType][key] || 0) + 1;
      } else {
        const key = `${baseType}Count`;
        acc[key] = (acc[key] || 0) + 1;
      }

      return acc;
    }, {});
    emit('changeShow', { show, idsShow: options });
  },
  { deep: true },
);

onMounted(() => {
  store.initContainer();
  window.addEventListener('resize', onResize);
  nextTick(() => {
    onResize();
    init_done.value = true;
    emit('init', p_container_id.value);
  });
  if (box.value) {
    resizeObserver = new ResizeObserver(() => {
      handleResize();
    });
    resizeObserver.observe(box.value);
  }
});
onUnmounted(() => {
  store.removeContainer();
  window.removeEventListener('resize', onResize);
  emit('destroy', p_container_id.value);
  if (resizeObserver && box.value) {
    resizeObserver.unobserve(box.value);
    resizeObserver.disconnect();
  }
});
provide('containerId', p_container_id);
function onResize() {
  const clientWidth = box.value?.clientWidth || 0;
  store.setParentProps({
    width: clientWidth,
    height: box.value?.clientHeight || 0,
    isMobile: clientWidth < 600,
  });
}
</script>

<template>
  <div class="draggable-container" ref="box" :id="containerId">
    <template v-if="p_container_id && init_done">
      <SidebarContainer location="left" />
      <SidebarContainer location="right" />
      <SidebarContainer location="top" />
      <SidebarContainer location="bottom" />
    </template>
    <slot v-if="p_container_id && init_done" :containerId="containerId" />
  </div>
</template>

<style scoped>
.draggable-container {
  height: 100%;
  width: 100%;
  position: relative;
}
</style>
<style>
@import 'vue-draggable-resizable/style.css';
.map-divider {
  margin: 0;
  display: block;
  flex: 1 1 0px;
  max-width: 100%;
  height: 0px;
  max-height: 0px;
  border: solid;
  border-width: thin 0 0 0;
  transition: inherit;
  border-color: #fff;
  opacity: 0.3;
}
:root {
  --card-background-color: rgba(32, 43, 54, 0.9);
  --card-color: #fff;
}
</style>
