// libs/react/map-core/src/modules/GotoControl/GotoControl.tsx
import {
  applyGotoSetting,
  type GotoSetting,
  gotoSettingFromCoordinateText,
  readGotoSetting,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiMapMarkerOutline } from '@mdi/js';
import { useEffect, useState } from 'react';

import { MapControlButton } from '../../components/MapControlButton';
import { useLang } from '../../extra/lang/hook';
import { useMapControl } from '../../extra/registry/useMapControl';
import { InputText } from '../../field';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import { useShow } from '../../hooks/useShow';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

export interface GotoControlProps extends WithMapPropType {
  show?: boolean;
}

export function GotoControl(props: GotoControlProps) {
  const mergedProps = { ...defaultMapProps, ...props };
  const { callMap, mapId, order } = useMap(mergedProps);
  const { trans } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);
  const [setting, setSetting] = useState<GotoSetting>({ center: [0, 0] });

  function loadCurrentView() {
    callMap((map) => {
      setSetting(readGotoSetting(map));
    });
  }

  function handleToggle() {
    const nextShow = !show;
    toggleShow(nextShow);
    if (nextShow) {
      loadCurrentView();
    }
  }

  function onSetSetting() {
    callMap((map) => {
      applyGotoSetting(map, setting);
    });
  }

  async function onPasteCoordinates() {
    try {
      const text = await navigator.clipboard?.readText?.();
      const partial = gotoSettingFromCoordinateText(text || '');
      if (!partial) return;
      setSetting((prev) => ({ ...prev, ...partial }));
    } catch {
      // Clipboard permission denied — ignore.
    }
  }

  const { moduleContainerProps, panelBind, control } = useMapControl(mapId, {
    id: 'mapGotoControl',
    panelKind: 'popup',
    title: trans('map.goto-control.title'),
    from: mergedProps,
    order,
    show,
    setShow: toggleShow,
    actions: [{ type: 'mapGotoControl', run: () => handleToggle() }],
    getButtonState: () =>
      mdiButtonState(mdiMapMarkerOutline, {
        visible: true,
        active: show,
        title: trans('map.goto-control.title'),
        order,
      }),
    onClick: () => handleToggle(),
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => toggleShow(!!v)}
            title={trans('map.goto-control.title')}
            height={300}
            width={400}
            {...bind}
            {...panelBind}
          >
            <div className="map-goto-control">
              <div className="map-goto-control__fields">
                <div>
                  <label className="map-goto-control__center-label">
                    {trans('map.goto-control.field.center')}
                  </label>
                  <div className="map-goto-control__center">
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[0])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [Number(v), prev.center[1]],
                        }))
                      }
                    />
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[1])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [prev.center[0], Number(v)],
                        }))
                      }
                    />
                  </div>
                </div>
                <div>
                  <InputText
                    label={trans('map.goto-control.field.zoom')}
                    type="number"
                    min={0}
                    max={24}
                    value={setting.zoom != null ? String(setting.zoom) : ''}
                    onChange={(v) =>
                      setSetting((prev) => ({
                        ...prev,
                        zoom: v === '' ? undefined : Number(v),
                      }))
                    }
                  />
                </div>
              </div>
              <div className="map-goto-control__actions">
                <MapControlButton
                  onClick={() => void onPasteCoordinates()}
                  variant="outlined"
                >
                  {trans('map.goto-control.btn.paste')}
                </MapControlButton>
                <MapControlButton
                  className="map-goto-control__btn"
                  onClick={onSetSetting}
                  variant="filled"
                >
                  {trans('map.goto-control.btn.apply')}
                </MapControlButton>
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

// libs/vue/map-core/src/modules/GotoControl/GotoControl.vue
<script setup lang="ts">
import {
  applyGotoSetting,
  type GotoSetting,
  gotoSettingFromCoordinateText,
  readGotoSetting,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { mdiMapMarkerOutline } from '@mdi/js';
import { ref, watch } from 'vue';

import MapControlButton from '../../components/MapControlButton.vue';
import { useLang } from '../../extra/lang/hook';
import { useMapControl } from '../../extra/registry/useMapControl';
import { InputText } from '../../field';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import { useShow, WithShowProps } from '../../hooks/useShow';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const [show, setShow] = useShow(props.show);
const { callMap, mapId, order } = useMap(props);
const { trans } = useLang(mapId.value);
function onToggleShow() {
  setShow(!show.value);
  if (show.value) {
    callMap((_map) => {
      setting.value = readGotoSetting(_map);
    });
  }
}
const setting = ref<GotoSetting>({ center: [0, 0] });
const onSetSetting = () => {
  callMap((map) => {
    applyGotoSetting(map, setting.value);
  });
};
async function onPasteCoordinates() {
  try {
    const text = await navigator.clipboard?.readText?.();
    const partial = gotoSettingFromCoordinateText(text || '');
    if (!partial) return;
    setting.value = { ...setting.value, ...partial };
  } catch {
    // Clipboard permission denied — ignore.
  }
}
const { moduleContainerProps, panelBind, control } = useMapControl(mapId, {
  id: 'mapGotoControl',
  panelKind: 'popup',
  title: () => trans.value('map.goto-control.title'),
  from: props,
  order,
  show,
  setShow,
  actions: [
    {
      type: 'mapGotoControl',
      run: () => onToggleShow(),
    },
  ],
  getButtonState() {
    return mdiButtonState(mdiMapMarkerOutline, {
      visible: true,
      active: show.value,
      title: trans.value('map.goto-control.title'),
      order: order.value,
    });
  },
  onClick() {
    onToggleShow();
  },
});
watch(show, () => control?.sync());
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="slotProps">
      <DraggableItemPopup
        v-if="show"
        :height="300"
        :width="400"
        v-bind="{ ...slotProps, ...panelBind }"
        v-model:show="show"
        :title="trans('map.goto-control.title')"
      >
        <div class="map-goto-control">
          <div class="map-goto-control__fields">
            <div>
              <label class="map-goto-control__center-label">
                {{ trans('map.goto-control.field.center') }}
              </label>
              <div class="map-goto-control__center">
                <InputText
                  v-model="setting.center[0]"
                  type="number"
                  step="0.0000001"
                />
                <InputText
                  v-model="setting.center[1]"
                  type="number"
                  step="0.0000001"
                />
              </div>
            </div>
            <div>
              <InputText
                :label="trans('map.goto-control.field.zoom')"
                v-model="setting.zoom"
                type="number"
                min="0"
                max="24"
              />
            </div>
          </div>

          <div class="map-goto-control__actions">
            <map-control-button
              @click="onPasteCoordinates()"
              variant="outlined"
            >
              {{ trans('map.goto-control.btn.paste') }}
            </map-control-button>
            <map-control-button
              class="map-goto-control__btn"
              @click="onSetSetting()"
              variant="filled"
            >
              {{ trans('map.goto-control.btn.apply') }}
            </map-control-button>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>
