// libs/vue/map-dataset/src/modules/CreateControl/config/archive-settings.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-6">
      <input-text
        v-model="form.minzoom"
        :label="trans('map.layer-control.field.minzoom')"
      />
    </div>
    <div class="map-col-6">
      <input-text
        v-model="form.maxzoom"
        :label="trans('map.layer-control.field.maxzoom')"
      />
    </div>

    <template v-if="form.bounds">
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[0]"
          :label="trans('map.layer-control.field.bound.minx')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[1]"
          :label="trans('map.layer-control.field.bound.miny')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[2]"
          :label="trans('map.layer-control.field.bound.maxx')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[3]"
          :label="trans('map.layer-control.field.bound.maxy')"
        />
      </div>
    </template>

    <SourceLayerOptions
      v-if="form.tileKind === 'vector'"
      :options="options"
      @update:options="onOptions"
    />
  </div>
</template>

<script setup>
import { useLang, useMap } from '@hungpvq/vue-map-core';
import { InputText } from '@hungpvq/vue-map-core/fields';
import { computed } from 'vue';
import SourceLayerOptions from './source-layer-options.vue';

const form = defineModel();
const { mapId } = useMap();
const { trans } = useLang(mapId.value);

const options = computed(() =>
  Array.isArray(form.value?.sourceLayerOptions)
    ? form.value.sourceLayerOptions
    : [],
);

function onOptions(next) {
  form.value.sourceLayerOptions = next;
}
</script>

// libs/react/map-dataset/src/modules/CreateControl/config/archive-settings.tsx
import { InputText } from '@hungpvq/react-map-core/fields';
import {
  SourceLayerOptionsList,
  type SourceLayerOptionRow,
} from './source-layer-options';
import type { CreateConfigFormProps } from './types';

/** Archive (MBTiles/PMTiles/TileJSON) settings: zoom, bounds, source-layers. */
export function ConfigArchiveSettings({
  config,
  onChange,
  trans,
}: CreateConfigFormProps) {
  const bounds =
    (config.bounds as number[]) || [-180, -85.051129, 180, 85.051129];
  const options = Array.isArray(config.sourceLayerOptions)
    ? (config.sourceLayerOptions as SourceLayerOptionRow[])
    : [];

  return (
    <div className="map-row create-control-settings">
      <div className="map-col-6">
        <InputText
          label={trans('map.layer-control.field.minzoom')}
          value={String(config.minzoom ?? 0)}
          onChange={(v) => onChange({ minzoom: Number(v) })}
        />
      </div>
      <div className="map-col-6">
        <InputText
          label={trans('map.layer-control.field.maxzoom')}
          value={String(config.maxzoom ?? 22)}
          onChange={(v) => onChange({ maxzoom: Number(v) })}
        />
      </div>

      {['minx', 'miny', 'maxx', 'maxy'].map((key, i) => (
        <div key={key} className="map-col-6">
          <InputText
            label={trans(`map.layer-control.field.bound.${key}`)}
            value={String(bounds[i] ?? '')}
            onChange={(v) => {
              const next = [...bounds];
              next[i] = Number(v);
              onChange({ bounds: next });
            }}
          />
        </div>
      ))}

      {config.tileKind === 'vector' ? (
        <SourceLayerOptionsList
          options={options}
          trans={trans}
          onChange={(next) => onChange({ sourceLayerOptions: next })}
        />
      ) : null}
    </div>
  );
}
