// libs/vue/map-dataset/src/modules/CreateControl/config/DataSourceTabs.vue
<template>
  <div class="create-control-data">
    <div class="create-control-data__tabs" role="tablist">
      <button
        v-for="tab in tabs"
        :key="tab"
        type="button"
        role="tab"
        class="create-control-data__tab"
        :class="{ _active: activeTab === tab }"
        :aria-selected="activeTab === tab"
        @click="activeTab = tab"
      >
        {{ tabLabel(tab) }}
      </button>
    </div>
    <div class="create-control-data__panel" role="tabpanel">
      <slot v-if="activeTab === 'file'" name="file" />
      <slot v-if="activeTab === 'raw'" name="raw" />
      <slot v-if="activeTab === 'url'" name="url" />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CreateControlDataTab } from '@hungpvq/map-dataset/create-control';
import { CREATE_CONTROL_DEFAULT_DATA_TAB } from '@hungpvq/map-dataset/create-control';
import { useLang, useMap } from '@hungpvq/vue-map-core';
import { watch } from 'vue';

const props = defineProps<{
  tabs: CreateControlDataTab[];
}>();

const activeTab = defineModel<CreateControlDataTab>('activeTab', { required: true });

const { mapId } = useMap();
const { trans } = useLang(mapId.value);

watch(
  () => props.tabs,
  (tabs) => {
    if (!tabs.includes(activeTab.value)) {
      activeTab.value = CREATE_CONTROL_DEFAULT_DATA_TAB;
    }
  },
  { immediate: true },
);

function tabLabel(tab: CreateControlDataTab) {
  return trans.value(`map.layer-control.create.tab-${tab}`);
}
</script>

// libs/react/map-dataset/src/modules/CreateControl/config/DataSourceTabs.tsx
import type { CreateControlDataTab } from '@hungpvq/map-dataset/create-control';
import { CREATE_CONTROL_DEFAULT_DATA_TAB } from '@hungpvq/map-dataset/create-control';
import { type ReactNode, useEffect, useState } from 'react';

type DataSourceTabsProps = {
  tabs: CreateControlDataTab[];
  trans: (key: string) => string;
  activeTab?: CreateControlDataTab;
  onActiveTabChange?: (tab: CreateControlDataTab) => void;
  children: Partial<Record<CreateControlDataTab, ReactNode>>;
};

export function DataSourceTabs({
  tabs,
  trans,
  activeTab: activeTabProp,
  onActiveTabChange,
  children,
}: DataSourceTabsProps) {
  const [internalTab, setInternalTab] = useState<CreateControlDataTab>(
    CREATE_CONTROL_DEFAULT_DATA_TAB,
  );
  const activeTab = activeTabProp ?? internalTab;

  function setActiveTab(tab: CreateControlDataTab) {
    onActiveTabChange?.(tab);
    if (activeTabProp === undefined) {
      setInternalTab(tab);
    }
  }

  useEffect(() => {
    if (!tabs.includes(activeTab)) {
      setActiveTab(tabs[0] ?? CREATE_CONTROL_DEFAULT_DATA_TAB);
    }
    // Only react when tabs list changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tabs]);

  return (
    <div className="create-control-data">
      <div className="create-control-data__tabs" role="tablist">
        {tabs.map((tab) => (
          <button
            key={tab}
            type="button"
            role="tab"
            className={`create-control-data__tab${activeTab === tab ? ' _active' : ''}`}
            aria-selected={activeTab === tab}
            onClick={() => setActiveTab(tab)}
          >
            {trans(`map.layer-control.create.tab-${tab}`)}
          </button>
        ))}
      </div>
      <div className="create-control-data__panel" role="tabpanel">
        {children[activeTab]}
      </div>
    </div>
  );
}
