// libs/vue/map-dataset/src/modules/CreateControl/config/geojson-settings.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-6">
      <InputSelect
        v-model="form.type"
        :items="items_type"
        :label="trans('map.layer-control.field.style-type')"
      />
    </div>
    <div class="map-col-6">
      <div class="form-group">
        <label>{{ trans('map.layer-control.field.color') }}</label>
        <div class="input-container create-control-color">
          <input
            type="color"
            :value="form.color"
            @input="onColorChange($event.target.value)"
          />
        </div>
      </div>
    </div>
    <div class="map-col-12">
      <InputCrs
        :model-value="form.crs || '4326'"
        :label="trans('map.layer-control.field.crs')"
        :placeholder="trans('map.layer-control.field.crs-placeholder')"
        @update:model-value="onCrsChange"
      />
      <div
        v-if="crsMismatch"
        class="create-control-crs-mismatch"
        role="status"
      >
        {{ trans('map.layer-control.create.crs-mismatch') }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { getChartRandomColor } from '@hungpvq/map-core';
import { isCreateControlCrsMismatch } from '@hungpvq/map-dataset/create-control';
import { GEOJSON_STYLE_AUTO } from '@hungpvq/map-dataset/geojson';
import { useLang, useMap } from '@hungpvq/vue-map-core';
import { InputCrs, InputSelect } from '@hungpvq/vue-map-core/fields';
import { computed } from 'vue';

const form = defineModel();
const { mapId } = useMap();
const { trans } = useLang(mapId.value);

const items_type = computed(() => [
  {
    value: GEOJSON_STYLE_AUTO,
    text: trans.value('map.layer-control.field.style-type-auto'),
  },
  { value: 'point', text: 'point' },
  { value: 'line', text: 'line' },
  { value: 'area', text: 'area' },
]);

if (!form.value.crs) {
  form.value.crs = '4326';
}
if (!form.value.color) {
  form.value.color = getChartRandomColor();
}
if (!form.value.type) {
  form.value.type = 'point';
}

const crsMismatch = computed(() =>
  isCreateControlCrsMismatch(form.value.crs, form.value.detectedCrs),
);

function onCrsChange(crs) {
  form.value.crs = crs;
}

function onColorChange(color) {
  form.value.color = color;
}
</script>

// libs/react/map-dataset/src/modules/CreateControl/config/geojson-settings.tsx
import { isCreateControlCrsMismatch } from '@hungpvq/map-dataset/create-control';
import { GEOJSON_STYLE_AUTO } from '@hungpvq/map-dataset/geojson';
import { InputCrs, InputSelect } from '@hungpvq/react-map-core/fields';
import { useMemo } from 'react';

import type { CreateConfigFormProps } from './types';

/** GeoJSON layer settings — mirrors Vue `geojson-settings.vue`. */
export function GeojsonSettings({
  config,
  onChange,
  trans,
  mapId,
}: CreateConfigFormProps) {
  const styleItems = useMemo(
    () => [
      {
        value: GEOJSON_STYLE_AUTO,
        text: trans('map.layer-control.field.style-type-auto'),
      },
      { value: 'point', text: 'point' },
      { value: 'line', text: 'line' },
      { value: 'area', text: 'area' },
    ],
    [trans],
  );

  return (
    <div className="map-row create-control-settings">
      <div className="map-col-6">
        <InputSelect
          label={trans('map.layer-control.field.style-type')}
          value={String(config.type ?? 'point')}
          items={styleItems}
          onChange={(v) => onChange({ type: v })}
        />
      </div>
      <div className="map-col-6">
        <div className="form-group">
          <label>{trans('map.layer-control.field.color')}</label>
          <div className="input-container create-control-color">
            <input
              type="color"
              value={String(config.color ?? '#3498db')}
              onChange={(event) => onChange({ color: event.target.value })}
            />
          </div>
        </div>
      </div>
      <div className="map-col-12">
        <InputCrs
          mapId={mapId}
          label={trans('map.layer-control.field.crs')}
          placeholder={trans('map.layer-control.field.crs-placeholder')}
          value={String(config.crs ?? '4326')}
          onChange={(v) => onChange({ crs: v })}
        />
        {isCreateControlCrsMismatch(
          String(config.crs ?? ''),
          typeof config.detectedCrs === 'string' ? config.detectedCrs : null,
        ) ? (
          <div className="create-control-crs-mismatch" role="status">
            {trans('map.layer-control.create.crs-mismatch')}
          </div>
        ) : null}
      </div>
    </div>
  );
}
