// libs/vue/map-dataset/src/modules/CreateControl/config/mbtiles-json.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-12">
      <div
        v-if="showLoaded"
        class="create-control-loaded"
      >
        <div class="create-control-loaded__head">
          <div>
            <p class="create-control-loaded__eyebrow">
              {{
                trans(
                  createControlLoadedSourceEyebrowKey(
                    loadedSource?.kind ?? 'file',
                  ),
                )
              }}
            </p>
            <p class="create-control-loaded__title">
              {{ loadedSource?.label || form.name || 'MBTiles' }}
            </p>
            <p
              v-if="loadedSource?.detail"
              class="create-control-loaded__detail"
            >
              {{ loadedSource.detail }}
            </p>
          </div>
          <MapControlButton
            type="button"
            variant="outlined"
            @click="clearLoaded"
          >
            {{ trans('map.layer-control.create.clear-data') }}
          </MapControlButton>
        </div>
        <ul
          v-if="metaChips.length"
          class="create-control-loaded__meta"
        >
          <li
            v-for="chip in metaChips"
            :key="chip"
            class="create-control-loaded__chip"
          >
            {{ chip }}
          </li>
        </ul>
      </div>

      <template v-else>
        <div class="create-control-drop">
          <DragDropFile
            accept=".mbtiles,application/octet-stream"
            @change="onFileChange"
          />
          <div
            v-if="loadingFile"
            class="create-control-status--busy"
          >
            <span>{{ trans('map.layer-control.create.parsing') }}</span>
          </div>
        </div>
        <p class="create-control-status">
          {{ trans('map.layer-control.create.file-hint-mbtiles') }}
        </p>
        <div
          v-if="fileError"
          class="create-control-sample-error"
        >
          {{ fileError }}
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
import {
  buildCreateControlArchiveMetaChips,
  createControlLoadedSourceEyebrowKey,
  formatCreateControlBytes,
  loadCreateControlVectorTileFromFile,
} from '@hungpvq/map-dataset/create-control';
import { closeVectorTileArchive } from '@hungpvq/map-dataset/vector-tile';
import { MapControlButton, useLang, useMap } from '@hungpvq/vue-map-core';
import { DragDropFile } from '@hungpvq/vue-map-core/fields';
import { computed, ref } from 'vue';

const form = defineModel();
const loadingFile = ref(false);
const fileError = ref('');
const loadedSource = ref(null);
const { mapId } = useMap();
const { trans } = useLang(mapId.value);

const showLoaded = computed(
  () => !!form.value?.archiveId && !!loadedSource.value,
);

const metaChips = computed(() => {
  if (!form.value?.archiveId) return [];
  const chips = buildCreateControlArchiveMetaChips(form.value, {
    tileKindVector: trans.value('map.layer-control.create.tile-kind-vector'),
    tileKindRaster: trans.value('map.layer-control.create.tile-kind-raster'),
    format: trans.value('map.layer-control.create.meta-format'),
    zoom: trans.value('map.layer-control.create.meta-zoom'),
    layers: trans.value('map.layer-control.create.meta-layers'),
    bounds: trans.value('map.layer-control.create.meta-bounds'),
  });
  if (typeof loadedSource.value?.bytes === 'number') {
    chips.push(formatCreateControlBytes(loadedSource.value.bytes));
  }
  return chips;
});

async function clearLoaded() {
  const archiveId = form.value?.archiveId;
  if (archiveId) {
    try {
      await closeVectorTileArchive(archiveId);
    } catch {
      /* ignore */
    }
  }
  Object.assign(form.value, {
    url: '',
    tiles: [],
    archiveId: undefined,
    format: '',
    tileKind: 'vector',
    sourceLayer: '',
    sourceLayers: [],
    sourceLayerOptions: [],
    minzoom: 0,
    maxzoom: 22,
    bounds: [-180, -85.051129, 180, 85.051129],
  });
  loadedSource.value = null;
  fileError.value = '';
}

async function onFileChange(picked) {
  const file = Array.isArray(picked) ? picked[0] : picked;
  if (!(file instanceof File)) return;
  loadingFile.value = true;
  fileError.value = '';
  try {
    const { patch, loadedSource: next } =
      await loadCreateControlVectorTileFromFile(
        file,
        form.value.name,
        'mbtiles',
      );
    Object.assign(form.value, patch);
    loadedSource.value = next;
  } catch (err) {
    fileError.value =
      err instanceof Error
        ? err.message
        : trans.value('map.layer-control.create.parse-error');
  } finally {
    loadingFile.value = false;
  }
}
</script>

// libs/react/map-dataset/src/modules/CreateControl/config/mbtiles-json.tsx
import {
  buildCreateControlArchiveMetaChips,
  createControlLoadedSourceEyebrowKey,
  formatCreateControlBytes,
  loadCreateControlVectorTileFromFile,
  type CreateControlLoadedSource,
} from '@hungpvq/map-dataset/create-control';
import { closeVectorTileArchive } from '@hungpvq/map-dataset/vector-tile';
import { MapControlButton } from '@hungpvq/react-map-core';
import { DragDropFile } from '@hungpvq/react-map-core/fields';
import { useState } from 'react';
import type { CreateConfigFormProps } from './types';

function archiveMetaChips(
  config: CreateConfigFormProps['config'],
  trans: CreateConfigFormProps['trans'],
  loaded: CreateControlLoadedSource | null,
) {
  if (!config.archiveId) return [];
  const chips = buildCreateControlArchiveMetaChips(
    {
      tileKind: config.tileKind as string | undefined,
      format: config.format as string | undefined,
      archiveKind: config.archiveKind as string | undefined,
      name: config.name as string | undefined,
      minzoom: config.minzoom as number | undefined,
      maxzoom: config.maxzoom as number | undefined,
      bounds: config.bounds as number[] | undefined,
      sourceLayers: config.sourceLayers as string[] | undefined,
    },
    {
      tileKindVector: trans('map.layer-control.create.tile-kind-vector'),
      tileKindRaster: trans('map.layer-control.create.tile-kind-raster'),
      format: trans('map.layer-control.create.meta-format'),
      zoom: trans('map.layer-control.create.meta-zoom'),
      layers: trans('map.layer-control.create.meta-layers'),
      bounds: trans('map.layer-control.create.meta-bounds'),
    },
  );
  if (typeof loaded?.bytes === 'number') {
    chips.push(formatCreateControlBytes(loaded.bytes));
  }
  return chips;
}

const ARCHIVE_CLEAR_PATCH = {
  url: '',
  tiles: [],
  archiveId: undefined,
  format: '',
  tileKind: 'vector',
  sourceLayer: '',
  sourceLayers: [],
  sourceLayerOptions: [],
  minzoom: 0,
  maxzoom: 22,
  bounds: [-180, -85.051129, 180, 85.051129],
};

/** MBTiles file source — mirrors Vue `mbtiles-json.vue`. */
export function ConfigMbtilesJson({
  config,
  onChange,
  trans,
}: CreateConfigFormProps) {
  const [loadingFile, setLoadingFile] = useState(false);
  const [fileError, setFileError] = useState('');
  const [loadedSource, setLoadedSource] =
    useState<CreateControlLoadedSource | null>(null);

  const showLoaded = !!config.archiveId && !!loadedSource;
  const metaChips = archiveMetaChips(config, trans, loadedSource);

  async function clearLoaded() {
    const archiveId =
      typeof config.archiveId === 'string' ? config.archiveId : '';
    if (archiveId) {
      try {
        await closeVectorTileArchive(archiveId);
      } catch {
        /* ignore */
      }
    }
    onChange(ARCHIVE_CLEAR_PATCH);
    setLoadedSource(null);
    setFileError('');
  }

  async function onFileChange(picked: File | File[]) {
    const file = Array.isArray(picked) ? picked[0] : picked;
    if (!(file instanceof File)) return;
    setLoadingFile(true);
    setFileError('');
    try {
      const { patch, loadedSource: next } =
        await loadCreateControlVectorTileFromFile(
          file,
          typeof config.name === 'string' ? config.name : '',
          'mbtiles',
        );
      onChange(patch);
      setLoadedSource(next);
    } catch (err) {
      setFileError(
        err instanceof Error
          ? err.message
          : trans('map.layer-control.create.parse-error'),
      );
    } finally {
      setLoadingFile(false);
    }
  }

  return (
    <div className="map-row create-control-settings">
      <div className="map-col-12">
        {showLoaded ? (
          <div className="create-control-loaded">
            <div className="create-control-loaded__head">
              <div>
                <p className="create-control-loaded__eyebrow">
                  {trans(
                    createControlLoadedSourceEyebrowKey(
                      loadedSource?.kind ?? 'file',
                    ),
                  )}
                </p>
                <p className="create-control-loaded__title">
                  {loadedSource?.label ||
                    (config.name as string) ||
                    'MBTiles'}
                </p>
                {loadedSource?.detail ? (
                  <p className="create-control-loaded__detail">
                    {loadedSource.detail}
                  </p>
                ) : null}
              </div>
              <MapControlButton
                type="button"
                variant="outlined"
                onClick={clearLoaded}
              >
                {trans('map.layer-control.create.clear-data')}
              </MapControlButton>
            </div>
            {metaChips.length ? (
              <ul className="create-control-loaded__meta">
                {metaChips.map((chip) => (
                  <li key={chip} className="create-control-loaded__chip">
                    {chip}
                  </li>
                ))}
              </ul>
            ) : null}
          </div>
        ) : (
          <>
            <div className="create-control-drop">
              <DragDropFile
                accept=".mbtiles,application/octet-stream"
                onChange={onFileChange}
              />
              {loadingFile ? (
                <div className="create-control-status--busy">
                  <span>{trans('map.layer-control.create.parsing')}</span>
                </div>
              ) : null}
            </div>
            <p className="create-control-status">
              {trans('map.layer-control.create.file-hint-mbtiles')}
            </p>
            {fileError ? (
              <div className="create-control-sample-error">{fileError}</div>
            ) : null}
          </>
        )}
      </div>
    </div>
  );
}
