// libs/vue/map-dataset/src/modules/CreateControl/config/xyz-json.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-12">
      <InputSelect
        :model-value="sampleId"
        :items="sampleItems"
        :label="trans('map.layer-control.create.sample')"
        @update:model-value="onSelectSample"
      />
      <InputActionRow>
        <InputText
          v-model="dataUrl"
          :label="trans('map.layer-control.field.url')"
          @update:model-value="onUrlInput"
        />
        <template #action>
          <MapControlButton
            :disabled="loadingUrl || !dataUrl.trim()"
            @click="onLoadUrl"
            variant="tonal"
          >
            {{ trans('map.layer-control.create.load') }}
          </MapControlButton>
        </template>
      </InputActionRow>
      <div
        v-if="loadingUrl"
        class="create-control-status"
      >
        {{ trans('map.layer-control.create.loading-url') }}
      </div>
      <div
        v-if="urlError"
        class="create-control-sample-error"
      >
        {{ urlError }}
      </div>
    </div>
  </div>
</template>

<script setup>
import {
  CREATE_CONTROL_SAMPLE_NONE,
  getCreateControlSamples,
  loadCreateControlVectorTileFromUrl,
  resolveCreateControlSampleIdAfterUrlEdit,
  resolveCreateControlSampleSelection,
} from '@hungpvq/map-dataset/create-control';
import { MapControlButton, useLang, useMap } from '@hungpvq/vue-map-core';
import {
  InputActionRow,
  InputSelect,
  InputText,
} from '@hungpvq/vue-map-core/fields';
import { computed, ref } from 'vue';

const form = defineModel();
const sampleId = ref('');
const dataUrl = ref('');
const loadingUrl = ref(false);
const urlError = ref('');

const { mapId } = useMap();
const { trans } = useLang(mapId.value);

const sampleItems = computed(() => [
  { value: '', text: CREATE_CONTROL_SAMPLE_NONE },
  ...getCreateControlSamples('xyz').map((item) => ({
    value: item.id,
    text: item.label,
  })),
]);

function onSelectSample(id) {
  const nextId = typeof id === 'string' ? id : '';
  sampleId.value = nextId;
  urlError.value = '';
  const url = resolveCreateControlSampleSelection('xyz', nextId);
  if (url != null) dataUrl.value = url;
}

function onUrlInput() {
  urlError.value = '';
  sampleId.value = resolveCreateControlSampleIdAfterUrlEdit(
    'xyz',
    sampleId.value,
    dataUrl.value,
  );
}

async function onLoadUrl() {
  const url = dataUrl.value.trim();
  if (!url) return;
  loadingUrl.value = true;
  urlError.value = '';
  try {
    const { patch } = await loadCreateControlVectorTileFromUrl({
      url,
      sampleId: sampleId.value,
      currentName: form.value.name,
      layerKind: 'xyz',
    });
    Object.assign(form.value, patch);
  } catch (err) {
    urlError.value =
      err instanceof Error
        ? err.message
        : trans.value('map.layer-control.create.url-error');
  } finally {
    loadingUrl.value = false;
  }
}
</script>

// libs/react/map-dataset/src/modules/CreateControl/config/xyz-json.tsx
import {
  CREATE_CONTROL_SAMPLE_NONE,
  getCreateControlSamples,
  loadCreateControlVectorTileFromUrl,
  resolveCreateControlSampleIdAfterUrlEdit,
  resolveCreateControlSampleSelection,
} from '@hungpvq/map-dataset/create-control';
import { MapControlButton } from '@hungpvq/react-map-core';
import { InputActionRow, InputSelect, InputText } from '@hungpvq/react-map-core/fields';
import { useMemo, useState } from 'react';
import type { CreateConfigFormProps } from './types';

/** XYZ URL data source — mirrors Vue `xyz-json.vue` (no data-source tabs). */
export function ConfigRasterJson({ config, onChange, trans }: CreateConfigFormProps) {
  const [sampleId, setSampleId] = useState('');
  const [dataUrl, setDataUrl] = useState('');
  const [loadingUrl, setLoadingUrl] = useState(false);
  const [urlError, setUrlError] = useState('');
  const sampleItems = useMemo(
    () => [
      { value: '', text: CREATE_CONTROL_SAMPLE_NONE },
      ...getCreateControlSamples('xyz').map((item) => ({
        value: item.id,
        text: item.label,
      })),
    ],
    [],
  );

  function onSelectSample(id: string) {
    setSampleId(id);
    setUrlError('');
    const url = resolveCreateControlSampleSelection('xyz', id);
    if (url != null) setDataUrl(url);
  }

  function onUrlInput(value: string) {
    setDataUrl(value);
    setUrlError('');
    setSampleId((current) =>
      resolveCreateControlSampleIdAfterUrlEdit('xyz', current, value),
    );
  }

  async function onLoadUrl() {
    const url = dataUrl.trim();
    if (!url) return;
    setLoadingUrl(true);
    setUrlError('');
    try {
      const { patch } = await loadCreateControlVectorTileFromUrl({
        url,
        sampleId,
        currentName: typeof config.name === 'string' ? config.name : '',
        layerKind: 'xyz',
      });
      onChange(patch);
    } catch (err) {
      setUrlError(
        err instanceof Error
          ? err.message
          : trans('map.layer-control.create.url-error'),
      );
    } finally {
      setLoadingUrl(false);
    }
  }

  return (
    <div className="map-row create-control-settings">
      <div className="map-col-12">
        <InputSelect
          label={trans('map.layer-control.create.sample')}
          value={sampleId}
          items={sampleItems}
          onChange={(v) => onSelectSample(typeof v === 'string' ? v : '')}
        />
        <InputActionRow
          action={
            <MapControlButton
              disabled={loadingUrl || !dataUrl.trim()}
              onClick={onLoadUrl}
              variant="tonal"
            >
              {trans('map.layer-control.create.load')}
            </MapControlButton>
          }
        >
          <InputText
            label={trans('map.layer-control.field.url')}
            value={dataUrl}
            onChange={onUrlInput}
          />
        </InputActionRow>
        {loadingUrl ? (
          <div className="create-control-status">
            {trans('map.layer-control.create.loading-url')}
          </div>
        ) : null}
        {urlError ? (
          <div className="create-control-sample-error">{urlError}</div>
        ) : null}
      </div>
    </div>
  );
}
