// libs/react/draggable/src/components/draggable/item-drawer.tsx
import { focusFirst, restoreFocus } from '@hungpvq/draggable';
import {
  type MouseEvent as ReactMouseEvent,
  type ReactNode,
  type TouchEvent as ReactTouchEvent,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { createPortal } from 'react-dom';
import { useContainerId } from '../../context/ContainerContext';
import {
  ShareCardComponent,
  ShareHeaderComponent,
  useComponent,
  useHighlight,
  useIcon,
  useInitAction,
  useInitDrawer,
  useShow,
} from '../../hook';
import { useContainerSize } from '../../hook/useContainerSize';
import { useDrawerItem, useDragLayout } from '../../store';
import { useContainerReactive } from '../../store/useStoreReactive';
import { LocationSideBar } from '../../types';
import { ContextMenu, type ContextMenuRef } from '../ContextMenu';
import { ContextMenuItem } from '../ContextMenuItem';
import { DragButton } from '../parts/DragButton';

export interface DraggableDrawerProps {
  id?: string;
  show?: boolean;
  title?: string;
  containerId?: string;
  componentCard?: ShareCardComponent;
  componentCardHeader?: ShareHeaderComponent;
  disabledHeader?: boolean;
  disabledClose?: boolean;
  highlightMs?: number;
  location?: LocationSideBar;
  size?: number;
  minSize?: number;
  maxSize?: number;
  resizable?: boolean;
  onUpdateShow?: (value: boolean) => void;
  onClose?: () => void;
  onUpdateSize?: (value: number) => void;
  onResize?: (value: number) => void;
  children?: ReactNode;
  extraBtn?: ReactNode;
}

export function DraggableDrawer({
  id: stableId,
  show: propShow,
  title = '',
  containerId: propContainerId,
  componentCard,
  componentCardHeader,
  disabledHeader,
  disabledClose,
  highlightMs,
  location = 'right',
  size: propSize = 360,
  minSize = 200,
  maxSize,
  resizable = true,
  onUpdateShow,
  onClose,
  onUpdateSize,
  onResize,
  children,
  extraBtn,
}: DraggableDrawerProps) {
  const containerId = useContainerId(propContainerId);
  useContainerReactive(containerId);
  const { show, setShow, open, close } = useShow(
    { show: propShow },
    {
      'update:show': onUpdateShow,
      close: onClose,
    },
  );
  const { itemId } = useInitDrawer(
    containerId,
    setShow,
    {
      title,
      type: 'item-drawer',
      location,
    },
    stableId,
  );
  const { isHighlight, setHighLight } = useHighlight(highlightMs);
  useInitAction(containerId, itemId, {
    setHighLight,
    open,
    close,
  });
  const drawerStore = useDrawerItem(containerId);
  const drawerStoreRef = useRef(drawerStore);
  drawerStoreRef.current = drawerStore;
  const dragLayout = useDragLayout(containerId);
  const dragLayoutRef = useRef(dragLayout);
  dragLayoutRef.current = dragLayout;
  const { containerWidth, containerHeight } = useContainerSize(containerId);
  const { componentCard: Card, componentCardHeader: Header } = useComponent({
    componentCard,
    componentCardHeader,
    containerId,
  });

  const { CloseIcon, SidebarOpenMenu } = useIcon();
  const contextMenuRef = useRef<ContextMenuRef>(null);
  const drawerRootRef = useRef<HTMLDivElement>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const previousFocusRef = useRef<HTMLElement | null>(null);
  const titleId = `drawer-title-${itemId}`;

  const isHorizontal = location === 'left' || location === 'right';
  const [p_size, setPSize] = useState(
    () => dragLayout.getItemLayout(itemId)?.size ?? propSize,
  );
  const [isResizing, setIsResizing] = useState(false);
  const [slotEl, setSlotEl] = useState<HTMLElement | null>(null);
  const resizeState = useRef({ startPos: 0, startSize: 0 });
  const listenersRef = useRef<{
    move: (event: MouseEvent | TouchEvent) => void;
    end: () => void;
  } | null>(null);
  const prevLocationRef = useRef(location);

  const drawerItems = useMemo(
    () => drawerStore.getItemsForLocation(location),
    [drawerStore, location],
  );
  const activeDrawerId = useMemo(
    () => drawerStore.getShowForLocation(location),
    [drawerStore, location],
  );
  const showSwitcher = drawerItems.length > 1;

  const clampSize = useCallback(
    (value: number) => {
      const centerSize = isHorizontal ? containerWidth : containerHeight;
      const available = (centerSize || 0) + p_size;
      let next = value;
      if (maxSize != null) {
        next = Math.min(next, maxSize);
      }
      if (available > 0) {
        next = Math.min(next, Math.max(minSize, available - 80));
      }
      return Math.max(minSize, next);
    },
    [containerHeight, containerWidth, isHorizontal, maxSize, minSize, p_size],
  );

  useEffect(() => {
    setPSize((current) => {
      const next = clampSize(propSize);
      return next === current ? current : next;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps -- intentional: prop-driven sync only
  }, [propSize]);

  const setSize = useCallback(
    (value: number) => {
      const next = clampSize(value);
      setPSize(next);
      if (show) {
        drawerStoreRef.current.setDrawerSize(location, next);
      }
      dragLayoutRef.current.setItemLayout(itemId, {
        size: next,
        location,
      });
      onUpdateSize?.(next);
      onResize?.(next);
    },
    [clampSize, itemId, location, onResize, onUpdateSize, show],
  );

  useEffect(() => {
    const prev = prevLocationRef.current;
    if (prev !== location) {
      drawerStoreRef.current.moveDrawerLocation(itemId, location);
      prevLocationRef.current = location;
    }
    drawerStoreRef.current.registerDrawerShow(
      itemId,
      location,
      show,
      show ? p_size : undefined,
    );
    dragLayoutRef.current.setItemLayout(itemId, {
      size: p_size,
      location,
    });
  }, [itemId, location, show, p_size]);

  useEffect(() => {
    const syncSlot = () => {
      setSlotEl(document.getElementById(`drawer-${location}-${containerId}`));
    };
    syncSlot();
    const timer = window.setInterval(syncSlot, 100);
    return () => window.clearInterval(timer);
  }, [containerId, location]);

  const handleClose = useCallback(() => {
    close();
  }, [close]);

  useEffect(() => {
    if (!show) {
      restoreFocus(previousFocusRef.current);
      previousFocusRef.current = null;
      return;
    }
    previousFocusRef.current = document.activeElement as HTMLElement | null;
    const focusTimer = window.setTimeout(() => {
      if (drawerRootRef.current) focusFirst(drawerRootRef.current);
    }, 0);
    function onKeydown(event: KeyboardEvent) {
      if (event.key !== 'Escape') return;
      if (menuOpen) return;
      const root = drawerRootRef.current;
      if (!root) return;
      const target = event.target as Node | null;
      if (target && !root.contains(target) && document.activeElement !== root) {
        return;
      }
      event.preventDefault();
      close();
    }
    document.addEventListener('keydown', onKeydown);
    return () => {
      window.clearTimeout(focusTimer);
      document.removeEventListener('keydown', onKeydown);
    };
  }, [show, menuOpen, close]);

  const openMenu = useCallback((e: ReactMouseEvent) => {
    contextMenuRef.current?.open(e);
  }, []);

  const selectDrawer = useCallback(
    (nextId: string) => {
      drawerStoreRef.current.registerDrawerShow(
        nextId,
        location,
        true,
        p_size,
      );
      contextMenuRef.current?.close();
    },
    [location, p_size],
  );

  const detachResizeListeners = useCallback(() => {
    if (!listenersRef.current) return;
    window.removeEventListener('mousemove', listenersRef.current.move);
    window.removeEventListener('mouseup', listenersRef.current.end);
    window.removeEventListener('touchmove', listenersRef.current.move);
    window.removeEventListener('touchend', listenersRef.current.end);
    listenersRef.current = null;
  }, []);

  const onResizeStart = useCallback(
    (event: ReactMouseEvent | ReactTouchEvent) => {
      if (!resizable) return;
      event.preventDefault();
      setIsResizing(true);
      resizeState.current.startSize = p_size;
      if ('touches' in event) {
        resizeState.current.startPos = isHorizontal
          ? event.touches[0].clientX
          : event.touches[0].clientY;
      } else {
        resizeState.current.startPos = isHorizontal
          ? event.clientX
          : event.clientY;
      }

      const onResizeMove = (moveEvent: MouseEvent | TouchEvent) => {
        moveEvent.preventDefault();
        let current = 0;
        if ('touches' in moveEvent) {
          current = isHorizontal
            ? moveEvent.touches[0].clientX
            : moveEvent.touches[0].clientY;
        } else {
          current = isHorizontal ? moveEvent.clientX : moveEvent.clientY;
        }
        const delta = current - resizeState.current.startPos;
        let next = resizeState.current.startSize;
        switch (location) {
          case 'left':
            next = resizeState.current.startSize + delta;
            break;
          case 'right':
            next = resizeState.current.startSize - delta;
            break;
          case 'top':
            next = resizeState.current.startSize + delta;
            break;
          case 'bottom':
            next = resizeState.current.startSize - delta;
            break;
        }
        setSize(next);
      };

      const onResizeEnd = () => {
        setIsResizing(false);
        detachResizeListeners();
      };

      listenersRef.current = { move: onResizeMove, end: onResizeEnd };
      window.addEventListener('mousemove', onResizeMove);
      window.addEventListener('mouseup', onResizeEnd);
      window.addEventListener('touchmove', onResizeMove, { passive: false });
      window.addEventListener('touchend', onResizeEnd);
    },
    [detachResizeListeners, isHorizontal, location, p_size, resizable, setSize],
  );

  useEffect(() => {
    return () => {
      detachResizeListeners();
    };
  }, [detachResizeListeners]);

  const resizeHandleClass = useMemo(() => {
    return [
      'draggable-drawer-resize',
      `draggable-drawer-resize--${location}`,
      isResizing ? 'is-resizing' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }, [isResizing, location]);

  const menu = (
    <ContextMenu
      ref={contextMenuRef}
      ariaLabel="Switch drawer panel"
      onOpenChange={setMenuOpen}
    >
      <ul className="context-menu" role="presentation">
        {drawerItems.map((item) => (
          <ContextMenuItem
            key={item.id}
            active={item.id === activeDrawerId}
            onClick={() => selectDrawer(item.id)}
          >
            <span>{item.title ?? ''}</span>
          </ContextMenuItem>
        ))}
      </ul>
    </ContextMenu>
  );

  if (!show || !slotEl) {
    return menu;
  }

  return (
    <>
      {createPortal(
        <div
          ref={drawerRootRef}
          role="dialog"
          aria-labelledby={titleId}
          tabIndex={-1}
          className={[
            'draggable-drawer',
            `draggable-drawer--${location}`,
            isResizing ? 'draggable-drawer--resizing' : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <Card highlight={isHighlight}>
            <div className="draggable-drawer-inner">
              {!disabledHeader && (
                <Header
                  title={<span id={titleId}>{title}</span>}
                  extraBtn={
                    <>
                      {extraBtn}
                      {showSwitcher && (
                        <DragButton
                          onClick={openMenu}
                          aria-label="Open drawer menu"
                          aria-haspopup="menu"
                          aria-expanded={menuOpen}
                        >
                          <SidebarOpenMenu size={'16px'} />
                        </DragButton>
                      )}
                      {!disabledClose && (
                        <DragButton
                          aria-label="Close drawer"
                          onClick={handleClose}
                        >
                          <CloseIcon size={'16px'} />
                        </DragButton>
                      )}
                    </>
                  }
                />
              )}
              <div className="draggable-drawer-content">{children}</div>
            </div>
          </Card>
          {resizable && (
            <div
              className={resizeHandleClass}
              aria-hidden="true"
              onMouseDown={onResizeStart}
              onTouchStart={onResizeStart}
            />
          )}
        </div>,
        slotEl,
      )}
      {menu}
    </>
  );
}

// libs/vue/draggable/src/components/draggable/item-drawer.vue
<script lang="ts">
export default {
  name: 'DraggableDrawer',
};
</script>
<script setup lang="ts">
import ContextMenu from '../ContextMenu.vue';
import ContextMenuItem from '../ContextMenuItem.vue';
import { focusFirst, restoreFocus } from '@hungpvq/draggable';
import {
  computed,
  inject,
  nextTick,
  onBeforeUnmount,
  ref,
  Ref,
  watch,
} from 'vue';
import {
  useComponent,
  useContainerSize,
  useHighlight,
  useIcon,
  useInitAction,
  useShow,
  withShareProps,
  withShowEmit,
  withShowProps,
} from '../../hook';
import { useInitDrawer } from '../../hook/useInitDrawer';
import { useDragLayout, useDrawerItem } from '../../store';
import { LocationSideBar } from '../../types';
import DragButton from '../parts/DragButton.vue';

const { CloseIcon, SidebarOpenMenu } = useIcon();

const props = defineProps({
  ...withShowProps,
  ...withShareProps,
  location: {
    type: String,
    default: 'right',
    validator: (value: string) =>
      ['left', 'right', 'top', 'bottom'].includes(value),
  },
  size: { type: Number, default: 360 },
  minSize: { type: Number, default: 200 },
  maxSize: { type: Number, default: undefined },
  resizable: { type: Boolean, default: true },
});

const emit = defineEmits({
  ...withShowEmit,
  'update:size': (value: number) => typeof value === 'number',
  resize: (value: number) => typeof value === 'number',
});

const containerId = inject<Ref<string>>(
  'containerId',
  ref(props.containerId || ''),
);
if (!containerId.value) {
  throw new Error('Not set container id');
}

const location = computed(() => props.location as LocationSideBar);
const isHorizontal = computed(
  () => location.value === 'left' || location.value === 'right',
);

const { show, open, close } = useShow(props, emit);
const { itemId } = useInitDrawer(
  containerId.value,
  show,
  {
    title: props.title,
    type: 'item-drawer',
    location,
  },
  props.id,
);
const { isHighlight, setHighLight } = useHighlight(props.highlightMs);
useInitAction(containerId.value, itemId.value, {
  setHighLight,
  open,
  close,
});
const drawerStore = useDrawerItem(containerId.value);
const dragLayout = useDragLayout(containerId.value);
const { containerWidth, containerHeight } = useContainerSize(containerId.value);
const { componentCard, componentCardHeader } = useComponent({
  ...props,
  containerId: containerId.value,
});

const contextMenuRef = ref<
  | {
      open(event: MouseEvent): void;
      close(): void;
    }
  | undefined
>();
const menuOpen = ref(false);
const drawerRoot = ref<HTMLElement>();
const titleId = computed(() => `drawer-title-${itemId.value}`);
let previousFocus: HTMLElement | null = null;

const savedLayout = dragLayout.getItemLayout(itemId.value);
const p_size = ref(savedLayout?.size ?? props.size);
const slotTo = computed(
  () => `#drawer-${location.value}-${containerId.value}`,
);

const availableDrawerItems = computed(() =>
  drawerStore.getItemsForLocation(location.value),
);
const activeDrawerId = computed(() =>
  drawerStore.getShowForLocation(location.value),
);
const showSwitcher = computed(() => availableDrawerItems.value.length > 1);

watch(
  () => props.size,
  (value) => {
    if (value != null) {
      p_size.value = value;
    }
  },
);

function clampSize(value: number) {
  const centerSize = isHorizontal.value
    ? containerWidth.value
    : containerHeight.value;
  const available = (centerSize || 0) + p_size.value;
  let next = value;
  if (props.maxSize != null) {
    next = Math.min(next, props.maxSize);
  }
  if (available > 0) {
    next = Math.min(next, Math.max(props.minSize, available - 80));
  }
  return Math.max(props.minSize, next);
}

watch(
  [containerWidth, containerHeight, isHorizontal],
  () => {
    p_size.value = clampSize(p_size.value);
  },
  { immediate: true },
);

function setSize(value: number) {
  const next = clampSize(value);
  p_size.value = next;
  if (show.value) {
    drawerStore.setDrawerSize(location.value, next);
  }
  dragLayout.setItemLayout(itemId.value, {
    size: next,
    location: location.value,
  });
  emit('update:size', next);
  emit('resize', next);
}

watch(
  [show, p_size, location],
  ([isShow, size, loc], prev) => {
    const prevLoc = prev?.[2] as LocationSideBar | undefined;
    if (prevLoc && prevLoc !== loc) {
      drawerStore.moveDrawerLocation(itemId.value, loc);
    }
    drawerStore.registerDrawerShow(
      itemId.value,
      loc,
      !!isShow,
      isShow ? size : undefined,
    );
    dragLayout.setItemLayout(itemId.value, {
      size: size as number,
      location: loc as LocationSideBar,
    });
  },
  { immediate: true },
);

function onClose() {
  close();
}

function onKeydown(event: KeyboardEvent) {
  if (!show.value || event.key !== 'Escape') return;
  if (menuOpen.value) return;
  const root = drawerRoot.value;
  if (!root) return;
  const target = event.target as Node | null;
  if (target && !root.contains(target) && document.activeElement !== root) {
    return;
  }
  event.preventDefault();
  onClose();
}

watch(
  show,
  async (visible) => {
    document.removeEventListener('keydown', onKeydown);
    if (!visible) {
      restoreFocus(previousFocus);
      previousFocus = null;
      return;
    }
    previousFocus = document.activeElement as HTMLElement | null;
    document.addEventListener('keydown', onKeydown);
    await nextTick();
    if (drawerRoot.value) focusFirst(drawerRoot.value);
  },
  { immediate: true },
);

function openMenu(e: MouseEvent) {
  contextMenuRef.value?.open(e);
}

function closeContextMenu() {
  contextMenuRef.value?.close();
}

function selectDrawer(nextId: string) {
  drawerStore.registerDrawerShow(
    nextId,
    location.value,
    true,
    p_size.value,
  );
  closeContextMenu();
}

const isResizing = ref(false);
let startPos = 0;
let startSize = 0;

function onResizeStart(event: MouseEvent | TouchEvent) {
  if (!props.resizable) return;
  event.preventDefault();
  isResizing.value = true;
  startSize = p_size.value;
  if ('touches' in event) {
    startPos = isHorizontal.value
      ? event.touches[0].clientX
      : event.touches[0].clientY;
  } else {
    startPos = isHorizontal.value ? event.clientX : event.clientY;
  }
  window.addEventListener('mousemove', onResizeMove);
  window.addEventListener('mouseup', onResizeEnd);
  window.addEventListener('touchmove', onResizeMove, { passive: false });
  window.addEventListener('touchend', onResizeEnd);
}

function onResizeMove(event: MouseEvent | TouchEvent) {
  if (!isResizing.value) return;
  event.preventDefault();
  let current = 0;
  if ('touches' in event) {
    current = isHorizontal.value
      ? event.touches[0].clientX
      : event.touches[0].clientY;
  } else {
    current = isHorizontal.value ? event.clientX : event.clientY;
  }
  const delta = current - startPos;
  let next = startSize;
  switch (location.value) {
    case 'left':
      next = startSize + delta;
      break;
    case 'right':
      next = startSize - delta;
      break;
    case 'top':
      next = startSize + delta;
      break;
    case 'bottom':
      next = startSize - delta;
      break;
  }
  setSize(next);
}

function onResizeEnd() {
  isResizing.value = false;
  window.removeEventListener('mousemove', onResizeMove);
  window.removeEventListener('mouseup', onResizeEnd);
  window.removeEventListener('touchmove', onResizeMove);
  window.removeEventListener('touchend', onResizeEnd);
}

onBeforeUnmount(() => {
  onResizeEnd();
  document.removeEventListener('keydown', onKeydown);
});

const resizeHandleClass = computed(() => {
  return [
    'draggable-drawer-resize',
    `draggable-drawer-resize--${location.value}`,
    { 'is-resizing': isResizing.value },
  ];
});
</script>

<template>
  <Teleport v-if="show" :to="slotTo">
    <div
      ref="drawerRoot"
      class="draggable-drawer"
      role="dialog"
      :aria-labelledby="titleId"
      tabindex="-1"
      :class="[
        `draggable-drawer--${location}`,
        { 'draggable-drawer--resizing': isResizing },
      ]"
    >
      <component :is="componentCard" :highlight="isHighlight">
        <div class="draggable-drawer-inner">
          <template v-if="!disabledHeader">
            <component :is="componentCardHeader">
              <template #title>
                <span :id="titleId">
                  <slot name="title">
                    {{ title }}
                  </slot>
                </span>
              </template>
              <template #extra-btn>
                <slot name="extra-btn"></slot>
                <drag-button
                  v-if="showSwitcher"
                  aria-label="Open drawer menu"
                  aria-haspopup="menu"
                  :aria-expanded="menuOpen ? 'true' : 'false'"
                  @click="openMenu"
                >
                  <SidebarOpenMenu :size="16" />
                </drag-button>
                <drag-button
                  v-if="!disabledClose"
                  aria-label="Close drawer"
                  @click="onClose"
                >
                  <CloseIcon :size="16" />
                </drag-button>
              </template>
            </component>
          </template>
          <div class="draggable-drawer-content">
            <slot></slot>
          </div>
        </div>
      </component>
      <div
        v-if="resizable"
        :class="resizeHandleClass"
        aria-hidden="true"
        @mousedown="onResizeStart"
        @touchstart.prevent="onResizeStart"
      />
    </div>
  </Teleport>
  <ContextMenu
    ref="contextMenuRef"
    aria-label="Switch drawer panel"
    @update:open="menuOpen = $event"
  >
    <ul class="context-menu" role="presentation">
      <ContextMenuItem
        v-for="option in availableDrawerItems"
        :key="option.id"
        :active="option.id === activeDrawerId"
        @click="selectDrawer(option.id)"
      >
        <span>{{ option.title }}</span>
      </ContextMenuItem>
    </ul>
  </ContextMenu>
</template>
