// libs/react/draggable/src/components/draggable/item-modal.tsx
import { clampBounds, focusFirst, setModalSiblingsInert, trapTabKey } from '@hungpvq/draggable';
import {
  ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { createPortal } from 'react-dom';
import { Rnd } from 'react-rnd';
import { useContainerId } from '../../context/ContainerContext';
import {
  ShareCardComponent,
  ShareHeaderComponent,
  useComponent,
  useContainerOrder,
  useHighlight,
  useIcon,
  useInitAction,
  useInitItem,
  useShow,
} from '../../hook';
import { DragButton } from '../parts/DragButton';
import { useDragLayout } from '../../store';

const MODAL_Z_INDEX = 10000;

const STICKS_TO_RND: Record<string, string> = {
  t: 'top',
  r: 'right',
  b: 'bottom',
  l: 'left',
  tl: 'topLeft',
  tr: 'topRight',
  bl: 'bottomLeft',
  br: 'bottomRight',
};
const RESIZE_KEYS = [
  'top',
  'right',
  'bottom',
  'left',
  'topRight',
  'bottomRight',
  'bottomLeft',
  'topLeft',
];

export interface DraggableModalProps {
  id?: string;
  show?: boolean;
  title?: string;
  containerId?: string;
  componentCard?: ShareCardComponent;
  componentCardHeader?: ShareHeaderComponent;
  disabledHeader?: boolean;
  disabledClose?: boolean;
  highlightMs?: number;
  sticks?: string[];
  top?: number;
  left?: number;
  bottom?: number;
  right?: number;
  width?: number;
  height?: number;
  centerX?: boolean;
  centerY?: boolean;
  center?: boolean;
  mask?: boolean;
  maskClosable?: boolean;
  draggable?: boolean;
  resizable?: boolean;
  onUpdateShow?: (value: boolean) => void;
  onClose?: () => void;
  onBoundsChange?: (bounds: {
    x: number;
    y: number;
    width: number;
    height: number;
  }) => void;
  children?: ReactNode;
  extraBtn?: ReactNode;
}

export function DraggableModal({
  id: stableId,
  show: propShow,
  title = '',
  containerId: propContainerId,
  componentCard,
  componentCardHeader,
  disabledHeader,
  disabledClose,
  highlightMs,
  sticks = ['bl', 'br', 'tl', 'tr'],
  top,
  left,
  bottom,
  right,
  width: propWidth = 480,
  height: propHeight = 320,
  centerX = true,
  centerY = true,
  center = true,
  mask = true,
  maskClosable = true,
  draggable = true,
  resizable = true,
  onUpdateShow,
  onClose,
  onBoundsChange,
  children,
  extraBtn,
}: DraggableModalProps) {
  const containerId = useContainerId(propContainerId);
  const { show, setShow, open, close } = useShow(
    { show: propShow },
    {
      'update:show': onUpdateShow,
      close: onClose,
    },
  );
  const { itemId, zIndex } = useInitItem(
    containerId,
    show,
    setShow,
    {
      title,
      type: 'item-modal',
    },
    stableId,
  );
  const stackZIndex = MODAL_Z_INDEX + zIndex;
  const titleId = `draggable-modal-title-${itemId}`;
  const { isHighlight, setHighLight } = useHighlight(highlightMs);
  useInitAction(containerId, itemId, {
    setHighLight,
    open,
    close,
  });
  const { onToFront } = useContainerOrder(containerId, itemId);
  const dragLayout = useDragLayout(containerId);
  const dragLayoutRef = useRef(dragLayout);
  dragLayoutRef.current = dragLayout;
  const [initDone, setInitDone] = useState(false);
  const [layerEl, setLayerEl] = useState<HTMLElement | null>(null);
  const [layerWidth, setLayerWidth] = useState(0);
  const [layerHeight, setLayerHeight] = useState(0);
  const [p_height, setPHeight] = useState(propHeight || 320);
  const [p_width, setPWidth] = useState(propWidth || 480);
  const [p_x, setPX] = useState(0);
  const [p_y, setPY] = useState(0);
  const modalRootRef = useRef<HTMLDivElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);
  const mountedRef = useRef(false);
  const boundsRef = useRef({
    x: 0,
    y: 0,
    width: propWidth || 480,
    height: propHeight || 320,
  });
  const onBoundsChangeRef = useRef(onBoundsChange);
  onBoundsChangeRef.current = onBoundsChange;

  const { componentCard: Card, componentCardHeader: Header } = useComponent({
    componentCard,
    componentCardHeader,
    containerId,
  });

  const { CloseIcon, DragIcon } = useIcon();

  const enableResizing = useMemo(() => {
    if (!resizable) {
      const out: Record<string, boolean> = {};
      RESIZE_KEYS.forEach((k) => (out[k] = false));
      return out;
    }
    const out: Record<string, boolean> = {};
    RESIZE_KEYS.forEach((k) => (out[k] = false));
    sticks.forEach((s) => {
      const k = STICKS_TO_RND[s];
      if (k) out[k] = true;
    });
    return out;
  }, [sticks, resizable]);

  const emitBounds = useCallback(
    (x: number, y: number, width: number, height: number) => {
      const next = clampBounds(x, y, width, height, layerWidth, layerHeight);
      setPX(next.x);
      setPY(next.y);
      setPWidth(next.width);
      setPHeight(next.height);
      boundsRef.current = next;
      dragLayoutRef.current.setItemLayout(itemId, { bounds: next });
      onBoundsChangeRef.current?.(next);
    },
    [layerWidth, layerHeight, itemId],
  );

  const handleResize = useCallback(
    (
      _e: unknown,
      _dir: unknown,
      elementRef: HTMLElement,
      _delta: unknown,
      position: { x: number; y: number },
    ) => {
      setPWidth(elementRef.offsetWidth);
      setPHeight(elementRef.offsetHeight);
      setPX(position.x);
      setPY(position.y);
    },
    [],
  );

  const handleDragStop = useCallback(
    (_e: unknown, data: { x: number; y: number }) => {
      emitBounds(
        data.x,
        data.y,
        boundsRef.current.width,
        boundsRef.current.height,
      );
    },
    [emitBounds],
  );

  const handleResizeStop = useCallback(
    (
      _e: unknown,
      _dir: unknown,
      elementRef: HTMLElement,
      _delta: unknown,
      position: { x: number; y: number },
    ) => {
      emitBounds(
        position.x,
        position.y,
        elementRef.offsetWidth,
        elementRef.offsetHeight,
      );
    },
    [emitBounds],
  );

  const handleClose = useCallback(
    (e?: { stopPropagation?: () => void }) => {
      e?.stopPropagation?.();
      close();
    },
    [close],
  );

  const handleMaskClick = useCallback(() => {
    if (maskClosable) {
      close();
    }
  }, [maskClosable, close]);

  useEffect(() => {
    const sync = () => {
      const el = document.getElementById(`modal-layer-${containerId}`);
      setLayerEl(el);
      setLayerWidth(el?.clientWidth || 0);
      setLayerHeight(el?.clientHeight || 0);
    };
    sync();
    const timer = window.setInterval(sync, 100);
    window.addEventListener('resize', sync);
    return () => {
      window.clearInterval(timer);
      window.removeEventListener('resize', sync);
    };
  }, [containerId]);

  useEffect(() => {
    if (!show) return;
    const layer = document.getElementById(`modal-layer-${containerId}`);
    setModalSiblingsInert(layer, true);
    return () => {
      setModalSiblingsInert(
        document.getElementById(`modal-layer-${containerId}`),
        false,
      );
    };
  }, [show, containerId]);

  useEffect(() => {
    if (!show) {
      setInitDone(false);
      mountedRef.current = false;
      if (previousFocusRef.current?.focus) {
        previousFocusRef.current.focus();
      }
      previousFocusRef.current = null;
      return;
    }

    if (layerWidth <= 0 || layerHeight <= 0) {
      setInitDone(false);
      return;
    }

    const saved = dragLayoutRef.current.getItemLayout(itemId)?.bounds;
    if (saved && !mountedRef.current) {
      const next = clampBounds(
        saved.x,
        saved.y,
        saved.width,
        saved.height,
        layerWidth,
        layerHeight,
      );
      setPWidth(next.width);
      setPHeight(next.height);
      setPX(next.x);
      setPY(next.y);
      boundsRef.current = next;
      setInitDone(true);
      mountedRef.current = true;
    } else {
      const width = propWidth || 480;
      const height = propHeight || 320;
      let x = 0;
      let y = 0;
      const hasX = left != null || right != null;
      const hasY = top != null || bottom != null;

      if (left != null) x = left;
      if (top != null) y = top;
      if (right != null) x = layerWidth - right - width;
      if (bottom != null) y = layerHeight - bottom - height;
      if (!hasX && (center || centerX)) {
        x = Math.max(0, (layerWidth - width) / 2);
      }
      if (!hasY && (center || centerY)) {
        y = Math.max(0, (layerHeight - height) / 2);
      }

      const next = clampBounds(x, y, width, height, layerWidth, layerHeight);
      setPWidth(next.width);
      setPHeight(next.height);
      setPX(next.x);
      setPY(next.y);
      boundsRef.current = next;
      setInitDone(true);
      mountedRef.current = true;
    }

    previousFocusRef.current = document.activeElement as HTMLElement | null;
    const focusTimer = window.setTimeout(() => {
      if (modalRootRef.current) focusFirst(modalRootRef.current);
    }, 0);

    function onKeydown(event: KeyboardEvent) {
      if (!modalRootRef.current) return;
      if (event.key === 'Escape') {
        event.preventDefault();
        close();
        return;
      }
      trapTabKey(modalRootRef.current, event);
    }

    document.addEventListener('keydown', onKeydown);
    return () => {
      window.clearTimeout(focusTimer);
      document.removeEventListener('keydown', onKeydown);
    };
  }, [
    show,
    layerWidth,
    layerHeight,
    left,
    top,
    right,
    bottom,
    center,
    centerX,
    centerY,
    propWidth,
    propHeight,
    close,
    itemId,
  ]);

  function onDragging() {
    window?.getSelection()?.removeAllRanges();
  }

  if (!show || !initDone || !layerEl) return null;

  return createPortal(
    <div
      ref={modalRootRef}
      className="draggable-modal-root"
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
      tabIndex={-1}
      style={{ zIndex: stackZIndex }}
    >
      {mask && (
        <div
          className="draggable-modal-mask"
          aria-hidden="true"
          onClick={handleMaskClick}
        />
      )}
      <Rnd
        className="draggable-modal-panel"
        size={{ width: p_width, height: p_height }}
        position={{ x: p_x, y: p_y }}
        style={{ zIndex: stackZIndex + 1, overflow: 'visible' }}
        bounds="parent"
        disableDragging={!draggable}
        dragHandleClassName="drag"
        enableResizing={enableResizing}
        onResize={handleResize}
        onResizeStop={handleResizeStop}
        onDrag={onDragging}
        onDragStop={handleDragStop}
        onMouseDown={onToFront}
      >
        <Card width={p_width} height={p_height} highlight={isHighlight}>
          <div className="draggable-modal-desktop">
            {!disabledHeader && (
              <Header
                title={<span id={titleId}>{title}</span>}
                preTitle={
                  draggable ? (
                    <div className="draggable-popup-drag-container">
                      <DragIcon size={'16px'} />
                      <div className="drag grabbing"></div>
                    </div>
                  ) : undefined
                }
                extraBtn={
                  <>
                    {extraBtn}
                    {!disabledClose && (
                      <DragButton aria-label="Close dialog" onClick={handleClose}>
                        <CloseIcon size={'16px'} />
                      </DragButton>
                    )}
                  </>
                }
              />
            )}
            <div className="draggable-modal-desktop-content">{children}</div>
          </div>
        </Card>
      </Rnd>
    </div>,
    layerEl,
  );
}

// libs/vue/draggable/src/components/draggable/item-modal.vue
<script lang="ts">
export default {
  name: 'DraggableModal',
};
</script>
<script setup lang="ts">
import { clampBounds, focusFirst, setModalSiblingsInert, trapTabKey } from '@hungpvq/draggable';
import {
  computed,
  inject,
  nextTick,
  onBeforeUnmount,
  ref,
  Ref,
  watch,
} from 'vue';
import DragButton from '../parts/DragButton.vue';

import VueDraggableResizable from 'vue-draggable-resizable';
import {
  useComponent,
  useContainerOrder,
  useHighlight,
  useIcon,
  useInitAction,
  useInitItem,
  useShow,
  withShareProps,
  withShowEmit,
  withShowProps,
} from '../../hook';
import { useDragLayout } from '../../store';

const MODAL_Z_INDEX = 10000;

const { CloseIcon, DragIcon } = useIcon();
const props = defineProps({
  ...withShowProps,
  ...withShareProps,
  sticks: { type: Array, default: () => ['bl', 'br', 'tl', 'tr'] },
  top: { type: Number, default: undefined },
  left: { type: Number, default: undefined },
  bottom: { type: Number, default: undefined },
  right: { type: Number, default: undefined },
  width: { type: Number, default: 480 },
  height: { type: Number, default: 320 },
  centerX: { type: Boolean, default: true },
  centerY: { type: Boolean, default: true },
  center: { type: Boolean, default: true },
  mask: { type: Boolean, default: true },
  maskClosable: { type: Boolean, default: true },
  draggable: { type: Boolean, default: true },
  resizable: { type: Boolean, default: true },
});
const emit = defineEmits({
  ...withShowEmit,
  'update:bounds': (value: {
    x: number;
    y: number;
    width: number;
    height: number;
  }) =>
    typeof value?.x === 'number' &&
    typeof value?.y === 'number' &&
    typeof value?.width === 'number' &&
    typeof value?.height === 'number',
});
const containerId = inject<Ref<string>>(
  'containerId',
  ref(props.containerId || ''),
);
if (!containerId.value) {
  throw new Error('Not set container id');
}
const { show, open, close } = useShow(props, emit);
const { itemId, zIndex } = useInitItem(
  containerId.value,
  show,
  {
    title: props.title,
    type: 'item-modal',
  },
  props.id,
);
const stackZIndex = computed(() => MODAL_Z_INDEX + zIndex.value);
const { isHighlight, setHighLight } = useHighlight(props.highlightMs);
useInitAction(containerId.value, itemId.value, {
  setHighLight,
  open,
  close,
});
const { onToFront } = useContainerOrder(containerId.value, itemId.value);
const dragLayout = useDragLayout(containerId.value);
const layerWidth = ref(0);
const layerHeight = ref(0);
const modalLayerTo = computed(() => `#modal-layer-${containerId.value}`);
const titleId = computed(() => `draggable-modal-title-${itemId.value}`);
const init_done = ref(false);
const isActive = ref(true);
const p_height = ref(props.height || 320);
const p_width = ref(props.width || 480);
const p_x = ref(0);
const p_y = ref(0);
const modalRoot = ref<HTMLDivElement>();
let previousFocus: HTMLElement | null = null;

function emitBounds() {
  const bounds = {
    x: p_x.value,
    y: p_y.value,
    width: p_width.value,
    height: p_height.value,
  };
  dragLayout.setItemLayout(itemId.value, { bounds });
  emit('update:bounds', bounds);
}
function applyClamp() {
  const next = clampBounds(
    p_x.value,
    p_y.value,
    p_width.value,
    p_height.value,
    layerWidth.value,
    layerHeight.value,
  );
  p_x.value = next.x;
  p_y.value = next.y;
  p_width.value = next.width;
  p_height.value = next.height;
}
function activateEv() {
  isActive.value = true;
  onToFront();
}
function deactivateEv() {
  isActive.value = false;
}
const { componentCard, componentCardHeader } = useComponent({
  ...props,
  containerId: containerId.value,
});
function measureLayer() {
  const el = document.getElementById(`modal-layer-${containerId.value}`);
  layerWidth.value = el?.clientWidth || 0;
  layerHeight.value = el?.clientHeight || 0;
}
function onResize(x: number, y: number, width: number, height: number) {
  p_width.value = width;
  p_height.value = height;
  p_x.value = x;
  p_y.value = y;
}
function onDragging(x: number, y: number) {
  p_x.value = x;
  p_y.value = y;
  window?.getSelection()?.removeAllRanges();
}
function onDragStop(x: number, y: number) {
  p_x.value = x;
  p_y.value = y;
  applyClamp();
  emitBounds();
}
function onResizeStop(x: number, y: number, width: number, height: number) {
  p_width.value = width;
  p_height.value = height;
  p_x.value = x;
  p_y.value = y;
  applyClamp();
  emitBounds();
}
function onClose() {
  close();
}
function onMaskClick() {
  if (props.maskClosable) {
    onClose();
  }
}
function onKeydown(event: KeyboardEvent) {
  if (!show.value || !modalRoot.value) return;
  if (event.key === 'Escape') {
    event.preventDefault();
    onClose();
    return;
  }
  trapTabKey(modalRoot.value, event);
}
watch(
  show,
  async (visible) => {
    init_done.value = false;
    const layer = document.getElementById(`modal-layer-${containerId.value}`);
    setModalSiblingsInert(layer, visible);
    if (!visible) {
      document.removeEventListener('keydown', onKeydown);
      if (previousFocus && typeof previousFocus.focus === 'function') {
        previousFocus.focus();
      }
      previousFocus = null;
      return;
    }
    previousFocus = document.activeElement as HTMLElement | null;
    await nextTick();
    init();
    await nextTick();
    if (modalRoot.value) {
      focusFirst(modalRoot.value);
    }
    document.addEventListener('keydown', onKeydown);
  },
  { immediate: true },
);
onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeydown);
  if (show.value) {
    setModalSiblingsInert(
      document.getElementById(`modal-layer-${containerId.value}`),
      false,
    );
  }
});
watch(
  () => [props.left, props.top, props.width, props.height] as const,
  ([left, top, width, height]) => {
    if (!init_done.value || !show.value) return;
    if (width != null) p_width.value = width;
    if (height != null) p_height.value = height;
    if (left != null) p_x.value = left;
    if (top != null) p_y.value = top;
    applyClamp();
  },
);
function init() {
  measureLayer();
  if (layerWidth.value <= 0 || layerHeight.value <= 0) {
    init_done.value = false;
    return;
  }
  const saved = dragLayout.getItemLayout(itemId.value)?.bounds;
  if (saved) {
    p_width.value = saved.width;
    p_height.value = saved.height;
    p_x.value = saved.x;
    p_y.value = saved.y;
    applyClamp();
    init_done.value = true;
    return;
  }
  p_width.value = props.width || 480;
  p_height.value = props.height || 320;
  const hasX = props.left != null || props.right != null;
  const hasY = props.top != null || props.bottom != null;
  if (props.left != null) {
    p_x.value = props.left;
  }
  if (props.top != null) {
    p_y.value = props.top;
  }
  if (props.right != null) {
    p_x.value = layerWidth.value - props.right - p_width.value;
  }
  if (props.bottom != null) {
    p_y.value = layerHeight.value - props.bottom - p_height.value;
  }
  if (!hasX && (props.center || props.centerX)) {
    p_x.value = Math.max(0, (layerWidth.value - p_width.value) / 2);
  }
  if (!hasY && (props.center || props.centerY)) {
    p_y.value = Math.max(0, (layerHeight.value - p_height.value) / 2);
  }
  applyClamp();
  init_done.value = true;
}
</script>

<template>
  <Teleport v-if="show && init_done" :to="modalLayerTo">
    <div
      ref="modalRoot"
      class="draggable-modal-root"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="titleId"
      tabindex="-1"
      :style="{ zIndex: stackZIndex }"
    >
      <div
        v-if="mask"
        class="draggable-modal-mask"
        aria-hidden="true"
        @click="onMaskClick"
      />
      <VueDraggableResizable
        v-bind="$attrs"
        class="draggable-modal-panel"
        dragHandle=".drag"
        :parent="true"
        :handles="sticks"
        :draggable="draggable"
        :resizable="resizable"
        :w="p_width"
        :h="p_height"
        :x="p_x"
        :y="p_y"
        :z="stackZIndex + 1"
        @resizing="onResize"
        @resizeStop="onResizeStop"
        @dragging="onDragging"
        @dragStop="onDragStop"
        :active="isActive"
        @activated="activateEv()"
        @deactivated="deactivateEv()"
      >
        <component
          :is="componentCard"
          :width="p_width"
          :height="p_height"
          :highlight="isHighlight"
        >
          <div class="draggable-modal-desktop">
            <template v-if="!disabledHeader">
              <component :is="componentCardHeader">
                <template #title>
                  <span :id="titleId">
                    <slot name="title">
                      {{ title }}
                    </slot>
                  </span>
                </template>
                <template #pre-title>
                  <div v-if="draggable" class="draggable-popup-drag-container">
                    <DragIcon :size="16" />
                    <div class="drag grabbing"></div>
                  </div>
                </template>
                <template #extra-btn>
                  <slot name="extra-btn"></slot>
                  <drag-button
                v-if="!disabledClose"
                aria-label="Close dialog"
                @click.stop="onClose"
              >
                    <CloseIcon :size="16" />
                  </drag-button>
                </template>
              </component>
            </template>
            <div class="draggable-modal-desktop-content">
              <slot></slot>
            </div>
          </div>
        </component>
      </VueDraggableResizable>
    </div>
  </Teleport>
</template>
