// libs/vue/map-core/src/extra/event/modules/ActionControl.vue
<script lang="ts">
export default {
  name: 'action-control',
};
</script>
<script setup lang="ts">
import { logHelper } from '@hungpvq/map-core';

import {
  createEventActionSync,
  MittTypeMapEvent,
  MittTypeMapEventEventKey,
  type IEvent,
} from '@hungpvq/map-core/event';
import { onMounted } from 'vue';
import type { WithMapPropType } from '@hungpvq/map-core';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { useMapMittStore } from '../../mitt';
import { useEventMapItems } from '../hook/useEventMapItems';
import { logger } from '../logger';
import { useMapEventStore } from '../store';
const props = withDefaults(defineProps<WithMapPropType>(), {
  ...defaultMapProps,
});
const { callMap, mapId } = useMap(props);
const store = useMapEventStore(mapId.value);
const emitter = useMapMittStore<MittTypeMapEvent>(mapId.value);

function setCurrentEvent(event_map_type: string, event?: IEvent) {
  logHelper(logger, mapId.value, 'store').debug(
    'setCurrentEvent',
    event_map_type,
    event,
  );
  store.current[event_map_type] = event;
  emitter.emit(MittTypeMapEventEventKey.setCurrent, event);
}

const { updateEventMap } = createEventActionSync({
  callMap,
  setCurrent: setCurrentEvent,
});

const { items } = useEventMapItems(mapId.value, {
  onChange: (value) => {
    updateEventMap(value);
  },
});
onMounted(() => {
  updateEventMap(items.value);
});
</script>
<template>
  <div></div>
</template>

// libs/react/map-core/src/extra/event/modules/ActionControl.tsx
import { useCallback, useEffect, useMemo, useRef } from 'react';
import type { WithMapPropType } from '@hungpvq/map-core';
import {
  createEventActionSync,
  MittTypeMapEventEventKey,
  type IEvent,
  type MittTypeMapEvent,
} from '@hungpvq/map-core/event';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { useMapMittStore } from '../../../store/mitt-store';
import { useEventMapItems } from '../hook/useEventMapItems';
import { useMapEventStore } from '../store';

export function ActionControl(props: WithMapPropType) {
  const merged = { ...defaultMapProps, ...props };
  const { callMap, mapId } = useMap(merged);
  const store = useMapEventStore(mapId);
  const emitter = useMapMittStore<MittTypeMapEvent>(mapId);

  const setCurrentEvent = useCallback(
    (event_map_type: string, event?: IEvent) => {
      store.current[event_map_type] = event;
      emitter.emit(MittTypeMapEventEventKey.setCurrent, event);
    },
    [store, emitter],
  );

  const depsRef = useRef({ callMap, setCurrentEvent });
  depsRef.current = { callMap, setCurrentEvent };

  const { updateEventMap } = useMemo(
    () =>
      createEventActionSync({
        callMap: (cb) => depsRef.current.callMap(cb),
        setCurrent: (type, event) => depsRef.current.setCurrentEvent(type, event),
      }),
    [],
  );

  // Match Vue: apply map listeners immediately via onChange (don't rely only on
  // useEffect(items) — store.items is mutated in place).
  useEventMapItems(mapId, { onChange: updateEventMap });

  useEffect(() => {
    updateEventMap(store.items);
  }, [mapId, store, updateEventMap]);

  return null;
}
