// libs/react/map-dataset/src/modules/IdentifyControl/IdentifyShowFirstControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { logHelper, runMapControlAction } from '@hungpvq/map-core';
import { EventClick } from '@hungpvq/map-core/event';
import type {
  IDataset,
  IdentifyMultiResult,
  IIdentifyView,
} from '@hungpvq/map-dataset';
import {
  handleMultiIdentifyGetFirst,
  IDENTIFY_CONTROL,
  identifyResolver,
} from '@hungpvq/map-dataset';
import {
  defaultMapProps,
  useEventMap,
  useMap,
} from '@hungpvq/react-map-core';
import type { MapMouseEvent } from 'maplibre-gl';
import { useEffect, useMemo, useRef, useState } from 'react';
import { loggerIdentify } from '../../logger';
import { useMapDataset } from '../../store';

export function IdentifyShowFirstControl(
  props: WithMapPropType & {
    /**
     * Always open Identify Result panel (skip auto show-detail / attribute-table).
     */
    preferResultControl?: boolean;
  },
) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, callMap } = useMap({
    ...merged,
    controlId: IDENTIFY_CONTROL.id,
  });
  const { getAllComponentsByType, datasetVersion } = useMapDataset(mapId);
  const [views, setViews] = useState<Array<IIdentifyView & IDataset>>([]);
  const viewsRef = useRef(views);
  viewsRef.current = views;
  const loadingRef = useRef(false);
  const preferResultControlRef = useRef(!!props.preferResultControl);
  preferResultControlRef.current = !!props.preferResultControl;
  const callMapRef = useRef(callMap);
  callMapRef.current = callMap;

  useEffect(() => {
    const next =
      getAllComponentsByType<IIdentifyView & IDataset>('identify') || [];
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getAllComponentsByType]);

  const setLoading = (value: boolean) => {
    loadingRef.current = value;
    callMapRef.current((map) => {
      map.getCanvas().style.cursor = value ? 'wait' : '';
    });
    runMapControlAction(
      mapId,
      IDENTIFY_CONTROL.id,
      IDENTIFY_CONTROL.actionSetLoading,
      value,
    );
  };

  const onMapClickRef = useRef<(e: MapMouseEvent) => void>(() => undefined);

  const clickEvent = useMemo(
    () =>
      new EventClick().setHandler((e: MapMouseEvent) => {
        onMapClickRef.current(e);
      }),
    [],
  );

  const { add: addEventClick, remove: removeEventClick } = useEventMap(
    mapId,
    clickEvent,
    false,
  );

  async function onGetFeatures(e: MapMouseEvent) {
    if (loadingRef.current) return;
    const loadStartedAt = performance.now();
    const pointOrBox = e.point;
    setLoading(true);
    logHelper(loggerIdentify, mapId, 'FIRST', 'IdentifyShowFirstControl').info(
      'loading:start',
      { pointOrBox },
    );
    try {
      logHelper(
        loggerIdentify,
        mapId,
        'FIRST',
        'IdentifyShowFirstControl',
      ).debug('onGetFeatures', { pointOrBox });
      const record = await handleMultiIdentifyGetFirst(
        viewsRef.current,
        mapId,
        pointOrBox,
      );
      logHelper(
        loggerIdentify,
        mapId,
        'FIRST',
        'IdentifyShowFirstControl',
      ).debug('onGetFeatures', { record });
      onSelectFeatures(record, e);
      logHelper(
        loggerIdentify,
        mapId,
        'FIRST',
        'IdentifyShowFirstControl',
      ).info('loading:done', {
        durationMs: Math.round(performance.now() - loadStartedAt),
        featureCount: record?.features?.length ?? 0,
        empty: !record?.features?.length,
      });
    } finally {
      setLoading(false);
    }
  }

  function onSelectFeatures(
    record: IdentifyMultiResult | undefined,
    event?: MapMouseEvent,
  ) {
    logHelper(loggerIdentify, mapId, 'FIRST', 'IdentifyShowFirstControl').debug(
      'onSelectFeatures',
      { record },
    );
    const records =
      record?.features?.length ? [record] : ([] as IdentifyMultiResult[]);
    identifyResolver
      .execute({
        records,
        mapId: mapId,
        event,
        singleLayer: true,
        preferResultControl: preferResultControlRef.current,
      })
      .then((res) =>
        logHelper(
          loggerIdentify,
          mapId,
          'FIRST',
          'IdentifyShowFirstControl',
        ).debug('onSelectFeaturesResult', res),
      );
  }

  onMapClickRef.current = (e: MapMouseEvent) => {
    logHelper(loggerIdentify, mapId, 'FIRST', 'IdentifyShowFirstControl').debug(
      'onMapClick',
      { event: e },
    );
    void onGetFeatures(e);
  };

  useEffect(() => {
    addEventClick();
    return () => {
      removeEventClick();
      if (loadingRef.current) setLoading(false);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [addEventClick, removeEventClick]);

  return null;
}

// libs/vue/map-dataset/src/modules/IdentifyControl/IdentifyShowFirstControl.vue
<script lang="ts">
export default {
  name: 'inspect-show-first-control',
};
</script>
<script setup lang="ts">
import {
  logHelper,
  runMapControlAction,
  WithMapPropType,
} from '@hungpvq/map-core';
import { EventClick } from '@hungpvq/map-core/event';
import type { IDataset } from '@hungpvq/map-dataset';
import type { IdentifyMultiResult, IIdentifyView } from '@hungpvq/map-dataset/identify';
import { handleMultiIdentifyGetFirst, IDENTIFY_CONTROL, identifyResolver } from '@hungpvq/map-dataset/identify';
import { defaultMapProps, useEventMap, useMap } from '@hungpvq/vue-map-core';
import { MapMouseEvent } from 'maplibre-gl';
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { loggerIdentify } from '../../logger';
import { useMapDataset } from '../../store';

const props = withDefaults(
  defineProps<
    WithMapPropType & {
      /**
       * Always open Identify Result panel (skip auto show-detail / attribute-table).
       */
      preferResultControl?: boolean;
    }
  >(),
  {
    ...defaultMapProps,
    preferResultControl: false,
  },
);
const { mapId, callMap } = useMap(props);
const { getAllComponentsByType, getDatasetIds } = useMapDataset(mapId.value);
const views = ref<Array<IIdentifyView & IDataset>>([]);
const loading = ref(false);

function refreshViews() {
  views.value =
    getAllComponentsByType<IIdentifyView & IDataset>('identify') || [];
}

watch(getDatasetIds(), refreshViews, { deep: true, immediate: true });

const { add: addEventClick, remove: removeEventClick } = useEventMap(
  mapId.value,
  new EventClick().setHandler(onMapClick),
);

function setLoading(value: boolean) {
  loading.value = value;
  callMap((map) => {
    map.getCanvas().style.cursor = value ? 'wait' : '';
  });
  // Sync IdentifyControl toolbar spinner when both are mounted.
  runMapControlAction(
    mapId.value,
    IDENTIFY_CONTROL.id,
    IDENTIFY_CONTROL.actionSetLoading,
    value,
  );
}

function onMapClick(e: MapMouseEvent) {
  logHelper(
    loggerIdentify,
    mapId.value,
    'FIRST',
    'IdentifyShowFirstControl',
  ).debug('onMapClick', { event: e });
  void onGetFeatures(e);
}

function onSelectFeatures(
  record: IdentifyMultiResult | undefined,
  event?: MapMouseEvent,
) {
  logHelper(
    loggerIdentify,
    mapId.value,
    'FIRST',
    'IdentifyShowFirstControl',
  ).debug('onSelectFeatures', { record });
  const records =
    record?.features?.length ? [record] : ([] as IdentifyMultiResult[]);
  identifyResolver
    .execute({
      records,
      mapId: mapId.value,
      event,
      singleLayer: true,
      preferResultControl: !!props.preferResultControl,
    })
    .then((res) =>
      logHelper(
        loggerIdentify,
        mapId.value,
        'FIRST',
        'IdentifyShowFirstControl',
      ).debug('onSelectFeaturesResult', res),
    );
}

async function onGetFeatures(e: MapMouseEvent) {
  if (loading.value) return;
  const loadStartedAt = performance.now();
  setLoading(true);
  logHelper(
    loggerIdentify,
    mapId.value,
    'FIRST',
    'IdentifyShowFirstControl',
  ).info('loading:start', { pointOrBox: e.point });
  try {
    logHelper(
      loggerIdentify,
      mapId.value,
      'FIRST',
      'IdentifyShowFirstControl',
    ).debug('onGetFeatures', { pointOrBox: e.point });
    const record = await handleMultiIdentifyGetFirst(
      views.value,
      mapId.value,
      e.point,
    );
    logHelper(
      loggerIdentify,
      mapId.value,
      'FIRST',
      'IdentifyShowFirstControl',
    ).debug('onGetFeatures', { record });
    onSelectFeatures(record, e);
    logHelper(
      loggerIdentify,
      mapId.value,
      'FIRST',
      'IdentifyShowFirstControl',
    ).info('loading:done', {
      durationMs: Math.round(performance.now() - loadStartedAt),
      featureCount: record?.features?.length ?? 0,
      empty: !record?.features?.length,
    });
  } finally {
    setLoading(false);
  }
}

onMounted(() => {
  addEventClick();
});
onUnmounted(() => {
  removeEventClick();
  if (loading.value) setLoading(false);
});
</script>
<template>
  <div></div>
</template>
