// libs/react/map-dataset/src/modules/IdentifyControl/IdentifyControl.tsx
import { bindMapLongPress, getMapPointerProfile, type WithMapPropType } from '@hungpvq/map-core';
import type { EventBboxRangerHandle } from '@hungpvq/map-core/event';
import type { MapMenuItemProps } from '@hungpvq/map-core/menu';
import { EventBboxRanger, EventClick } from '@hungpvq/map-core/event';
import { MAP_CONTEXT_MENU_ID } from '@hungpvq/map-core/menu';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import type { IIdentifyView } from '@hungpvq/map-dataset/identify';
import {
  buildIdentifyResultPanelBase,
  clearIdentifyScope,
  IDENTIFY_ALL_LAYERS_VALUE,
  IDENTIFY_CONTROL,
  IDENTIFY_CONTROL_LOCALE,
  IDENTIFY_RESULT_CONTROL,
  resolveIdentifyLayerFilterId,
  runIdentifyMulti,
  type IdentifyLayerFilterPayload,
  type IdentifyResultUpdatePayload,
  type IdentifyScopeToggleResult,
} from '@hungpvq/map-dataset/identify';
import {
  defaultMapProps,
  MapCommonButton,
  ModuleContainer,
  UniversalRegistry,
  useEventMap,
  useLang,
  useMap,
  useRegisterMapControl,
  useShow,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import { mdiHandPointingUp } from '@mdi/js';
import type { MapMouseEvent, PointLike } from 'maplibre-gl';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useMapDataset } from '../../store/dataset-api';
import { useMapHighlight } from '../../store/highlight';
import { IdentifyResultControl } from './IdentifyResultControl';

function updateResultPanel(
  mapId: string,
  payload: IdentifyResultUpdatePayload,
) {
  UniversalRegistry.runControlAction(
    mapId,
    IDENTIFY_RESULT_CONTROL.id,
    IDENTIFY_RESULT_CONTROL.actionUpdate,
    payload,
  );
}

export function IdentifyControl(
  props: WithMapPropType & {
    show?: boolean;
    immediately?: boolean;
    /**
     * Always open Identify Result panel (skip auto show-detail / attribute-table),
     * even when those menus are registered.
     */
    preferResultControl?: boolean;
  },
) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps, order, callMap } = useMap({
    ...merged,
    controlId: IDENTIFY_CONTROL.id,
  });
  const { getAllComponentsByType, datasetVersion } = useMapDataset(mapId);
  const hl = useMapHighlight(mapId);
  const { trans, registerLocale } = useLang(mapId);
  const [show, toggleShow] = useShow(!!props.show);
  const [views, setViews] = useState<IIdentifyView[]>([]);
  /** Local layer filter for IdentifyControl only (not synced with layer-item). */
  const [filterIdentifyId, setFilterIdentifyId] = useState<
    string | undefined
  >();
  const [isUseClick, setIsUseClick] = useState(false);
  const [isSelectBbox, setIsSelectBbox] = useState(false);
  const [origin, setOrigin] = useState({ latitude: 0, longitude: 0 });
  const [loading, setLoading] = useState(false);

  const viewsRef = useRef(views);
  viewsRef.current = views;
  const filterIdentifyIdRef = useRef(filterIdentifyId);
  filterIdentifyIdRef.current = filterIdentifyId;
  const showRef = useRef(show);
  showRef.current = show;
  const immediatelyRef = useRef(!!props.immediately);
  immediatelyRef.current = !!props.immediately;
  const isUseClickRef = useRef(isUseClick);
  isUseClickRef.current = isUseClick;
  const isSelectBboxRef = useRef(isSelectBbox);
  isSelectBboxRef.current = isSelectBbox;
  const originRef = useRef(origin);
  originRef.current = origin;
  const loadingRef = useRef(loading);
  loadingRef.current = loading;
  const preferResultControlRef = useRef(!!props.preferResultControl);
  preferResultControlRef.current = !!props.preferResultControl;
  const transRef = useRef(trans);
  transRef.current = trans;

  useEffect(() => {
    registerLocale('en', IDENTIFY_CONTROL_LOCALE);
  }, [registerLocale]);

  const onMapClickRef = useRef<(e: MapMouseEvent) => void>(() => undefined);
  const onBboxSelectRef = useRef<EventBboxRangerHandle>(() => undefined);

  const clickEvent = useMemo(
    () =>
      new EventClick().setHandler((e: MapMouseEvent) => {
        onMapClickRef.current(e);
      }),
    [],
  );
  const bboxEvent = useMemo(
    () =>
      new EventBboxRanger().setHandler((bbox) => {
        onBboxSelectRef.current(bbox);
      }),
    [],
  );

  const {
    add: addEventClick,
    remove: removeEventClick,
    isActive: isEventClickActive,
  } = useEventMap(mapId, clickEvent, false);
  const {
    add: addEventBbox,
    remove: removeEventBbox,
    isActive: isEventClickBox,
  } = useEventMap(mapId, bboxEvent, false);

  const addEventClickRef = useRef(addEventClick);
  addEventClickRef.current = addEventClick;
  const removeEventClickRef = useRef(removeEventClick);
  removeEventClickRef.current = removeEventClick;
  const addEventBboxRef = useRef(addEventBbox);
  addEventBboxRef.current = addEventBbox;
  const removeEventBboxRef = useRef(removeEventBbox);
  removeEventBboxRef.current = removeEventBbox;
  const isEventClickActiveRef = useRef(isEventClickActive);
  isEventClickActiveRef.current = isEventClickActive;
  const isEventClickBoxRef = useRef(isEventClickBox);
  isEventClickBoxRef.current = isEventClickBox;
  const unbindLongPressRef = useRef<(() => void) | null>(null);

  const syncResultPanel = useCallback(
    (extra?: IdentifyResultUpdatePayload) => {
      updateResultPanel(mapId, {
        ...buildIdentifyResultPanelBase({
          loading: loadingRef.current,
          origin: originRef.current,
          views: viewsRef.current,
          allLayersText: transRef.current('map.identify.all_layers'),
          selectedLayerId: filterIdentifyIdRef.current,
          isEventClickActive: isEventClickActiveRef.current,
          isEventClickBox: isEventClickBoxRef.current,
        }),
        ...extra,
      });
    },
    [mapId],
  );

  useEffect(() => {
    const next = (
      getAllComponentsByType<IIdentifyView>('identify') || []
    ).reverse();
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getAllComponentsByType]);

  useEffect(() => {
    syncResultPanel();
  }, [
    views,
    filterIdentifyId,
    show,
    loading,
    origin,
    isEventClickActive,
    isEventClickBox,
    syncResultPanel,
  ]);

  const onGetFeatures = useCallback(
    async (
      pointOrBox: PointLike | [PointLike, PointLike],
      event?: MapMouseEvent,
    ) => {
      setLoading(true);
      loadingRef.current = true;
      // Activate identify session (toolbar) without forcing ResultControl open.
      toggleShow(true);
      showRef.current = true;
      syncResultPanel({ loading: true });
      callMapRef.current((map) => {
        map.getCanvas().style.cursor = 'wait';
      });
      try {
        const allIdentifies = (
          getAllComponentsByType<IIdentifyView>('identify') || []
        ).reverse();
        viewsRef.current = allIdentifies;
        setViews(allIdentifies);
        await runIdentifyMulti({
          identifies: allIdentifies,
          mapId,
          pointOrBox,
          event,
          filterIdentifyId: filterIdentifyIdRef.current,
          preferResultControl: preferResultControlRef.current,
        });
      } finally {
        setLoading(false);
        loadingRef.current = false;
        callMapRef.current((map) => {
          map.getCanvas().style.cursor = '';
        });
        syncResultPanel({ loading: false });
      }
    },
    [mapId, getAllComponentsByType, toggleShow, syncResultPanel],
  );

  const onGetFeaturesRef = useRef(onGetFeatures);
  onGetFeaturesRef.current = onGetFeatures;
  const toggleShowRef = useRef(toggleShow);
  toggleShowRef.current = toggleShow;
  const callMapRef = useRef(callMap);
  callMapRef.current = callMap;

  useEffect(() => {
    UniversalRegistry.registerMenuHandlerForMap(
      mapId,
      MAP_CONTEXT_MENU_ID.identifyHere,
      (menuProps: MapMenuItemProps) => {
        const { lng, lat } = menuProps.layer.lngLat;
        const run = (point: PointLike) => {
          const nextOrigin = { latitude: lat, longitude: lng };
          setOrigin(nextOrigin);
          originRef.current = nextOrigin;
          toggleShowRef.current(true);
          showRef.current = true;
          void onGetFeaturesRef.current(point);
        };
        if (menuProps.layer.point) {
          run(menuProps.layer.point as PointLike);
          return;
        }
        callMapRef.current((map) => {
          run(map.project([lng, lat]));
        });
      },
    );
  }, [mapId]);

  const onStartMapClick = useCallback(() => {
    setIsUseClick(true);
    addEventClickRef.current();
    syncResultPanel({ isEventClickActive: true });
    unbindLongPressRef.current?.();
    unbindLongPressRef.current = null;
    if (getMapPointerProfile().coarse) {
      callMapRef.current((map) => {
        unbindLongPressRef.current = bindMapLongPress(map, {
          onLongPress: (point) => {
            if (isEventClickBoxRef.current) return;
            const lngLat = map.unproject([point.x, point.y]);
            const nextOrigin = {
              latitude: lngLat.lat,
              longitude: lngLat.lng,
            };
            setOrigin(nextOrigin);
            originRef.current = nextOrigin;
            void onGetFeaturesRef.current(point);
          },
        });
      });
    }
  }, [syncResultPanel]);

  const onRemoveMapClick = useCallback(() => {
    setIsUseClick(false);
    removeEventClickRef.current();
    unbindLongPressRef.current?.();
    unbindLongPressRef.current = null;
    syncResultPanel({ isEventClickActive: false });
  }, [syncResultPanel]);

  const onStartBox = useCallback(() => {
    setIsSelectBbox(true);
    addEventBboxRef.current();
    syncResultPanel({ isEventClickBox: true });
  }, [syncResultPanel]);

  const onRemoveBox = useCallback(() => {
    setIsSelectBbox(false);
    window.setTimeout(() => {
      removeEventBboxRef.current();
      syncResultPanel({ isEventClickBox: false });
    }, 500);
  }, [syncResultPanel]);

  const onUseMapClick = useCallback(() => {
    if (!isUseClickRef.current) onStartMapClick();
    else onRemoveMapClick();
  }, [onStartMapClick, onRemoveMapClick]);

  const onUseBoxSelect = useCallback(() => {
    if (!isSelectBboxRef.current) onStartBox();
    else onRemoveBox();
  }, [onStartBox, onRemoveBox]);

  const onRemoveIdentify = useCallback(() => {
    if (immediatelyRef.current) return;
    onRemoveMapClick();
    onRemoveBox();
  }, [onRemoveMapClick, onRemoveBox]);

  const close = useCallback(() => {
    setFilterIdentifyId(undefined);
    filterIdentifyIdRef.current = undefined;
    clearIdentifyScope(mapId);
    onRemoveIdentify();
    hl.hideIfSource('identify');
    setLoading(false);
    loadingRef.current = false;
    const clearedOrigin = { latitude: 0, longitude: 0 };
    setOrigin(clearedOrigin);
    originRef.current = clearedOrigin;
    toggleShow(false);
    showRef.current = false;
    syncResultPanel({
      show: false,
      loading: false,
      origin: clearedOrigin,
      selectedLayerId: IDENTIFY_ALL_LAYERS_VALUE,
      items: [],
    });
  }, [mapId, onRemoveIdentify, hl, toggleShow, syncResultPanel]);

  onMapClickRef.current = (e: MapMouseEvent) => {
    if (isEventClickBoxRef.current) return;
    const nextOrigin = { latitude: e.lngLat.lat, longitude: e.lngLat.lng };
    setOrigin(nextOrigin);
    originRef.current = nextOrigin;
    toggleShowRef.current(true);
    showRef.current = true;
    onGetFeatures(e.point, e);
  };

  onBboxSelectRef.current = (bbox) => {
    if (isEventClickActiveRef.current) return;
    onRemoveBox();
    if (!bbox) return;
    toggleShowRef.current(true);
    showRef.current = true;
    onGetFeatures([
      [bbox[0].x, bbox[0].y],
      [bbox[1].x, bbox[1].y],
    ]);
  };

  useEffect(() => {
    if (props.immediately) onUseMapClick();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleToggle() {
    const next = !showRef.current;
    toggleShow();
    showRef.current = next;
    syncResultPanel({ show: next });
    if (next) {
      if (!isUseClickRef.current) onStartMapClick();
    } else {
      onRemoveIdentify();
    }
  }

  /** One-way from layer-item: start identify + filter; do not open result popup. */
  function applyScopedSession(result?: IdentifyScopeToggleResult) {
    const clearedOrigin = { latitude: 0, longitude: 0 };
    if (result?.active && result.identifyId) {
      setFilterIdentifyId(result.identifyId);
      filterIdentifyIdRef.current = result.identifyId;
      setOrigin(clearedOrigin);
      originRef.current = clearedOrigin;
      toggleShow(true);
      showRef.current = true;
      syncResultPanel({
        selectedLayerId: result.identifyId,
        items: [],
        loading: false,
        origin: clearedOrigin,
      });
      if (!isUseClickRef.current) onStartMapClick();
      return;
    }
    if (
      result?.identifyId &&
      filterIdentifyIdRef.current &&
      filterIdentifyIdRef.current === result.identifyId
    ) {
      setFilterIdentifyId(undefined);
      filterIdentifyIdRef.current = undefined;
      setOrigin(clearedOrigin);
      originRef.current = clearedOrigin;
      syncResultPanel({
        selectedLayerId: IDENTIFY_ALL_LAYERS_VALUE,
        items: [],
        loading: false,
        origin: clearedOrigin,
      });
    }
    if (!immediatelyRef.current) onRemoveMapClick();
  }

  function onLayerFilterChange(identifyId: string) {
    const id = resolveIdentifyLayerFilterId(identifyId);
    setFilterIdentifyId(id);
    filterIdentifyIdRef.current = id;
    syncResultPanel({
      selectedLayerId: id ?? IDENTIFY_ALL_LAYERS_VALUE,
    });
    const current = originRef.current;
    if (current.latitude !== 0 || current.longitude !== 0) {
      callMap((map) => {
        const point = map.project([current.longitude, current.latitude]);
        void onGetFeatures(point);
      });
    }
  }

  const toolbarConfig = useMemo(
    () => ({
      kind: 'single' as const,
      id: IDENTIFY_CONTROL.id,
      getState: () =>
        mdiButtonState(mdiHandPointingUp, {
          visible: viewsRef.current.length > 0,
          active: showRef.current,
          loading: loadingRef.current,
          title: trans('map.identify.title'),
          order,
        }),
      onClick: () => handleToggle(),
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [trans, order],
  );

  const { state, control } = useToolbarControl(mapId, merged, toolbarConfig);

  useEffect(() => {
    control.sync();
  }, [show, loading, views.length, control]);

  function setIdentifyLoading(value: boolean) {
    setLoading(value);
    loadingRef.current = value;
    syncResultPanel({ loading: value });
    control.sync();
  }

  useRegisterMapControl(mapId, {
    id: IDENTIFY_CONTROL.id,
    panelKind: 'button',
    title: trans('map.identify.title'),
    buttonPosition: merged.position,
    show,
    setShow: (value) => {
      toggleShow(value);
      showRef.current = value;
      syncResultPanel({ show: value });
    },
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
      immediately: props.immediately,
      preferResultControl: props.preferResultControl,
    }),
    actions: [
      { type: IDENTIFY_CONTROL.id, run: () => handleToggle() },
      {
        type: IDENTIFY_CONTROL.actionSetScoped,
        run: (event) =>
          applyScopedSession(event as IdentifyScopeToggleResult | undefined),
      },
      {
        type: IDENTIFY_CONTROL.actionUseMapClick,
        run: () => onUseMapClick(),
      },
      {
        type: IDENTIFY_CONTROL.actionUseBoxSelect,
        run: () => onUseBoxSelect(),
      },
      {
        type: IDENTIFY_CONTROL.actionSetLayerFilter,
        run: (event) => {
          const payload = event as IdentifyLayerFilterPayload | undefined;
          onLayerFilterChange(payload?.identifyId ?? '');
        },
      },
      {
        type: IDENTIFY_CONTROL.actionClose,
        run: () => close(),
      },
      {
        type: IDENTIFY_CONTROL.actionSetLoading,
        run: (event) => {
          setIdentifyLoading(!!event);
        },
      },
    ],
  });

  return (
    <>
      <ModuleContainer
        {...moduleContainerProps}
        btn={
          state ? (
            <MapCommonButton
              option={state}
              onClick={(e) => {
                e.stopPropagation();
                control.onAction(e.nativeEvent);
              }}
            />
          ) : null
        }
      />
      <IdentifyResultControl
        position={merged.position}
        controlLayout={merged.controlLayout}
      />
    </>
  );
}

// libs/vue/map-dataset/src/modules/IdentifyControl/IdentifyControl.vue
<script lang="ts">
export default {
  name: 'InspectControl',
};
</script>

<script setup lang="ts">
import { bindMapLongPress, getMapPointerProfile, type WithMapPropType } from '@hungpvq/map-core';
import {
  EventBboxRanger,
  EventBboxRangerHandle,
  EventClick,
} from '@hungpvq/map-core/event';
import {
  MAP_CONTEXT_MENU_ID,
  type MapMenuItemProps,
} from '@hungpvq/map-core/menu';
import type { IIdentifyView } from '@hungpvq/map-dataset/identify';
import {
  buildIdentifyResultPanelBase,
  clearIdentifyScope,
  IDENTIFY_ALL_LAYERS_VALUE,
  IDENTIFY_CONTROL,
  IDENTIFY_CONTROL_LOCALE,
  IDENTIFY_RESULT_CONTROL,
  resolveIdentifyLayerFilterId,
  runIdentifyMulti,
  type IdentifyLayerFilterPayload,
  type IdentifyResultUpdatePayload,
  type IdentifyScopeToggleResult,
} from '@hungpvq/map-dataset/identify';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import {
  defaultMapProps,
  MapCommonButton,
  ModuleContainer,
  UniversalRegistry,
  useEventMap,
  useLang,
  useMap,
  useRegisterMapControl,
  useToolbarControl,
  type WithShowProps,
} from '@hungpvq/vue-map-core';
import { mdiHandPointingUp } from '@mdi/js';
import { LngLatBounds, MapMouseEvent, type PointLike } from 'maplibre-gl';
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue';
import { useMapDataset } from '../../store/dataset-api';
import { useMapHighlight } from '../../store/highlight';
import IdentifyResultControl from './IdentifyResultControl.vue';

const path = {
  icon: mdiHandPointingUp,
};
const props = withDefaults(
  defineProps<
    WithMapPropType &
      WithShowProps & {
        immediately?: boolean;
        /**
         * Always open Identify Result panel (skip auto show-detail / attribute-table),
         * even when those menus are registered.
         */
        preferResultControl?: boolean;
      }
  >(),
  { ...defaultMapProps, preferResultControl: false },
);
const { mapId, moduleContainerProps, order, callMap } = useMap(props);
const { getAllComponentsByType, getDatasetIds } = useMapDataset(mapId.value);
const hl = useMapHighlight(mapId.value);
const { trans, registerLocale } = useLang(mapId.value);
registerLocale('en', IDENTIFY_CONTROL_LOCALE);

const views = ref<Array<IIdentifyView>>([]);
/** Local layer filter for IdentifyControl only (not synced with layer-item). */
const filterIdentifyId = ref<string | undefined>();
const origin = reactive({ latitude: 0, longitude: 0 });
const show = ref(!!props.show);
const loading = ref(false);

function refreshViews() {
  views.value = (
    getAllComponentsByType<IIdentifyView>('identify') || []
  ).reverse();
}
watch(getDatasetIds(), refreshViews, { deep: true, immediate: true });

const hasViews = computed(() => views.value.length > 0);
watch(hasViews, () => {
  control.sync();
});

const {
  add: addEventClick,
  remove: removeEventClick,
  isActive: isEventClickActive,
} = useEventMap(mapId.value, new EventClick().setHandler(onMapClick));
const {
  add: addEventBbox,
  remove: removeEventBbox,
  isActive: isEventClickBox,
} = useEventMap(mapId.value, new EventBboxRanger().setHandler(onBboxSelect));

function setShow(value: boolean) {
  show.value = value;
}

function updateResultPanel(payload: IdentifyResultUpdatePayload) {
  UniversalRegistry.runControlAction(
    mapId.value,
    IDENTIFY_RESULT_CONTROL.id,
    IDENTIFY_RESULT_CONTROL.actionUpdate,
    payload,
  );
}

function syncResultPanel(extra?: IdentifyResultUpdatePayload) {
  updateResultPanel({
    ...buildIdentifyResultPanelBase({
      loading: loading.value,
      origin: { ...origin },
      views: views.value,
      allLayersText: trans.value('map.identify.all_layers'),
      selectedLayerId: filterIdentifyId.value,
      isEventClickActive: isEventClickActive.value,
      isEventClickBox: isEventClickBox.value,
    }),
    ...extra,
  });
}

useRegisterMapControl(mapId, {
  id: IDENTIFY_CONTROL.id,
  panelKind: 'button',
  title: () => trans.value('map.identify.title'),
  buttonPosition: () => props.position,
  show,
  setShow: (value) => {
    setShow(value);
    updateResultPanel({ show: value });
  },
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
    immediately: props.immediately,
        preferResultControl: props.preferResultControl,
  }),
  actions: [
    {
      type: IDENTIFY_CONTROL.id,
      run: () => {
        toggleShow();
      },
    },
    {
      type: IDENTIFY_CONTROL.actionSetScoped,
      run: (event) => {
        applyScopedSession(event as IdentifyScopeToggleResult | undefined);
      },
    },
    {
      type: IDENTIFY_CONTROL.actionUseMapClick,
      run: () => onUseMapClick(),
    },
    {
      type: IDENTIFY_CONTROL.actionUseBoxSelect,
      run: () => onUseBoxSelect(),
    },
    {
      type: IDENTIFY_CONTROL.actionSetLayerFilter,
      run: (event) => {
        const payload = event as IdentifyLayerFilterPayload | undefined;
        onLayerFilterChange(payload?.identifyId ?? '');
      },
    },
    {
      type: IDENTIFY_CONTROL.actionClose,
      run: () => close(),
    },
    {
      type: IDENTIFY_CONTROL.actionSetLoading,
      run: (event) => {
        setIdentifyLoading(!!event);
      },
    },
  ],
});

/** One-way from layer-item: start identify + filter; do not open result popup. */
function applyScopedSession(result?: IdentifyScopeToggleResult) {
  if (result?.active && result.identifyId) {
    filterIdentifyId.value = result.identifyId;
    show.value = true;
    origin.latitude = 0;
    origin.longitude = 0;
    syncResultPanel({
      selectedLayerId: result.identifyId,
      items: [],
      loading: false,
      origin: { latitude: 0, longitude: 0 },
    });
    if (!isUseClick.value) onStartMapClick();
    return;
  }
  if (
    result?.identifyId &&
    filterIdentifyId.value &&
    filterIdentifyId.value === result.identifyId
  ) {
    filterIdentifyId.value = undefined;
    origin.latitude = 0;
    origin.longitude = 0;
    syncResultPanel({
      selectedLayerId: IDENTIFY_ALL_LAYERS_VALUE,
      items: [],
      loading: false,
      origin: { latitude: 0, longitude: 0 },
    });
  }
  if (!props.immediately) onRemoveMapClick();
}

function onLayerFilterChange(identifyId: string) {
  const id = resolveIdentifyLayerFilterId(identifyId);
  filterIdentifyId.value = id;
  syncResultPanel({
    selectedLayerId: id ?? IDENTIFY_ALL_LAYERS_VALUE,
  });
  // Keep map highlight + last click; re-query with the new layer filter.
  if (origin.latitude !== 0 || origin.longitude !== 0) {
    callMap((map) => {
      const point = map.project([origin.longitude, origin.latitude]);
      onGetFeatures({
        point,
        lngLat: { lng: origin.longitude, lat: origin.latitude },
      } as MapMouseEvent);
    });
  }
}

function runIdentifyAt(
  lng: number,
  lat: number,
  point: PointLike,
  event?: MapMouseEvent,
) {
  origin.latitude = lat;
  origin.longitude = lng;
  onGetFeatures(event ?? ({ point, lngLat: { lng, lat } } as MapMouseEvent));
}

function onMapClick(e: MapMouseEvent) {
  if (isEventClickBox.value) return;
  runIdentifyAt(e.lngLat.lng, e.lngLat.lat, e.point, e);
}

function onIdentifyHere(menuProps: MapMenuItemProps) {
  const { lng, lat } = menuProps.layer.lngLat;
  const point = menuProps.layer.point;
  if (point) {
    runIdentifyAt(lng, lat, point);
    return;
  }
  callMap((map) => {
    runIdentifyAt(lng, lat, map.project([lng, lat]));
  });
}

function onBboxSelect(bbox: Parameters<EventBboxRangerHandle>[0]) {
  if (isEventClickActive.value) return;
  onRemoveBox();
  if (!bbox) return;
  const bounds = new LngLatBounds([bbox[0].x, bbox[0].y, bbox[1].x, bbox[1].y]);
  show.value = true;
  onGetFeatures(bounds);
}

async function onGetFeatures(e: MapMouseEvent | LngLatBounds) {
  let pointOrBox: PointLike | [PointLike, PointLike];
  if ('point' in e) {
    pointOrBox = e.point;
  } else {
    pointOrBox = e as unknown as [PointLike, PointLike];
  }

  loading.value = true;
  control.sync();
  callMap((map) => {
    map.getCanvas().style.cursor = 'wait';
  });
  // Keep panel spinner in sync if result panel is already open.
  syncResultPanel({ loading: true });
  try {
    await runIdentifyMulti({
      identifies: views.value,
      mapId: mapId.value,
      pointOrBox,
      event: 'point' in e ? e : undefined,
      filterIdentifyId: filterIdentifyId.value,
      preferResultControl: !!props.preferResultControl,
    });
  } finally {
    loading.value = false;
    control.sync();
    callMap((map) => {
      map.getCanvas().style.cursor = '';
    });
    syncResultPanel({ loading: false });
  }
}

function toggleShow() {
  const next = !show.value;
  show.value = next;
  syncResultPanel({ show: next });
  if (next) {
    if (!isUseClick.value) onStartMapClick();
  } else {
    onRemoveIdentify();
  }
}

function close() {
  filterIdentifyId.value = undefined;
  clearIdentifyScope(mapId.value);
  onRemoveIdentify();
  hl.hideIfSource('identify');
  show.value = false;
  loading.value = false;
  origin.latitude = 0;
  origin.longitude = 0;
  syncResultPanel({
    show: false,
    loading: false,
    origin: { latitude: 0, longitude: 0 },
    selectedLayerId: IDENTIFY_ALL_LAYERS_VALUE,
    items: [],
  });
}

/** Used by IdentifyShowFirstControl via actionSetLoading. */
function setIdentifyLoading(value: boolean) {
  loading.value = value;
  syncResultPanel({ loading: value });
  control.sync();
}

function onRemoveIdentify() {
  if (props.immediately) return;
  onRemoveMapClick();
  onRemoveBox();
}

const isUseClick = ref(false);
let unbindLongPress: (() => void) | null = null;
function onUseMapClick() {
  if (!isUseClick.value) onStartMapClick();
  else onRemoveMapClick();
}
function onStartMapClick() {
  isUseClick.value = true;
  addEventClick();
  syncResultPanel({ isEventClickActive: true });
  unbindLongPress?.();
  unbindLongPress = null;
  if (getMapPointerProfile().coarse) {
    callMap((map) => {
      unbindLongPress = bindMapLongPress(map, {
        onLongPress: (point) => {
          if (isEventClickBox.value) return;
          const lngLat = map.unproject([point.x, point.y]);
          runIdentifyAt(lngLat.lng, lngLat.lat, point);
        },
      });
    });
  }
}
function onRemoveMapClick() {
  isUseClick.value = false;
  removeEventClick();
  unbindLongPress?.();
  unbindLongPress = null;
  syncResultPanel({ isEventClickActive: false });
}

const isSelectBbox = ref(false);
function onUseBoxSelect() {
  if (!isSelectBbox.value) onStartBox();
  else onRemoveBox();
}
function onStartBox() {
  isSelectBbox.value = true;
  addEventBbox();
  syncResultPanel({ isEventClickBox: true });
}
function onRemoveBox() {
  isSelectBbox.value = false;
  setTimeout(() => {
    removeEventBbox();
    syncResultPanel({ isEventClickBox: false });
  }, 500);
}

onMounted(() => {
  if (props.immediately) onUseMapClick();
  syncResultPanel();
});
onUnmounted(() => {
  onRemoveIdentify();
});

UniversalRegistry.registerMenuHandlerForMap(
  mapId.value,
  MAP_CONTEXT_MENU_ID.identifyHere,
  onIdentifyHere,
);

watch(views, () => syncResultPanel(), { deep: true });
watch([isEventClickActive, isEventClickBox], () => syncResultPanel());

const { state, control } = useToolbarControl(mapId.value, props, {
  kind: 'single',
  id: IDENTIFY_CONTROL.id,
  getState() {
    return mdiButtonState(path.icon, {
      visible: hasViews.value,
      active: show.value,
      loading: loading.value,
      title: trans.value('map.identify.title'),
      order: order.value,
    });
  },
  onClick() {
    toggleShow();
  },
});
watch([show, loading], () => control.sync());
</script>

<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>
  </ModuleContainer>
  <IdentifyResultControl
    :position="props.position"
    :control-layout="props.controlLayout"
  />
</template>
