// libs/vue/map-core/src/extra/crs/modules/CrsControl.vue
<script setup lang="ts">
import { type WithMapPropType } from '@hungpvq/map-core';
import {
  buildMapCrsCatalog,
  type CrsItem,
  formatCrsLabel,
  searchCrsCatalog,
} from '@hungpvq/map-core/crs';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiDelete, mdiInboxOutline, mdiPlus } from '@mdi/js';
import { computed, ref, watch } from 'vue';

import { defineProps, withDefaults } from 'vue';
import { Collapse, InputSelect, InputText } from '../../../field';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { useShow, type WithShowProps } from '../../../hooks/useShow';
import ModuleContainer from '../../../modules/ModuleContainer/ModuleContainer.vue';
import { useLang } from '../../lang/hook';
import { useMapControl } from '../../registry/useMapControl';
import { useMapCrsDisplayEpsgs, useMapCrsItems } from '../useMapCrsItems';

const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const { mapId, order } = useMap(props);
const { trans } = useLang(mapId.value);
const [show, setShow] = useShow(props.show);

function onToggleShow() {
  setShow(!show.value);
}
const { items: crs_items, setItems } = useMapCrsItems(mapId.value);
const { displayEpsgs, setDisplayEpsgs } = useMapCrsDisplayEpsgs(mapId.value);
const filterQuery = ref('');

const catalogItems = computed(() => buildMapCrsCatalog(crs_items.value));
const filteredCatalog = computed(() => {
  const q = filterQuery.value.trim();
  if (!q) return catalogItems.value;
  return searchCrsCatalog(catalogItems.value, q);
});
const customItems = computed(() =>
  crs_items.value.filter((item) => !item.default),
);

const unit_items = [
  { text: 'degree', value: 'degree' },
  { text: 'meter', value: 'meter' },
];
const path = {
  delete: mdiDelete,
  plus: mdiPlus,
};

const onRemove = (item: CrsItem) => {
  setItems(crs_items.value.filter((x) => x.epsg !== item.epsg));
  if (displayEpsgs.value.includes(item.epsg)) {
    setDisplayEpsgs(displayEpsgs.value.filter((epsg) => epsg !== item.epsg));
  }
};
const onAdd = () => {
  crs_items.value.push({ name: '', unit: 'degree', epsg: '' });
  setItems(crs_items.value);
};
const patchCustomItem = (item: CrsItem, patch: Partial<CrsItem>) => {
  Object.assign(item, patch);
  setItems([...crs_items.value]);
};
const patchCustomUnit = (
  item: CrsItem,
  value: string | { text: string; value: string } | undefined,
) => {
  const raw =
    value && typeof value === 'object' && 'value' in value
      ? value.value
      : value;
  if (raw === 'meter' || raw === 'degree') {
    patchCustomItem(item, { unit: raw });
  }
};
const isDisplayed = (epsg: string) => displayEpsgs.value.includes(epsg);
const toggleDisplay = (epsg: string, checked: boolean) => {
  if (epsg === '4326') return;
  if (checked) {
    if (!displayEpsgs.value.includes(epsg)) {
      setDisplayEpsgs([...displayEpsgs.value, epsg]);
    }
    return;
  }
  setDisplayEpsgs(displayEpsgs.value.filter((code) => code !== epsg));
};

const singleButton = {
  kind: 'single' as const,
  getState() {
    return mdiButtonState(mdiInboxOutline, {
      visible: true,
      active: show.value,
      title: trans.value('map.crs-control.title'),
      order: order.value,
    });
  },
  onClick() {
    onToggleShow();
  },
};
const { moduleContainerProps, panelBind, control } = useMapControl(mapId, {
  id: 'mapCrsControl',
  panelKind: 'popup',
  title: () => trans.value('map.crs-control.title'),
  from: props,
  order,
  show,
  setShow,
  defaultPanelSize: { width: 400, height: 480 },
  actions: [
    {
      type: 'mapCrsControl',
      run: () => onToggleShow(),
    },
  ],
  host: { button: singleButton },
  toolbar: singleButton,
});
watch(show, () => control.sync());
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="slotProps">
      <DraggableItemPopup
        v-if="show"
        v-bind="{ ...slotProps, ...panelBind }"
        v-model:show="show"
        :title="trans('map.crs-control.title')"
      >
        <div class="crs-container">
          <div class="crs-catalog">
            <input
              v-model="filterQuery"
              type="search"
              class="crs-catalog__filter"
              :placeholder="trans('map.crs-control.filter')"
            />
            <ul class="crs-catalog__list">
              <li
                v-for="item in filteredCatalog"
                :key="item.epsg"
                class="crs-catalog__item"
              >
                <label
                  class="crs-item-header__display"
                  :title="trans('map.crs-display.show')"
                >
                  <input
                    type="checkbox"
                    :checked="isDisplayed(item.epsg)"
                    :disabled="item.epsg === '4326'"
                    @change="
                      toggleDisplay(
                        item.epsg,
                        ($event.target as HTMLInputElement).checked,
                      )
                    "
                  />
                </label>
                <span class="crs-catalog__label">{{
                  formatCrsLabel(item)
                }}</span>
              </li>
            </ul>
          </div>

          <div
            v-if="customItems.length"
            class="crs-custom"
          >
            <div class="crs-custom__title">
              {{ trans('map.crs-control.custom') }}
            </div>
            <div class="crs-custom__list">
              <Collapse
                v-for="(crs_item, index) in customItems"
                :key="crs_item.epsg || `custom-${index}`"
                :selected="false"
              >
                <template #header>
                  <div class="crs-item-header">
                    <div class="crs-item-header__title">
                      {{ crs_item.name || crs_item.epsg || 'New CRS' }}
                    </div>
                    <div class="crs-item-header__action">
                      <button
                        type="button"
                        class="clickable"
                        @click.stop="onRemove(crs_item)"
                      >
                        <SvgIcon
                          size="16"
                          type="mdi"
                          :path="path.delete"
                        />
                      </button>
                    </div>
                  </div>
                </template>
                <div class="crs-item">
                  <div>
                    <InputText
                      :model-value="crs_item.name"
                      :label="trans('map.crs-control.field.name')"
                      @update:model-value="
                        patchCustomItem(crs_item, { name: $event })
                      "
                    />
                  </div>
                  <div>
                    <InputText
                      :model-value="crs_item.epsg"
                      :label="trans('map.crs-control.field.epsg')"
                      @update:model-value="
                        patchCustomItem(crs_item, { epsg: $event })
                      "
                    />
                  </div>
                  <div>
                    <InputText
                      :model-value="crs_item.proj4js"
                      :label="trans('map.crs-control.field.proj4js')"
                      @update:model-value="
                        patchCustomItem(crs_item, { proj4js: $event })
                      "
                    />
                  </div>
                  <div>
                    <InputSelect
                      :model-value="crs_item.unit"
                      :label="trans('map.crs-control.field.unit')"
                      :items="unit_items"
                      @update:model-value="patchCustomUnit(crs_item, $event)"
                    />
                  </div>
                </div>
              </Collapse>
            </div>
          </div>

          <div class="crs-item__add">
            <button
              type="button"
              class="layer-item__button clickable"
              @click.stop="onAdd()"
            >
              <SvgIcon
                size="16"
                type="mdi"
                :path="path.plus"
              />
            </button>
          </div>
        </div>
      </DraggableItemPopup>
    </template>

    <slot />
  </ModuleContainer>
</template>

// libs/react/map-core/src/extra/crs/modules/CrsControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import type { CrsItem } from '@hungpvq/map-core/crs';
import {
  buildMapCrsCatalog,
  formatCrsLabel,
  searchCrsCatalog,
} from '@hungpvq/map-core/crs';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiDelete, mdiInboxOutline, mdiPlus } from '@mdi/js';
import { Icon } from '@mdi/react';
import { useCallback, useEffect, useMemo, useState } from 'react';

import { BaseCollapse, InputSelect, InputText } from '../../../field';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { useShow } from '../../../hooks/useShow';
import { ModuleContainer } from '../../../modules/ModuleContainer/ModuleContainer';
import { useLang } from '../../lang/hook';
import { useMapControl } from '../../registry/useMapControl';
import { useMapCrsDisplayEpsgs, useMapCrsItems } from '../useMapCrsItems';

export interface CrsControlProps extends WithMapPropType {
  show?: boolean;
}

const UNIT_ITEMS = [
  { text: 'degree', value: 'degree' },
  { text: 'meter', value: 'meter' },
] as const;

export function CrsControl(props: CrsControlProps) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, order } = useMap(merged);
  const { trans } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);
  const { items: crsItems, setItems } = useMapCrsItems(mapId);
  const { displayEpsgs, setDisplayEpsgs } = useMapCrsDisplayEpsgs(mapId);
  const [filterQuery, setFilterQuery] = useState('');

  const catalogItems = useMemo(() => buildMapCrsCatalog(crsItems), [crsItems]);
  const filteredCatalog = useMemo(() => {
    const q = filterQuery.trim();
    if (!q) return catalogItems;
    return searchCrsCatalog(catalogItems, q);
  }, [catalogItems, filterQuery]);
  const customItems = useMemo(
    () => crsItems.filter((item) => !item.default),
    [crsItems],
  );

  const handleToggle = useCallback(() => {
    toggleShow(!show);
  }, [show, toggleShow]);

  const singleButton = {
    kind: 'single' as const,
    getState() {
      return mdiButtonState(mdiInboxOutline, {
        visible: true,
        active: show,
        title: trans('map.crs-control.title'),
        order,
      });
    },
    onClick: handleToggle,
  };

  const { moduleContainerProps, panelBind, control } = useMapControl(mapId, {
    id: 'mapCrsControl',
    panelKind: 'popup',
    title: trans('map.crs-control.title'),
    from: merged,
    order,
    show,
    setShow: toggleShow,
    defaultPanelSize: { width: 400, height: 480 },
    actions: [{ type: 'mapCrsControl', run: () => handleToggle() }],
    host: { button: singleButton },
    toolbar: singleButton,
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  const updateCrsItem = useCallback(
    (index: number, patch: Partial<CrsItem>) => {
      Object.assign(crsItems[index], patch);
      setItems([...crsItems]);
    },
    [crsItems, setItems],
  );

  const onRemove = useCallback(
    (item: CrsItem) => {
      setItems(crsItems.filter((x) => x.epsg !== item.epsg));
      if (displayEpsgs.includes(item.epsg)) {
        setDisplayEpsgs(displayEpsgs.filter((epsg) => epsg !== item.epsg));
      }
    },
    [crsItems, displayEpsgs, setDisplayEpsgs, setItems],
  );

  const toggleDisplay = useCallback(
    (epsg: string, checked: boolean) => {
      if (epsg === '4326') return;
      if (checked) {
        if (!displayEpsgs.includes(epsg)) {
          setDisplayEpsgs([...displayEpsgs, epsg]);
        }
        return;
      }
      setDisplayEpsgs(displayEpsgs.filter((code) => code !== epsg));
    },
    [displayEpsgs, setDisplayEpsgs],
  );

  const onAdd = useCallback(() => {
    setItems([...crsItems, { name: '', unit: 'degree', epsg: '' }]);
  }, [crsItems, setItems]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => toggleShow(!!v)}
            title={trans('map.crs-control.title')}
            {...bind}
            {...panelBind}
          >
            <div className="crs-container">
              <div className="crs-catalog">
                <input
                  type="search"
                  className="crs-catalog__filter"
                  value={filterQuery}
                  placeholder={trans('map.crs-control.filter')}
                  onChange={(e) => setFilterQuery(e.target.value)}
                />
                <ul className="crs-catalog__list">
                  {filteredCatalog.map((item) => (
                    <li
                      key={item.epsg}
                      className="crs-catalog__item"
                    >
                      <label
                        className="crs-item-header__display"
                        title={trans('map.crs-display.show')}
                      >
                        <input
                          type="checkbox"
                          checked={displayEpsgs.includes(item.epsg)}
                          disabled={item.epsg === '4326'}
                          onChange={(e) =>
                            toggleDisplay(item.epsg, e.target.checked)
                          }
                        />
                      </label>
                      <span className="crs-catalog__label">
                        {formatCrsLabel(item)}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {customItems.length ? (
                <div className="crs-custom">
                  <div className="crs-custom__title">
                    {trans('map.crs-control.custom')}
                  </div>
                  <div className="crs-custom__list">
                    {customItems.map((crsItem, index) => {
                      const storeIndex = crsItems.indexOf(crsItem);
                      return (
                        <BaseCollapse
                          key={crsItem.epsg || `custom-${index}`}
                          selected={false}
                          header={
                            <div className="crs-item-header">
                              <div className="crs-item-header__title">
                                {crsItem.name || crsItem.epsg || 'New CRS'}
                              </div>
                              <div className="crs-item-header__action">
                                <button
                                  type="button"
                                  className="clickable"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    onRemove(crsItem);
                                  }}
                                >
                                  <Icon
                                    path={mdiDelete}
                                    size="16px"
                                  />
                                </button>
                              </div>
                            </div>
                          }
                        >
                          <div className="crs-item">
                            <div>
                              <InputText
                                value={crsItem.name}
                                label={trans('map.crs-control.field.name')}
                                onChange={(v) =>
                                  updateCrsItem(storeIndex, { name: v })
                                }
                              />
                            </div>
                            <div>
                              <InputText
                                value={crsItem.epsg}
                                label={trans('map.crs-control.field.epsg')}
                                onChange={(v) =>
                                  updateCrsItem(storeIndex, { epsg: v })
                                }
                              />
                            </div>
                            <div>
                              <InputText
                                value={crsItem.proj4js || ''}
                                label={trans('map.crs-control.field.proj4js')}
                                onChange={(v) =>
                                  updateCrsItem(storeIndex, { proj4js: v })
                                }
                              />
                            </div>
                            <div>
                              <InputSelect
                                value={crsItem.unit}
                                label={trans('map.crs-control.field.unit')}
                                items={[...UNIT_ITEMS]}
                                onChange={(v) =>
                                  updateCrsItem(storeIndex, {
                                    unit: v as CrsItem['unit'],
                                  })
                                }
                              />
                            </div>
                          </div>
                        </BaseCollapse>
                      );
                    })}
                  </div>
                </div>
              ) : null}

              <div className="crs-item__add">
                <button
                  type="button"
                  className="crs-item__add-btn clickable"
                  onClick={(e) => {
                    e.stopPropagation();
                    onAdd();
                  }}
                >
                  <Icon
                    path={mdiPlus}
                    size="16px"
                  />
                </button>
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}
