// libs/vue/map-core/src/modules/RegistryControl/RegistryControl.vue
<script lang="ts">
export default {
  name: 'RegistryControl',
};
</script>
<script setup lang="ts">
import {
  filterMapControls,
  type MapControlHandle,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { mdiConsole } from '@mdi/js';
import { computed, onUnmounted, ref, watch } from 'vue';
import MapCommonButton from '../../components/MapCommonButton.vue';
import MapControlButton from '../../components/MapControlButton.vue';
import { useLang } from '../../extra/lang/hook';
import { UniversalRegistry } from '../../extra/registry/plugin';
import { useRegisterMapControl } from '../../extra/registry/useRegisterMapControl';
import { useToolbarControl } from '../../extra/toolbar/helper';
import { InputSelect } from '../../field';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import { useShow, WithShowProps } from '../../hooks/useShow';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';

const CONTROL_ID = 'mapRegistryControl';

const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
  position: 'top-right',
});

const [show, setShow] = useShow(props.show ?? false);
const { mapId, moduleContainerProps, order } = useMap({
  ...props,
  controlId: CONTROL_ID,
});
const { trans } = useLang(mapId.value);
const controls = ref<MapControlHandle[]>([]);
const query = ref('');
const selectedId = ref('');
const actionType = ref('');
let refreshTimer: ReturnType<typeof setInterval> | undefined;

const filtered = computed(() =>
  filterMapControls(controls.value, query.value),
);

const selected = computed(
  () => controls.value.find((ctrl) => ctrl.id === selectedId.value) ?? null,
);

const propsJson = computed(() =>
  selected.value ? JSON.stringify(selected.value.props, null, 2) : '',
);

const actionTypeItems = computed(() => [
  {
    value: '',
    text: trans.value('map.registry-control.actionDefault'),
  },
  ...(selected.value?.actions ?? []).map((action) => ({
    value: action.type,
    text: action.type,
  })),
]);

const { panelBind } = useRegisterMapControl(mapId, {
  id: CONTROL_ID,
  panelKind: 'popup',
  title: () => trans.value('map.registry-control.title'),
  buttonPosition: () => props.position,
  show,
  setShow,
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
  }),
  actions: [
    {
      type: CONTROL_ID,
      run: () => onToggleShow(),
    },
  ],
});

const { state, control } = useToolbarControl(mapId.value, props, {
  id: CONTROL_ID,
  getState() {
    return mdiButtonState(mdiConsole, {
      visible: true,
      active: show.value,
      title: trans.value('map.registry-control.title'),
      order: order.value,
    });
  },
  onClick() {
    onToggleShow();
  },
});

watch(show, () => control.sync());

function onToggleShow() {
  setShow(!show.value);
}

function refresh() {
  if (!mapId.value) return;
  controls.value = UniversalRegistry.listControls(mapId.value);
  if (
    selectedId.value &&
    !controls.value.some((ctrl) => ctrl.id === selectedId.value)
  ) {
    selectedId.value = '';
    actionType.value = '';
  }
}

function select(id: string) {
  selectedId.value = id;
  actionType.value = '';
  refresh();
}

function open() {
  if (!selectedId.value) return;
  UniversalRegistry.openControl(mapId.value, selectedId.value);
  refresh();
}

function close() {
  if (!selectedId.value) return;
  UniversalRegistry.closeControl(mapId.value, selectedId.value);
  refresh();
}

function movePopup() {
  if (!selectedId.value) return;
  UniversalRegistry.setControlPosition(mapId.value, selectedId.value, {
    top: 80 + Math.round(Math.random() * 120),
    right: 60 + Math.round(Math.random() * 80),
  });
  refresh();
}

function toggleSidebarSide() {
  if (!selected.value) return;
  const current = selected.value.getPanelPosition().location || 'left';
  UniversalRegistry.setControlPosition(mapId.value, selected.value.id, {
    location: current === 'left' ? 'right' : 'left',
  });
  refresh();
}

function run() {
  if (!selectedId.value) return;
  UniversalRegistry.runControlAction(
    mapId.value,
    selectedId.value,
    actionType.value || undefined,
  );
  refresh();
}

watch(
  mapId,
  (id) => {
    if (!id) return;
    refresh();
    let n = 0;
    if (refreshTimer) clearInterval(refreshTimer);
    refreshTimer = setInterval(() => {
      refresh();
      n += 1;
      if (n >= 8 && refreshTimer) {
        clearInterval(refreshTimer);
        refreshTimer = undefined;
      }
    }, 250);
  },
  { immediate: true },
);

onUnmounted(() => {
  if (refreshTimer) clearInterval(refreshTimer);
});
</script>

<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      />
    </template>
    <template #draggable="slotProps">
      <DraggableItemPopup
        v-if="show"
        v-model:show="show"
        :title="trans('map.registry-control.title')"
        :height="580"
        :width="400"
        v-bind="{ ...slotProps, ...panelBind }"
      >
        <div
          class="map-registry-control"
          :aria-label="trans('map.registry-control.title')"
        >
          <header class="map-registry-control__header">
            <p class="map-registry-control__hint">
              {{ trans('map.registry-control.hint') }}
            </p>
            <MapControlButton
              class="map-registry-control__btn"
              variant="outlined"
              size="small"
              @click="refresh"
            >
              {{ trans('map.registry-control.refresh') }}
            </MapControlButton>
          </header>

          <input
            v-model="query"
            type="search"
            class="map-registry-control__search"
            :aria-label="trans('map.registry-control.search')"
            :placeholder="trans('map.registry-control.searchPlaceholder')"
          />

          <p v-if="!filtered.length" class="map-registry-control__empty">
            {{ trans('map.registry-control.empty') }}
          </p>
          <ul v-else class="map-registry-control__list">
            <li
              v-for="ctrl in filtered"
              :key="ctrl.id"
              class="map-registry-control__item"
              :class="{ 'is-selected': selectedId === ctrl.id }"
            >
              <MapControlButton
                class="map-registry-control__select"
                variant="plain"
                size="small"
                @click="select(ctrl.id)"
              >
                <strong>{{ ctrl.id }}</strong>
                <span>{{ ctrl.panelKind }}</span>
                <span v-if="ctrl.title">{{ ctrl.title }}</span>
                <span v-if="ctrl.panelKind !== 'button'">
                  {{
                    ctrl.isOpen()
                      ? trans('map.registry-control.openState')
                      : trans('map.registry-control.closedState')
                  }}
                </span>
              </MapControlButton>
            </li>
          </ul>

          <section v-if="selected" class="map-registry-control__detail">
            <h3>{{ selected.id }}</h3>
            <pre class="map-registry-control__props">{{ propsJson }}</pre>

            <div class="map-registry-control__actions">
              <template v-if="selected.panelKind !== 'button'">
                <MapControlButton
                  class="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  @click="open"
                >
                  {{ trans('map.registry-control.open') }}
                </MapControlButton>
                <MapControlButton
                  class="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  @click="close"
                >
                  {{ trans('map.registry-control.close') }}
                </MapControlButton>
                <MapControlButton
                  v-if="
                    selected.panelKind === 'popup' ||
                    selected.panelKind === 'float'
                  "
                  class="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  @click="movePopup"
                >
                  {{ trans('map.registry-control.movePopup') }}
                </MapControlButton>
                <MapControlButton
                  v-if="selected.panelKind === 'sidebar'"
                  class="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  @click="toggleSidebarSide"
                >
                  {{ trans('map.registry-control.toggleSidebar') }}
                </MapControlButton>
              </template>

              <div class="map-registry-control__run">
                <InputSelect
                  v-model="actionType"
                  :label="trans('map.registry-control.actionType')"
                  :items="actionTypeItems"
                  item-value="value"
                  item-text="text"
                />
                <MapControlButton
                  class="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  @click="run"
                >
                  {{ trans('map.registry-control.runAction') }}
                </MapControlButton>
              </div>
            </div>
          </section>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>

// libs/react/map-core/src/modules/RegistryControl/RegistryControl.tsx
import {
  filterMapControls,
  type MapControlHandle,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiConsole } from '@mdi/js';
import { useCallback, useEffect, useMemo, useState } from 'react';

import { MapCommonButton } from '../../components/MapCommonButton';
import { MapControlButton } from '../../components/MapControlButton';
import { useLang } from '../../extra/lang/hook';
import { UniversalRegistry } from '../../extra/registry/plugin';
import { useRegisterMapControl } from '../../extra/registry/useRegisterMapControl';
import { useToolbarControl } from '../../extra/toolbar/helper';
import { InputSelect } from '../../field';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import { useShow } from '../../hooks/useShow';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

export interface RegistryControlProps extends WithMapPropType {
  show?: boolean;
}

const CONTROL_ID = 'mapRegistryControl';

export function RegistryControl(props: RegistryControlProps) {
  const merged = {
    ...defaultMapProps,
    position: 'top-right' as const,
    ...props,
  };
  const { mapId, moduleContainerProps, order } = useMap({
    ...merged,
    controlId: CONTROL_ID,
  });
  const { trans } = useLang(mapId);
  const [show, setShow] = useShow(props.show ?? false);
  const [controls, setControls] = useState<MapControlHandle[]>([]);
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState('');
  const [actionType, setActionType] = useState('');

  const refresh = useCallback(() => {
    if (!mapId) return;
    const next = UniversalRegistry.listControls(mapId);
    setControls(next);
    if (selectedId && !next.some((ctrl) => ctrl.id === selectedId)) {
      setSelectedId('');
      setActionType('');
    }
  }, [mapId, selectedId]);

  useEffect(() => {
    if (!mapId) return;
    refresh();
    let n = 0;
    const timer = setInterval(() => {
      refresh();
      n += 1;
      if (n >= 8) clearInterval(timer);
    }, 250);
    return () => clearInterval(timer);
  }, [mapId, refresh]);

  const filtered = useMemo(
    () => filterMapControls(controls, query),
    [controls, query],
  );

  const selected = useMemo(
    () => controls.find((ctrl) => ctrl.id === selectedId) ?? null,
    [controls, selectedId],
  );

  const propsJson = selected ? JSON.stringify(selected.props, null, 2) : '';

  const actionTypeItems = useMemo(
    () => [
      { value: '', text: trans('map.registry-control.actionDefault') },
      ...(selected?.actions ?? []).map((action) => ({
        value: action.type,
        text: action.type,
      })),
    ],
    [selected, trans],
  );

  const handleToggle = useCallback(() => {
    setShow(!show);
  }, [setShow, show]);

  const { panelBind } = useRegisterMapControl(mapId, {
    id: CONTROL_ID,
    panelKind: 'popup',
    title: trans('map.registry-control.title'),
    buttonPosition: merged.position,
    show,
    setShow,
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
    }),
    actions: [{ type: CONTROL_ID, run: () => handleToggle() }],
  });

  const { state, control } = useToolbarControl(mapId, merged, {
    kind: 'single',
    id: CONTROL_ID,
    getState: () =>
      mdiButtonState(mdiConsole, {
        visible: true,
        active: show,
        title: trans('map.registry-control.title'),
        order,
      }),
    onClick: () => handleToggle(),
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  function open() {
    if (!selectedId) return;
    UniversalRegistry.openControl(mapId, selectedId);
    refresh();
  }

  function close() {
    if (!selectedId) return;
    UniversalRegistry.closeControl(mapId, selectedId);
    refresh();
  }

  function movePopup() {
    if (!selectedId) return;
    UniversalRegistry.setControlPosition(mapId, selectedId, {
      top: 80 + Math.round(Math.random() * 120),
      right: 60 + Math.round(Math.random() * 80),
    });
    refresh();
  }

  function toggleSidebarSide() {
    if (!selected) return;
    const current = selected.getPanelPosition().location || 'left';
    UniversalRegistry.setControlPosition(mapId, selected.id, {
      location: current === 'left' ? 'right' : 'left',
    });
    refresh();
  }

  function run() {
    if (!selectedId) return;
    UniversalRegistry.runControlAction(
      mapId,
      selectedId,
      actionType || undefined,
    );
    refresh();
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(value) => setShow(!!value)}
            title={trans('map.registry-control.title')}
            height={580}
            width={400}
            {...bind}
            {...panelBind}
          >
            <div
              className="map-registry-control"
              aria-label={trans('map.registry-control.title')}
            >
              <header className="map-registry-control__header">
                <p className="map-registry-control__hint">
                  {trans('map.registry-control.hint')}
                </p>
                <MapControlButton
                  className="map-registry-control__btn"
                  variant="outlined"
                  size="small"
                  onClick={refresh}
                >
                  {trans('map.registry-control.refresh')}
                </MapControlButton>
              </header>

              <input
                type="search"
                className="map-registry-control__search"
                value={query}
                aria-label={trans('map.registry-control.search')}
                placeholder={trans('map.registry-control.searchPlaceholder')}
                onChange={(e) => setQuery(e.target.value)}
              />

              {filtered.length === 0 ? (
                <p className="map-registry-control__empty">
                  {trans('map.registry-control.empty')}
                </p>
              ) : (
                <ul className="map-registry-control__list">
                  {filtered.map((ctrl) => (
                    <li
                      key={ctrl.id}
                      className={`map-registry-control__item${
                        selectedId === ctrl.id ? ' is-selected' : ''
                      }`}
                    >
                      <MapControlButton
                        className="map-registry-control__select"
                        variant="plain"
                        size="small"
                        onClick={() => {
                          setSelectedId(ctrl.id);
                          setActionType('');
                          refresh();
                        }}
                      >
                        <strong>{ctrl.id}</strong>
                        <span>{ctrl.panelKind}</span>
                        {ctrl.title ? <span>{ctrl.title}</span> : null}
                        {ctrl.panelKind !== 'button' ? (
                          <span>
                            {ctrl.isOpen()
                              ? trans('map.registry-control.openState')
                              : trans('map.registry-control.closedState')}
                          </span>
                        ) : null}
                      </MapControlButton>
                    </li>
                  ))}
                </ul>
              )}

              {selected ? (
                <section className="map-registry-control__detail">
                  <h3>{selected.id}</h3>
                  <pre className="map-registry-control__props">{propsJson}</pre>

                  <div className="map-registry-control__actions">
                    {selected.panelKind !== 'button' ? (
                      <>
                        <MapControlButton
                          className="map-registry-control__btn"
                          variant="outlined"
                          size="small"
                          onClick={open}
                        >
                          {trans('map.registry-control.open')}
                        </MapControlButton>
                        <MapControlButton
                          className="map-registry-control__btn"
                          variant="outlined"
                          size="small"
                          onClick={close}
                        >
                          {trans('map.registry-control.close')}
                        </MapControlButton>
                        {(selected.panelKind === 'popup' ||
                          selected.panelKind === 'float') && (
                          <MapControlButton
                            className="map-registry-control__btn"
                            variant="outlined"
                            size="small"
                            onClick={movePopup}
                          >
                            {trans('map.registry-control.movePopup')}
                          </MapControlButton>
                        )}
                        {selected.panelKind === 'sidebar' && (
                          <MapControlButton
                            className="map-registry-control__btn"
                            variant="outlined"
                            size="small"
                            onClick={toggleSidebarSide}
                          >
                            {trans('map.registry-control.toggleSidebar')}
                          </MapControlButton>
                        )}
                      </>
                    ) : null}

                    <div className="map-registry-control__run">
                      <InputSelect
                        label={trans('map.registry-control.actionType')}
                        value={actionType}
                        items={actionTypeItems}
                        onChange={(value) => setActionType(String(value))}
                      />
                      <MapControlButton
                        className="map-registry-control__btn"
                        variant="outlined"
                        size="small"
                        onClick={run}
                      >
                        {trans('map.registry-control.runAction')}
                      </MapControlButton>
                    </div>
                  </div>
                </section>
              ) : null}
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}
