// apps/vue/demo-map/src/views/AllMapView.vue
<script setup lang="ts">
import type { MapSimple } from '@hungpvq/map-core';
import { getChartRandomColor } from '@hungpvq/map-core';
import type {
  MeasureActionItem,
  MeasurementHandleType,
} from '@hungpvq/map-core/measurement';
import {
  createDatasetPartListViewUiComponentBuilder,
  createGroupDataset,
  createMultiMapboxLayerComponent,
  createRootDataset,
} from '@hungpvq/map-dataset';
import { createDatasetPartGeojsonSourceComponent } from '@hungpvq/map-dataset/geojson';
import {
  createMenuItemToggleShow,
  createMultiLegend,
} from '@hungpvq/map-dataset/menu';
import {
  LayerSimpleMapboxBuild,
  LayerStyleType,
} from '@hungpvq/map-dataset/style';
import { getUUIDv4 } from '@hungpvq/shared';
import {
  BaseMapCard,
  BaseMapControl,
  CrsControl,
  EventManagementControl,
  FullScreenControl,
  GeoLocateControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  InfoControl,
  LegendControl,
  Map,
  MapContextMenuControl,
  MeasurementControl,
  MouseCoordinatesControl,
  PrintAdvancedControl,
  PrintControl,
  RegistryControl,
  SettingControl,
  ThemeControl,
  ToolbarControl,
  WorkerControl,
  ZoomControl,
} from '@hungpvq/vue-map-core';
import {
  ComponentManagementControl,
  DatasetControl,
  IdentifyControl,
  LayerControl,
  useMapDataset,
} from '@hungpvq/vue-map-dataset';
import { DevtoolsControl } from '@hungpvq/vue-map-devtools';
import { DrawControl, InspectControl } from '@hungpvq/vue-map-draw';
import { mdiPlus } from '@mdi/js';
import { ref } from 'vue';

import DemoLanguageControl from '../components/DemoLanguageControl.vue';
import AsideControl from '../layout/aside-control.vue';

const mapRef = ref();
const mapId = ref(getUUIDv4());

function onMapLoaded(map: MapSimple) {
  mapId.value = map.id;
  const { setMapId } = useMapDataset(mapId.value);
  setMapId(mapId.value);
}

const actionMeasures: MeasureActionItem[] = [
  {
    title: 'add to layer',
    icon: mdiPlus,
    type: 'add-to-layer',
    show: (ctx) => !!ctx.measurementType,
    handle: (ctx) => {
      const { addDataset } = useMapDataset(mapId.value);
      const coordinates = ctx.coordinates;
      if (!coordinates || coordinates.length < 1) {
        return;
      }
      const dataset = createDatasetMeasure(
        ctx.handler,
        ctx.measurementType || '',
      );
      addDataset(dataset);
      ctx.clear();
    },
    disabled: (ctx) => !ctx.coordinates || ctx.coordinates.length < 1,
    index: 0,
  },
];

function convertMeasureTypeToStyleType(
  measurementType: string,
): LayerStyleType {
  switch (measurementType) {
    case 'area':
      return 'area';
    case 'distance':
    case 'line':
      return 'line';
    case 'point':
      return 'point';
    default:
      return 'line';
  }
}

function createDatasetMeasure(
  handler: MeasurementHandleType,
  measurementType: string,
) {
  const result = handler.getResult();
  const dataset = createRootDataset('Dataset Measure');
  const source = createDatasetPartGeojsonSourceComponent('source', {
    type: 'FeatureCollection',
    features: result.features || ([] as any),
  });
  const groupLayer1 = createGroupDataset('Group layer 1');
  const list1 = createDatasetPartListViewUiComponentBuilder(
    'List Measure:' + measurementType,
  )
    .setColor(getChartRandomColor())
    .configDisabledOpacity()
    .configInitShowLegend()
    .setLegend(
      createMultiLegend([
        {
          type: 'text',
          value: {
            text: 'Measure',
            value: (result.format || result.value || 0) + '',
          },
        },
      ]),
    )
    .addMenus([createMenuItemToggleShow()])
    .build();
  const layers = [
    new LayerSimpleMapboxBuild()
      .setStyleType(convertMeasureTypeToStyleType(measurementType || 'line'))
      .setColor(list1.color)
      .build(),
  ];
  const layer1 = createMultiMapboxLayerComponent('Layer Measure', layers);
  groupLayer1.add(layer1);
  groupLayer1.add(list1);
  dataset.add(source);
  dataset.add(groupLayer1);
  return dataset;
}
</script>
<template>
  <Map
    ref="mapRef"
    @mapLoaded="onMapLoaded"
    :mapId="mapId"
    button-in-mobile="toolbar"
  >
    <DevtoolsControl position="bottom-right" />
    <AsideControl position="top-left" />
    <ToolbarControl position="top-left" />
    <ComponentManagementControl />
    <MeasurementControl
      position="top-right"
      :actions="actionMeasures"
    />
    <IdentifyControl position="top-right" />
    <DrawControl position="top-right" />
    <LayerControl
      position="top-left"
      show
    >
      <template #endList="{ mapId }">
        <BaseMapCard
          :mapId="mapId"
          showOpacity
          allow-add-basemap
        />
      </template>
    </LayerControl>
    <InspectControl position="top-right" />
    <PrintAdvancedControl />
    <PrintControl />
    <GotoControl position="top-right" />
    <InfoControl position="top-right" />
    <RegistryControl position="top-right" />
    <WorkerControl position="top-left" />
    <GlobeControl />
    <LegendControl />
    <CrsControl />
    <SettingControl />
    <ThemeControl />
    <DemoLanguageControl />
    <GeoLocateControl />
    <FullScreenControl />
    <ZoomControl />
    <HomeControl />
    <MouseCoordinatesControl />
    <MapContextMenuControl />
    <BaseMapControl
      position="bottom-left"
      allow-add-basemap
    />
    <DatasetControl position="top-left" />
    <EventManagementControl position="top-left" />
  </Map>
</template>

// apps/react/demo-map/src/views/all-map-view.tsx
import type { MapSimple } from '@hungpvq/map-core';
import type { MeasureActionItem } from '@hungpvq/map-core/measurement';
import {
  BaseMapCard,
  BaseMapControl,
  CrsControl,
  EventManagementControl,
  FullScreenControl,
  GeoLocateControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  InfoControl,
  LegendControl,
  Map,
  MapContextMenuControl,
  MeasurementControl,
  MouseCoordinatesControl,
  PrintAdvancedControl,
  PrintControl,
  RegistryControl,
  SettingControl,
  ThemeControl,
  ToolbarControl,
  WorkerControl,
  ZoomControl,
} from '@hungpvq/react-map-core';
import {
  ComponentManagementControl,
  DatasetControl,
  IdentifyControl,
  LayerControl,
  useMapDataset,
} from '@hungpvq/react-map-dataset';
import { DevtoolsControl } from '@hungpvq/react-map-devtools';
import { DrawControl, InspectControl } from '@hungpvq/react-map-draw';
import { mdiPlus } from '@mdi/js';
import { useMemo } from 'react';

import { DemoLanguageControl } from '../components/DemoLanguageControl';
import { MapPageShell } from '../components/MapPageShell';
import { useDatasetRegistry } from '../hooks/useDatasetRegistry';
import { AsideControl } from '../layout/AsideControl';
import { createDatasetMeasure } from './all-map-view-measure';

export function AllMapView() {
  useDatasetRegistry();
  const { addDataset, setMapId } = useMapDataset();

  function onMapLoaded(map: MapSimple) {
    setMapId(map.id);
  }

  const actionMeasures: MeasureActionItem[] = useMemo(
    () => [
      {
        title: 'add to layer',
        icon: mdiPlus,
        type: 'add-to-layer',
        show: (ctx) => !!ctx.measurementType,
        handle: (ctx) => {
          const coordinates = ctx.coordinates;
          if (!coordinates || coordinates.length < 1) {
            return;
          }
          const dataset = createDatasetMeasure(
            ctx.handler,
            ctx.measurementType || '',
          );
          void addDataset(dataset);
          ctx.clear();
        },
        disabled: (ctx) => !ctx.coordinates || ctx.coordinates.length < 1,
        index: 0,
      },
    ],
    [addDataset],
  );

  return (
    <MapPageShell>
      <Map buttonInMobile="toolbar" onMapLoaded={onMapLoaded}>
        <DevtoolsControl position="bottom-right" />
        <AsideControl position="top-left" />
        <ToolbarControl position="top-left" />
        <ComponentManagementControl />
        <MeasurementControl position="top-right" actions={actionMeasures} />
        <IdentifyControl position="top-right" />
        <DrawControl position="top-right" />
        <LayerControl
          position="top-left"
          show
          endList={({ mapId }) => (
            <BaseMapCard mapId={mapId} showOpacity allowAddBasemap />
          )}
        />
        <InspectControl position="top-right" />
        <PrintAdvancedControl />
        <PrintControl />
        <GotoControl position="top-right" />
        <InfoControl position="top-right" />
        <RegistryControl position="top-right" />
        <WorkerControl position="top-left" />
        <GlobeControl />
        <LegendControl />
        <CrsControl />
        <SettingControl />
        <ThemeControl />
        <DemoLanguageControl />
        <GeoLocateControl />
        <FullScreenControl />
        <ZoomControl />
        <HomeControl />
        <MouseCoordinatesControl />
        <MapContextMenuControl />
        <BaseMapControl position="bottom-left" allowAddBasemap />
        <DatasetControl position="top-left" />
        <EventManagementControl position="top-left" />
      </Map>
    </MapPageShell>
  );
}
