// apps/demo-map/src/views/Draw/inspect.vue
<script setup lang="ts">
import { BaseMapControl } from '@hungpvq/vue-map-core';
import { Map } from '@hungpvq/vue-map-core';
import { InspectControl } from '@hungpvq/vue-map-draw';
import AsideControl from '../../layout/aside-control.vue';
</script>
<template>
  <Map>
    <AsideControl position="top-left" />
    <InspectControl position="top-right" />
    <BaseMapControl position="bottom-left" />
  </Map>
</template>

<style></style>

<style>
* {
  padding: 0;
  margin: 0;
}

body,
html,
#root {
  height: 100%;
}
</style>

// apps/react/demo-map/src/views/inspect.tsx
import { BaseMapControl, Map } from '@hungpvq/react-map-core';
import { MapPageShell } from '../components/MapPageShell';
import { AsideControl } from '../layout/AsideControl';
import './stub-page.css';

export function InspectPage() {
  return (
    <MapPageShell>
      <Map>
        <AsideControl position="top-left" />
        <BaseMapControl position="bottom-left" />
      </Map>
      <div className="stub-banner">
        <strong>Draw / InspectControl</strong> requires <code>@hungpvq/vue-map-draw</code> — not
        yet ported to React. Use the Vue demo at <code>/inspect/</code>.
      </div>
    </MapPageShell>
  );
}
