// apps/vue/demo-map/src/views/dataset-list/sample-custom-menu.vue
<template>
  <li
    class="layer-context-menu__item layer-context-menu__item--has-children"
    :class="{ 'is-open': open }"
    @click.stop="open = !open"
  >
    <div class="layer-context-menu__item-icon">
      <SvgIcon size="16" type="mdi" :path="mdiStar" />
    </div>
    <span>{{ 'name' in item ? item.name : 'Sample custom menu' }}</span>
    <div class="layer-context-menu__chevron">
      <SvgIcon size="16" type="mdi" :path="mdiChevronRight" />
    </div>
    <ul class="context-menu layer-context-menu layer-context-menu--submenu">
      <li class="layer-context-menu__item" @click.stop="onLog">
        <div class="layer-context-menu__item-icon">
          <SvgIcon size="16" type="mdi" :path="mdiInformation" />
        </div>
        <span>Log layer (keep open)</span>
      </li>
      <li class="layer-context-menu__item" @click.stop="onDone">
        <div class="layer-context-menu__item-icon">
          <SvgIcon size="16" type="mdi" :path="mdiClose" />
        </div>
        <span>Done (close menu)</span>
      </li>
    </ul>
  </li>
</template>
<script setup lang="ts">
import type { IListViewUI } from '@hungpvq/map-dataset';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import { loggerFactory } from '@hungpvq/shared-log';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiChevronRight, mdiClose, mdiInformation, mdiStar } from '@mdi/js';
import { ref } from 'vue';

defineOptions({ name: 'SampleLayerMenu' });

const logger = loggerFactory.createLogger().setNamespace('demo:list-menu', 2);

const props = defineProps<{
  item: MenuAction<IListViewUI>;
  data?: IListViewUI;
  mapId?: string;
}>();

const emit = defineEmits<{
  close: [];
}>();

const open = ref(false);

function onLog() {
  logger.with({ fn: 'onLog', span: 'menu.action' }).info('layer menu', {
    mapId: props.mapId,
    layerId: props.data?.id,
    layerName: props.data?.getName?.(),
  });
}

function onDone() {
  emit('close');
}
</script>

// apps/react/demo-map/src/views/sample-custom-menu.tsx
import type { IListViewUI } from '@hungpvq/map-dataset';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import { loggerFactory } from '@hungpvq/shared-log';
import { mdiChevronRight, mdiClose, mdiInformation, mdiStar } from '@mdi/js';
import { Icon } from '@mdi/react';
import { useState } from 'react';

const logger = loggerFactory.createLogger().setNamespace('demo:list-menu', 2);

export function SampleCustomMenu({
  item,
  data,
  mapId,
  onClose,
}: {
  item: MenuAction<IListViewUI>;
  data?: IListViewUI;
  mapId?: string;
  onClose?: () => void;
}) {
  const [open, setOpen] = useState(false);
  const name = 'name' in item ? item.name : 'Sample custom menu';

  return (
    <li
      className={[
        'layer-context-menu__item',
        'layer-context-menu__item--has-children',
        open ? 'is-open' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={(event) => {
        event.stopPropagation();
        setOpen((prev) => !prev);
      }}
    >
      <div className="layer-context-menu__item-icon">
        <Icon
          path={mdiStar}
          size="16px"
        />
      </div>
      <span>{name}</span>
      <div className="layer-context-menu__chevron">
        <Icon
          path={mdiChevronRight}
          size="16px"
        />
      </div>
      <ul className="context-menu layer-context-menu layer-context-menu--submenu">
        <li
          className="layer-context-menu__item"
          onClick={(event) => {
            event.stopPropagation();
            logger
              .with({ fn: 'onLog', span: 'menu.action' })
              .info('layer menu', {
                mapId,
                layerId: data?.id,
                layerName: data?.getName?.(),
              });
          }}
        >
          <div className="layer-context-menu__item-icon">
            <Icon
              path={mdiInformation}
              size="16px"
            />
          </div>
          <span>Log layer (keep open)</span>
        </li>
        <li
          className="layer-context-menu__item"
          onClick={(event) => {
            event.stopPropagation();
            onClose?.();
          }}
        >
          <div className="layer-context-menu__item-icon">
            <Icon
              path={mdiClose}
              size="16px"
            />
          </div>
          <span>Done (close menu)</span>
        </li>
      </ul>
    </li>
  );
}
