// libs/react/map-dataset/src/modules/StyleControl/component/TabItem.tsx
import type { Tab } from '@hungpvq/map-dataset/style';
import { MapControlButton } from '@hungpvq/react-map-core';
import type { ComponentType } from 'react';

import { resolveTabProps } from '../style/type/tab-utils';

function resolveComponent(
  factory: unknown,
): ComponentType<Record<string, unknown>> | undefined {
  if (typeof factory !== 'function') return undefined;
  return (factory as () => ComponentType<Record<string, unknown>>)();
}

export function TabItem({
  value,
  text,
  item,
  default_value,
  disabled,
  active,
}: {
  value?: unknown;
  text?: unknown;
  item: Tab;
  default_value?: unknown;
  disabled?: boolean;
  active?: boolean;
}) {
  const Label = resolveComponent(item.component?.label);
  const labelProps = resolveTabProps(item.props?.label, item);
  const defaultShowInItem =
    value != null && value !== ''
      ? value
      : default_value != null && default_value !== ''
        ? default_value
        : 'None';

  return (
    <MapControlButton
      className={`tab-item${active ? ' tab-item-active' : ''}${
        disabled ? ' tab-item-disabled' : ''
      }`}
      disabled={disabled}
      variant="text"
    >
      <div className="tab-item-title" title={String(text ?? '')}>
        {String(text ?? '')}
      </div>
      <div className="tab-item-sub-title" title={String(defaultShowInItem)}>
        {Label ? (
          <Label
            {...labelProps}
            tab={item}
            value={value}
            default_value={default_value}
          />
        ) : (
          <p>{String(defaultShowInItem)}</p>
        )}
      </div>
    </MapControlButton>
  );
}

// libs/vue/map-dataset/src/modules/StyleControl/component/tab-item.vue
<template lang="">
  <MapControlButton
    class="tab-item"
    :class="{ 'tab-item-active': active, 'tab-item-disabled': disabled }"
    :disabled="disabled"
    v-bind="$attrs"
    variant="text"
  >
    <div class="tab-item-title" :title="text">
      {{ text }}
    </div>
    <div class="tab-item-sub-title" :title="defaultShowInItem">
      <p v-if="!item.component || !item.component.label">
        {{ defaultShowInItem }}
      </p>
      <component
        v-else
        :is="item.component.label()"
        v-bind="attrs"
        :tab="item"
        :value="value"
        :default_value="default_value"
      ></component>
    </div>
  </MapControlButton>
</template>
<script setup lang="ts">
import { MapControlButton } from '@hungpvq/vue-map-core';
import { computed } from 'vue';
const props = defineProps({
  value: {},
  text: {},
  item: {
    type: Object,
    default: () => ({ key: '', type: 'unit', unit: 'px' }),
  },
  default_value: {},
  disabled: Boolean,
  active: Boolean,
});
const attrs = computed(() => {
  if (!props.item || !props.item.props || !props.item.props.label) {
    return {};
  }
  if (typeof props.item.props.label == 'function') {
    return props.item.props.label(props.item);
  }
  return props.item.props.label;
});
const defaultShowInItem = computed(() => {
  if (props.value != null && props.value != '') {
    return props.value;
  }
  if (props.default_value != null && props.default_value != '') {
    return props.default_value;
  }
  return 'None';
});
</script>
