// libs/react/map-dataset/src/modules/IdentifyControl/IdentifyControl.tsx
import type { EventBboxRangerHandle, WithMapPropType } from '@hungpvq/map-core';
import {
  EventBboxRanger,
  EventClick,
  logHelper,
} from '@hungpvq/map-core';
import type {
  IDataset,
  IdentifyMultiResult,
  IdentifyResult,
  IIdentifyView,
  MenuAction,
} from '@hungpvq/map-dataset';
import {
  convertFeatureToItem,
  handleMenuAction,
  handleMultiIdentify,
  handleMultiIdentifyGetFirst,
} from '@hungpvq/map-dataset';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import {
  BaseButton,
  MapCommonButton,
  ModuleContainer,
  defaultMapProps,
  useCoordinate,
  useEventMap,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import { mdiCursorPointer, mdiHandPointingUp, mdiSelect } from '@mdi/js';
import Icon from '@mdi/react';
import type { MapMouseEvent, PointLike } from 'maplibre-gl';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { loggerIdentify } from '../../logger';
import { useMapDataset, useMapDatasetHighlight } from '../../store';
import { IdentifyMenuItem } from './IdentifyMenuItem';

const ICON_SIZE = 16 / 24;

interface Grouped {
  id: string;
  name: string;
  items: ({ id: string | number; name?: string; data: unknown } & {
    identify: IIdentifyView;
  })[];
}

function groupItems(items: IdentifyMultiResult[]): Grouped[] {
  const groups: Grouped[] = [];
  const groupExistingIds = new Map<string, Set<string | number>>();

  for (const item of items) {
    let group: Grouped | undefined;
    const groupIdentify = item.identify.group;
    if (groupIdentify) {
      group = groups.find((g) => g.id === groupIdentify.id);
      if (!group) {
        group = { id: groupIdentify.id, name: groupIdentify.name, items: [] };
        groups.push(group);
      }
    } else {
      group = {
        id: item.identify.id,
        name: item.identify.getName(),
        items: [],
      };
      groups.push(group);
    }
    let existingIds = groupExistingIds.get(group.id);
    if (!existingIds) {
      existingIds = new Set<string | number>();
      groupExistingIds.set(group.id, existingIds);
    }

    for (const f of item.features) {
      const fid = f.id;
      if (!existingIds.has(fid)) {
        group.items.push({ ...f, identify: item.identify });
        existingIds.add(fid);
      }
    }
  }
  return groups;
}

export function IdentifyControl(
  props: WithMapPropType & { show?: boolean; immediately?: boolean },
) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps, order } = useMap(merged);
  const { getAllComponentsByType, datasetVersion } = useMapDataset(mapId);
  const { setFeatureHighlight } = useMapDatasetHighlight(mapId);
  const { trans, setLocaleDefault } = useLang(mapId);
  const { format: formatCoordinate } = useCoordinate(mapId);
  const [show, toggleShow] = useShow(!!props.show);
  const [views, setViews] = useState<IIdentifyView[]>([]);
  const [isUseClick, setIsUseClick] = useState(false);
  const [isSelectBbox, setIsSelectBbox] = useState(false);
  const [origin, setOrigin] = useState({ latitude: 0, longitude: 0 });
  const [resultItems, setResultItems] = useState<Grouped[]>([]);
  const [loading, setLoading] = useState(false);

  const viewsRef = useRef(views);
  viewsRef.current = views;
  const showRef = useRef(show);
  showRef.current = show;
  const immediatelyRef = useRef(!!props.immediately);
  immediatelyRef.current = !!props.immediately;
  const isUseClickRef = useRef(isUseClick);
  isUseClickRef.current = isUseClick;
  const isSelectBboxRef = useRef(isSelectBbox);
  isSelectBboxRef.current = isSelectBbox;

  useEffect(() => {
    setLocaleDefault({
      map: {
        identify: {
          title: 'Identify',
          point: 'Point',
          no_selection: 'Please select a point on the map',
          no_data: 'No data found',
          loading: 'Loading...',
        },
      },
    });
  }, [setLocaleDefault]);

  useEffect(() => {
    const next = (
      getAllComponentsByType<IIdentifyView>('identify') || []
    ).reverse();
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getAllComponentsByType]);

  const onMapClickRef = useRef<(e: MapMouseEvent) => void>(() => undefined);
  const onBboxSelectRef = useRef<EventBboxRangerHandle>(() => undefined);

  const clickEvent = useMemo(
    () =>
      new EventClick().setHandler((e: MapMouseEvent) => {
        onMapClickRef.current(e);
      }),
    [],
  );
  const bboxEvent = useMemo(
    () =>
      new EventBboxRanger().setHandler((bbox) => {
        onBboxSelectRef.current(bbox);
      }),
    [],
  );

  const {
    add: addEventClick,
    remove: removeEventClick,
    isActive: isEventClickActive,
  } = useEventMap(mapId, clickEvent, false);
  const {
    add: addEventBbox,
    remove: removeEventBbox,
    isActive: isEventClickBox,
  } = useEventMap(mapId, bboxEvent, false);

  const addEventClickRef = useRef(addEventClick);
  addEventClickRef.current = addEventClick;
  const removeEventClickRef = useRef(removeEventClick);
  removeEventClickRef.current = removeEventClick;
  const addEventBboxRef = useRef(addEventBbox);
  addEventBboxRef.current = addEventBbox;
  const removeEventBboxRef = useRef(removeEventBbox);
  removeEventBboxRef.current = removeEventBbox;

  const onSelectFeatures = useCallback(
    (event?: MapMouseEvent, features: IdentifyMultiResult[] = []) => {
      logHelper(loggerIdentify, mapId, 'MULTI', 'IdentifyControl').debug(
        'onSelectFeatures',
        features,
      );
      setResultItems(groupItems(features));
      if (
        immediatelyRef.current &&
        features[0]?.features?.[0]
      ) {
        const menu = features[0].identify.getMenu('show-detail');
        if (menu) {
          handleMenuAction(menu, {
            event,
            layer: features[0].identify,
            mapId,
            value: features[0].features[0].data,
          });
        }
      }
    },
    [mapId],
  );

  const onGetFeatures = useCallback(
    async (
      pointOrBox: PointLike | [PointLike, PointLike],
      event?: MapMouseEvent,
    ) => {
      setLoading(true);
      try {
        // Always read latest identify views (datasets may load after first mount)
        const identifies = (
          getAllComponentsByType<IIdentifyView>('identify') || []
        ).reverse();
        viewsRef.current = identifies;
        setViews(identifies);
        logHelper(loggerIdentify, mapId, 'MULTI', 'IdentifyControl').debug(
          'onGetFeatures',
          { pointOrBox, identifies },
        );
        const startTime = Date.now();
        const features = await handleMultiIdentify(
          identifies,
          mapId,
          pointOrBox,
        );
        const elapsedTime = Date.now() - startTime;
        if (elapsedTime < 500) {
          await new Promise((resolve) =>
            setTimeout(resolve, 500 - elapsedTime),
          );
        }
        logHelper(loggerIdentify, mapId, 'MULTI', 'IdentifyControl').debug(
          'onGetFeatures',
          { features },
        );
        onSelectFeatures(
          event,
          features.filter(
            (item): item is IdentifyMultiResult =>
              'features' in item && item.features.length > 0,
          ),
        );
      } finally {
        setLoading(false);
      }
    },
    [mapId, onSelectFeatures, getAllComponentsByType],
  );

  const onStartMapClick = useCallback(() => {
    setIsUseClick(true);
    addEventClickRef.current();
  }, []);

  const onRemoveMapClick = useCallback(() => {
    setIsUseClick(false);
    removeEventClickRef.current();
  }, []);

  const onStartBox = useCallback(() => {
    setIsSelectBbox(true);
    addEventBboxRef.current();
  }, []);

  const onRemoveBox = useCallback(() => {
    setIsSelectBbox(false);
    window.setTimeout(() => {
      removeEventBboxRef.current();
    }, 500);
  }, []);

  const onUseMapClick = useCallback(() => {
    if (!isUseClickRef.current) onStartMapClick();
    else onRemoveMapClick();
  }, [onStartMapClick, onRemoveMapClick]);

  const onUseBoxSelect = useCallback(() => {
    if (!isSelectBboxRef.current) onStartBox();
    else onRemoveBox();
  }, [onStartBox, onRemoveBox]);

  const onRemoveIdentify = useCallback(() => {
    if (immediatelyRef.current) return;
    onRemoveMapClick();
    onRemoveBox();
  }, [onRemoveMapClick, onRemoveBox]);

  const close = useCallback(() => {
    onRemoveIdentify();
    setFeatureHighlight(undefined, 'identify');
    onSelectFeatures(undefined, []);
  }, [onRemoveIdentify, setFeatureHighlight, onSelectFeatures]);

  onMapClickRef.current = (e: MapMouseEvent) => {
    if (isEventClickBox) return;
    logHelper(loggerIdentify, mapId, 'MULTI', 'IdentifyControl').debug(
      'onMapClick',
      { event: e },
    );
    setOrigin({ latitude: e.lngLat.lat, longitude: e.lngLat.lng });
    onGetFeatures(e.point, e);
  };

  onBboxSelectRef.current = (bbox) => {
    if (isEventClickActive) return;
    logHelper(loggerIdentify, mapId, 'MULTI', 'IdentifyControl').debug(
      'onBboxSelect',
      bbox,
    );
    onRemoveBox();
    if (!bbox) return;
    onGetFeatures([
      [bbox[0].x, bbox[0].y],
      [bbox[1].x, bbox[1].y],
    ]);
  };

  useEffect(() => {
    if (props.immediately) onUseMapClick();
    // start click-to-identify once when immediately is set
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleToggle() {
    toggleShow();
    onUseMapClick();
  }

  function onMenuAction(
    identify: IIdentifyView,
    menu: MenuAction,
    item: unknown,
    event?: MapMouseEvent | React.MouseEvent,
  ) {
    const nativeEvent =
      event && 'nativeEvent' in event ? event.nativeEvent : event;
    handleMenuAction(menu, {
      event: nativeEvent,
      layer: identify,
      mapId,
      value: item,
    });
  }

  function onFeatureClick(
    identify: IIdentifyView,
    item: unknown,
    event?: React.MouseEvent,
  ) {
    const menu = identify.getMenu?.('show-detail');
    if (menu) {
      onMenuAction(identify, menu, item, event);
      return;
    }
    if (identify.showDetail) {
      identify.showDetail(mapId, item as never);
    }
  }

  const currentPoint = useMemo(() => {
    const point = formatCoordinate(origin);
    return `${point.longitude}, &nbsp;${point.latitude}`;
  }, [origin, formatCoordinate]);

  const hasSelectedPoint = origin.latitude !== 0 || origin.longitude !== 0;

  const toolbarConfig = useMemo(
    () => ({
      kind: 'single' as const,
      id: 'mapIdentifyControl',
      getState: () => ({
        visible: viewsRef.current.length > 0,
        active: showRef.current,
        title: trans('map.identify.title'),
        order,
        icon: { type: 'mdi' as const, path: mdiHandPointingUp },
      }),
      onClick: () => handleToggle(),
    }),
    // handleToggle is stable enough via refs; sync toolbar when show/views change separately.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [trans, order],
  );

  const { state, control } = useToolbarControl(mapId, merged, toolbarConfig);

  useEffect(() => {
    control.sync();
  }, [show, views.length, control]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => {
              // Only sync visibility — do not clear results here.
              // Clearing is handled by onClose when the user dismisses the popup.
              if (!v) toggleShow(false);
              else toggleShow(true);
            }}
            onClose={close}
            title={trans('map.identify.title')}
            width={400}
            height={300}
            extraBtn={
              <>
                <BaseButton
                  active={isEventClickActive}
                  disabled={isEventClickActive}
                  onClick={(e) => {
                    e.stopPropagation();
                    onUseMapClick();
                  }}
                >
                  <Icon path={mdiCursorPointer} size={ICON_SIZE} />
                </BaseButton>
                <BaseButton
                  active={isEventClickBox}
                  disabled={isEventClickBox}
                  onClick={(e) => {
                    e.stopPropagation();
                    onUseBoxSelect();
                  }}
                >
                  <Icon path={mdiSelect} size={ICON_SIZE} />
                </BaseButton>
              </>
            }
            {...bind}
          >
            <div className="identify-control-container">
              <div className="identify-control-header">
                <b>{trans('map.identify.point')}:</b>
                <span dangerouslySetInnerHTML={{ __html: currentPoint }} />
              </div>
              <hr className="identify-control-separator" />
              <div className="identify-control-body">
                {loading ? (
                  <div className="identify-control-state">
                    <div className="identify-control-state__content">
                      <div className="identify-control-state__loading" />
                      <span>{trans('map.identify.loading')}</span>
                    </div>
                  </div>
                ) : !hasSelectedPoint ? (
                  <div className="identify-control-state">
                    <div className="identify-control-state__content">
                      <span>{trans('map.identify.no_selection')}</span>
                    </div>
                  </div>
                ) : resultItems.length === 0 ? (
                  <div className="identify-control-state">
                    <div className="identify-control-state__content">
                      <span>{trans('map.identify.no_data')}</span>
                    </div>
                  </div>
                ) : (
                  resultItems.map((item) => (
                    <div key={item.id} className="identify-control-list-item">
                      <div className="identify-control-list-item__container">
                        <div
                          className="identify-control-list-item__header"
                          title={item.name}
                        >
                          {item.name || '---'}
                        </div>
                        <div className="identify-control-list-item__child-container">
                          {item.items.map((child) => (
                            <div
                              key={String(child.id)}
                              className="identify-control-child-item"
                              title={child.name || String(child.id)}
                              role="button"
                              tabIndex={0}
                              onClick={(event) =>
                                onFeatureClick(child.identify, child.data, event)
                              }
                              onKeyDown={(event) => {
                                if (event.key === 'Enter' || event.key === ' ') {
                                  event.preventDefault();
                                  onFeatureClick(child.identify, child.data);
                                }
                              }}
                            >
                              <span className="identify-control-child-item__name">
                                {child.name || String(child.id) || '---'}
                              </span>
                              <div className="identify-control-child-item__spacer" />
                              <div
                                className="identify-control-child-item__action"
                                onClick={(e) => e.stopPropagation()}
                              >
                                {child.identify.getMenus().map((menu, i) => (
                                  <IdentifyMenuItem
                                    key={i}
                                    item={menu}
                                    onClick={(event) =>
                                      onMenuAction(
                                        child.identify,
                                        menu,
                                        child.data,
                                        event,
                                      )
                                    }
                                  />
                                ))}
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

export function IdentifyShowFirstControl(props: WithMapPropType) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId } = useMap(merged);
  const { getAllComponentsByType, datasetVersion } = useMapDataset(mapId);
  const [views, setViews] = useState<Array<IIdentifyView & IDataset>>([]);
  const viewsRef = useRef(views);
  viewsRef.current = views;

  useEffect(() => {
    const next =
      getAllComponentsByType<IIdentifyView & IDataset>('identify') || [];
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getAllComponentsByType]);

  const onMapClickRef = useRef<(e: MapMouseEvent) => void>(() => undefined);

  const clickEvent = useMemo(
    () =>
      new EventClick().setHandler((e: MapMouseEvent) => {
        onMapClickRef.current(e);
      }),
    [],
  );

  const { add: addEventClick, remove: removeEventClick } = useEventMap(
    mapId,
    clickEvent,
    false,
  );

  onMapClickRef.current = (e: MapMouseEvent) => {
    logHelper(
      loggerIdentify,
      mapId,
      'FIRST',
      'IdentifyShowFirstControl',
    ).debug('onMapClick', { event: e });
    void onGetFeatures(e);
  };

  async function onGetFeatures(e: MapMouseEvent) {
    const pointOrBox = e.point;
    logHelper(
      loggerIdentify,
      mapId,
      'FIRST',
      'IdentifyShowFirstControl',
    ).debug('onGetFeatures', { pointOrBox });
    try {
      const feature = await handleMultiIdentifyGetFirst(
        viewsRef.current,
        mapId,
        pointOrBox,
      );
      logHelper(
        loggerIdentify,
        mapId,
        'FIRST',
        'IdentifyShowFirstControl',
      ).debug('onGetFeatures', { feature });
      onSelectFeatures(feature, e);
    } catch {
      // no feature under cursor
    }
  }

  function onSelectFeatures(feature: IdentifyResult, event?: MapMouseEvent) {
    logHelper(
      loggerIdentify,
      mapId,
      'FIRST',
      'IdentifyShowFirstControl',
    ).debug('onSelectFeatures', { feature });
    if (feature && 'feature' in feature && feature.feature) {
      const menu = feature.identify.getMenu('show-detail');
      if (menu) {
        handleMenuAction(menu, {
          event,
          layer: feature.identify,
          mapId,
          value: convertFeatureToItem(feature.feature.data),
        });
      } else if (feature.identify.showDetail) {
        feature.identify.showDetail(mapId, feature.feature.data);
      }
    }
  }

  useEffect(() => {
    addEventClick();
    return () => removeEventClick();
  }, [addEventClick, removeEventClick]);

  return null;
}

// libs/map/dataset/src/modules/IdentifyControl/IdentifyControl.vue
<script lang="ts">
export default {
  name: 'InspectControl',
};
</script>

<script setup lang="ts">
import { logHelper } from '@hungpvq/shared-map';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import {
  BaseButton,
  defaultMapProps,
  EventBboxRanger,
  EventBboxRangerHandle,
  EventClick,
  MapCommonButton,
  ModuleContainer,
  useCoordinate,
  useEventMap,
  useLang,
  useMap,
  useToolbarControl,
  WithMapPropType,
  WithShowProps,
} from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCursorPointer, mdiHandPointingUp, mdiSelect } from '@mdi/js';
import { LngLatBounds, MapMouseEvent, type PointLike } from 'maplibre-gl';
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { handleMenuAction } from '../../extra/menu';
import type {
  IdentifyMultiResult,
  IIdentifyView,
  MenuAction,
} from '../../interfaces/dataset.parts';
import { loggerIdentify } from '../../logger';
import { handleMultiIdentify } from '../../model';
import { useMapDataset } from '../../store';
import { useMapDatasetHighlight } from '../../store/highlight';
import MenuItem from './menu/index.vue';

const path = {
  icon: mdiHandPointingUp,
  boxSelect: mdiSelect,
  mapClick: mdiCursorPointer,
};
const props = withDefaults(
  defineProps<
    WithMapPropType &
      WithShowProps & {
        immediately?: boolean;
      }
  >(),
  { ...defaultMapProps },
);
const { mapId, moduleContainerProps, order } = useMap(props);
const { getAllComponentsByType, getDatasetIds } = useMapDataset(mapId.value);
const { setFeatureHighlight } = useMapDatasetHighlight(mapId.value);
const { trans, setLocaleDefault } = useLang(mapId.value);
const { format: formatCoordinate } = useCoordinate(mapId.value);
setLocaleDefault({
  map: {
    identify: {
      title: 'Identify',
      point: 'Point',
      no_selection: 'Please select a point on the map',
      no_data: 'No data found',
      loading: 'Loading...',
    },
  },
});
const views = ref<Array<IIdentifyView>>([]);
const datasetIds = computed(() => {
  return getDatasetIds().value;
});
watch(
  datasetIds,
  () => {
    updateList();
  },
  { deep: true },
);
onMounted(() => {
  updateList();
});
const cUsedIdentify = computed(() => {
  return views.value;
});
function updateList() {
  getViewFromStore();
}
function getViewFromStore() {
  views.value = (
    getAllComponentsByType<IIdentifyView>('identify') || []
  ).reverse();
}
const hasViews = computed(() => {
  return views.value.length > 0;
});
const {
  add: addEventClick,
  remove: removeEventClick,
  isActive: isEventClickActive,
} = useEventMap(mapId.value, new EventClick().setHandler(onMapClick));
const {
  add: addEventBbox,
  remove: removeEventBbox,
  isActive: isEventClickBox,
} = useEventMap(mapId.value, new EventBboxRanger().setHandler(onBboxSelect));

const origin = reactive({ latitude: 0, longitude: 0 });
function onMapClick(e: MapMouseEvent) {
  if (isEventClickBox.value) return;
  logHelper(loggerIdentify, mapId.value, 'MULTI', 'IdentifyControl').debug(
    'onMapClick',
    { event: e },
  );
  origin.latitude = e.lngLat.lat;
  origin.longitude = e.lngLat.lng;
  onGetFeatures(e);
}
function onBboxSelect(bbox: Parameters<EventBboxRangerHandle>[0]) {
  if (isEventClickActive.value) return;
  logHelper(loggerIdentify, mapId.value, 'MULTI', 'IdentifyControl').debug(
    'onBboxSelect',
    bbox,
  );
  onRemoveBox();
  if (!bbox) return;

  const bounds = new LngLatBounds([bbox[0].x, bbox[0].y, bbox[1].x, bbox[1].y]);
  onGetFeatures(bounds);
}
const result = reactive<{
  items: Grouped[];
  loading: boolean;
}>({
  items: [],
  loading: false,
});
const currentPoint = computed(() => {
  if (!origin) {
    return '';
  }
  const point = formatCoordinate(origin);
  return point.longitude + ', &nbsp;' + point.latitude;
});
const hasSelectedPoint = computed(() => {
  return origin.latitude !== 0 || origin.longitude !== 0;
});
function onSelectFeatures(
  event?: MapMouseEvent,
  features: IdentifyMultiResult[] = [],
) {
  logHelper(loggerIdentify, mapId.value, 'MULTI', 'IdentifyControl').debug(
    'onSelectFeatures',
    features,
  );
  result.items = groupItems(features);
  if (
    props.immediately &&
    features &&
    features[0] &&
    features[0].features &&
    features[0].features[0]
  ) {
    const menu = features[0].identify.getMenu('show-detail');
    if (menu)
      onMenuAction(
        features[0].identify,
        menu,
        features[0].features[0].data,
        event,
      );
  }
}
async function onGetFeatures(e: MapMouseEvent | LngLatBounds) {
  let pointOrBox: PointLike | [PointLike, PointLike];
  if ('point' in e) {
    pointOrBox = e.point;
  } else {
    // Convert LngLatBounds to PointLike box
    // This assumes the map instance is available or handleMultiIdentify can handle bounds.
    // However, coordinate-to-point conversion needs the map.
    // For now, let's keep it as is if handleMultiIdentify handles unknown types loosely,
    // but better to cast specifically.
    pointOrBox = e as unknown as [PointLike, PointLike];
  }

  result.loading = true;
  try {
    logHelper(loggerIdentify, mapId.value, 'MULTI', 'IdentifyControl').debug(
      'onGetFeatures',
      { pointOrBox, identifies: cUsedIdentify.value },
    );
    const startTime = Date.now();
    const features = await handleMultiIdentify(
      cUsedIdentify.value,
      mapId.value,
      pointOrBox,
    );
    const elapsedTime = Date.now() - startTime;
    if (elapsedTime < 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 - elapsedTime));
    }
    logHelper(loggerIdentify, mapId.value, 'MULTI', 'IdentifyControl').debug(
      'onGetFeatures',
      { features },
    );
    onSelectFeatures(
      'point' in e ? e : undefined,
      features.filter(
        (item): item is IdentifyMultiResult =>
          'features' in item && item.features.length > 0,
      ),
    );
  } finally {
    result.loading = false;
  }
}
const show = ref(props.show);
function toggleShow() {
  show.value = !show.value;
  onUseMapClick();
}
function close() {
  onRemoveIdentify();
  setFeatureHighlight(undefined, 'identify');
  onSelectFeatures(undefined, []);
}
function onRemoveIdentify() {
  if (props.immediately) {
    return;
  }
  onRemoveMapClick();
  onRemoveBox();
}

const isUseClick = ref(false);
function onUseMapClick() {
  if (!isUseClick.value) {
    onStartMapClick();
  } else {
    onRemoveMapClick();
  }
}
function onStartMapClick() {
  isUseClick.value = true;
  addEventClick();
}
function onRemoveMapClick() {
  isUseClick.value = false;
  removeEventClick();
}
const isSelectBbox = ref(false);
function onUseBoxSelect() {
  if (!isSelectBbox.value) {
    onStartBox();
  } else {
    onRemoveBox();
  }
}
function onStartBox() {
  isSelectBbox.value = true;
  addEventBbox();
}
function onRemoveBox() {
  isSelectBbox.value = false;
  setTimeout(() => {
    removeEventBbox();
  }, 500);
}

function onMenuAction(
  identify: IIdentifyView,
  menu: MenuAction,
  item: unknown,
  event?: MapMouseEvent | MouseEvent,
) {
  handleMenuAction(menu, {
    event,
    layer: identify,
    mapId: mapId.value,
    value: item,
  });
}
onMounted(() => {
  if (props.immediately) onUseMapClick();
});
interface Grouped {
  id: string;
  name: string;
  items: ({ id: string | number; name?: string; data: unknown } & {
    identify: IIdentifyView;
  })[];
}
function groupItems(items: IdentifyMultiResult[]): Grouped[] {
  const groups: Grouped[] = [];
  const groupExistingIds = new Map<string, Set<string | number>>();

  for (const item of items) {
    let group: Grouped | undefined;
    const groupIdentify = item.identify.group;
    if (groupIdentify) {
      group = groups.find((g) => g.id === groupIdentify.id);
      if (!group) {
        group = { id: groupIdentify.id, name: groupIdentify.name, items: [] };
        groups.push(group);
      }
    } else {
      group = {
        id: item.identify.id,
        name: item.identify.getName(),
        items: [],
      };
      groups.push(group);
    }
    let existingIds = groupExistingIds.get(group.id);
    if (!existingIds) {
      existingIds = new Set<string | number>();
      groupExistingIds.set(group.id, existingIds);
    }

    // gộp features + add identify
    for (const f of item.features) {
      const fid = f.id;

      if (!existingIds.has(fid)) {
        group.items.push({ ...f, identify: item.identify });
        existingIds.add(fid);
      }
    }
  }
  return groups;
}
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapIdentifyControl',
  getState() {
    return {
      visible: hasViews.value,
      active: show.value,
      title: trans.value('map.identify.title'),
      order: order.value,
      icon: {
        type: 'mdi',
        path: path.icon,
      },
    };
  },
  onClick() {
    toggleShow();
  },
});
watch(show, () => control.sync());
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>

    <template #draggable="p">
      <DraggableItemPopup
        v-if="show"
        v-model:show="show"
        v-bind="p"
        :width="400"
        :height="300"
        @close="close"
        :title="trans('map.identify.title')"
      >
        <template #extra-btn>
          <BaseButton
            @click.stop="onUseMapClick()"
            :active="isEventClickActive"
            :disabled="isEventClickActive"
          >
            <SvgIcon size="16" type="mdi" :path="path.mapClick" />
          </BaseButton>
          <BaseButton
            @click.stop="onUseBoxSelect()"
            :active="isEventClickBox"
            :disabled="isEventClickBox"
          >
            <SvgIcon size="16" type="mdi" :path="path.boxSelect" />
          </BaseButton>
        </template>
        <div class="identify-control-container">
          <div class="identify-control-header">
            <b>{{ trans('map.identify.point') }}:</b>
            <span v-html="currentPoint"> </span>
          </div>
          <hr class="identify-control-separator" />
          <div class="identify-control-body">
            <!-- Loading state -->
            <div v-if="result.loading" class="identify-control-state">
              <div class="identify-control-state__content">
                <div class="identify-control-state__loading"></div>
                <span>{{ trans('map.identify.loading') }}</span>
              </div>
            </div>
            <!-- No selection state -->
            <div v-else-if="!hasSelectedPoint" class="identify-control-state">
              <div class="identify-control-state__content">
                <span>{{ trans('map.identify.no_selection') }}</span>
              </div>
            </div>

            <!-- Empty result state -->
            <div
              v-else-if="result.items.length === 0"
              class="identify-control-state"
            >
              <div class="identify-control-state__content">
                <span>{{ trans('map.identify.no_data') }}</span>
              </div>
            </div>

            <!-- Results list -->
            <template v-else>
              <div
                v-for="item in result.items"
                :key="item.id"
                class="identify-control-list-item"
              >
                <div class="identify-control-list-item__container">
                  <div
                    class="identify-control-list-item__header"
                    :title="item.name"
                  >
                    {{ item.name || '---' }}
                  </div>
                  <div class="identify-control-list-item__child-container">
                    <div
                      class="identify-control-child-item"
                      v-for="child in item.items"
                      :key="child.id"
                      :title="child.name"
                    >
                      <span class="identify-control-child-item__name">
                        {{ child.name }}
                      </span>
                      <div class="identify-control-child-item__spacer"></div>
                      <div class="identify-control-child-item__action">
                        <template
                          v-for="(menu, i) in child.identify.getMenus()"
                          :key="i"
                        >
                          <MenuItem
                            :item="menu"
                            @click="
                              onMenuAction(
                                child.identify,
                                menu,
                                child.data,
                                $event,
                              )
                            "
                          />
                        </template>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </template>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
  </ModuleContainer>
</template>
<style>
.boxdraw {
  border: dashed 2px black;
  background-color: var(--map-identify-box-bg, rgba(255, 255, 255, 0.19));
}
</style>
<style scoped lang="scss">
.identify-control__button {
  display: inline-flex;
  min-width: 20px;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.identify-control {
  &-container {
    display: flex;
    flex-direction: column;
    height: 100%;

    b {
      color: var(--map-identify-primary, var(--map-primary-color, #1a73e8));
      padding-right: 4px;
      font-weight: bolder;
    }
  }

  &-header {
    padding: 8px;
    width: 100%;
    flex: 0 0 auto;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    box-sizing: border-box;
  }

  &-separator {
    flex: 0 0 auto;
    display: block;
    flex: 1 1 0px;
    max-width: 100%;
    height: 0;
    max-height: 0;
    border: solid;
    border-width: thin 0 0 0;
  }

  &-body {
    flex-grow: 1;
    overflow: auto;
    padding: 16px;
  }

  &-list-item {
    // box-shadow: 0 3px 1px -2px rgba(0, 0, 0, 0.2),
    //   0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12);
    display: block;
    max-width: 100%;
    position: relative;
    padding: 4px;
    border: solid;
    border-width: thin;
    margin-bottom: 4px;

    &__header {
      color: var(--map-identify-primary, var(--map-primary-color, #1a73e8));
      font-weight: bolder;
      white-space: nowrap !important;
      overflow: hidden !important;
      text-overflow: ellipsis !important;
      font-size: 1rem !important;
      line-height: 1.75rem;
      letter-spacing: 0.009375em !important;
    }

    &__container {
      display: flex;
      letter-spacing: normal;
      min-height: 30px;
      outline: none;
      padding: 8px;
      position: relative;
      flex-direction: column;
    }
    &__child-container {
      display: flex;
      letter-spacing: normal;
      min-height: 30px;
      outline: none;
      position: relative;
      flex-direction: column;
      gap: 4px;
    }
  }

  &-child-item {
    flex-grow: 0;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;

    &__spacer {
      flex-grow: 1;
    }

    &__action {
      flex-grow: 0;
      flex-shrink: 0;
    }
  }
}
.identify-control-child-item {
  min-height: 30px;
  display: flex;
  align-items: center;
  border: solid;
  border-width: thin;
  padding: 8px;
}
.identify-control-state {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;

  &__content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
  }

  &__loading {
    width: 24px;
    height: 24px;
    border: 2px solid
      var(--map-identify-primary, var(--map-primary-color, #1a73e8));
    border-radius: 50%;
    border-right-color: transparent;
    animation: spin 1s linear infinite;
  }
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
}
.identify-control-child-item__name {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
