// libs/react/map-dataset/src/modules/CreateControl/CreateControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { CREATE_CONTROL_LOCALE, LAYER_TYPES, LayerHelper, loadCreateControlDraft, reportCreateLayerError, saveCreateControlDraft, suggestLayerName, type LayerType } from '@hungpvq/map-dataset/create-control';
import { defaultMapProps, MapControlButton, ModuleContainer, useLang, useMap, useRegisterMapControl } from '@hungpvq/react-map-core';
import { InputSelect, InputText } from '@hungpvq/react-map-core/fields';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useMapDataset } from '../../store/dataset-api';
import {
  CreateConfigForm,
  createControlComponentKey,
  hasCreateConfigSettings,
} from './config/CreateConfigForm';

export interface CreateControlProps extends WithMapPropType {
  show: boolean;
  onShowChange: (show: boolean) => void;
}

export function CreateControl(props: CreateControlProps) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps } = useMap({ ...merged, controlId: 'mapCreateControl' });
  const { trans, setLocaleDefault } = useLang(mapId);
  const { panelBind } = useRegisterMapControl(mapId, {
    id: 'mapCreateControl',
    panelKind: 'popup',
    title: trans('map.layer-control.create.title'),
    buttonPosition: merged.position,
    show: props.show,
    setShow: props.onShowChange,
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
    }),
    actions: [
      {
        type: 'mapCreateControl',
        run: () => props.onShowChange(!props.show),
      },
    ],
  });
  const localeInitialized = useRef(false);
  if (!localeInitialized.current) {
    setLocaleDefault(CREATE_CONTROL_LOCALE);
    localeInitialized.current = true;
  }

  const { addDataset } = useMapDataset(mapId);
  const initialType: LayerType = 'vector';
  const [helper, setHelper] = useState(() => new LayerHelper(initialType));
  const [configKey, setConfigKey] = useState(0);
  const [form, setForm] = useState<{ type: LayerType; config: Record<string, unknown> }>({
    type: initialType,
    config: { name: suggestLayerName(initialType), ...helper.default_value },
  });

  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState('');
  const [validationErrors, setValidationErrors] = useState<string[]>([]);

  const itemsType = useMemo(
    () => (Object.keys(LAYER_TYPES) as LayerType[]).map((x) => ({ value: x, text: LAYER_TYPES[x] })),
    [],
  );

  function onChangeType(type: string) {
    const layerType = type as LayerType;
    const nextHelper = new LayerHelper(layerType);
    const prevSuggested = suggestLayerName(form.type);
    const keepName = form.config.name && form.config.name !== prevSuggested;

    setHelper(nextHelper);
    setValidationErrors([]);
    setCreateError('');
    setForm((prev) => ({
      type: layerType,
      config: {
        name: keepName ? prev.config.name : suggestLayerName(layerType),
        ...nextHelper.default_value,
      },
    }));
    setConfigKey((k) => k + 1);
  }

  async function onAddLayer() {
    if (creating) return;
    const errors = helper.validationErrors(form.config);
    setValidationErrors(errors);
    if (errors.length) return;
    const name = String(form.config.name ?? '');
    setCreating(true);
    setCreateError('');
    try {
      addDataset(await helper.create({ ...form.config, name }));
      reset();
      props.onShowChange(false);
    } catch (err) {
      const mapError = reportCreateLayerError(err, {
        crs: typeof form.config.crs === 'string' ? form.config.crs : undefined,
        layerType: form.type,
        name,
      });
      setCreateError(
        mapError.message ||
          (mapError.context?.['reason'] === 'too_deep_or_circular_or_large'
            ? trans('map.layer-control.create.create-error-data-too-large')
            : trans('map.layer-control.create.create-error')),
      );
    } finally {
      setCreating(false);
    }
  }

  function reset() {
    const nextHelper = new LayerHelper(initialType);
    setHelper(nextHelper);
    setConfigKey((k) => k + 1);
    setCreating(false);
    setCreateError('');
    setValidationErrors([]);
    setForm({
      type: initialType,
      config: { name: suggestLayerName(initialType), ...nextHelper.default_value },
    });
  }

  useEffect(() => {
    const draft = loadCreateControlDraft(mapId);
    if (draft) {
      if (draft.type === 'vector' || draft.type === 'raster') {
        onChangeType(draft.type);
      }
      setForm((prev) => ({
        ...prev,
        config: {
          ...prev.config,
          ...(draft.name ? { name: draft.name } : {}),
          ...(draft.crs ? { crs: draft.crs } : {}),
        },
      }));
      return;
    }
    onChangeType(initialType);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    saveCreateControlDraft(mapId, {
      type: form.type,
      name: typeof form.config.name === 'string' ? form.config.name : undefined,
      crs: typeof form.config.crs === 'string' ? form.config.crs : undefined,
    });
  }, [form.type, form.config.name, form.config.crs, mapId]);

  const componentKey = createControlComponentKey(form.type);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        props.show ? (
          <DraggableItemPopup
            {...bind}
            {...panelBind}
            show={props.show}
            onUpdateShow={(v) => {
              if (!v) reset();
              props.onShowChange(!!v);
            }}
            title={trans('map.layer-control.create.title')}
            width={400}
            height={420}
          >
            <div className="create-control-container">
              <div className="create-control-form map-row">
                <div className="map-col-12">
                  <InputSelect
                    label={trans('map.layer-control.field.layer-type')}
                    value={form.type}
                    items={itemsType}
                    onChange={(v) => onChangeType(String(v))}
                  />
                </div>

                <div className="map-col-12">
                  <InputText
                    label={trans('map.layer-control.field.layer-name')}
                    value={String(form.config.name ?? '')}
                    onChange={(v) => setForm({ ...form, config: { ...form.config, name: v } })}
                  />
                </div>

                <div className="map-col-12 create-control-section-label">
                  {trans('map.layer-control.create.data-source')}
                </div>

                <CreateConfigForm
                  key={`${configKey}-data`}
                  section="data"
                  componentKey={componentKey}
                  config={form.config}
                  trans={trans}
                  onChange={(patch) =>
                    setForm({ ...form, config: { ...form.config, ...patch } })
                  }
                />

                {hasCreateConfigSettings(componentKey) ? (
                  <>
                    <div className="map-col-12 create-control-section-label">
                      {trans('map.layer-control.create.layer-setting')}
                    </div>

                    <CreateConfigForm
                      key={`${configKey}-settings`}
                      section="settings"
                      componentKey={componentKey}
                      config={form.config}
                      trans={trans}
                      onChange={(patch) =>
                        setForm({ ...form, config: { ...form.config, ...patch } })
                      }
                    />
                  </>
                ) : null}
              </div>

              <div className="create-control-actions">
                {validationErrors.length ? (
                  <div className="create-control-validation">
                    {validationErrors.map((key) => (
                      <div key={key} className="create-control-validation__item">
                        {trans(`map.layer-control.create.${key}`)}
                      </div>
                    ))}
                  </div>
                ) : null}
                {createError ? (
                  <div className="create-control-sample-error">{createError}</div>
                ) : null}
                {creating ? (
                  <div className="create-control-actions__status">
                    {trans('map.layer-control.create.creating')}
                  </div>
                ) : null}
                <MapControlButton variant="filled"
                  className="btn-container"
                  disabled={creating}
                  onClick={() => void onAddLayer()}
                >
                  {trans('map.layer-control.create-btn')}
                </MapControlButton>
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

// libs/vue/map-dataset/src/modules/CreateControl/CreateControl.vue
<script setup lang="ts">
import { WithMapPropType } from '@hungpvq/map-core';
import { CREATE_CONTROL_LOCALE, LAYER_TYPES, loadCreateControlDraft, reportCreateLayerError, saveCreateControlDraft, suggestLayerName, type LayerType } from '@hungpvq/map-dataset/create-control';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { MapControlButton, ModuleContainer, useLang, useMap, useRegisterMapControl } from '@hungpvq/vue-map-core';
import { InputSelect, InputText } from '@hungpvq/vue-map-core/fields';
import { computed, onMounted, ref, watch, type Ref } from 'vue';
import { useMapDataset } from '../../store/dataset-api';
import { LayerHelper } from './helper';

defineOptions({
  name: 'CreateLayerControl',
});

const props = defineProps<
  WithMapPropType & {
    show: boolean;
  }
>();

const { mapId, moduleContainerProps } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);
setLocaleDefault(CREATE_CONTROL_LOCALE);
const { addDataset } = useMapDataset(mapId.value);
const emit = defineEmits(['update:show']);

const cShow = computed({
  get() {
    return props.show;
  },
  set(value) {
    emit('update:show', value);
  },
});

const { panelBind } = useRegisterMapControl(mapId, {
  id: 'mapCreateControl',
  panelKind: 'popup',
  title: () => trans.value('map.layer-control.create.title'),
  buttonPosition: () => props.position,
  show: cShow as Ref<boolean>,
  setShow: (value) => {
    cShow.value = value;
  },
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
  }),
  actions: [
    {
      type: 'mapCreateControl',
      run: () => {
        cShow.value = !cShow.value;
      },
    },
  ],
});

const initialState = {
  type: 'vector' as LayerType,
};

const keyRender = ref(1);
const helper = new LayerHelper(initialState.type);

const form = ref({
  type: initialState.type,
  config: {
    name: suggestLayerName(initialState.type),
    ...helper.default_value,
  } as Record<string, any>,
});

onMounted(() => {
  const draft = loadCreateControlDraft(mapId.value);
  if (!draft) return;
  if (draft.type === 'vector' || draft.type === 'raster') {
    onChangeType(draft.type);
  }
  if (draft.name) form.value.config.name = draft.name;
  if (draft.crs) form.value.config.crs = draft.crs;
});

watch(
  () => ({
    type: form.value.type,
    name: form.value.config?.name,
    crs: form.value.config?.crs,
  }),
  (snapshot) => {
    saveCreateControlDraft(mapId.value, {
      type: snapshot.type,
      name: snapshot.name,
      crs: snapshot.crs,
    });
  },
  { deep: true },
);

const itemsType = (Object.keys(LAYER_TYPES) as Array<LayerType>).map((x) => ({
  value: x,
  text: LAYER_TYPES[x],
}));

const creating = ref(false);
const createError = ref('');
const validationErrors = ref<string[]>([]);

function onChangeType(type: unknown) {
  if (typeof type !== 'string') return;

  const layerType = type as LayerType;
  const prevSuggested = suggestLayerName(form.value.type);
  const keepName =
    form.value.config.name && form.value.config.name !== prevSuggested;

  helper.setType(layerType);
  validationErrors.value = [];
  createError.value = '';

  form.value = {
    type: layerType,
    config: {
      name: keepName ? form.value.config.name : suggestLayerName(layerType),
      ...helper.default_value,
    } as Record<string, any>,
  };
  keyRender.value++;
}

async function onAddLayer() {
  const handle = helper.create;
  if (!handle || creating.value) return;
  const errors = helper.validationErrors(form.value.config);
  validationErrors.value = errors;
  if (errors.length) return;
  creating.value = true;
  createError.value = '';
  try {
    addDataset(await handle(form.value.config));
    reset();
    cShow.value = false;
  } catch (err) {
    const mapError = reportCreateLayerError(err, {
      crs:
        typeof form.value.config.crs === 'string'
          ? form.value.config.crs
          : undefined,
      layerType: form.value.type,
      name:
        typeof form.value.config.name === 'string'
          ? form.value.config.name
          : undefined,
    });
    createError.value =
      mapError.message ||
      (mapError.context?.['reason'] === 'too_deep_or_circular_or_large'
        ? trans.value('map.layer-control.create.create-error-data-too-large')
        : trans.value('map.layer-control.create.create-error'));
  } finally {
    creating.value = false;
  }
}

function reset() {
  helper.setType(initialState.type);
  createError.value = '';
  creating.value = false;
  validationErrors.value = [];
  form.value = {
    type: initialState.type,
    config: {
      name: suggestLayerName(initialState.type),
      ...helper.default_value,
    } as Record<string, any>,
  };
  keyRender.value++;
}

function close() {
  reset();
}

onMounted(() => {
  onChangeType(form.value.type);
});
</script>

<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="p">
      <DraggableItemPopup
        v-model:show="cShow"
        v-bind="{ ...p, ...panelBind }"
        :width="400"
        :height="420"
        @close="close"
        :title="trans('map.layer-control.create.title')"
      >
        <div class="create-control-container">
          <div class="form-container create-control-form map-row">
            <div class="map-col-12">
              <InputSelect
                v-model="form.type"
                :items="itemsType"
                @update:model-value="onChangeType"
                :label="trans('map.layer-control.field.layer-type')"
              />
            </div>

            <div class="map-col-12">
              <InputText
                v-model="form.config.name"
                :label="trans('map.layer-control.field.layer-name')"
                required
              />
            </div>

            <div class="map-col-12">
              <div class="create-control-section-label">
                {{ trans('map.layer-control.create.data-source') }}
              </div>
            </div>

            <component
              :is="helper.dataSourceComponent()"
              v-model="form.config"
              :key="`${keyRender}-data`"
            />

            <template v-if="helper.hasLayerSettings">
              <div class="map-col-12">
                <div class="create-control-section-label">
                  {{ trans('map.layer-control.create.layer-setting') }}
                </div>
              </div>

              <component
                :is="helper.settingsComponent()"
                v-model="form.config"
                :key="`${keyRender}-settings`"
              />
            </template>
          </div>

          <div class="create-control-actions">
            <div
              v-if="validationErrors.length"
              class="create-control-validation"
            >
              <div
                v-for="key in validationErrors"
                :key="key"
                class="create-control-validation__item"
              >
                {{ trans(`map.layer-control.create.${key}`) }}
              </div>
            </div>
            <div v-if="createError" class="create-control-sample-error">
              {{ createError }}
            </div>
            <div v-if="creating" class="create-control-actions__status">
              {{ trans('map.layer-control.create.creating') }}
            </div>
            <MapControlButton
              :disabled="creating"
              @click="onAddLayer()"
              class="btn-container" variant="filled">
              {{ trans('map.layer-control.create-btn') }}
            </MapControlButton>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
  </ModuleContainer>
</template>
