// libs/map/draw/src/modules/DrawControl/DrawControl.vue
<script lang="ts">
export default {
  name: 'draw-control',
};
</script>
<script setup lang="ts">
import { ContextMenu } from '@hungpvq/content-menu';
import { fitBounds } from '@hungpvq/shared-map';
import {
  defaultMapProps,
  ModuleContainer,
  useLang,
  useMap,
  WithMapPropType,
} from '@hungpvq/vue-map-core';
import MapboxDraw, { MapboxDrawOptions } from '@mapbox/mapbox-gl-draw';
import { Feature, FeatureCollection } from 'geojson';
import { computed, nextTick, ref } from 'vue';
import { DrawingTypeName } from '..';
import { isDraftOption } from '../../store';
import { MapDrawConfig, MapDrawOption } from '../../types';
import DrawDraftList from './components/DrawDraftList.vue';
import DrawToolbar from './components/DrawToolbar.vue';
import { useDrawDrafts } from './hooks/useDrawDrafts';
import { useDrawEvents } from './hooks/useDrawEvents';
import StaticMode from './models/static-mode';
import { getDrawStyles } from './theme';

type DrawControlMapboxDrawControls = Omit<
  MapboxDrawOptions,
  'displayControlsDefault'
>;
const props = withDefaults(
  defineProps<
    WithMapPropType & {
      drawOptions?: MapDrawOption;
      drawControlOptions?: DrawControlMapboxDrawControls;
    }
  >(),
  {
    ...defaultMapProps,
  },
);
const drawOptions = ref(props.drawOptions);
const control = new MapboxDraw({
  displayControlsDefault: false,
  boxSelect: false,
  styles: getDrawStyles(
    props.drawOptions?.primaryColor,
    props.drawOptions?.activeColor,
  ),
  ...props.drawControlOptions,
  modes: {
    ...MapboxDraw.modes,
    static: StaticMode,
    ...props.drawControlOptions?.modes,
  },
});
const { mapId, moduleContainerProps, callMap } = useMap(props);
const { setLocaleDefault } = useLang(mapId.value);
setLocaleDefault({
  map: {
    'draw-control': {
      draftList: {
        title: 'Draft items',
        field: {
          id: 'Id',
          type: 'Type',
          action: '#',
        },
        type: {
          created: 'Created',
          updated: 'Updated',
          deleted: 'Deleted',
        },
        action: {
          fillBound: 'Fill bound',
        },
      },
    },
  },
});
const isShow = ref(false);
function onStart(config: MapDrawOption) {
  isShow.value = true;
  drawOptions.value = props.drawOptions || config;
  drawSupport.value = drawOptions.value.drawSupports || [];
  callMap((map) => {
    map.on('draw.create', onDrawCreated);
    map.on('draw.update', onDrawUpdated);
    map.on('draw.delete', onDrawDeleted);
    if (!map.hasControl(control as any)) map.addControl(control as any);
  });
  onSelectMethod('select');
}
function close() {
  removeEventClick();
  isDraw.value = false;
  isShow.value = false;
  callMap((map) => {
    map.off('draw.create', onDrawCreated);
    map.off('draw.update', onDrawUpdated);
    map.off('draw.delete', onDrawDeleted);
    if (map.hasControl(control as any)) map.removeControl(control as any);
  });
}

const {
  draftItems,
  draftCounts,
  showListDraftItem,
  getCountDraftItem,
  onCommit,
  onDiscard,
  onDiscardItem,
  onShowListDraftItem,
  save,
} = useDrawDrafts(mapId.value, drawOptions, {
  onStart,
  onEnd: close,
});

const {
  onDrawCreated,
  onDrawUpdated,
  onDrawDeleted,
  addEventClick,
  removeEventClick,
  current_feature,
  isDraw,
  method,
} = useDrawEvents(mapId.value, control, drawOptions, {
  onSelectMethod,
  redrawSource,
  getContext,
});

function onSelectMethod(value: 'select' | 'delete') {
  removeEventClick();
  method.value = value;
  switch (value) {
    case 'select':
    case 'delete':
      addEventClick();
      control?.changeMode('static');
      break;
    default:
      break;
  }
}
function onDraw(type: string) {
  current_feature.value = undefined;
  control.changeMode(type);
  isDraw.value = true;
}
const drawSupport = ref<MapDrawConfig['drawSupports']>([]);

async function onSave() {
  onSelectMethod('select');
  isDraw.value = false;
  current_feature.value = undefined;
  await save(control.getAll() as FeatureCollection, getContext());
  await clearDraw();
  await redrawSource();
}

function onCancel() {
  isDraw.value = false;
  const action = drawOptions.value;
  action?.cancel && action?.cancel(current_feature.value);
  clearDraw();
  redrawSource();
  current_feature.value = undefined;
}
async function redrawSource() {
  const action = drawOptions.value;
  if (!action) {
    return;
  }
  getCountDraftItem();
  if (!isDraftOption(drawOptions.value)) {
    return action.redraw && action.redraw(mapId.value);
  }
}
function clearDraw() {
  current_feature.value = undefined;
  if (drawOptions.value?.cleanAfterDone) {
    control?.deleteAll();
  }
  nextTick(() => {
    onSelectMethod('select');
  });
}

function getContext() {
  return { mapId: mapId.value };
}

const contextMenuRef = ref<
  | {
      open(event: MouseEvent): void;
      close(): void;
    }
  | undefined
>();
const drawSupportItem = computed(() => {
  return drawSupport.value.map((x) => {
    if (typeof x === 'string') {
      return { id: x, name: DrawingTypeName[x] || x };
    }
    return x;
  });
});
function closeContextMenu() {
  if (contextMenuRef.value) contextMenuRef.value.close();
}
function onStartDraw(e: MouseEvent) {
  removeEventClick();
  if (drawSupport.value.length > 1) {
    if (contextMenuRef.value) contextMenuRef.value.open(e);
    return;
  }
  onDraw(drawSupport.value[0]);
}

function onFlyTo(value: Feature) {
  callMap((map) => {
    fitBounds(map, value);
  });
}
</script>
<template setup>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <DrawToolbar
        :drawOptions="drawOptions"
        :isShow="isShow"
        :isDraw="isDraw"
        :method="method"
        :draftCounts="draftCounts"
        @cancel="onCancel"
        @save="onSave"
        @close="close"
        @start-draw="onStartDraw"
        @select-method="onSelectMethod"
        @commit="onCommit"
        @discard="onDiscard"
        @show-list="onShowListDraftItem"
      />
    </template>

    <ContextMenu ref="contextMenuRef">
      <ul class="context-menu">
        <li
          v-for="(option, index) in drawSupportItem"
          :key="index"
          @click.stop="
            onDraw(option.id);
            closeContextMenu();
          "
          class="context-menu__item"
        >
          <span v-html="option.name"></span>
        </li>
      </ul>
    </ContextMenu>

    <template #draggable="props">
      <DrawDraftList
        v-bind="props"
        v-model:show="showListDraftItem"
        :draftItems="draftItems"
        :mapId="mapId"
        @fly-to="onFlyTo"
        @discard-item="onDiscardItem"
      />
    </template>
  </ModuleContainer>
</template>

// libs/react/map-draw/src/modules/DrawControl/DrawControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import {
  DrawingTypeName,
  MapDraw,
  StaticMode,
  getDrawCreateModeEffects,
  getDrawStyles,
  isDraftOption,
  type MapDrawOption,
  type MapDrawOptions,
} from '@hungpvq/map-draw';
import {
  ContextMenu,
  type ContextMenuRef,
} from '@hungpvq/react-draggable';
import {
  ModuleContainer,
  defaultMapProps,
  useLang,
  useMap,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import {
  mdiClose,
  mdiContentSave,
  mdiContentSaveCheck,
  mdiDeleteOutline,
  mdiPencil,
  mdiPlus,
  mdiUndoVariant,
  mdiViewListOutline,
} from '@mdi/js';
import type { FeatureCollection } from 'geojson';
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type MouseEvent as ReactMouseEvent,
} from 'react';
import { DRAW_CONTROL_LOCALE } from '@hungpvq/map-draw';
import '../../style.css';
import { DrawDraftList, DrawDraftListPanel } from './components/DrawDraftList';
import { DrawToolbar } from './components/DrawToolbar';
import { useDrawDrafts } from './hooks/useDrawDrafts';
import { useDrawEvents } from './hooks/useDrawEvents';

export interface DrawControlProps extends WithMapPropType {
  drawOptions?: MapDrawOption;
  drawControlOptions?: MapDrawOptions;
}

export function DrawControl(props: DrawControlProps) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps, callMap, order } = useMap(merged);
  const { registerLocale } = useLang(mapId);

  useEffect(() => {
    registerLocale('en', DRAW_CONTROL_LOCALE);
  }, [registerLocale]);

  const [isShow, setIsShow] = useState(false);
  const [drawOptions, setDrawOptions] = useState<MapDrawOption | undefined>(
    props.drawOptions,
  );
  const [drawSupport, setDrawSupport] = useState<string[]>([]);

  const contextMenuRef = useRef<ContextMenuRef>(null);
  const controlRef = useRef(
    new MapDraw({
      displayControlsDefault: false,
      boxSelect: false,
      styles: getDrawStyles(
        props.drawOptions?.primaryColor,
        props.drawOptions?.activeColor,
      ),
      ...props.drawControlOptions,
      modes: {
        ...MapDraw.modes,
        static: StaticMode,
        ...props.drawControlOptions?.modes,
      },
    }),
  );

  const startEndRef = useRef<{
    onStart: (config: MapDrawOption) => void;
    onEnd: () => void;
  }>({
    onStart: () => undefined,
    onEnd: () => undefined,
  });

  const {
    draftItems,
    draftCounts,
    showList,
    setShowList,
    refreshDrafts,
    onCommit,
    onDiscard,
    onShowListDraftItem,
    setFeature,
    save,
  } = useDrawDrafts(mapId, drawOptions, {
    onStart: (config) => startEndRef.current.onStart(config),
    onEnd: () => startEndRef.current.onEnd(),
  });

  const {
    isDraw,
    setIsDraw,
    method,
    setMethod,
    currentFeature,
    setCurrentFeature,
    removeEventClick,
    handlersRef,
    onSelectMethod,
  } = useDrawEvents(mapId, controlRef.current, drawOptions, setFeature);

  const close = useCallback(() => {
    removeEventClick();
    setIsDraw(false);
    setIsShow(false);
    callMap((map) => {
      const control = controlRef.current;
      const h = handlersRef.current;
      map.off('draw.create', h.onDrawCreated);
      map.off('draw.update', h.onDrawUpdated);
      map.off('draw.delete', h.onDrawDeleted);
      if (map.hasControl(control as never)) map.removeControl(control as never);
    });
  }, [callMap, handlersRef, removeEventClick, setIsDraw]);

  useEffect(() => {
    return () => {
      close();
    };
  }, [close]);

  const onStart = useCallback(
    (config: MapDrawOption) => {
      setIsShow(true);
      const next = props.drawOptions || config;
      setDrawOptions(next);
      setDrawSupport(next.drawSupports || []);
      callMap((map) => {
        const control = controlRef.current;
        const h = handlersRef.current;
        map.on('draw.create', h.onDrawCreated);
        map.on('draw.update', h.onDrawUpdated);
        map.on('draw.delete', h.onDrawDeleted);
        if (!map.hasControl(control as never)) map.addControl(control as never);
        control.changeMode('static');
      });
      onSelectMethod('select');
    },
    [callMap, handlersRef, onSelectMethod, props.drawOptions],
  );

  startEndRef.current = { onStart, onEnd: close };

  const onDraw = (type: string) => {
    const effects = getDrawCreateModeEffects(type);
    if (effects.detachMapClick) {
      removeEventClick();
    }
    setCurrentFeature(undefined);
    setMethod(effects.method);
    controlRef.current.changeMode(effects.drawMode);
    setIsDraw(effects.isDraw);
  };

  const supportItems = useMemo(
    () =>
      drawSupport.map((x) => ({
        id: x,
        name: DrawingTypeName[x as keyof typeof DrawingTypeName] || x,
      })),
    [drawSupport],
  );

  const onStartDraw = (e: ReactMouseEvent) => {
    removeEventClick();
    if (drawSupport.length > 1) {
      contextMenuRef.current?.open(e);
      return;
    }
    if (drawSupport[0]) onDraw(drawSupport[0]);
    else if (supportItems[0]) onDraw(supportItems[0].id);
  };

  const onSave = async () => {
    setIsDraw(false);
    onSelectMethod('select');
    setCurrentFeature(undefined);
    await save(controlRef.current.getAll() as FeatureCollection, { mapId });
    if (drawOptions?.cleanAfterDone) controlRef.current.deleteAll();
    refreshDrafts();
    if (!isDraftOption(drawOptions)) {
      await drawOptions?.redraw?.(mapId);
    }
  };

  const onCancel = () => {
    setIsDraw(false);
    void drawOptions?.cancel?.(currentFeature);
    if (drawOptions?.cleanAfterDone) controlRef.current.deleteAll();
    onSelectMethod('select');
    setCurrentFeature(undefined);
  };

  const { control: toolbarControl } = useToolbarControl(mapId, merged, {
    kind: 'module',
    moduleId: 'mapDrawControl',
    order: order,
    orientation: 'row',
    buttons: [
      {
        id: 'cancel',
        getState: () => ({
          visible: isShow && isDraw,
          title: 'Cancel',
          icon: { type: 'mdi' as const, path: mdiClose },
        }),
        onClick: () => onCancel(),
      },
      {
        id: 'save',
        getState: () => ({
          visible: isShow && isDraw,
          title: 'Save',
          icon: { type: 'mdi' as const, path: mdiContentSave },
        }),
        onClick: () => {
          void onSave();
        },
      },
      {
        id: 'close',
        getState: () => ({
          visible: isShow && !isDraw,
          title: 'Close',
          icon: { type: 'mdi' as const, path: mdiClose },
        }),
        onClick: () => close(),
      },
      {
        id: 'add',
        getState: () => ({
          visible: isShow && !isDraw,
          active: method === 'create',
          title: 'Draw',
          icon: { type: 'mdi' as const, path: mdiPlus },
        }),
        onClick: (e) => onStartDraw(e as unknown as ReactMouseEvent),
      },
      {
        id: 'select',
        getState: () => ({
          visible: isShow && !isDraw,
          active: method === 'select',
          title: 'Select',
          icon: { type: 'mdi' as const, path: mdiPencil },
        }),
        onClick: () => onSelectMethod('select'),
      },
      {
        id: 'delete',
        getState: () => ({
          visible: isShow && !isDraw,
          active: method === 'delete',
          title: 'Delete',
          icon: { type: 'mdi' as const, path: mdiDeleteOutline },
        }),
        onClick: () => onSelectMethod('delete'),
      },
      {
        id: 'commit',
        getState: () => ({
          visible: !!(isDraftOption(drawOptions) && drawOptions?.draft?.show),
          disabled: isDraw || draftCounts === 0,
          title: 'Commit drafts',
          icon: { type: 'mdi' as const, path: mdiContentSaveCheck },
        }),
        onClick: () => {
          void onCommit();
        },
      },
      {
        id: 'discard',
        getState: () => ({
          visible: !!(isDraftOption(drawOptions) && drawOptions?.draft?.show),
          disabled: isDraw || draftCounts === 0,
          title: 'Discard drafts',
          icon: { type: 'mdi' as const, path: mdiUndoVariant },
        }),
        onClick: () => onDiscard(),
      },
      {
        id: 'list',
        getState: () => ({
          visible: !!(isDraftOption(drawOptions) && drawOptions?.draft?.show),
          disabled: draftCounts === 0,
          title: 'Draft list',
          icon: { type: 'mdi' as const, path: mdiViewListOutline },
        }),
        onClick: () => onShowListDraftItem(),
      },
    ],
  });

  useEffect(() => {
    toolbarControl.sync();
  }, [isShow, isDraw, method, draftCounts, drawOptions, toolbarControl]);

  return (
    <>
      <DrawDraftList
        show={showList}
        setShow={setShowList}
        draftCounts={draftCounts}
        mapId={mapId}
      />
      <ModuleContainer
        {...moduleContainerProps}
        btn={
          <DrawToolbar
            drawOptions={drawOptions}
            isShow={isShow}
            isDraw={isDraw}
            method={method}
            draftCounts={draftCounts}
            onCancel={onCancel}
            onSave={() => void onSave()}
            onClose={close}
            onStartDraw={onStartDraw}
            onSelectMethod={onSelectMethod}
            onCommit={() => void onCommit()}
            onDiscard={() => onDiscard()}
            onShowList={onShowListDraftItem}
          />
        }
        draggable={
          showList
            ? () => (
                <DrawDraftListPanel
                  draftItems={draftItems}
                  draftCounts={draftCounts}
                  onDiscardItem={(item) => onDiscard(item)}
                  onClose={() => setShowList(false)}
                />
              )
            : undefined
        }
      />
      <ContextMenu ref={contextMenuRef}>
        <ul className="context-menu">
          {supportItems.map((option) => (
            <li
              key={option.id}
              className="context-menu__item"
              onClick={(e) => {
                e.stopPropagation();
                onDraw(option.id);
                contextMenuRef.current?.close();
              }}
            >
              <span>{option.name}</span>
            </li>
          ))}
        </ul>
      </ContextMenu>
    </>
  );
}
