// libs/map/dataset/src/modules/DatasetControl/DatasetControl.vue
<script lang="ts">
export default {
  name: 'dataset-control',
};
</script>

<script setup lang="ts">
import { DraggableItemSideBar } from '@hungpvq/vue-draggable';
import {
  BaseButton,
  defaultMapProps,
  MapCommonButton,
  ModuleContainer,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
  WithMapPropType,
  WithShowProps,
} from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiDatabaseOutline, mdiDelete, mdiInformation } from '@mdi/js';
import { computed, onMounted, shallowRef, watch } from 'vue';
import {
  createMenuClickAddComponentBuilder,
  createMenuClickBuilder,
  handleMenuActionClick,
} from '../../extra/menu';
import type { IDataset } from '../../interfaces/dataset.base';
import { useMapDataset } from '../../store';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const { mapId, moduleContainerProps, order } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);
setLocaleDefault({
  map: {
    'dataset-control': {
      title: 'Dataset Control',
    },
  },
});
const path = {
  icon: mdiDatabaseOutline,
  detail: mdiInformation,
  delete: mdiDelete,
};
const [show, toggleShow] = useShow(props.show);
const { getDatasets, getDatasetIds, removeDataset } = useMapDataset(
  mapId.value,
);
const datasetIds = computed(() => {
  return getDatasetIds().value;
});
watch(
  datasetIds,
  () => {
    updateList();
  },
  { deep: true },
);
function updateList() {
  getViewFromStore();
}
const views = shallowRef<Array<IDataset>>([]);
function getViewFromStore() {
  views.value = getDatasets();
}
function onShowDetail(view: IDataset) {
  handleMenuActionClick(
    createMenuClickBuilder()
      .addTupleStatic('addComponent', {
        value: createMenuClickAddComponentBuilder()
          .setComponentKey('dataset-detail')
          .setAttr({
            dataset: view,
          })
          .setCheck('detail-dataset')
          .build(),
      })
      .build(),
    { layer: view, mapId: mapId.value, value: view },
  );
}
function onRemove(view: IDataset) {
  removeDataset(view);
}
onMounted(() => {
  updateList();
});
defineSlots<{
  item(props: { item: IDataset }): any;
  default(): any;
}>();
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapDatasetControl',
  getState() {
    return {
      visible: !show.value,
      active: show.value,
      title: trans.value('map.dataset-control.title'),
      order: order.value,
      icon: {
        type: 'mdi',
        path: path.icon,
      },
    };
  },
  onClick() {
    toggleShow();
  },
});
watch(show, () => control.sync());
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>

    <template #draggable="props">
      <DraggableItemSideBar
        :containerId="props.containerId"
        v-model:show="show"
        :title="trans('map.dataset-control.title')"
      >
        <template #title> {{ trans('map.dataset-control.title') }} </template>
        <div class="dataset-control">
          <div v-for="view in views" :key="view.id">
            <slot name="item" :item="view">
              <div class="dataset-item">
                <span class="dataset-item__title">{{ view.getName() }}</span>
                <div class="dataset-item__title-action">
                  <BaseButton @click.stop="onShowDetail(view)">
                    <SvgIcon size="16" type="mdi" :path="path.detail" />
                  </BaseButton>

                  <BaseButton @click.stop="onRemove(view)">
                    <SvgIcon size="16" type="mdi" :path="path.delete" />
                  </BaseButton>
                </div>
              </div>
            </slot>
          </div>
        </div>
      </DraggableItemSideBar>
    </template>
    <slot />
  </ModuleContainer>
</template>

<style scoped lang="scss">
.dataset-control {
  display: flex;
  flex-direction: column;
  height: 100%;
  .dataset-item {
    .dataset-item__title {
      display: inline-block;
      text-align: left;
      flex-grow: 1;
      white-space: nowrap;
      overflow: hidden;
    }
    .dataset-item__title-action {
      display: flex;
      flex-grow: 0;
      align-items: center;
    }
    display: flex;
    min-height: 30px;
    padding: 4px 8px;
  }
}
</style>

// libs/react/map-dataset/src/modules/DatasetControl/DatasetControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import type { IDataset } from '@hungpvq/map-dataset';
import {
  DATASET_CONTROL_LOCALE,
  createMenuClickAddComponentBuilder,
  createMenuClickBuilder,
  handleMenuActionClick,
  traverseTree,
} from '@hungpvq/map-dataset';
import { DraggableItemSideBar, DraggableItemPopup } from '@hungpvq/react-draggable';
import {
  BaseButton,
  MapCommonButton,
  ModuleContainer,
  defaultMapProps,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import { mdiDatabaseOutline, mdiDelete, mdiInformation } from '@mdi/js';
import Icon from '@mdi/react';
import { useEffect, useState } from 'react';
import { useMapDataset } from '../../store';

const ICON_SIZE = 16 / 24;

export function DatasetControl(props: WithMapPropType & { show?: boolean }) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps, order } = useMap(merged);
  const { trans, setLocaleDefault } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);
  const { getDatasets, removeDataset, datasetVersion } = useMapDataset(mapId);
  const [views, setViews] = useState<IDataset[]>([]);

  useEffect(() => {
    setLocaleDefault(DATASET_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  useEffect(() => {
    const next = getDatasets();
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getDatasets]);

  const { state, control } = useToolbarControl(mapId, merged, {
    kind: 'single',
    id: 'mapDatasetControl',
    getState: () => ({
      visible: !show,
      active: show,
      title: trans('map.dataset-control.title'),
      order,
      icon: { type: 'mdi' as const, path: mdiDatabaseOutline },
    }),
    onClick: () => toggleShow(),
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  function onShowDetail(view: IDataset) {
    handleMenuActionClick(
      createMenuClickBuilder()
        .addTupleStatic('addComponent', {
          value: createMenuClickAddComponentBuilder()
            .setComponentKey('dataset-detail')
            .setAttr({ dataset: view })
            .setCheck('detail-dataset')
            .build(),
        })
        .build(),
      { layer: view, mapId, value: view },
    );
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) => (
        <DraggableItemSideBar
          show={show}
          onUpdateShow={(v) => toggleShow(!!v)}
          title={trans('map.dataset-control.title')}
          containerId={bind.containerId}
        >
          <div className="dataset-control">
            {views.map((view) => (
              <div key={view.id} className="dataset-item">
                <span className="dataset-item__title">{view.getName()}</span>
                <div className="dataset-item__title-action">
                  <BaseButton
                    onClick={(e) => {
                      e.stopPropagation();
                      onShowDetail(view);
                    }}
                  >
                    <Icon path={mdiInformation} size={ICON_SIZE} />
                  </BaseButton>
                  <BaseButton
                    onClick={(e) => {
                      e.stopPropagation();
                      removeDataset(view);
                    }}
                  >
                    <Icon path={mdiDelete} size={ICON_SIZE} />
                  </BaseButton>
                </div>
              </div>
            ))}
          </div>
        </DraggableItemSideBar>
      )}
    />
  );
}

export function DatasetDetail({
  dataset,
  onClose,
  mapId: propsMapId,
}: {
  dataset: IDataset;
  onClose?: () => void;
  mapId?: string;
}) {
  const { moduleContainerProps } = useMap({ mapId: propsMapId });
  const items: { level: number; path: number[]; node: IDataset }[] = [];
  traverseTree(dataset, (node, level, path) => {
    items.push({ node, level, path });
  });

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) => (
        <DraggableItemPopup
          show
          title={dataset.getName()}
          onUpdateShow={(v) => !v && onClose?.()}
          width={400}
          height={400}
          {...bind}
        >
          <ul className="dataset-list">
            {items.map((item, index) => (
              <li
                key={index}
                className="dataset-list-item"
                style={{ paddingLeft: `${item.level * 0.5}rem` }}
              >
                <span>{item.path.join('.')}</span>
                <span>({item.node.type})</span>
                <span>{item.node.getName()}</span>
              </li>
            ))}
          </ul>
        </DraggableItemPopup>
      )}
    />
  );
}
