// libs/react/map-dataset/src/modules/CreateControl/config/filegdb-upload.tsx
import {
  applyCreateControlLayerName,
  assertCreateControlFileSize,
  buildCreateControlLoadedMetaChips,
  collectFileGdbFilesFromDataTransfer,
  createControlGeojsonPreviewPatch,
  type CreateControlLoadedSource,
  FILEGDB_FILE_ACCEPT,
  formatCreateControlParseStatus,
  looksLikeFileGdbFiles,
  parseCreateControlUploadedFiles,
  subscribeCreateControlParseProgress,
  summarizeCreateControlUploadFiles,
} from '@hungpvq/map-dataset/create-control';
import { terminateGeojsonWorker } from '@hungpvq/map-dataset/geojson';
import { MapControlButton } from '@hungpvq/react-map-core';
import { DragDropFile } from '@hungpvq/react-map-core/fields';
import { useMemo, useRef, useState } from 'react';

import type { CreateConfigFormProps } from './types';

function filterGdbUploadFiles(files: File[]): File[] {
  const nested = files.filter((file) =>
    (file.webkitRelativePath || file.name || '')
      .replace(/\\/g, '/')
      .toLowerCase()
      .includes('.gdb/'),
  );
  return nested.length ? nested : files;
}

/** FileGDB zip / folder upload — mirrors Vue `filegdb-upload.vue`. */
export function ConfigFilegdbUpload({
  config,
  onChange,
  trans,
}: CreateConfigFormProps) {
  const [parsing, setParsing] = useState(false);
  const [parseError, setParseError] = useState('');
  const [parseStatusText, setParseStatusText] = useState('');
  const [loadedSource, setLoadedSource] =
    useState<CreateControlLoadedSource | null>(null);
  const [replaceFileMode, setReplaceFileMode] = useState(false);
  const parseGeneration = useRef(0);
  const folderInputRef = useRef<HTMLInputElement | null>(null);

  const showFileSummary =
    !!config.geojson && loadedSource?.kind === 'file' && !replaceFileMode;

  const loadedMetaChips = useMemo(
    () =>
      buildCreateControlLoadedMetaChips(loadedSource, {
        featuresCount: trans('map.layer-control.create.features-count'),
        geometryTypes: trans('map.layer-control.create.geometry-types'),
      }),
    [loadedSource, trans],
  );

  function syncGeojsonPreview(
    geojson: CreateConfigFormProps['config']['geojson'],
    crs?: string | null,
    layers?: Array<{ name: string; geojson: unknown }> | null,
  ) {
    const patch = createControlGeojsonPreviewPatch(
      geojson as never,
      crs ?? undefined,
      layers as never,
    );
    onChange(patch);
  }

  function clearLoadedData() {
    parseGeneration.current += 1;
    setLoadedSource(null);
    setReplaceFileMode(false);
    setParseError('');
    syncGeojsonPreview(null);
  }

  function cancelParsing() {
    parseGeneration.current += 1;
    terminateGeojsonWorker();
    setParsing(false);
    setParseStatusText('');
  }

  function openFolderPicker() {
    if (!folderInputRef.current) {
      const input = document.createElement('input');
      input.type = 'file';
      input.multiple = true;
      input.setAttribute('webkitdirectory', '');
      input.setAttribute('directory', '');
      input.onchange = () => {
        const list = input.files;
        if (list?.length) void onChangeFile(Array.from(list));
        input.value = '';
      };
      folderInputRef.current = input;
    }
    folderInputRef.current.click();
  }

  async function onChangeFile(input: File | File[]) {
    const files = filterGdbUploadFiles(
      (Array.isArray(input) ? input : input ? [input] : []).filter(
        (file): file is File => file instanceof File,
      ),
    );
    if (!files.length) return;

    if (!looksLikeFileGdbFiles(files)) {
      setParseError(trans('map.layer-control.create.parse-error'));
      return;
    }

    const gen = ++parseGeneration.current;
    setParseError('');
    try {
      assertCreateControlFileSize(files);
    } catch (err) {
      setParseError(
        err instanceof Error
          ? err.message
          : trans('map.layer-control.create.parse-error'),
      );
      syncGeojsonPreview(null);
      setLoadedSource(null);
      return;
    }

    const { totalBytes } = summarizeCreateControlUploadFiles(files);
    const parsingLabel = trans('map.layer-control.create.parsing');
    setParsing(true);
    setParseStatusText(
      formatCreateControlParseStatus(parsingLabel, totalBytes),
    );
    const unsubProgress = subscribeCreateControlParseProgress(
      parsingLabel,
      totalBytes,
      setParseStatusText,
    );
    try {
      const result = await parseCreateControlUploadedFiles(files);
      if (gen !== parseGeneration.current) return;
      const preview = createControlGeojsonPreviewPatch(
        result.geojson as never,
        result.crs ?? undefined,
        result.layers,
      );
      onChange({
        ...preview,
        name: applyCreateControlLayerName(
          typeof config.name === 'string' ? config.name : '',
          result.suggestedName,
          'filegdb',
        ),
      });
      setLoadedSource(result.loadedSource);
      setReplaceFileMode(false);
    } catch (err) {
      if (gen !== parseGeneration.current) return;
      setParseError(
        err instanceof Error
          ? err.message
          : trans('map.layer-control.create.parse-error'),
      );
      syncGeojsonPreview(null);
      setLoadedSource(null);
    } finally {
      unsubProgress();
      if (gen === parseGeneration.current) {
        setParsing(false);
        setParseStatusText('');
      }
    }
  }

  return (
    <div className="map-row create-control-settings">
      <div className="map-col-12">
        {showFileSummary ? (
          <div className="create-control-loaded">
            <div className="create-control-loaded__head">
              <div>
                <p className="create-control-loaded__eyebrow">
                  {trans('map.layer-control.create.loaded-from-file')}
                </p>
                <p className="create-control-loaded__title">
                  {loadedSource?.label}
                </p>
                {loadedSource?.detail ? (
                  <p className="create-control-loaded__detail">
                    {loadedSource.detail}
                  </p>
                ) : null}
              </div>
              <MapControlButton
                type="button"
                variant="outlined"
                onClick={clearLoadedData}
              >
                {trans('map.layer-control.create.clear-data')}
              </MapControlButton>
            </div>
            {loadedMetaChips.length ? (
              <ul className="create-control-loaded__meta">
                {loadedMetaChips.map((chip) => (
                  <li key={chip} className="create-control-loaded__chip">
                    {chip}
                  </li>
                ))}
              </ul>
            ) : null}
            <div className="create-control-loaded__actions">
              <MapControlButton
                type="button"
                variant="outlined"
                onClick={() => setReplaceFileMode(true)}
              >
                {trans('map.layer-control.create.replace-file')}
              </MapControlButton>
            </div>
          </div>
        ) : null}

        {!showFileSummary || replaceFileMode ? (
          <>
            <div className="create-control-drop">
              <DragDropFile
                multiple
                accept={FILEGDB_FILE_ACCEPT}
                resolveDropFiles={collectFileGdbFilesFromDataTransfer}
                onChange={onChangeFile}
              />
              <div
                className="create-control-loaded__actions"
                style={{ marginTop: '0.75rem' }}
              >
                <MapControlButton
                  type="button"
                  variant="outlined"
                  onClick={openFolderPicker}
                >
                  {trans('map.layer-control.create.filegdb-choose-folder')}
                </MapControlButton>
              </div>
              {parsing ? (
                <div className="create-control-status--busy">
                  <span>
                    {parseStatusText ||
                      trans('map.layer-control.create.parsing')}
                  </span>
                  <MapControlButton
                    type="button"
                    variant="outlined"
                    onClick={cancelParsing}
                  >
                    {trans('map.layer-control.create.cancel')}
                  </MapControlButton>
                </div>
              ) : null}
            </div>
            <p className="create-control-status">
              {trans('map.layer-control.create.file-hint-filegdb')}
            </p>
            {parseError ? (
              <div className="create-control-sample-error">{parseError}</div>
            ) : null}
          </>
        ) : null}
      </div>
    </div>
  );
}

// libs/vue/map-dataset/src/modules/CreateControl/config/filegdb-upload.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-12">
      <div v-if="showFileSummary" class="create-control-loaded">
        <div class="create-control-loaded__head">
          <div>
            <p class="create-control-loaded__eyebrow">
              {{ trans('map.layer-control.create.loaded-from-file') }}
            </p>
            <p class="create-control-loaded__title">{{ loadedSource.label }}</p>
            <p v-if="loadedSource.detail" class="create-control-loaded__detail">
              {{ loadedSource.detail }}
            </p>
          </div>
          <MapControlButton
            type="button"
            @click="clearLoadedData"
            variant="outlined"
          >
            {{ trans('map.layer-control.create.clear-data') }}
          </MapControlButton>
        </div>
        <ul v-if="loadedMetaChips.length" class="create-control-loaded__meta">
          <li
            v-for="chip in loadedMetaChips"
            :key="chip"
            class="create-control-loaded__chip"
          >
            {{ chip }}
          </li>
        </ul>
        <div class="create-control-loaded__actions">
          <MapControlButton
            type="button"
            @click="replaceFileMode = true"
            variant="outlined"
          >
            {{ trans('map.layer-control.create.replace-file') }}
          </MapControlButton>
        </div>
      </div>

      <template v-if="!showFileSummary || replaceFileMode">
        <div class="create-control-drop">
          <DragDropFile
            :multiple="true"
            :accept="FILEGDB_FILE_ACCEPT"
            :resolve-drop-files="collectFileGdbFilesFromDataTransfer"
            @change="onChangeFile"
          />
          <div
            class="create-control-loaded__actions"
            style="margin-top: 0.75rem"
          >
            <MapControlButton
              type="button"
              variant="outlined"
              @click="openFolderPicker"
            >
              {{ trans('map.layer-control.create.filegdb-choose-folder') }}
            </MapControlButton>
          </div>
          <div v-if="parsing" class="create-control-status--busy">
            <span>{{
              parseStatusText || trans('map.layer-control.create.parsing')
            }}</span>
            <MapControlButton
              type="button"
              @click="cancelParsing"
              variant="outlined"
            >
              {{ trans('map.layer-control.create.cancel') }}
            </MapControlButton>
          </div>
        </div>
        <p class="create-control-status">
          {{ trans('map.layer-control.create.file-hint-filegdb') }}
        </p>
        <div v-if="parseError" class="create-control-sample-error">
          {{ parseError }}
        </div>
      </template>
    </div>
  </div>
</template>

<script setup>
import {
  applyCreateControlLayerName,
  assertCreateControlFileSize,
  buildCreateControlLoadedMetaChips,
  collectFileGdbFilesFromDataTransfer,
  createControlGeojsonPreviewPatch,
  FILEGDB_FILE_ACCEPT,
  formatCreateControlParseStatus,
  looksLikeFileGdbFiles,
  parseCreateControlUploadedFiles,
  subscribeCreateControlParseProgress,
  summarizeCreateControlUploadFiles,
} from '@hungpvq/map-dataset/create-control';
import { terminateGeojsonWorker } from '@hungpvq/map-dataset/geojson';
import { MapControlButton, useLang, useMap } from '@hungpvq/vue-map-core';
import { DragDropFile } from '@hungpvq/vue-map-core/fields';
import { computed, markRaw, ref } from 'vue';

const form = defineModel();
const parsing = ref(false);
const parseError = ref('');
const parseStatusText = ref('');
const loadedSource = ref(null);
const replaceFileMode = ref(false);
let parseGeneration = 0;
let folderInput;

const { mapId } = useMap();
const { trans } = useLang(mapId.value);

const showFileSummary = computed(
  () =>
    !!form.value?.geojson &&
    loadedSource.value?.kind === 'file' &&
    !replaceFileMode.value,
);

const loadedMetaChips = computed(() =>
  buildCreateControlLoadedMetaChips(loadedSource.value, {
    featuresCount: trans.value('map.layer-control.create.features-count'),
    geometryTypes: trans.value('map.layer-control.create.geometry-types'),
  }),
);

function syncGeojsonPreview(geojson, crs, layers) {
  const patch = createControlGeojsonPreviewPatch(geojson, crs, layers);
  if (patch.geojson) {
    form.value.geojson = markRaw(patch.geojson);
  } else {
    form.value.geojson = patch.geojson;
  }
  if ('crs' in patch) form.value.crs = patch.crs;
  if ('detectedCrs' in patch) form.value.detectedCrs = patch.detectedCrs;
  if ('gdbLayers' in patch) {
    form.value.gdbLayers = Array.isArray(patch.gdbLayers)
      ? markRaw(patch.gdbLayers)
      : patch.gdbLayers;
  }
  if ('sourceLayers' in patch) form.value.sourceLayers = patch.sourceLayers;
  if ('sourceLayerOptions' in patch) {
    form.value.sourceLayerOptions = patch.sourceLayerOptions;
  }
}

function clearLoadedData() {
  parseGeneration += 1;
  loadedSource.value = null;
  replaceFileMode.value = false;
  parseError.value = '';
  syncGeojsonPreview(null);
}

function cancelParsing() {
  parseGeneration += 1;
  terminateGeojsonWorker();
  parsing.value = false;
  parseStatusText.value = '';
}

function openFolderPicker() {
  if (!folderInput) {
    folderInput = document.createElement('input');
    folderInput.type = 'file';
    folderInput.multiple = true;
    folderInput.setAttribute('webkitdirectory', '');
    folderInput.setAttribute('directory', '');
    folderInput.onchange = () => {
      const list = folderInput.files;
      if (list?.length) void onChangeFile(Array.from(list));
      folderInput.value = '';
    };
  }
  folderInput.click();
}

function normalizeUploadFiles(input) {
  const files = Array.isArray(input) ? input : input ? [input] : [];
  return files.filter((file) => file instanceof File);
}

/** Keep only members under `*.gdb/` when the picker returned a parent folder. */
function filterGdbUploadFiles(files) {
  const nested = files.filter((file) =>
    (file.webkitRelativePath || file.name || '')
      .replace(/\\/g, '/')
      .toLowerCase()
      .includes('.gdb/'),
  );
  return nested.length ? nested : files;
}

async function onChangeFile(input) {
  const files = filterGdbUploadFiles(normalizeUploadFiles(input));
  if (!files.length) return;

  if (!looksLikeFileGdbFiles(files)) {
    parseError.value = trans.value('map.layer-control.create.parse-error');
    return;
  }

  const gen = ++parseGeneration;
  parseError.value = '';
  try {
    assertCreateControlFileSize(files);
  } catch (err) {
    parseError.value =
      err instanceof Error
        ? err.message
        : trans.value('map.layer-control.create.parse-error');
    syncGeojsonPreview(null);
    loadedSource.value = null;
    return;
  }

  const { totalBytes } = summarizeCreateControlUploadFiles(files);
  const parsingLabel = trans.value('map.layer-control.create.parsing');
  parsing.value = true;
  parseStatusText.value = formatCreateControlParseStatus(
    parsingLabel,
    totalBytes,
  );
  const unsubProgress = subscribeCreateControlParseProgress(
    parsingLabel,
    totalBytes,
    (text) => {
      parseStatusText.value = text;
    },
  );
  try {
    const result = await parseCreateControlUploadedFiles(files);
    if (gen !== parseGeneration) return;
    syncGeojsonPreview(result.geojson, result.crs, result.layers);
    loadedSource.value = result.loadedSource;
    form.value.name = applyCreateControlLayerName(
      form.value.name,
      result.suggestedName,
      'filegdb',
    );
    replaceFileMode.value = false;
  } catch (err) {
    if (gen !== parseGeneration) return;
    parseError.value =
      err instanceof Error
        ? err.message
        : trans.value('map.layer-control.create.parse-error');
    syncGeojsonPreview(null);
    loadedSource.value = null;
  } finally {
    unsubProgress();
    if (gen === parseGeneration) {
      parsing.value = false;
      parseStatusText.value = '';
    }
  }
}
</script>
