// libs/react/map-dataset/src/modules/CreateControl/config/xyz-settings.tsx
import { InputText } from '@hungpvq/react-map-core/fields';

import type { CreateConfigFormProps } from './types';

/** XYZ layer settings — mirrors Vue `xyz-settings.vue`. */
export function ConfigRasterSettings({
  config,
  onChange,
  trans,
}: CreateConfigFormProps) {
  const bounds = (config.bounds as number[]) || [
    -180, -85.051129, 180, 85.051129,
  ];
  return (
    <div className="map-row create-control-settings">
      <div className="map-col-6">
        <InputText
          label={trans('map.layer-control.field.minzoom')}
          value={String(config.minzoom ?? 0)}
          onChange={(v) => onChange({ minzoom: Number(v) })}
        />
      </div>
      <div className="map-col-6">
        <InputText
          label={trans('map.layer-control.field.maxzoom')}
          value={String(config.maxzoom ?? 22)}
          onChange={(v) => onChange({ maxzoom: Number(v) })}
        />
      </div>
      {config.tileKind === 'vector' ? (
        <div className="map-col-12">
          <InputText
            label={trans('map.layer-control.field.source-layer')}
            value={String(config.sourceLayer ?? '')}
            onChange={(v) => onChange({ sourceLayer: v })}
          />
        </div>
      ) : null}
      {['minx', 'miny', 'maxx', 'maxy'].map((key, i) => (
        <div
          key={key}
          className="map-col-6"
        >
          <InputText
            label={trans(`map.layer-control.field.bound.${key}`)}
            value={String(bounds[i] ?? '')}
            onChange={(v) => {
              const next = [...bounds];
              next[i] = Number(v);
              onChange({ bounds: next });
            }}
          />
        </div>
      ))}
    </div>
  );
}

// libs/vue/map-dataset/src/modules/CreateControl/config/xyz-settings.vue
<template>
  <div class="map-row create-control-settings">
    <div class="map-col-6">
      <input-text
        v-model="form.minzoom"
        :label="trans('map.layer-control.field.minzoom')"
      />
    </div>
    <div class="map-col-6">
      <input-text
        v-model="form.maxzoom"
        :label="trans('map.layer-control.field.maxzoom')"
      />
    </div>
    <div v-if="form.tileKind === 'vector'" class="map-col-12">
      <input-text
        v-model="form.sourceLayer"
        :label="trans('map.layer-control.field.source-layer')"
      />
    </div>
    <template v-if="form.bounds">
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[0]"
          :label="trans('map.layer-control.field.bound.minx')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[1]"
          :label="trans('map.layer-control.field.bound.miny')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[2]"
          :label="trans('map.layer-control.field.bound.maxx')"
        />
      </div>
      <div class="map-col-6">
        <input-text
          v-model="form.bounds[3]"
          :label="trans('map.layer-control.field.bound.maxy')"
        />
      </div>
    </template>
  </div>
</template>

<script setup>
import { useLang, useMap } from '@hungpvq/vue-map-core';
import { InputText } from '@hungpvq/vue-map-core/fields';

const form = defineModel();
const { mapId } = useMap();
const { trans } = useLang(mapId.value);
</script>
