// libs/vue/map-core/src/components/MapAutoHostButtons.vue
<template>
  <MapCommonButton
    v-if="mode === 'single' && singleState"
    :option="singleState"
    @click.stop="onSingleClick"
  />
  <MapControlGroupButton
    v-else-if="mode === 'module'"
    :row="row"
  >
    <MapCommonButton
      v-for="[id, btn] in moduleEntries"
      v-show="btn?.visible != false"
      :key="id"
      :option="btn"
      @click.stop="onModuleClick(id, $event)"
    />
  </MapControlGroupButton>
  <MapControlGroupButton
    v-else-if="mode === 'expandable' && launcher"
    :row="row"
    class="map-host-expandable"
  >
    <template v-if="expandRight">
      <MapCommonButton
        v-if="launcher.visible != false"
        :option="launcher"
        @click.stop="onModuleClick('launcher', $event)"
      />
      <template v-if="launcher.active">
        <MapCommonButton
          v-for="[id, btn] in optionEntries"
          v-show="btn?.visible != false"
          :key="id"
          :option="btn"
          @click.stop="onModuleClick(id, $event)"
        />
      </template>
    </template>
    <template v-else>
      <template v-if="launcher.active">
        <MapCommonButton
          v-for="[id, btn] in optionEntries"
          v-show="btn?.visible != false"
          :key="id"
          :option="btn"
          @click.stop="onModuleClick(id, $event)"
        />
      </template>
      <MapCommonButton
        v-if="launcher.visible != false"
        :option="launcher"
        @click.stop="onModuleClick('launcher', $event)"
      />
    </template>
  </MapControlGroupButton>
</template>

<script lang="ts">
export default {
  name: 'MapAutoHostButtons',
};
</script>

<script setup lang="ts">
import type { Position } from '@hungpvq/map-core';
import type { MapControlButtonUIState } from '@hungpvq/map-core/toolbar';
import { computed } from 'vue';

import { defineProps } from 'vue';
import MapCommonButton from './MapCommonButton.vue';
import MapControlGroupButton from './MapControlGroupButton.vue';

const props = defineProps<{
  state: unknown;
  position?: Position | string;
  onAction: (...args: unknown[]) => void;
}>();

function isButtonRecord(
  value: unknown,
): value is Record<string, MapControlButtonUIState> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const vals = Object.values(value as Record<string, unknown>);
  if (vals.length === 0) return false;
  return vals.every(
    (v) => v != null && typeof v === 'object' && !Array.isArray(v),
  );
}

const mode = computed<'single' | 'module' | 'expandable' | 'empty'>(() => {
  if (!props.state) return 'empty';
  if (!isButtonRecord(props.state)) return 'single';
  return 'launcher' in props.state ? 'expandable' : 'module';
});

const singleState = computed(() =>
  mode.value === 'single'
    ? (props.state as MapControlButtonUIState)
    : undefined,
);

const recordState = computed(() =>
  isButtonRecord(props.state) ? props.state : undefined,
);

const launcher = computed(() => recordState.value?.launcher);

const moduleEntries = computed(() => {
  const state = recordState.value;
  if (!state) return [] as [string, MapControlButtonUIState][];
  return Object.entries(state);
});

const optionEntries = computed(() => {
  const state = recordState.value;
  if (!state) return [] as [string, MapControlButtonUIState][];
  return Object.entries(state).filter(
    ([id, btn]) => id !== 'launcher' && btn?.role === 'option',
  );
});

const expandRight = computed(() =>
  String(props.position ?? '').endsWith('left'),
);

const row = computed(() => {
  const state = recordState.value;
  if (!state) return true;
  const sample = state.launcher ?? Object.values(state)[0];
  return sample?.orientation === 'row';
});

function onSingleClick(event: MouseEvent) {
  props.onAction(event);
}

function onModuleClick(id: string, event: MouseEvent) {
  props.onAction(id, event);
}
</script>

// libs/react/map-core/src/components/MapAutoHostButtons.tsx
import type { Position } from '@hungpvq/map-core';
import type { MapControlButtonUIState } from '@hungpvq/map-core/toolbar';
import React, { useMemo } from 'react';

import { MapCommonButton } from './MapCommonButton';
import { MapControlGroupButton } from './MapControlGroupButton';

export type MapAutoHostButtonsProps = {
  state: unknown;
  position?: Position | string;
  onAction: (...args: unknown[]) => void;
};

function isButtonRecord(
  value: unknown,
): value is Record<string, MapControlButtonUIState> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const vals = Object.values(value as Record<string, unknown>);
  if (vals.length === 0) return false;
  return vals.every(
    (v) => v != null && typeof v === 'object' && !Array.isArray(v),
  );
}

export function MapAutoHostButtons({
  state,
  position,
  onAction,
}: MapAutoHostButtonsProps) {
  const mode = useMemo(() => {
    if (!state) return 'empty' as const;
    if (!isButtonRecord(state)) return 'single' as const;
    return 'launcher' in state ? ('expandable' as const) : ('module' as const);
  }, [state]);

  const record = isButtonRecord(state) ? state : undefined;
  const launcher = record?.launcher;
  const moduleEntries = record ? Object.entries(record) : [];
  const optionEntries = record
    ? Object.entries(record).filter(
        ([id, btn]) => id !== 'launcher' && btn?.role === 'option',
      )
    : [];

  const expandRight = String(position ?? '').endsWith('left');
  const sample = launcher ?? (record ? Object.values(record)[0] : undefined);
  const row = sample?.orientation === 'row';

  if (mode === 'single' && state) {
    return (
      <MapCommonButton
        option={state as MapControlButtonUIState}
        onClick={(e) => {
          e.stopPropagation();
          onAction(e.nativeEvent);
        }}
      />
    );
  }

  if (mode === 'module') {
    return (
      <MapControlGroupButton row={row}>
        {moduleEntries.map(([id, btn]) =>
          btn && btn.visible !== false ? (
            <MapCommonButton
              key={id}
              option={btn}
              onClick={(e) => {
                e.stopPropagation();
                onAction(id, e.nativeEvent);
              }}
            />
          ) : null,
        )}
      </MapControlGroupButton>
    );
  }

  if (mode === 'expandable' && launcher) {
    const launcherBtn =
      launcher.visible !== false ? (
        <MapCommonButton
          key="launcher"
          option={launcher}
          onClick={(e) => {
            e.stopPropagation();
            onAction('launcher', e.nativeEvent);
          }}
        />
      ) : null;

    const optionBtns = launcher.active
      ? optionEntries.map(([id, btn]) =>
          btn && btn.visible !== false ? (
            <MapCommonButton
              key={id}
              option={btn}
              onClick={(e) => {
                e.stopPropagation();
                onAction(id, e.nativeEvent);
              }}
            />
          ) : null,
        )
      : null;

    return (
      <MapControlGroupButton row={row} className="map-host-expandable">
        {expandRight ? (
          <>
            {launcherBtn}
            {optionBtns}
          </>
        ) : (
          <>
            {optionBtns}
            {launcherBtn}
          </>
        )}
      </MapControlGroupButton>
    );
  }

  return null;
}
