// libs/vue/map-core/src/components/MapCard.vue
<template>
  <div
    class="hungpvq-draggable-card"
    :style="cardStyle"
    v-bind="$attrs"
  >
    <div>
      <slot />
    </div>
    <div class="card-arrow">
      <div class="card-arrow-top-left"></div>
      <div class="card-arrow-top-right"></div>
      <div class="card-arrow-bottom-left"></div>
      <div class="card-arrow-bottom-right"></div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  name: 'MapCard',
  props: {
    height: {
      type: [String, Number],
      default: undefined,
    },
    width: {
      type: [String, Number],
      default: undefined,
    },
  },
  data: () => ({}),
  computed: {
    cardStyle() {
      return { height: this.height, width: this.width };
    },
  },
  methods: {},
};
</script>

// libs/react/map-core/src/components/MapCard.tsx
import React, { useMemo } from 'react';

export interface MapCardProps extends React.HTMLAttributes<HTMLDivElement> {
  height?: string | number;
  width?: string | number;
  children?: React.ReactNode;
}

export function MapCard({
  height,
  width,
  children,
  className = '',
  style,
  ...props
}: MapCardProps) {
  const cardStyle = useMemo(
    () => ({
      height:
        height !== undefined
          ? typeof height === 'number'
            ? `${height}px`
            : height
          : undefined,
      width:
        width !== undefined
          ? typeof width === 'number'
            ? `${width}px`
            : width
          : undefined,
      ...style,
    }),
    [height, width, style],
  );

  return (
    <div
      className={`hungpvq-draggable-card ${className}`}
      style={cardStyle}
      {...props}
    >
      <div>{children}</div>
      <div className="card-arrow">
        <div className="card-arrow-top-left"></div>
        <div className="card-arrow-top-right"></div>
        <div className="card-arrow-bottom-left"></div>
        <div className="card-arrow-bottom-right"></div>
      </div>
    </div>
  );
}
