// libs/vue/map-core/src/components/MapImage.vue
<template>
  <div class="map-image">
    <div
      class="map-image__sizer"
      style="padding-bottom: 100%"
    ></div>
    <div
      class="map-image__image"
      :style="styleImage"
    ></div>
    <div class="map-image__content"><slot /></div>
  </div>
</template>

<script>
export default {
  name: 'MapImage',
  props: {
    src: {},
  },
  data: () => ({}),
  computed: {
    styleImage() {
      if (!this.src) {
        return {};
      }
      return {
        'background-image': `url(${this.src})`,
      };
    },
  },
  methods: {},
};
</script>

// libs/react/map-core/src/components/MapImage.tsx
import React, { useMemo } from 'react';

export interface MapImageProps extends React.HTMLAttributes<HTMLDivElement> {
  src?: string;
  children?: React.ReactNode;
}

export function MapImage({
  src,
  children,
  className = '',
  style,
  ...props
}: MapImageProps) {
  const styleImage = useMemo(() => {
    if (!src) {
      return {};
    }
    return {
      backgroundImage: `url(${src})`,
    };
  }, [src]);

  return (
    <div
      className={`map-image ${className}`}
      style={style}
      {...props}
    >
      <div
        className="map-image__sizer"
        style={{ paddingBottom: '100%' }}
      ></div>
      <div
        className="map-image__image"
        style={styleImage}
      ></div>
      <div className="map-image__content">{children}</div>
    </div>
  );
}
