// libs/vue/map-core/src/components/MapTabs.vue
<script lang="ts">
export default {
  name: 'MapTabs',
};
</script>
<script setup lang="ts">
import { computed, useSlots } from 'vue';

import type { MapTabItem } from './map-tabs';
import MapControlButton from './MapControlButton.vue';

export type { MapTabItem } from './map-tabs';

const props = withDefaults(
  defineProps<{
    items: MapTabItem[];
    modelValue: string;
    /** When false, render only the tab bar (no pane host). */
    withPanes?: boolean;
  }>(),
  {
    withPanes: true,
  },
);

const emit = defineEmits<{
  'update:modelValue': [id: string];
}>();

const slots = useSlots();

const activeId = computed(() => {
  if (props.items.some((item) => item.id === props.modelValue)) {
    return props.modelValue;
  }
  return props.items[0]?.id ?? '';
});

function select(id: string) {
  if (id !== props.modelValue) emit('update:modelValue', id);
}

const hasPanes = computed(
  () =>
    props.withPanes &&
    props.items.some((item) => typeof slots[item.id] === 'function'),
);
</script>

<template>
  <div
    class="map-tabs-root"
    :class="{ 'map-tabs-root--bar-only': !hasPanes }"
  >
    <div
      class="map-tabs"
      role="tablist"
    >
      <MapControlButton
        v-for="item in items"
        :key="item.id"
        role="tab"
        :aria-selected="activeId === item.id"
        variant="text"
        size="small"
        :active="activeId === item.id"
        @click="select(item.id)"
      >
        {{ item.label }}
      </MapControlButton>
    </div>
    <div
      v-if="hasPanes"
      class="map-tabs__panes"
    >
      <div
        v-for="item in items"
        :key="item.id"
        class="map-tabs__pane"
        role="tabpanel"
        :hidden="activeId !== item.id"
      >
        <slot :name="item.id" />
      </div>
    </div>
  </div>
</template>

// libs/react/map-core/src/components/MapTabs.tsx
import React, { type ReactNode, useMemo } from 'react';

import { MapControlButton } from './MapControlButton';

export type MapTabItem = {
  id: string;
  label: string;
};

export type MapTabsProps = {
  items: MapTabItem[];
  value: string;
  onChange: (id: string) => void;
  /** When false, render only the tab bar (no pane host). */
  withPanes?: boolean;
  /** Pane content keyed by tab id. Omitted ids simply hide. */
  panes?: Record<string, ReactNode>;
  className?: string;
};

export function MapTabs({
  items,
  value,
  onChange,
  withPanes = true,
  panes,
  className,
}: MapTabsProps) {
  const activeId = useMemo(() => {
    if (items.some((item) => item.id === value)) return value;
    return items[0]?.id ?? '';
  }, [items, value]);

  const hasPanes =
    withPanes && !!panes && items.some((item) => panes[item.id] != null);

  return (
    <div
      className={[
        'map-tabs-root',
        !hasPanes ? 'map-tabs-root--bar-only' : '',
        className || '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      <div
        className="map-tabs"
        role="tablist"
      >
        {items.map((item) => (
          <MapControlButton
            key={item.id}
            role="tab"
            aria-selected={activeId === item.id}
            variant="text"
            size="small"
            active={activeId === item.id}
            onClick={() => {
              if (item.id !== value) onChange(item.id);
            }}
          >
            {item.label}
          </MapControlButton>
        ))}
      </div>
      {hasPanes ? (
        <div className="map-tabs__panes">
          {items.map((item) => (
            <div
              key={item.id}
              className="map-tabs__pane"
              role="tabpanel"
              hidden={activeId !== item.id}
            >
              {panes?.[item.id]}
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
}
