// libs/react/map-core/src/extra/toolbar/modules/ToolbarControl.tsx
import {
  MAP_BUTTON_SIZE_PX,
  type Position,
  type WithMapPropType,
} from '@hungpvq/map-core';
import type { MapControlButtonState } from '@hungpvq/map-core/toolbar';
import {
  TOOLBAR_CONTROL_LOCALE,
  cornerVerticalMenuBudgetsPx,
  createToolbarStoreApi,
  groupToolbarButtons,
  maxVisibleButtonsInStackHeight,
  maxVisibleToolbarButtons,
  mdiButtonState,
  measureCornerMenuUsedPx,
  measureCornerStandaloneReserved,
  splitToolbarOverflow,
  splitToolbarOverflowKeepGroups,
  toolbarAvailableWidth,
} from '@hungpvq/map-core/toolbar';
import { mdiDotsHorizontal } from '@mdi/js';
import { useContext, useEffect, useMemo, useRef, useState } from 'react';
import { MapCommonButton } from '../../../components/MapCommonButton';
import { MapControlGroupButton } from '../../../components/MapControlGroupButton';
import { MapContext } from '../../../context/MapContext';
import { defaultMapProps, useMap } from '../../../hooks';
import { ModuleContainer } from '../../../modules/ModuleContainer/ModuleContainer';
import { useLang } from '../../lang';
import { useMapToolbarStore } from '../store';

const CORNER_POSITIONS: Position[] = [
  'top-left',
  'top-right',
  'bottom-left',
  'bottom-right',
];

export type ToolbarControlProps = Omit<
  WithMapPropType,
  'controlLayout' | 'controlVisible'
> & {
  maxVisible?: number;
};

function overflowClassFor(position: Position) {
  return [
    'map-toolbar-overflow',
    position.startsWith('top')
      ? 'map-toolbar-overflow-top'
      : 'map-toolbar-overflow-bottom',
    position.endsWith('left')
      ? 'map-toolbar-overflow-left'
      : 'map-toolbar-overflow-right',
  ].join(' ');
}

export function ToolbarControl(props: ToolbarControlProps) {
  const merged = {
    ...defaultMapProps,
    position: 'top-left' as const,
    ...props,
  };
  const { moduleContainerProps, mapId } = useMap({
    ...merged,
    controlId: 'mapToolbarControl',
    controlLayout: 'button',
  });
  const mapContext = useContext(MapContext);
  const menuMode =
    !!mapContext?.isMobile && mapContext?.buttonInMobile === 'menu';

  const { trans, setLocaleDefault } = useLang(mapId);
  const [buttons, setButtons] = useState<MapControlButtonState[]>([]);
  const [moreOpen, setMoreOpen] = useState(false);
  const [moreOpenCorner, setMoreOpenCorner] = useState<Position | null>(null);
  const [availableWidth, setAvailableWidth] = useState(() =>
    typeof window === 'undefined'
      ? 0
      : toolbarAvailableWidth(window.innerWidth),
  );
  const [hostHeight, setHostHeight] = useState(0);
  const [reservedByCorner, setReservedByCorner] = useState<
    Partial<Record<Position, { width: number; height: number }>>
  >({});
  const [menuUsedByCorner, setMenuUsedByCorner] = useState<
    Partial<Record<Position, number>>
  >({});
  const rootRef = useRef<HTMLDivElement | null>(null);
  const toolbarStore = useMapToolbarStore(mapId);

  const findMapContainer = () => {
    const fromRef = rootRef.current?.closest('.map-container');
    if (fromRef instanceof HTMLElement) return fromRef;
    const fromContent = document
      .getElementById(mapId)
      ?.closest('.map-container');
    return fromContent instanceof HTMLElement ? fromContent : null;
  };

  const syncHost = () => {
    const el = findMapContainer();
    if (el) {
      setHostHeight(el.clientHeight);
      setAvailableWidth(toolbarAvailableWidth(el.clientWidth));
    } else {
      setHostHeight(0);
      setAvailableWidth(
        toolbarAvailableWidth(
          typeof window === 'undefined' ? 0 : window.innerWidth,
        ),
      );
    }

    if (!menuMode) {
      setReservedByCorner({});
      setMenuUsedByCorner({});
      return;
    }
    const nextReserved: Partial<
      Record<Position, { width: number; height: number }>
    > = {};
    const nextUsed: Partial<Record<Position, number>> = {};
    for (const position of CORNER_POSITIONS) {
      const host = document.getElementById(`${position}-${mapId}`);
      nextReserved[position] = measureCornerStandaloneReserved(host);
      const used = measureCornerMenuUsedPx(host);
      if (used != null) nextUsed[position] = used;
    }
    setReservedByCorner(nextReserved);
    setMenuUsedByCorner(nextUsed);
  };

  useEffect(() => {
    setLocaleDefault(TOOLBAR_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  useEffect(() => {
    const store = createToolbarStoreApi(toolbarStore);
    const syncButtons = () => {
      setButtons(store.getAll().map((btn) => ({ ...btn })));
    };
    const unsub = store.subscribe(syncButtons);
    syncButtons();
    return unsub;
  }, [toolbarStore]);

  useEffect(() => {
    syncHost();
    const observer =
      typeof ResizeObserver !== 'undefined'
        ? new ResizeObserver(() => syncHost())
        : undefined;
    const mapEl = findMapContainer();
    if (observer && mapEl) observer.observe(mapEl);
    if (observer && menuMode) {
      for (const position of CORNER_POSITIONS) {
        const host = document.getElementById(`${position}-${mapId}`);
        if (host) observer.observe(host);
      }
    }
    window.addEventListener('resize', syncHost);
    const onDoc = (e: MouseEvent) => {
      const t = e.target;
      if (
        t instanceof Element &&
        t.closest('.map-toolbar-control, .map-toolbar-overflow')
      ) {
        return;
      }
      setMoreOpen(false);
      setMoreOpenCorner(null);
    };
    document.addEventListener('pointerdown', onDoc);
    return () => {
      observer?.disconnect();
      window.removeEventListener('resize', syncHost);
      document.removeEventListener('pointerdown', onDoc);
    };
  }, [menuMode, mapId, buttons.length]);

  const groups = useMemo(() => groupToolbarButtons(buttons), [buttons]);
  const maxVisibleToolbar =
    props.maxVisible ??
    maxVisibleToolbarButtons(availableWidth, MAP_BUTTON_SIZE_PX.medium);
  const toolbarSplit = useMemo(
    () => splitToolbarOverflow(groups, maxVisibleToolbar),
    [groups, maxVisibleToolbar],
  );

  const cornerData = useMemo(() => {
    return CORNER_POSITIONS.map((position) => {
      const cornerGroups = groupToolbarButtons(
        buttons.filter((b) => (b.position || 'bottom-right') === position),
      );
      if (!cornerGroups.length) return null;
      const side = position.endsWith('left') ? 'left' : 'right';
      const budgets = cornerVerticalMenuBudgetsPx({
        hostHeight,
        topReservedPx: reservedByCorner[`top-${side}` as Position]?.height ?? 0,
        bottomReservedPx:
          reservedByCorner[`bottom-${side}` as Position]?.height ?? 0,
        topMenuUsedPx: menuUsedByCorner[`top-${side}` as Position],
        bottomMenuUsedPx: menuUsedByCorner[`bottom-${side}` as Position],
      });
      const budgetPx = position.startsWith('top')
        ? budgets.topPx
        : budgets.bottomPx;
      const prefer = position.startsWith('bottom') ? 'end' : 'start';
      const maxVisible =
        props.maxVisible ??
        maxVisibleButtonsInStackHeight(budgetPx, MAP_BUTTON_SIZE_PX.medium);
      const split = splitToolbarOverflowKeepGroups(
        cornerGroups,
        maxVisible,
        prefer,
      );
      return {
        position,
        prefer,
        maxVisible,
        split,
        showMore: split.overflow.length > 0 && maxVisible >= 1,
        hasChrome:
          cornerGroups.length > 0 &&
          (split.visible.length > 0 || maxVisible >= 1),
      };
    }).filter((c): c is NonNullable<typeof c> => c != null && c.hasChrome);
  }, [buttons, hostHeight, props.maxVisible, reservedByCorner, menuUsedByCorner]);

  const overflowOpen = moreOpen && toolbarSplit.overflow.length > 0;
  const pos = merged.position || 'bottom-right';
  const moreOption = mdiButtonState(mdiDotsHorizontal, {
    title: trans('map.toolbar.more'),
    active: moreOpen,
  });

  useEffect(() => {
    if (!toolbarSplit.overflow.length) setMoreOpen(false);
  }, [toolbarSplit.overflow.length]);

  if (menuMode) {
    return (
      <div className="map-toolbar-menu-hosts">
        {cornerData.map((corner) => {
          const cornerMoreOpen = moreOpenCorner === corner.position;
          const moreOpt = mdiButtonState(mdiDotsHorizontal, {
            title: trans('map.toolbar.more'),
            active: cornerMoreOpen,
          });
          const toggleMore = (e: { stopPropagation: () => void }) => {
            e.stopPropagation();
            setMoreOpenCorner((cur) =>
              cur === corner.position ? null : corner.position,
            );
          };
          return (
            <ModuleContainer
              key={corner.position}
              {...moduleContainerProps}
              position={corner.position}
              controlOrder={0}
              btn={
                <div
                  className="map-toolbar-control map-toolbar-corner"
                  data-position={corner.position}
                >
                  <div className="map-toolbar-corner-stack">
                    {corner.showMore && corner.prefer === 'end' ? (
                      <MapCommonButton
                        option={moreOpt}
                        aria-haspopup="true"
                        aria-expanded={cornerMoreOpen}
                        onPointerDown={(e) => e.stopPropagation()}
                        onClick={toggleMore}
                      />
                    ) : null}
                    {corner.split.visible.map((group) => (
                      <MapControlGroupButton
                        key={group.id}
                        row={group.orientation === 'row'}
                      >
                        {group.buttons.map((btn) => (
                          <MapCommonButton
                            key={btn.id}
                            option={btn}
                            onClick={(e) => btn.action(e.nativeEvent)}
                          />
                        ))}
                      </MapControlGroupButton>
                    ))}
                    {corner.showMore && corner.prefer === 'start' ? (
                      <MapCommonButton
                        option={moreOpt}
                        aria-haspopup="true"
                        aria-expanded={cornerMoreOpen}
                        onPointerDown={(e) => e.stopPropagation()}
                        onClick={toggleMore}
                      />
                    ) : null}
                  </div>
                </div>
              }
              btnOutside={
                corner.showMore && cornerMoreOpen ? (
                  <div
                    className="map-toolbar-overflow"
                    role="menu"
                    onPointerDown={(e) => e.stopPropagation()}
                  >
                    {corner.split.overflow.map((group) => (
                      <MapControlGroupButton key={group.id} row>
                        {group.buttons.map((btn) => (
                          <MapCommonButton
                            key={btn.id}
                            option={btn}
                            onClick={(e) => {
                              btn.action(e.nativeEvent);
                              setMoreOpenCorner(null);
                            }}
                          />
                        ))}
                      </MapControlGroupButton>
                    ))}
                  </div>
                ) : null
              }
            />
          );
        })}
      </div>
    );
  }

  if (!groups.length) {
    return <ModuleContainer {...moduleContainerProps} />;
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        <div ref={rootRef} className="map-toolbar-control">
          <MapControlGroupButton row>
            {toolbarSplit.visible.map((group) => (
              <MapControlGroupButton key={group.id} row>
                {group.buttons.map((btn) => (
                  <MapCommonButton
                    key={btn.id}
                    option={btn}
                    onClick={(e) => btn.action(e.nativeEvent)}
                  />
                ))}
              </MapControlGroupButton>
            ))}
            {toolbarSplit.overflow.length ? (
              <MapCommonButton
                option={moreOption}
                aria-haspopup="true"
                aria-expanded={overflowOpen}
                onClick={(e) => {
                  e.stopPropagation();
                  setMoreOpen((open) => !open);
                }}
              />
            ) : null}
          </MapControlGroupButton>
          {overflowOpen ? (
            <div className={overflowClassFor(pos)} role="menu">
              {toolbarSplit.overflow.map((group) => (
                <MapControlGroupButton key={group.id} row>
                  {group.buttons.map((btn) => (
                    <MapCommonButton
                      key={btn.id}
                      option={btn}
                      onClick={(e) => {
                        btn.action(e.nativeEvent);
                        setMoreOpen(false);
                      }}
                    />
                  ))}
                </MapControlGroupButton>
              ))}
            </div>
          ) : null}
        </div>
      }
    />
  );
}

// libs/vue/map-core/src/extra/toolbar/modules/ToolbarControl/ToolbarControl.vue
<script setup lang="ts">
import {
  MAP_BUTTON_SIZE_PX,
  type Position,
  type WithMapPropType,
} from '@hungpvq/map-core';
import type { MapControlButtonState } from '@hungpvq/map-core/toolbar';
import {
  TOOLBAR_CONTROL_LOCALE,
  cornerVerticalMenuBudgetsPx,
  groupToolbarButtons,
  maxVisibleButtonsInStackHeight,
  maxVisibleToolbarButtons,
  mdiButtonState,
  measureCornerMenuUsedPx,
  measureCornerStandaloneReserved,
  splitToolbarOverflow,
  splitToolbarOverflowKeepGroups,
  toolbarAvailableWidth,
} from '@hungpvq/map-core/toolbar';
import { mdiDotsHorizontal } from '@mdi/js';
import {
  computed,
  inject,
  onMounted,
  onUnmounted,
  ref,
  unref,
  watch,
  type ComputedRef,
} from 'vue';
import MapCommonButton from '../../../../components/MapCommonButton.vue';
import MapControlGroupButton from '../../../../components/MapControlGroupButton.vue';
import { defaultMapProps, useMap } from '../../../../hooks';
import ModuleContainer from '../../../../modules/ModuleContainer/ModuleContainer.vue';
import { useLang } from '../../../lang';
import { useMapToolbar } from '../../store';

const CORNER_POSITIONS: Position[] = [
  'top-left',
  'top-right',
  'bottom-left',
  'bottom-right',
];

const props = withDefaults(
  defineProps<
    Omit<WithMapPropType, 'controlLayout'> & { maxVisible?: number }
  >(),
  {
    ...defaultMapProps,
    position: 'top-left' as const,
  },
);
const { moduleContainerProps, mapId } = useMap({
  ...props,
  controlLayout: 'button',
});
const { trans, setLocaleDefault } = useLang(mapId.value);
setLocaleDefault(TOOLBAR_CONTROL_LOCALE);

const isMobile = inject<ComputedRef<boolean> | boolean | undefined>(
  '$map.isMobile',
  undefined,
);
const buttonInMobile = inject<
  ComputedRef<string | undefined> | string | undefined
>('$map.buttonInMobile', undefined);

const menuMode = computed(
  () => !!unref(isMobile) && unref(buttonInMobile) === 'menu',
);

const buttons = ref<MapControlButtonState[]>([]);
const store = useMapToolbar(mapId.value);
const moreOpen = ref(false);
const moreOpenCorner = ref<Position | null>(null);
const availableWidth = ref(
  typeof window === 'undefined' ? 0 : toolbarAvailableWidth(window.innerWidth),
);
const hostHeight = ref(0);
const reservedByCorner = ref<
  Partial<Record<Position, { width: number; height: number }>>
>({});
const menuUsedByCorner = ref<Partial<Record<Position, number>>>({});
const rootRef = ref<HTMLElement | null>(null);

let unsubStore: (() => void) | undefined;
let offResize: (() => void) | undefined;
let offDoc: (() => void) | undefined;
let resizeObserver: ResizeObserver | undefined;

function findMapContainer(): HTMLElement | null {
  const fromRef = rootRef.value?.closest('.map-container');
  if (fromRef instanceof HTMLElement) return fromRef;
  const fromContent = document
    .getElementById(mapId.value)
    ?.closest('.map-container');
  return fromContent instanceof HTMLElement ? fromContent : null;
}

function syncCornerReserved() {
  if (!menuMode.value) {
    reservedByCorner.value = {};
    menuUsedByCorner.value = {};
    return;
  }
  const nextReserved: Partial<
    Record<Position, { width: number; height: number }>
  > = {};
  const nextUsed: Partial<Record<Position, number>> = {};
  for (const position of CORNER_POSITIONS) {
    const host = document.getElementById(`${position}-${mapId.value}`);
    nextReserved[position] = measureCornerStandaloneReserved(host);
    const used = measureCornerMenuUsedPx(host);
    if (used != null) nextUsed[position] = used;
  }
  reservedByCorner.value = nextReserved;
  menuUsedByCorner.value = nextUsed;
}

function readHost() {
  const el = findMapContainer();
  if (el) {
    hostHeight.value = el.clientHeight;
    return el.clientWidth;
  }
  hostHeight.value = 0;
  return typeof window === 'undefined' ? 0 : window.innerWidth;
}

function syncHost() {
  availableWidth.value = toolbarAvailableWidth(readHost());
  syncCornerReserved();
}

function observeHost() {
  resizeObserver?.disconnect();
  resizeObserver = undefined;
  if (typeof ResizeObserver === 'undefined') return;

  resizeObserver = new ResizeObserver(() => syncHost());
  const mapEl = findMapContainer();
  if (mapEl) resizeObserver.observe(mapEl);

  if (menuMode.value) {
    for (const position of CORNER_POSITIONS) {
      const host = document.getElementById(`${position}-${mapId.value}`);
      if (host) resizeObserver.observe(host);
    }
  }
}

onMounted(() => {
  unsubStore = store.subscribe(() => {
    buttons.value = store.getAll();
  });
  buttons.value = store.getAll();

  window.addEventListener('resize', syncHost);
  offResize = () => window.removeEventListener('resize', syncHost);

  const onDoc = (e: MouseEvent) => {
    if (!moreOpen.value && !moreOpenCorner.value) return;
    const t = e.target;
    if (
      t instanceof Element &&
      t.closest('.map-toolbar-control, .map-toolbar-overflow')
    ) {
      return;
    }
    moreOpen.value = false;
    moreOpenCorner.value = null;
  };
  document.addEventListener('pointerdown', onDoc);
  offDoc = () => document.removeEventListener('pointerdown', onDoc);
});

watch(
  [rootRef, menuMode, buttons],
  () => {
    observeHost();
    syncHost();
  },
  { flush: 'post' },
);

onUnmounted(() => {
  unsubStore?.();
  offResize?.();
  offDoc?.();
  resizeObserver?.disconnect();
});

const groupedButtons = computed(() => groupToolbarButtons(buttons.value));
const maxVisibleToolbar = computed(
  () =>
    props.maxVisible ??
    maxVisibleToolbarButtons(availableWidth.value, MAP_BUTTON_SIZE_PX.medium),
);
const toolbarSplit = computed(() =>
  splitToolbarOverflow(groupedButtons.value, maxVisibleToolbar.value),
);

function splitForCorner(position: Position) {
  const groups = groupToolbarButtons(
    buttons.value.filter((b) => (b.position || 'bottom-right') === position),
  );
  const side = position.endsWith('left') ? 'left' : 'right';
  const budgets = cornerVerticalMenuBudgetsPx({
    hostHeight: hostHeight.value,
    topReservedPx: reservedByCorner.value[`top-${side}` as Position]?.height ?? 0,
    bottomReservedPx:
      reservedByCorner.value[`bottom-${side}` as Position]?.height ?? 0,
    topMenuUsedPx: menuUsedByCorner.value[`top-${side}` as Position],
    bottomMenuUsedPx: menuUsedByCorner.value[`bottom-${side}` as Position],
  });
  const budgetPx = position.startsWith('top') ? budgets.topPx : budgets.bottomPx;
  const prefer = position.startsWith('bottom') ? 'end' : 'start';
  const maxVisible =
    props.maxVisible ??
    maxVisibleButtonsInStackHeight(budgetPx, MAP_BUTTON_SIZE_PX.medium);
  const split = splitToolbarOverflowKeepGroups(groups, maxVisible, prefer);
  return {
    position,
    prefer,
    maxVisible,
    split,
    // Hide corner when budget fits nothing (avoids a spilling lone More).
    showMore: split.overflow.length > 0 && maxVisible >= 1,
    hasChrome: groups.length > 0 && (split.visible.length > 0 || maxVisible >= 1),
  };
}

const cornerData = computed(() =>
  CORNER_POSITIONS.map(splitForCorner).filter((c) => c.hasChrome),
);

const overflowOpen = computed(
  () => moreOpen.value && toolbarSplit.value.overflow.length > 0,
);

const overflowPlacement = computed(() => {
  const pos = props.position || 'bottom-right';
  return {
    vertical: pos.startsWith('top') ? 'top' : 'bottom',
    horizontal: pos.endsWith('left') ? 'left' : 'right',
  };
});

const moreOption = computed(() =>
  mdiButtonState(mdiDotsHorizontal, {
    title: trans.value('map.toolbar.more'),
    active: moreOpen.value,
  }),
);

function cornerMoreOption(position: Position) {
  return mdiButtonState(mdiDotsHorizontal, {
    title: trans.value('map.toolbar.more'),
    active: moreOpenCorner.value === position,
  });
}

watch(
  () => toolbarSplit.value.overflow.length,
  (n) => {
    if (!n) moreOpen.value = false;
  },
);

function onOverflowAction(btn: MapControlButtonState, e: MouseEvent) {
  btn.action(e);
  moreOpen.value = false;
  moreOpenCorner.value = null;
}

function toggleCornerMore(position: Position) {
  moreOpenCorner.value =
    moreOpenCorner.value === position ? null : position;
}
</script>

<template>
  <ModuleContainer v-if="!menuMode" v-bind="moduleContainerProps">
    <template #btn>
      <div
        v-if="groupedButtons.length"
        ref="rootRef"
        class="map-toolbar-control"
      >
        <MapControlGroupButton row>
          <MapControlGroupButton
            v-for="group in toolbarSplit.visible"
            :key="group.id"
            row
          >
            <MapCommonButton
              v-for="btn in group.buttons"
              :key="btn.id"
              :option="btn"
              @click="btn.action($event)"
            />
          </MapControlGroupButton>
          <MapCommonButton
            v-if="toolbarSplit.overflow.length"
            :option="moreOption"
            aria-haspopup="true"
            :aria-expanded="overflowOpen"
            @click.stop="moreOpen = !moreOpen"
          />
        </MapControlGroupButton>
        <div
          v-if="overflowOpen"
          class="map-toolbar-overflow"
          :class="[
            overflowPlacement.vertical === 'top'
              ? 'map-toolbar-overflow-top'
              : 'map-toolbar-overflow-bottom',
            overflowPlacement.horizontal === 'left'
              ? 'map-toolbar-overflow-left'
              : 'map-toolbar-overflow-right',
          ]"
          role="menu"
        >
          <MapControlGroupButton
            v-for="group in toolbarSplit.overflow"
            :key="group.id"
            row
          >
            <MapCommonButton
              v-for="btn in group.buttons"
              :key="btn.id"
              :option="btn"
              @click="onOverflowAction(btn, $event)"
            />
          </MapControlGroupButton>
        </div>
      </div>
    </template>
    <slot />
  </ModuleContainer>

  <div v-else class="map-toolbar-menu-hosts">
    <ModuleContainer
      v-for="corner in cornerData"
      :key="corner.position"
      v-bind="moduleContainerProps"
      :position="corner.position"
      :control-order="0"
    >
      <template #btn>
        <div
          class="map-toolbar-control map-toolbar-corner"
          :data-position="corner.position"
        >
          <div class="map-toolbar-corner-stack">
            <MapCommonButton
              v-if="corner.showMore && corner.prefer === 'end'"
              :option="cornerMoreOption(corner.position)"
              aria-haspopup="true"
              :aria-expanded="moreOpenCorner === corner.position"
              @pointerdown.stop
              @click.stop="toggleCornerMore(corner.position)"
            />
            <MapControlGroupButton
              v-for="group in corner.split.visible"
              :key="group.id"
              :row="group.orientation === 'row'"
            >
              <MapCommonButton
                v-for="btn in group.buttons"
                :key="btn.id"
                :option="btn"
                @click="btn.action($event)"
              />
            </MapControlGroupButton>
            <MapCommonButton
              v-if="corner.showMore && corner.prefer === 'start'"
              :option="cornerMoreOption(corner.position)"
              aria-haspopup="true"
              :aria-expanded="moreOpenCorner === corner.position"
              @pointerdown.stop
              @click.stop="toggleCornerMore(corner.position)"
            />
          </div>
        </div>
      </template>
      <template #btnOutside>
        <div
          v-if="corner.showMore && moreOpenCorner === corner.position"
          class="map-toolbar-overflow"
          role="menu"
          @pointerdown.stop
        >
          <MapControlGroupButton
            v-for="group in corner.split.overflow"
            :key="group.id"
            row
          >
            <MapCommonButton
              v-for="btn in group.buttons"
              :key="btn.id"
              :option="btn"
              @click="onOverflowAction(btn, $event)"
            />
          </MapControlGroupButton>
        </div>
      </template>
    </ModuleContainer>
    <slot />
  </div>
</template>
