// libs/react/map-core/src/extra/event/modules/ActionControl.tsx
import { useCallback, useEffect, useRef } from 'react';
import type { WithMapPropType } from '@hungpvq/map-core';
import type { IEvent, MittTypeMapEvent } from '@hungpvq/map-core/event';
import { MittTypeMapEventEventKey } from '@hungpvq/map-core/event';
import { defaultMapProps, useMap } from '../../../hooks';
import { useMapMittStore } from '../../mitt';
import { useEventMapItems } from '../hook';
import { useMapEventStore } from '../store';

export function ActionControl(props: WithMapPropType) {
  const merged = { ...defaultMapProps, ...props };
  const { callMap, mapId } = useMap(merged);
  const store = useMapEventStore(mapId);
  const emitter = useMapMittStore<MittTypeMapEvent>(mapId);
  const currentListener = useRef<
    Record<string, Record<string, IEvent | undefined>>
  >({});

  const setCurrentEvent = useCallback(
    (event_map_type: string, event?: IEvent) => {
      store.current[event_map_type] = event;
      emitter.emit(MittTypeMapEventEventKey.setCurrent, event);
    },
    [store, emitter],
  );

  const updateEventMap = useCallback(
    (events: IEvent[]) => {
      const listeners: Record<string, IEvent[]> = {};
      events.forEach((event) => {
        const key = event.event_map_type;
        if (!listeners[key]) listeners[key] = [];
        listeners[key].push(event);
      });
      callMap((map) => {
        if (!currentListener.current[map.id]) {
          currentListener.current[map.id] = {};
        }
        const keyAdd: string[] = [];
        for (const key of Object.keys(listeners)) {
          keyAdd.push(key);
          const group = listeners[key];
          const current = currentListener.current[map.id][key];
          const newCurrent = group[0];
          if (current && current.id === newCurrent.id) continue;
          if (current) current.removeFromMap(map);
          currentListener.current[map.id][key] = newCurrent;
          if (newCurrent) newCurrent.addToMap(map);
          setCurrentEvent(key, newCurrent);
        }
        for (const key of Object.keys(currentListener.current[map.id])) {
          if (!keyAdd.includes(key)) {
            const current = currentListener.current[map.id][key];
            if (current) current.removeFromMap(map);
            delete currentListener.current[map.id][key];
            setCurrentEvent(key, undefined);
          }
        }
      });
    },
    [callMap, setCurrentEvent],
  );

  // Match Vue: apply map listeners immediately via onChange (don't rely only on
  // useEffect(items) — store.items is mutated in place).
  useEventMapItems(mapId, { onChange: updateEventMap });

  useEffect(() => {
    updateEventMap(store.items);
  }, [mapId, store, updateEventMap]);

  return null;
}

// libs/map/core/src/extra/event/modules/ActionControl.vue
<script lang="ts">
export default {
  name: 'action-control',
};
</script>
<script setup lang="ts">
import { logHelper } from '@hungpvq/shared-map';
import { groupBy } from 'lodash';

import { onMounted } from 'vue';
import { defaultMapProps, useMap, type WithMapPropType } from '../../../hooks';
import { useMapMittStore } from '../../mitt';
import { useEventMapItems } from '../hook';
import { logger } from '../logger';
import { useMapEventStore } from '../store';
import { IEvent, MittTypeMapEvent, MittTypeMapEventEventKey } from '../types';
const props = withDefaults(defineProps<WithMapPropType>(), {
  ...defaultMapProps,
});
const { callMap, mapId } = useMap(props);
const store = useMapEventStore(mapId.value);
const emitter = useMapMittStore<MittTypeMapEvent>(mapId.value);
const current_listener: Record<string, Record<string, IEvent | undefined>> = {};
const { items } = useEventMapItems(mapId.value, {
  onChange: (value) => {
    updateEventMap(value);
  },
});
onMounted(() => {
  updateEventMap(items.value);
});
function setCurrentEvent(
  mapId: string,
  event_map_type: string,
  event?: IEvent,
) {
  logHelper(logger, mapId, 'store').debug(
    'setCurrentEvent',
    event_map_type,
    event,
  );
  store.current[event_map_type] = event;
  emitter.emit(MittTypeMapEventEventKey.setCurrent, event);
}
function updateEventMap(events: IEvent[]) {
  const listeners = groupBy<IEvent>(events, (event) => {
    return event.event_map_type;
  });
  callMap((map) => {
    const key_add: string[] = [];
    if (!current_listener[map.id]) {
      current_listener[map.id] = {};
    }
    for (const key in listeners) {
      key_add.push(key);
      if (Object.prototype.hasOwnProperty.call(listeners, key)) {
        const events = listeners[key];
        const current = current_listener[map.id][key];
        const new_current = events[0];

        if (current && current.id === new_current.id) {
          return;
        }
        if (current) {
          current.removeFromMap(map);
        }
        current_listener[map.id][key] = new_current;
        if (new_current) {
          new_current.addToMap(map);
        }
        setCurrentEvent(mapId.value, key, new_current);
      }
    }
    for (const key in current_listener[map.id]) {
      if (Object.prototype.hasOwnProperty.call(current_listener[map.id], key)) {
        const element = current_listener[map.id][key];
        if (!key_add.includes(key) && element) {
          element.removeFromMap(map);
          setCurrentEvent(mapId.value, key, undefined);
          current_listener[map.id][key] = undefined;
        }
      }
    }
  });
}
</script>
<template>
  <div></div>
</template>
