// libs/react/map-core/src/extra/measurement/modules/setting/field-geometry.tsx
import type {
  CoordinatesNumber,
  DraftCoordinatesNumber,
} from '@hungpvq/map-core';
import { parseCoordinateListText } from '@hungpvq/map-core';
import {
  mdiCrosshairsGps,
  mdiDeleteOutline,
  mdiDownloadOutline,
  mdiPlus,
} from '@mdi/js';
import { Icon } from '@mdi/react';
import type { Feature, FeatureCollection, Geometry, Position } from 'geojson';
import { saveAs } from 'file-saver';
import { useMemo, type ClipboardEvent } from 'react';

type Coord = DraftCoordinatesNumber;

export interface FieldGeometryProps {
  value?: Coord[];
  maxLength?: number;
  title?: string;
  titleActionDownload?: string;
  titleActionFillBound?: string;
  titleActionAddPoint?: string;
  onChange?: (value: Coord[]) => void;
  onClickFillBound?: (
    geometry: Geometry | Feature | FeatureCollection,
  ) => void;
  onClickRemove?: (index: number) => void;
}

function toPointFeature(coordinates: Position): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'Point', coordinates },
  };
}

function toLineStringFeature(coordinates: Position[]): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'LineString', coordinates },
  };
}

function toPolygonFeature(coordinates: Position[][]): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'Polygon', coordinates },
  };
}

function toGeometry(coordinates: Coord[]) {
  const validCoords = coordinates.filter(
    (c): c is CoordinatesNumber => c[0] !== null && c[1] !== null,
  );
  if (!validCoords.length) return undefined;
  if (validCoords.length === 1) return toPointFeature(validCoords[0]);
  if (validCoords.length === 2) return toLineStringFeature(validCoords);
  return toPolygonFeature([[...validCoords, validCoords[0]]]);
}

export function FieldGeometry({
  value = [],
  maxLength = 0,
  title,
  titleActionDownload,
  titleActionFillBound,
  titleActionAddPoint,
  onChange,
  onClickFillBound,
  onClickRemove,
}: FieldGeometryProps) {
  const isCanAdd = useMemo(
    () => !maxLength || value.length < maxLength,
    [maxLength, value.length],
  );

  function submit(next: Coord[]) {
    onChange?.([...next]);
  }

  function onAddItem() {
    submit([...value, [null, null]]);
  }

  function onUpdateCoord(index: number, axis: 0 | 1, raw: string) {
    const next = value.map((item, i) => {
      if (i !== index) return item;
      const copy: Coord = [...item] as Coord;
      copy[axis] = raw === '' ? null : Number(raw);
      return copy;
    });
    submit(next);
  }

  /** Paste one pair or multi-line CSV into the list (from this row). */
  function onPasteCoordinate(
    event: ClipboardEvent<HTMLInputElement>,
    index: number,
  ) {
    const text = event.clipboardData.getData('text');
    const parsed = parseCoordinateListText(text);
    if (!parsed.length) return;
    event.preventDefault();

    let points = parsed.map(([lng, lat]) => [lng, lat] as Coord);
    if (maxLength > 0) {
      const room = Math.max(0, maxLength - index);
      points = points.slice(0, room);
    }
    if (!points.length) return;

    const next = [
      ...value.slice(0, index),
      ...points,
      ...value.slice(index + points.length),
    ];
    submit(maxLength > 0 && next.length > maxLength ? next.slice(0, maxLength) : next);
  }

  function onDeleteItem(index: number) {
    const next = value.slice();
    next.splice(index, 1);
    onClickRemove?.(index);
    submit(next);
  }

  function onDownload() {
    const geom = toGeometry(value);
    if (!geom) return;
    const geojson = {
      type: 'FeatureCollection',
      features: [geom],
    };
    const blob = new Blob([JSON.stringify(geojson)], {
      type: 'text/plain;charset=utf-8',
    });
    saveAs(blob, 'geojson.json');
  }

  function onFlyTo() {
    const geom = toGeometry(value);
    if (geom) onClickFillBound?.(geom);
  }

  return (
    <div className="map-measurement-geometry">
      <div className="map-measurement-geometry__header">
        {title ? (
          <div className="map-measurement-geometry__title">{title}</div>
        ) : null}
        <div className="map-measurement-geometry__actions">
          <button
            type="button"
            onClick={onFlyTo}
            disabled={!value.length}
            className="map-measurement-geometry__btn"
            title={titleActionFillBound}
          >
            <Icon path={mdiCrosshairsGps} size="16px" />
          </button>
          <button
            type="button"
            onClick={onDownload}
            className="map-measurement-geometry__btn"
            disabled={!value.length}
            title={titleActionDownload}
          >
            <Icon path={mdiDownloadOutline} size="16px" />
          </button>
          {isCanAdd ? (
            <button
              type="button"
              onClick={onAddItem}
              className="map-measurement-geometry__btn"
              title={titleActionAddPoint}
            >
              <Icon path={mdiPlus} size="16px" />
            </button>
          ) : null}
        </div>
      </div>
      <div className="map-measurement-geometry__list">
        {value.map((item, index) => (
          <div className="map-measurement-geometry__item" key={index}>
            <div>#{index + 1}</div>
            <div>
              <input
                className="map-measurement-geometry__input"
                type="number"
                step="any"
                value={item[0] ?? ''}
                onChange={(e) => onUpdateCoord(index, 0, e.target.value)}
                onPaste={(e) => onPasteCoordinate(e, index)}
              />
            </div>
            <div>
              <input
                className="map-measurement-geometry__input"
                type="number"
                step="any"
                value={item[1] ?? ''}
                onChange={(e) => onUpdateCoord(index, 1, e.target.value)}
                onPaste={(e) => onPasteCoordinate(e, index)}
              />
            </div>
            <div>
              <button
                type="button"
                onClick={() => onDeleteItem(index)}
                className="map-measurement-geometry__btn"
              >
                <Icon path={mdiDeleteOutline} size="16px" />
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// libs/vue/map-core/src/extra/measurement/modules/setting/field-geometry.vue
<script setup lang="ts">
import type {
  CoordinatesNumber,
  DraftCoordinatesNumber,
} from '@hungpvq/map-core';
import { parseCoordinateListText } from '@hungpvq/map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import {
  mdiCrosshairsGps,
  mdiDeleteOutline,
  mdiDownloadOutline,
  mdiPlus,
  mdiUploadOutline,
} from '@mdi/js';
import FileSaver from 'file-saver';
import type { Feature, Position } from 'geojson';
import { computed } from 'vue';

const props = defineProps<{
  modelValue?: DraftCoordinatesNumber[];
  maxLength?: number;
  title?: string;
  titleActionDownload?: string;
  titleActionFillBound?: string;
  titleActionAddPoint?: string;
}>();

const model = defineModel<DraftCoordinatesNumber[]>({
  default: () => [[0, 0]],
});

const path = {
  add: mdiPlus,
  fillBound: mdiCrosshairsGps,
  delete: mdiDeleteOutline,
  download: mdiDownloadOutline,
  upload: mdiUploadOutline,
};

const emit = defineEmits<{
  (_e: 'click:remove', _index: number): void;
  (_e: 'click:fillbound', _geometry: Feature): void;
}>();

function toPointFeature(coordinates: Position): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'Point', coordinates },
  };
}

function toLineStringFeature(coordinates: Position[]): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'LineString', coordinates },
  };
}

function toPolygonFeature(coordinates: Position[][]): Feature {
  return {
    type: 'Feature',
    properties: {},
    geometry: { type: 'Polygon', coordinates },
  };
}

const submit = (value: DraftCoordinatesNumber[] = []) => {
  model.value = [...value];
};

const onAddItem = () => {
  if (!model.value) {
    model.value = [];
  }
  model.value.push([null, null]);
};

const onUpdatePathItem = () => {
  submit(model.value);
};

const onDeleteItem = (index: number) => {
  model.value.splice(index, 1);
  emit('click:remove', index);
  submit(model.value);
};

/** Paste one pair or multi-line CSV into the list (from this row). */
function onPasteCoordinate(event: ClipboardEvent, index: number) {
  const text = event.clipboardData?.getData('text') ?? '';
  const parsed = parseCoordinateListText(text);
  if (!parsed.length) return;
  event.preventDefault();

  const max = props.maxLength ?? 0;
  let points = parsed.map(
    ([lng, lat]) => [lng, lat] as DraftCoordinatesNumber,
  );
  if (max > 0) {
    const room = Math.max(0, max - index);
    points = points.slice(0, room);
  }
  if (!points.length) return;

  const next = [
    ...model.value.slice(0, index),
    ...points,
    ...model.value.slice(index + points.length),
  ];
  if (max > 0 && next.length > max) {
    submit(next.slice(0, max));
    return;
  }
  submit(next);
}

const convertGeometry = (coordinates: DraftCoordinatesNumber[]) => {
  const validCoords = coordinates.filter(
    (c): c is CoordinatesNumber => c[0] !== null && c[1] !== null,
  );
  if (!validCoords || !validCoords.length) {
    return;
  }
  if (validCoords.length === 1) {
    return toPointFeature(validCoords[0]);
  }
  if (validCoords.length === 2) {
    return toLineStringFeature(validCoords);
  }
  return toPolygonFeature([[...validCoords, validCoords[0]]]);
};

const onDownload = () => {
  const geom = convertGeometry(model.value);
  if (!geom) return;
  const geojson = {
    type: 'FeatureCollection',
    features: [geom],
  };
  const blob = new window.Blob([JSON.stringify(geojson)], {
    type: 'text/plain;charset=utf-8',
  });

  FileSaver.saveAs(blob, 'geojson.json');
};

const onFlyTo = () => {
  const geom = convertGeometry(model.value);
  if (geom) {
    emit('click:fillbound', geom);
  }
};

const isCanAdd = computed(() => {
  return !(props.maxLength ?? 0) || model.value.length < (props.maxLength ?? 0);
});
</script>
<template>
  <div class="map-measurement-geometry">
    <div class="map-measurement-geometry__header">
      <div v-if="title" class="map-measurement-geometry__title">
        {{ title }}
      </div>
      <div class="map-measurement-geometry__actions">
        <button
          type="button"
          @click="onFlyTo"
          :disabled="!modelValue || modelValue.length < 1"
          class="map-measurement-geometry__btn"
          :title="titleActionFillBound"
        >
          <SvgIcon
            :size="16"
            type="mdi"
            :path="path.fillBound"
            :title="titleActionFillBound"
          />
        </button>
        <button
          type="button"
          @click="onDownload"
          class="map-measurement-geometry__btn"
          :disabled="!modelValue || modelValue.length < 1"
        >
          <SvgIcon
            :size="16"
            type="mdi"
            :path="path.download"
            :title="titleActionDownload"
          />
        </button>
        <button
          type="button"
          @click="onAddItem"
          class="map-measurement-geometry__btn"
          v-if="isCanAdd"
        >
          <SvgIcon :size="16" type="mdi" :path="path.add" />
        </button>
      </div>
    </div>
    <div class="map-measurement-geometry__list">
      <div
        class="map-measurement-geometry__item"
        v-for="(item, index) in modelValue"
        :key="index"
      >
        <div>#{{ index + 1 }}</div>
        <div class="">
          <input
            class="map-measurement-geometry__input"
            v-model="model[index][0]"
            type="number"
            step="any"
            @change="onUpdatePathItem()"
            @paste="onPasteCoordinate($event, index)"
          />
        </div>
        <div class="">
          <input
            class="map-measurement-geometry__input"
            v-model="model[index][1]"
            type="number"
            step="any"
            @change="onUpdatePathItem()"
            @paste="onPasteCoordinate($event, index)"
          />
        </div>
        <div class="">
          <button
            type="button"
            @click="onDeleteItem(index)"
            class="map-measurement-geometry__btn"
          >
            <SvgIcon :size="16" type="mdi" :path="path.delete" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
