// libs/react/map-core/src/field/input-checkbox.tsx
import React from 'react';

export interface InputCheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'checked'> {
  label?: string;
  disabled?: boolean;
  checked?: boolean;
  onChange?: (checked: boolean) => void;
}

export function InputCheckbox({
  label,
  disabled = false,
  checked = false,
  onChange,
  className = '',
  ...props
}: InputCheckboxProps) {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e.target.checked);
  };

  return (
    <div className="form-group">
      <div className="form-control form-checkbox">
        <input
          type="checkbox"
          checked={checked}
          onChange={handleChange}
          disabled={disabled}
          className={className}
          {...props}
        />
        {label && <label>{label}</label>}
      </div>
    </div>
  );
}

// libs/map/core/src/field/input-checkbox.vue
<template lang="">
  <div class="form-group">
    <div class="form-control form-checkbox">
      <input type="checkbox" v-model="form" :disabled="disabled" />
      <label> {{ label }} </label>
    </div>
  </div>
</template>
<script setup lang="ts">
const form = defineModel({});
defineProps({
  label: String,
  disabled: Boolean,
});
</script>
<style scoped>
.form-checkbox {
  display: flex;
}
.form-checkbox label {
  padding-left: 8px;
}
</style>
