// libs/vue/map-dataset/src/modules/StyleControl/style-control.vue
<script setup lang="ts">
import { MapSimple } from '@hungpvq/map-core';
import {
  ComponentType,
  findSiblingOrNearestLeaf,
  IDataset,
  IMapboxLayerView,
  isMapboxLayerView,
} from '@hungpvq/map-dataset';
import { copyByJson } from '@hungpvq/shared';
import { DraggableItemSideBar } from '@hungpvq/vue-draggable';
import {
  ModuleContainer,
  RegistryItem,
  useLang,
  useMap,
  useMapControl,
  useShow,
} from '@hungpvq/vue-map-core';
import { onMounted, Ref, ref, shallowRef } from 'vue';

const emit = defineEmits(['close']);
const props = defineProps<{ item: IDataset }>();
const { mapId, callMap } = useMap();
const { trans } = useLang(mapId.value);
const [show, toggleShow] = useShow(false);
const { panelPosition, moduleContainerProps } = useMapControl(mapId, {
  id: 'mapStyleControl',
  panelKind: 'sidebar',
  title: () => trans.value('map.style-control.title'),
  show,
  setShow: toggleShow,
  initialPanelPosition: { location: 'right' },
  actions: [
    {
      type: 'mapStyleControl',
      run: () => toggleShow(),
    },
  ],
});
const layer = ref<unknown>();
const layer_map = ref<IMapboxLayerView | undefined>(undefined);
const layer_map_component: Ref<ComponentType> = shallowRef({
  componentKey: '',
});

onMounted(() => {
  toggleShow(true);
  layer_map.value = undefined;
  updateValue();
});

const onClose = () => {
  layer_map.value = undefined;
  layer.value = undefined;
  emit('close');
};

const onUpdateStyle = (value: unknown) => {
  callMap((map: MapSimple) => {
    if (!layer_map.value) {
      return;
    }
    layer_map.value.updateValue(map, value);
  });
  updateValue();
};

const updateValue = () => {
  const layerView = findSiblingOrNearestLeaf<IMapboxLayerView & IDataset>(
    props.item,
    (dataset) => isMapboxLayerView(dataset),
  );
  if (layerView) {
    if (isMapboxLayerView(layerView)) {
      layer_map.value = layerView || undefined;
      layer_map_component.value = layerView.getComponentUpdate();
      layer.value = copyByJson(layerView.getData());
    }
  }
};
</script>
<template>
  <ModuleContainer v-bind="$attrs">
    <template #draggable="p">
      <DraggableItemSideBar
        :containerId="p.containerId"
        v-model:show="show"
        v-if="layer_map_component.componentKey"
        @close="onClose"
        :title="trans('map.style-control.title')"
        :location="panelPosition.location || 'right'"
      >
        <template #title>
          <span class="layer-control__title">
            {{ trans('map.style-control.title') }}
          </span>
        </template>
        <div class="style-control">
          <RegistryItem
            :componentKey="layer_map_component.componentKey"
            v-model="layer"
            @update-style="onUpdateStyle"
            :trans="trans"
            :map-id="mapId"
          />
        </div>
      </DraggableItemSideBar>
    </template>
  </ModuleContainer>
</template>

// libs/react/map-dataset/src/modules/StyleControl/StyleControl.tsx
import type {
  ComponentType,
  IDataset,
  IMapboxLayerView,
} from '@hungpvq/map-dataset';
import {
  findSiblingOrNearestLeaf,
  isMapboxLayerView,
} from '@hungpvq/map-dataset';
import { DraggableItemSideBar } from '@hungpvq/react-draggable';
import {
  ModuleContainer,
  RegistryItem,
  useLang,
  useMap,
  useMapControl,
  useShow,
} from '@hungpvq/react-map-core';
import { copyByJson } from '@hungpvq/shared';
import { useEffect, useRef, useState } from 'react';

export function StyleControl({
  item,
  onClose,
}: {
  item: IDataset;
  onClose?: () => void;
}) {
  const { mapId, callMap } = useMap({
    controlId: 'mapStyleControl',
  });
  const { trans } = useLang(mapId);
  const [show, toggleShow] = useShow(false);
  const { panelPosition, moduleContainerProps } = useMapControl(mapId, {
    id: 'mapStyleControl',
    panelKind: 'sidebar',
    title: trans('map.style-control.title'),
    show,
    setShow: toggleShow,
    initialPanelPosition: { location: 'right' },
    actions: [{ type: 'mapStyleControl', run: () => toggleShow() }],
  });
  const [layer, setLayer] = useState<unknown>();
  const [layerView, setLayerView] = useState<IMapboxLayerView | undefined>();
  const [component, setComponent] = useState<ComponentType>({
    componentKey: '',
  });
  const layerViewRef = useRef(layerView);
  layerViewRef.current = layerView;

  useEffect(() => {
    toggleShow(true);
    setLayerView(undefined);
    updateValue();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [item]);

  function updateValue() {
    const layerViewFound = findSiblingOrNearestLeaf<
      IMapboxLayerView & IDataset
    >(item, (dataset) => isMapboxLayerView(dataset));
    if (layerViewFound && isMapboxLayerView(layerViewFound)) {
      setLayerView(layerViewFound);
      setComponent(layerViewFound.getComponentUpdate());
      setLayer(copyByJson(layerViewFound.getData()));
    }
  }

  function onUpdateStyle(value: unknown) {
    callMap((map) => {
      layerViewRef.current?.updateValue(map, value);
    });
    updateValue();
  }

  function handleClose() {
    setLayerView(undefined);
    setLayer(undefined);
    onClose?.();
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        component.componentKey ? (
          <DraggableItemSideBar
            containerId={bind.containerId}
            location={panelPosition.location || 'right'}
            show={show}
            onUpdateShow={(v) => {
              toggleShow(!!v);
              if (!v) handleClose();
            }}
            onClose={handleClose}
            title={trans('map.style-control.title')}
            titleNode={
              <span className="layer-control__title">
                {trans('map.style-control.title')}
              </span>
            }
          >
            <div className="style-control">
              <RegistryItem
                componentKey={component.componentKey}
                mapId={mapId}
                value={layer}
                trans={trans}
                onUpdateStyle={onUpdateStyle}
              />
            </div>
          </DraggableItemSideBar>
        ) : null
      }
    />
  );
}
