// libs/react/map-draw/src/modules/DrawControl/components/DrawDraftList.tsx
import type { MapPopupProps } from '@hungpvq/map-core';
import type { IDraftRecord } from '@hungpvq/map-draw';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import {
  MapControlButton,
  useLang,
  useMapControl,
} from '@hungpvq/react-map-core';
import { mdiCrosshairsGps, mdiDeleteOutline } from '@mdi/js';
import { Icon } from '@mdi/react';
import type { Feature } from 'geojson';

export interface DrawDraftListProps {
  show: boolean;
  setShow: (value: boolean) => void;
  draftItems: IDraftRecord[];
  mapId: string;
  onFlyTo: (feature: Feature) => void;
  onDiscardItem: (item: IDraftRecord) => void;
  popupProps?: MapPopupProps;
  /** ModuleContainer bindDrag spread onto popup position */
  bindDrag?: {
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
    containerId: string;
  };
}

/** Registers `mapDrawDraftList` and renders the draft popup table (Vue parity). */
export function DrawDraftList({
  show,
  setShow,
  draftItems,
  mapId,
  onFlyTo,
  onDiscardItem,
  bindDrag,
  popupProps,
}: DrawDraftListProps) {
  const { trans } = useLang(mapId);
  const { panelBind } = useMapControl(mapId, {
    id: 'mapDrawDraftList',
    panelKind: 'popup',
    title: trans('map.draw-control.draftList.title'),
    from: { popupProps },
    show,
    setShow,
    actions: [
      {
        type: 'mapDrawDraftList',
        run: () => {
          setShow(!show);
        },
      },
    ],
  });

  return (
    <DraggableItemPopup
      height={400}
      width={400}
      {...(bindDrag ?? {})}
      {...panelBind}
      show={show}
      onUpdateShow={setShow}
      title={trans('map.draw-control.draftList.title')}
    >
      <table className="draft-items-table">
        <thead>
          <tr>
            <th className="table-col-id">
              {trans('map.draw-control.draftList.field.id')}
            </th>
            <th className="table-col-type">
              {trans('map.draw-control.draftList.field.type')}
            </th>
            <th className="table-col-action">
              {trans('map.draw-control.draftList.field.action')}
            </th>
          </tr>
        </thead>
        <tbody>
          {draftItems.length === 0 ? (
            <tr>
              <td
                colSpan={3}
                className="table-col-empty"
              >
                {trans('map.draw-control.draftList.empty')}
              </td>
            </tr>
          ) : (
            draftItems.map((item) => (
              <tr key={String(item.id)}>
                <td
                  title={String(item.id)}
                  className="table-col-id"
                >
                  {item.id}
                </td>
                <td className="table-col-type">
                  {trans(`map.draw-control.draftList.type.${item.status}`)}
                </td>
                <td className="table-col-action">
                  {item.modified ? (
                    <MapControlButton
                      variant="plain"
                      type="button"
                      className="menu-item"
                      title={trans(
                        'map.draw-control.draftList.action.fillBound',
                      )}
                      onClick={() => onFlyTo(item.modified as Feature)}
                    >
                      <Icon
                        path={mdiCrosshairsGps}
                        size="16px"
                      />
                    </MapControlButton>
                  ) : null}
                  <MapControlButton
                    variant="plain"
                    type="button"
                    className="menu-item"
                    title={trans('map.draw-control.draftList.action.discard')}
                    onClick={() => onDiscardItem(item)}
                  >
                    <Icon
                      path={mdiDeleteOutline}
                      size="16px"
                    />
                  </MapControlButton>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
    </DraggableItemPopup>
  );
}

// libs/vue/map-draw/src/modules/DrawControl/components/DrawDraftList.vue
<script setup lang="ts">
import type { MapPopupProps } from '@hungpvq/map-core';
import type { IDraftRecord } from '@hungpvq/map-draw';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import {
  MapControlButton,
  useLang,
  useMapControl,
} from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCrosshairsGps, mdiDeleteOutline } from '@mdi/js';
import type { Feature } from 'geojson';
import { computed, type Ref } from 'vue';

const props = defineProps<{
  show: boolean;
  draftItems: IDraftRecord[];
  mapId: string;
  popupProps?: MapPopupProps;
}>();

const emit = defineEmits<{
  'update:show': [value: boolean];
  'fly-to': [feature: Feature];
  'discard-item': [item: IDraftRecord];
}>();

const { trans } = useLang(props.mapId);

const show = computed({
  get: () => props.show,
  set: (value: boolean) => emit('update:show', value),
});

const { panelBind } = useMapControl(() => props.mapId, {
  id: 'mapDrawDraftList',
  panelKind: 'popup',
  title: () => trans.value('map.draw-control.draftList.title'),
  from: () => ({ popupProps: props.popupProps }),
  show: show as Ref<boolean>,
  setShow: (value) => {
    show.value = value;
  },
  actions: [
    {
      type: 'mapDrawDraftList',
      run: () => {
        show.value = !show.value;
      },
    },
  ],
});

const path = {
  delete: mdiDeleteOutline,
  fillBound: mdiCrosshairsGps,
};
</script>

<template>
  <DraggableItemPopup
    :height="400"
    :width="400"
    v-bind="panelBind"
    :show="show"
    @update:show="(val) => emit('update:show', val)"
    :title="trans('map.draw-control.draftList.title')"
  >
    <table class="draft-items-table">
      <thead>
        <tr>
          <th class="table-col-id">
            {{ trans('map.draw-control.draftList.field.id') }}
          </th>
          <th class="table-col-type">
            {{ trans('map.draw-control.draftList.field.type') }}
          </th>
          <th class="table-col-action">
            {{ trans('map.draw-control.draftList.field.action') }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="!draftItems.length">
          <td
            colspan="3"
            class="table-col-empty"
          >
            {{ trans('map.draw-control.draftList.empty') }}
          </td>
        </tr>
        <tr
          v-for="item in draftItems"
          :key="item.id"
        >
          <td
            :title="item.id + ''"
            class="table-col-id"
          >
            {{ item.id }}
          </td>
          <td class="table-col-type">
            {{ trans('map.draw-control.draftList.type.' + item.status) }}
          </td>
          <td class="table-col-action">
            <MapControlButton
              variant="plain"
              type="button"
              v-if="item.modified"
              @click="emit('fly-to', item.modified as any)"
              class="menu-item"
              :title="trans('map.draw-control.draftList.action.fillBound')"
            >
              <SvgIcon
                :size="16"
                type="mdi"
                :path="path.fillBound"
                :title="trans('map.draw-control.draftList.action.fillBound')"
              />
            </MapControlButton>
            <MapControlButton
              variant="plain"
              type="button"
              @click="emit('discard-item', item)"
              class="menu-item"
              :title="trans('map.draw-control.draftList.action.discard')"
            >
              <SvgIcon
                :size="16"
                type="mdi"
                :path="path.delete"
                :title="trans('map.draw-control.draftList.action.discard')"
              />
            </MapControlButton>
          </td>
        </tr>
      </tbody>
    </table>
  </DraggableItemPopup>
</template>

<style scoped>
.draft-items-table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
}

.draft-items-table th,
.draft-items-table td {
  padding: 8px 12px;
  border-bottom: 1px solid #ffffff30;
  text-align: left;

  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.draft-items-table thead th {
  font-weight: bold;
}
.table-col-action {
  width: 64px;
}
.table-col-empty {
  text-align: center;
  opacity: 0.75;
  font-style: italic;
}
.menu-item {
  cursor: pointer;
}
</style>
