// libs/react/map-draw/src/modules/DrawControl/components/DrawToolbar.tsx
import { isDraftOption, type MapDrawOption } from '@hungpvq/map-draw';
import {
  MapControlButton,
  MapControlGroupButton,
} from '@hungpvq/react-map-core';
import {
  mdiClose,
  mdiContentSave,
  mdiContentSaveCheck,
  mdiDeleteOutline,
  mdiPencil,
  mdiPlus,
  mdiUndoVariant,
  mdiViewListOutline,
} from '@mdi/js';
import { Icon } from '@mdi/react';
import type {
  KeyboardEvent as ReactKeyboardEvent,
  MouseEvent as ReactMouseEvent,
} from 'react';

export interface DrawToolbarProps {
  drawOptions?: MapDrawOption;
  isShow: boolean;
  isDraw: boolean;
  method: string;
  draftCounts: number;
  onCancel: () => void;
  onSave: () => void;
  onClose: () => void;
  onStartDraw: (e: ReactMouseEvent) => void;
  onSelectMethod: (method: 'select' | 'delete') => void;
  onCommit: () => void;
  onDiscard: () => void;
  onShowList: () => void;
}

export function DrawToolbar({
  drawOptions,
  isShow,
  isDraw,
  method,
  draftCounts,
  onCancel,
  onSave,
  onClose,
  onStartDraw,
  onSelectMethod,
  onCommit,
  onDiscard,
  onShowList,
}: DrawToolbarProps) {
  if (!drawOptions) return null;

  function onToolbarKeydown(event: ReactKeyboardEvent<HTMLDivElement>) {
    if (event.key !== 'Escape') return;
    if (!isShow || !isDraw) return;
    event.preventDefault();
    onCancel();
  }

  return (
    <div
      className="d-flex button-custom-container button-draw-container"
      role="toolbar"
      aria-label="Draw tools"
      onKeyDown={onToolbarKeydown}
    >
      {isShow ? (
        isDraw ? (
          <MapControlGroupButton row>
            <MapControlButton
              onClick={onCancel}
              title="Cancel"
            >
              <Icon
                path={mdiClose}
                size={0.75}
              />
            </MapControlButton>
            <MapControlButton
              onClick={onSave}
              title="Save"
            >
              <Icon
                path={mdiContentSave}
                size={0.75}
              />
            </MapControlButton>
          </MapControlGroupButton>
        ) : (
          <MapControlGroupButton row>
            <MapControlButton
              onClick={onClose}
              title="Close"
            >
              <Icon
                path={mdiClose}
                size={0.75}
              />
            </MapControlButton>
            <MapControlButton
              active={method === 'create'}
              title="Draw"
              onClick={onStartDraw}
            >
              <Icon
                path={mdiPlus}
                size={0.75}
              />
            </MapControlButton>
            <MapControlButton
              active={method === 'select'}
              title="Select"
              onClick={() => onSelectMethod('select')}
            >
              <Icon
                path={mdiPencil}
                size={0.75}
              />
            </MapControlButton>
            <MapControlButton
              active={method === 'delete'}
              title="Delete"
              onClick={() => onSelectMethod('delete')}
            >
              <Icon
                path={mdiDeleteOutline}
                size={0.75}
              />
            </MapControlButton>
          </MapControlGroupButton>
        )
      ) : null}
      {isDraftOption(drawOptions) && drawOptions.draft.show ? (
        <MapControlGroupButton row>
          <MapControlButton
            disabled={isDraw || draftCounts === 0}
            title="Commit drafts"
            onClick={onCommit}
          >
            <Icon
              path={mdiContentSaveCheck}
              size={0.75}
            />
          </MapControlButton>
          <MapControlButton
            disabled={isDraw || draftCounts === 0}
            title="Discard drafts"
            onClick={onDiscard}
          >
            <Icon
              path={mdiUndoVariant}
              size={0.75}
            />
          </MapControlButton>
          <MapControlButton
            disabled={draftCounts === 0}
            title="Draft list"
            onClick={onShowList}
          >
            <Icon
              path={mdiViewListOutline}
              size={0.75}
            />
            {draftCounts > 0 ? (
              <span className="draft-item-count-badge map-control-badge">
                {draftCounts}
              </span>
            ) : null}
          </MapControlButton>
        </MapControlGroupButton>
      ) : null}
    </div>
  );
}

// libs/vue/map-draw/src/modules/DrawControl/components/DrawToolbar.vue
<script setup lang="ts">
import type { MapDrawOption } from '@hungpvq/map-draw';
import { isDraftOption } from '@hungpvq/map-draw';
import { MapControlButton, MapControlGroupButton } from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import {
  mdiClose,
  mdiContentSave,
  mdiContentSaveCheck,
  mdiDeleteOutline,
  mdiDraw,
  mdiPencil,
  mdiPlus,
  mdiUndoVariant,
  mdiViewListOutline,
} from '@mdi/js';

const props = defineProps<{
  drawOptions?: MapDrawOption;
  isShow: boolean;
  isDraw: boolean;
  method: string;
  draftCounts: number;
}>();

const emit = defineEmits<{
  cancel: [];
  save: [];
  close: [];
  'start-draw': [event: MouseEvent];
  'select-method': [method: 'select' | 'delete'];
  commit: [];
  discard: [];
  'show-list': [];
}>();

const path = {
  add: mdiPlus,
  delete: mdiDeleteOutline,
  update: mdiPencil,
  save: mdiContentSave,
  discard: mdiClose,
  close: mdiClose,
  draw: mdiDraw,
  draftCommit: mdiContentSaveCheck,
  draftDiscard: mdiUndoVariant,
  draftList: mdiViewListOutline,
};

function onToolbarKeydown(event: KeyboardEvent) {
  if (event.key !== 'Escape') return;
  if (!props.isShow || !props.isDraw) return;
  event.preventDefault();
  emit('cancel');
}
</script>

<template>
  <div
    class="d-flex button-custom-container button-draw-container"
    role="toolbar"
    aria-label="Draw tools"
    v-if="drawOptions"
    @keydown="onToolbarKeydown"
  >
    <template v-if="isShow">
      <MapControlGroupButton row v-if="isDraw">
        <MapControlButton title="Cancel" @click="emit('cancel')">
          <SvgIcon :size="18" type="mdi" :path="path.discard" />
        </MapControlButton>
        <MapControlButton title="Save" @click="emit('save')">
          <SvgIcon :size="18" type="mdi" :path="path.save" />
        </MapControlButton>
      </MapControlGroupButton>
      <MapControlGroupButton row v-else>
        <MapControlButton title="Close" @click="emit('close')">
          <SvgIcon :size="18" type="mdi" :path="path.close" />
        </MapControlButton>
        <MapControlButton
          title="Draw"
          :active="method === 'create'"
          @click="emit('start-draw', $event)"
        >
          <SvgIcon :size="18" type="mdi" :path="path.add" />
        </MapControlButton>
        <MapControlButton
          title="Select"
          :active="method === 'select'"
          @click="emit('select-method', 'select')"
        >
          <SvgIcon :size="18" type="mdi" :path="path.update" />
        </MapControlButton>
        <MapControlButton
          title="Delete"
          :active="method === 'delete'"
          @click="emit('select-method', 'delete')"
        >
          <SvgIcon :size="18" type="mdi" :path="path.delete" />
        </MapControlButton>
      </MapControlGroupButton>
    </template>
    <MapControlGroupButton
      row
      v-if="isDraftOption(drawOptions) && drawOptions.draft.show"
    >
      <MapControlButton
        title="Commit drafts"
        @click="emit('commit')"
        :disabled="isDraw || draftCounts == 0"
      >
        <SvgIcon :size="18" type="mdi" :path="path.draftCommit" />
      </MapControlButton>
      <MapControlButton
        title="Discard drafts"
        @click="emit('discard')"
        :disabled="isDraw || draftCounts == 0"
      >
        <SvgIcon :size="18" type="mdi" :path="path.draftDiscard" />
      </MapControlButton>
      <MapControlButton
        title="Draft list"
        @click="emit('show-list')"
        :disabled="draftCounts == 0"
      >
        <SvgIcon
          :size="18"
          type="mdi"
          :path="path.draftList"
          :disabled="draftCounts == 0"
        />
        <span
          class="draft-item-count-badge map-control-badge"
          v-if="draftCounts"
          >{{ draftCounts }}</span
        >
      </MapControlButton>
    </MapControlGroupButton>
  </div>
</template>

<style scoped>
.button-draw-container {
  display: flex;
  gap: 4px;
}
.map-control-badge {
  position: absolute;
  top: -6px;
  right: 2px;
  padding: 2px 6px;
  font-size: 0.5rem;
  font-weight: bold;
  border-radius: 999px;
  min-width: 1rem;
  height: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
}
.draft-item-count-badge {
  background: var(--map-draw-badge-bg, var(--map-primary-color, #004e98));
  color: var(--map-draw-badge-text, var(--map-text-inverse, white));
}
</style>
