// libs/vue/map-dataset/src/modules/LayerHighlight/LayerHighlight.vue
<template>
  <div></div>
</template>
<script setup lang="ts">
import {
  EventClick,
  logHelper,
  type MapSimple,
  type WithMapPropType,
} from '@hungpvq/map-core';
import type {
  HighlightHandle,
  IdentifySingleResult,
  IHighlightView,
} from '@hungpvq/map-dataset';
import {
  findSiblingOrNearestLeaf,
  handleMultiIdentifyGetFirst,
} from '@hungpvq/map-dataset';
import { defaultMapProps, useEventMap, useMap } from '@hungpvq/vue-map-core';
import type { Feature } from 'geojson';
import type { GeoJSONFeature, MapMouseEvent, PointLike } from 'maplibre-gl';
import { onMounted, onUnmounted, shallowRef, watch } from 'vue';
import { loggerHighlight } from '../../logger';
import { useMapDataset } from '../../store';
import { useMapDatasetHighlight } from '../../store/highlight';
import { useDefaultHighlight } from './helper';

const props = withDefaults(
  defineProps<
    WithMapPropType & {
      durationMs?: number;
      color?: string;
      enableClick?: boolean;
    }
  >(),
  {
    ...defaultMapProps,
    durationMs: 5000,
    color: '#004E98',
  },
);
const { mapId, callMap } = useMap(props, undefined, onRemoveMap);
const { getAllComponentsByType } = useMapDataset(mapId.value);
const { add: addEventClick, remove: removeEventClick } = useEventMap(
  mapId.value,
  new EventClick().setHandler(onMapClick),
);
const { getFeatureHighlight, setFeatureHighlight, getDatesetHighlight } =
  useMapDatasetHighlight(mapId.value);

onMounted(() => {
  if (props.enableClick) addEventClick();
});
onUnmounted(() => {
  removeEventClick();
});
function onMapClick(e: MapMouseEvent) {
  logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
    'onMapClick',
    e,
  );
  onGetFeatures(e.point);
}
async function onGetFeatures(pointOrBox?: PointLike | [PointLike, PointLike]) {
  const feature: IdentifySingleResult = await handleMultiIdentifyGetFirst(
    (getAllComponentsByType<IHighlightView>('highlight') || []) as any[],
    mapId.value,
    pointOrBox,
  );
  logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
    'onGetFeatures',
    feature,
  );
  setFeatureHighlight(feature.feature.data, 'highlight', feature.identify);
}
function onRemoveMap(map: MapSimple) {
  stopAnimation(map);
}

const handleHighligh = shallowRef<HighlightHandle | undefined>();
const handleDefault = useDefaultHighlight(props.color);
function updateHighlight(geojsonData?: Feature | GeoJSONFeature) {
  const durationMs = props.durationMs;
  logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
    'updateHighlight',
    'geojsonData',
    geojsonData,
  );
  if (!geojsonData) {
    return;
  }
  const dataset = getDatesetHighlight();
  let highlightView: IHighlightView | undefined = undefined;
  if (dataset) {
    highlightView = findSiblingOrNearestLeaf(
      dataset,
      (dataset) => dataset.type == 'highlight',
    ) as unknown as IHighlightView;
  }

  logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
    'updateHighlight',
    'highlightView',
    highlightView,
  );
  callMap((map: MapSimple) => {
    stopAnimation(map);
    handleHighligh.value = handleDefault;
    handleDefault.setDataset(highlightView);
    if (
      highlightView &&
      'startAnimation' in highlightView &&
      'stopAnimation' in highlightView
    ) {
      handleHighligh.value = highlightView;
      logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
        'updateHighlight',
        'use handle highlight of highlight dataset',
      );
    } else {
      logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug(
        'updateHighlight',
        'use handle default',
      );
    }
    logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug('start', {
      map,
      feature: geojsonData,
      durationMs,
      handleHighligh: handleHighligh.value,
    });
    handleHighligh.value.setOnDone(map, () => {
      clear();
    });
    handleHighligh.value.startAnimation({
      map,
      feature: geojsonData,
      durationMs,
    });
  });
}

watch(
  () => getFeatureHighlight()?.value, // đây là cái Vue thực sự theo dõi
  (value) => {
    if (!value) {
      callMap((map) => {
        stopAnimation(map);
      });
      return;
    }
    updateHighlight(value);
  },
);

function stopAnimation(map: MapSimple) {
  if (!handleHighligh.value) {
    return;
  }
  handleHighligh.value.stopAnimation(map);
  logHelper(loggerHighlight, mapId.value, 'LayerHighlight').debug('done', {
    handleHighligh: handleHighligh.value,
  });
}
function clear() {
  setFeatureHighlight(undefined, '', undefined);
}
</script>

// libs/react/map-dataset/src/modules/LayerHighlight/LayerHighlight.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { EventClick, logHelper, type MapSimple } from '@hungpvq/map-core';
import type {
  HighlightHandle,
  IdentifySingleResult,
  IHighlightView,
} from '@hungpvq/map-dataset';
import {
  findSiblingOrNearestLeaf,
  handleMultiIdentifyGetFirst,
} from '@hungpvq/map-dataset';
import { defaultMapProps, useEventMap, useMap } from '@hungpvq/react-map-core';
import type { Feature } from 'geojson';
import type { GeoJSONFeature, MapMouseEvent, PointLike } from 'maplibre-gl';
import { useEffect, useMemo, useRef } from 'react';
import { loggerHighlight } from '../../logger';
import { useMapDataset, useMapDatasetHighlight } from '../../store';
import { createDefaultHighlight } from './helper';

export function LayerHighlight(
  props: WithMapPropType & {
    enableClick?: boolean;
    color?: string;
    durationMs?: number;
  },
) {
  const merged = { ...defaultMapProps, ...props };
  const durationMs = props.durationMs ?? 5000;
  const color = props.color ?? '#004E98';

  const handleHighlight = useRef<HighlightHandle | undefined>();
  const handleDefault = useMemo(() => createDefaultHighlight(color), [color]);
  const getAllRef = useRef<
    ReturnType<typeof useMapDataset>['getAllComponentsByType'] | null
  >(null);
  const onGetFeaturesRef = useRef<
    (point?: PointLike | [PointLike, PointLike]) => Promise<void>
  >(async () => undefined);

  const clickEvent = useRef(
    new EventClick().setHandler((e: MapMouseEvent) => {
      void onGetFeaturesRef.current(e.point);
    }),
  );

  const { mapId, callMap } = useMap(merged, undefined, (map) => {
    handleHighlight.current?.stopAnimation(map);
  });
  const { getAllComponentsByType } = useMapDataset(mapId);
  const {
    getFeatureHighlight,
    setFeatureHighlight,
    getDatesetHighlight,
    version: highlightVersion,
  } = useMapDatasetHighlight(mapId);

  getAllRef.current = getAllComponentsByType;

  const { add, remove } = useEventMap(mapId, clickEvent.current, false);

  useEffect(() => {
    if (props.enableClick) add();
    return () => remove();
  }, [props.enableClick, add, remove]);

  async function onGetFeatures(
    pointOrBox?: PointLike | [PointLike, PointLike],
  ) {
    const highlights =
      (getAllRef.current?.(
        'highlight',
      ) as IHighlightView[] | undefined) || [];
    const feature: IdentifySingleResult = await handleMultiIdentifyGetFirst(
      highlights as never,
      mapId,
      pointOrBox,
    );
    logHelper(loggerHighlight, mapId, 'LayerHighlight').debug(
      'onGetFeatures',
      feature,
    );
    if (!feature?.feature?.data) return;
    setFeatureHighlight(feature.feature.data, 'highlight', feature.identify);
  }
  onGetFeaturesRef.current = onGetFeatures;

  function stopAnimation(map: MapSimple) {
    if (!handleHighlight.current) return;
    handleHighlight.current.stopAnimation(map);
  }

  function clear() {
    setFeatureHighlight(undefined, '', undefined);
  }

  function updateHighlight(geojsonData?: Feature | GeoJSONFeature) {
    if (!geojsonData) return;

    const dataset = getDatesetHighlight();
    let highlightView: IHighlightView | undefined;
    if (dataset) {
      highlightView = findSiblingOrNearestLeaf(
        dataset,
        (d) => d.type === 'highlight',
      ) as unknown as IHighlightView;
    }

    callMap((map: MapSimple) => {
      stopAnimation(map);
      handleHighlight.current = handleDefault;
      handleDefault.setDataset(highlightView);
      if (
        highlightView &&
        'startAnimation' in highlightView &&
        'stopAnimation' in highlightView
      ) {
        handleHighlight.current = highlightView;
      }
      handleHighlight.current.setOnDone(map, () => {
        clear();
      });
      handleHighlight.current.startAnimation({
        map,
        feature: geojsonData as GeoJSONFeature,
        durationMs,
      });
    });
  }

  useEffect(() => {
    const value = getFeatureHighlight();
    if (!value) {
      callMap((map) => stopAnimation(map));
      return;
    }
    updateHighlight(value);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [highlightVersion, mapId]);

  return null;
}
