// libs/vue/map-dataset/src/extra/component/add-to-group.vue
<template>
  <li
    class="layer-context-menu__item layer-context-menu__item--has-children"
    :class="{ 'is-open': open }"
    @click.stop="open = !open"
  >
    <div class="layer-context-menu__item-icon">
      <SvgIcon
        size="16"
        type="mdi"
        :path="('icon' in item && item.icon) || mdiFolderPlusOutline"
      />
    </div>
    <span>{{ 'name' in item ? item.name : 'Add to group' }}</span>
    <div class="layer-context-menu__chevron">
      <SvgIcon size="16" type="mdi" :path="mdiChevronRight" />
    </div>
    <ul class="context-menu layer-context-menu layer-context-menu--submenu">
      <template v-for="(child, index) in children" :key="child.id || index">
        <li
          v-if="child.type === 'divider'"
          class="layer-context-menu__item layer-context-menu__divider"
        >
          <div class="layer-context-menu__divider-line"></div>
        </li>
        <li
          v-else
          class="layer-context-menu__item"
          @click.stop="onChildClick(child, $event)"
        >
          <div class="layer-context-menu__item-icon">
            <SvgIcon
              size="16"
              type="mdi"
              :path="('icon' in child && child.icon) || mdiCircleSmall"
            />
          </div>
          <span>{{ 'name' in child ? child.name : '' }}</span>
        </li>
      </template>
    </ul>
  </li>
</template>
<script setup lang="ts">
import { getListViewGroupInfo } from '@hungpvq/map-dataset';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import {
  createAddToGroupSubmenu,
  handleMenuAction,
} from '@hungpvq/map-dataset/menu';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiChevronRight, mdiCircleSmall, mdiFolderPlusOutline } from '@mdi/js';
import { computed, ref } from 'vue';

import type { WithLayerItemMenuComponentType } from './types';

defineOptions({ name: 'LayerActionAddToGroup' });

const props = defineProps<WithLayerItemMenuComponentType>();

const emit = defineEmits<{
  close: [];
}>();

const open = ref(false);

const children = computed(() => {
  void open.value;
  const groups = props.getGroups?.() ?? [];
  const excludeGroupId = getListViewGroupInfo(props.data?.group)?.id;
  return createAddToGroupSubmenu(groups, excludeGroupId);
});

function onChildClick(action: MenuAction, event: MouseEvent) {
  if (!props.data) return;
  handleMenuAction(action, {
    event,
    layer: props.data,
    mapId: props.mapId,
    value: props.data,
  });
  emit('close');
}
</script>

// libs/react/map-dataset/src/extra/component/add-to-group.tsx
import type { MenuAction } from '@hungpvq/map-dataset';
import {
  createAddToGroupSubmenu,
  getListViewGroupInfo,
  handleMenuAction,
} from '@hungpvq/map-dataset';
import { mdiChevronRight, mdiCircleSmall, mdiFolderPlusOutline } from '@mdi/js';
import Icon from '@mdi/react';
import { useState } from 'react';
import type { WithLayerItemMenuComponentType } from './types';

export function AddToGroup(props: WithLayerItemMenuComponentType) {
  const [open, setOpen] = useState(false);
  const groups = props.getGroups?.() ?? [];
  const excludeGroupId = getListViewGroupInfo(props.data?.group)?.id;
  const children = createAddToGroupSubmenu(groups, excludeGroupId);
  const name = 'name' in props.item ? props.item.name : 'Add to group';
  const icon =
    ('icon' in props.item && props.item.icon) || mdiFolderPlusOutline;

  function onChildClick(action: MenuAction, event: React.MouseEvent) {
    event.stopPropagation();
    if (!props.data) return;
    handleMenuAction(action, {
      event: event.nativeEvent,
      layer: props.data,
      mapId: props.mapId,
      value: props.data,
    });
    props.onClose?.();
  }

  return (
    <li
      className={[
        'layer-context-menu__item',
        'layer-context-menu__item--has-children',
        open ? 'is-open' : '',
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={(event) => {
        event.stopPropagation();
        setOpen((prev) => !prev);
      }}
    >
      <div className="layer-context-menu__item-icon">
        <Icon path={icon} size="16px" />
      </div>
      <span>{name}</span>
      <div className="layer-context-menu__chevron">
        <Icon path={mdiChevronRight} size="16px" />
      </div>
      <ul className="context-menu layer-context-menu layer-context-menu--submenu">
        {children.map((child, index) => {
          const key = child.id || String(index);
          if (child.type === 'divider') {
            return (
              <li
                key={key}
                className="layer-context-menu__item layer-context-menu__divider"
              >
                <div className="layer-context-menu__divider-line" />
              </li>
            );
          }
          return (
            <li
              key={key}
              className="layer-context-menu__item"
              onClick={(event) => onChildClick(child, event)}
            >
              <div className="layer-context-menu__item-icon">
                <Icon
                  path={('icon' in child && child.icon) || mdiCircleSmall}
                  size="16px"
                />
              </div>
              <span>{('name' in child && child.name) || ''}</span>
            </li>
          );
        })}
      </ul>
    </li>
  );
}
