// libs/react/draggable/src/components/ManagementControl/ManagementControl.tsx
import { useContainerId } from '../../context/ContainerContext';
import { useManagement } from '../../hook';
import { ShowStatusDragItem } from './ShowStatusDragItem';
import { ShowStatusDrawer } from './ShowStatusDrawer';
import { ShowStatusSideBar } from './ShowStatusSideBar';

export interface ManagementControlProps {
  containerId?: string;
}

const EMPTY_SIDEBAR = {
  left: { items: [] as string[], show: undefined as string | undefined },
  right: { items: [] as string[], show: undefined as string | undefined },
  top: { items: [] as string[], show: undefined as string | undefined },
  bottom: { items: [] as string[], show: undefined as string | undefined },
};

const EMPTY_DRAWER = {
  left: {
    items: [] as string[],
    size: 0,
    show: undefined as string | undefined,
  },
  right: {
    items: [] as string[],
    size: 0,
    show: undefined as string | undefined,
  },
  top: {
    items: [] as string[],
    size: 0,
    show: undefined as string | undefined,
  },
  bottom: {
    items: [] as string[],
    size: 0,
    show: undefined as string | undefined,
  },
};

const EMPTY_GROUP = { items: [] as string[], show: [] as string[] };

export function ManagementControl({
  containerId: propContainerId,
}: ManagementControlProps) {
  const containerId = useContainerId(propContainerId);
  const { width, height, popup, modal, float, bottom, sideBar, drawer } =
    useManagement(containerId);

  const sidebarMap = sideBar || EMPTY_SIDEBAR;
  const drawerMap = drawer || EMPTY_DRAWER;
  const popupGroup = popup || EMPTY_GROUP;
  const modalGroup = modal || EMPTY_GROUP;
  const floatGroup = float || EMPTY_GROUP;
  const bottomGroup = bottom || EMPTY_GROUP;

  const sidebarCount = Object.values(sidebarMap).reduce(
    (sum, side) => sum + (side?.items?.length || 0),
    0,
  );
  const drawerCount = Object.values(drawerMap).reduce(
    (sum, side) => sum + (side?.items?.length || 0),
    0,
  );

  return (
    <div className="mgmt">
      <section className="mgmt__section">
        <header className="mgmt__header">
          <span className="mgmt__title">Container</span>
        </header>
        <div className="mgmt__metrics">
          <div className="mgmt__metric">
            <span className="mgmt__metric-label">Width</span>
            <span className="mgmt__metric-value">{width}</span>
          </div>
          <div className="mgmt__metric">
            <span className="mgmt__metric-label">Height</span>
            <span className="mgmt__metric-value">{height}</span>
          </div>
        </div>
      </section>

      {sidebarCount > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Sidebars</span>
            <span className="mgmt__count">{sidebarCount}</span>
          </header>
          <ShowStatusSideBar items={sidebarMap} containerId={containerId} />
        </section>
      )}

      {drawerCount > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Drawers</span>
            <span className="mgmt__count">{drawerCount}</span>
          </header>
          <ShowStatusDrawer items={drawerMap} containerId={containerId} />
        </section>
      )}

      {popupGroup.items.length > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Popups</span>
            <span className="mgmt__count">
              {popupGroup.show.length}/{popupGroup.items.length}
            </span>
          </header>
          <ShowStatusDragItem
            items={popupGroup.items}
            itemShows={popupGroup.show}
            containerId={containerId}
          />
        </section>
      )}

      {modalGroup.items.length > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Modals</span>
            <span className="mgmt__count">
              {modalGroup.show.length}/{modalGroup.items.length}
            </span>
          </header>
          <ShowStatusDragItem
            items={modalGroup.items}
            itemShows={modalGroup.show}
            containerId={containerId}
          />
        </section>
      )}

      {floatGroup.items.length > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Floats</span>
            <span className="mgmt__count">
              {floatGroup.show.length}/{floatGroup.items.length}
            </span>
          </header>
          <ShowStatusDragItem
            items={floatGroup.items}
            itemShows={floatGroup.show}
            containerId={containerId}
          />
        </section>
      )}

      {bottomGroup.items.length > 0 && (
        <section className="mgmt__section">
          <header className="mgmt__header">
            <span className="mgmt__title">Bottoms</span>
            <span className="mgmt__count">
              {bottomGroup.show.length}/{bottomGroup.items.length}
            </span>
          </header>
          <ShowStatusDragItem
            items={bottomGroup.items}
            itemShows={bottomGroup.show}
            containerId={containerId}
          />
        </section>
      )}
    </div>
  );
}

// libs/vue/draggable/src/components/ManagementControl/index.vue
<script lang="ts">
export default {
  name: 'ManagementControl',
};
</script>

<script setup lang="ts">
import { assertDefined } from '@hungpvq/draggable';
import { computed, inject, ref, Ref } from 'vue';
import { useManagement, withShareProps } from '../../hook';
import ShowStatusDragItem from './ShowStatusDragItem.vue';
import ShowStatusDrawer from './ShowStatusDrawer.vue';
import ShowStatusSideBar from './ShowStatusSideBar.vue';

const props = defineProps({
  ...withShareProps,
});
const containerId = assertDefined(
  inject<Ref<string>>('containerId', ref(props.containerId || '')),
  '[ManagementControl] Missing containerId',
);
const { width, height, popup, modal, float, bottom, sideBar, drawer } =
  useManagement(containerId.value);

const sidebarCount = computed(() =>
  Object.values(sideBar.value || {}).reduce(
    (sum, side) => sum + (side?.items?.length || 0),
    0,
  ),
);
const drawerCount = computed(() =>
  Object.values(drawer.value || {}).reduce(
    (sum, side) => sum + (side?.items?.length || 0),
    0,
  ),
);
</script>
<template>
  <div class="mgmt">
    <section class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Container</span>
      </header>
      <div class="mgmt__metrics">
        <div class="mgmt__metric">
          <span class="mgmt__metric-label">Width</span>
          <span class="mgmt__metric-value">{{ width }}</span>
        </div>
        <div class="mgmt__metric">
          <span class="mgmt__metric-label">Height</span>
          <span class="mgmt__metric-value">{{ height }}</span>
        </div>
      </div>
    </section>

    <section v-if="sidebarCount > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Sidebars</span>
        <span class="mgmt__count">{{ sidebarCount }}</span>
      </header>
      <ShowStatusSideBar :items="sideBar" :containerId="containerId" />
    </section>

    <section v-if="drawerCount > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Drawers</span>
        <span class="mgmt__count">{{ drawerCount }}</span>
      </header>
      <ShowStatusDrawer :items="drawer" :containerId="containerId" />
    </section>

    <section v-if="popup.items.length > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Popups</span>
        <span class="mgmt__count"
          >{{ popup.show.length }}/{{ popup.items.length }}</span
        >
      </header>
      <ShowStatusDragItem
        :items="popup.items"
        :itemShows="popup.show"
        :containerId="containerId"
      />
    </section>

    <section v-if="modal.items.length > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Modals</span>
        <span class="mgmt__count"
          >{{ modal.show.length }}/{{ modal.items.length }}</span
        >
      </header>
      <ShowStatusDragItem
        :items="modal.items"
        :itemShows="modal.show"
        :containerId="containerId"
      />
    </section>

    <section v-if="float.items.length > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Floats</span>
        <span class="mgmt__count"
          >{{ float.show.length }}/{{ float.items.length }}</span
        >
      </header>
      <ShowStatusDragItem
        :items="float.items"
        :itemShows="float.show"
        :containerId="containerId"
      />
    </section>

    <section v-if="bottom.items.length > 0" class="mgmt__section">
      <header class="mgmt__header">
        <span class="mgmt__title">Bottoms</span>
        <span class="mgmt__count"
          >{{ bottom.show ? 1 : 0 }}/{{ bottom.items.length }}</span
        >
      </header>
      <ShowStatusDragItem
        :items="bottom.items"
        :itemShows="bottom.show ? [bottom.show] : []"
        :containerId="containerId"
      />
    </section>
  </div>
</template>
