// libs/react/draggable/src/components/ManagementControl/ItemList.tsx
import type { ReactNode } from 'react';

import { Item } from './Item';

export interface ItemListProps {
  items: string[];
  show?: string;
  containerId: string;
  itemShows?: string[];
  onClickItem?: (id: string) => void;
  renderExtra?: (item: string, show: boolean) => ReactNode;
}

export function ItemList({
  items,
  show,
  containerId,
  itemShows,
  onClickItem,
  renderExtra,
}: ItemListProps) {
  if (!items.length) {
    return <p className="mgmt__empty">Empty</p>;
  }

  return (
    <ul className="mgmt-list">
      {items.map((item) => {
        const isShow = show === item || !!itemShows?.includes(item);
        return (
          <li
            key={item}
            role="button"
            tabIndex={0}
            className={['mgmt-row', isShow ? 'mgmt-row--active' : '']
              .filter(Boolean)
              .join(' ')}
            onClick={() => onClickItem?.(item)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                onClickItem?.(item);
              }
            }}
          >
            <div className="mgmt-row__label">
              <Item
                item={item}
                containerId={containerId}
              />
            </div>
            <div className="mgmt-row__status">
              <span
                className={['mgmt-dot', isShow ? 'mgmt-dot--on' : '']
                  .filter(Boolean)
                  .join(' ')}
              />
            </div>
            <div className="mgmt-row__actions">
              {renderExtra?.(item, isShow)}
            </div>
          </li>
        );
      })}
    </ul>
  );
}

// libs/vue/draggable/src/components/ManagementControl/ItemList.vue
<template>
  <ul
    v-if="items.length > 0"
    class="mgmt-list"
  >
    <li
      v-for="item in items"
      :key="item"
      role="button"
      tabindex="0"
      :class="[
        'mgmt-row',
        { 'mgmt-row--active': show === item || itemShows?.includes(item) },
      ]"
      @click="$emit('click:item', item)"
      @keydown.enter.prevent="$emit('click:item', item)"
      @keydown.space.prevent="$emit('click:item', item)"
    >
      <div class="mgmt-row__label">
        <Item
          :item="item"
          :containerId="containerId"
        />
      </div>
      <div class="mgmt-row__status">
        <span
          class="mgmt-dot"
          :class="{
            'mgmt-dot--on': show === item || itemShows?.includes(item),
          }"
        />
      </div>
      <div class="mgmt-row__actions">
        <slot
          name="extra"
          :item="item"
          :show="show === item || itemShows?.includes(item)"
        ></slot>
      </div>
    </li>
  </ul>
  <p
    v-else
    class="mgmt__empty"
  >
    Empty
  </p>
</template>

<script setup lang="ts">
import Item from './Item.vue';

defineProps<{
  items: string[];
  show?: string;
  containerId: string;
  itemShows?: string[];
}>();

defineEmits<{
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  (_e: 'click:item', _id: string): void;
}>();
</script>
