// libs/react/draggable/src/components/ManagementControl/Item.tsx
import { useDragContainer } from '../../store';
import { useStoreReactive } from '../../store/useStoreReactive';

export interface ItemProps {
  item: string;
  containerId: string;
}

const TYPE_LABELS: Record<string, string> = {
  'item-popup': 'Popup',
  'item-float': 'Float',
  'item-modal': 'Modal',
  'item-bottom': 'Bottom',
  'item-sidebar': 'Sidebar',
  'item-drawer': 'Drawer',
};

export function Item({ item, containerId }: ItemProps) {
  useStoreReactive();
  const { getItemAction } = useDragContainer(containerId);
  const action = getItemAction(item);
  const title = action?.title || item;
  const typeKey = action?.type || '';
  const typeLabel = TYPE_LABELS[typeKey] || typeKey || '';

  return (
    <span className="mgmt-item-meta">
      {typeLabel ? (
        <span className="mgmt-type" data-type={typeKey}>
          {typeLabel}
        </span>
      ) : null}
      <span className="mgmt-item-title" title={title}>
        {title}
      </span>
    </span>
  );
}

// libs/vue/draggable/src/components/ManagementControl/Item.vue
<template>
  <span class="mgmt-item-meta">
    <span v-if="typeLabel" class="mgmt-type" :data-type="typeKey">{{
      typeLabel
    }}</span>
    <span class="mgmt-item-title" :title="title">{{ title }}</span>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';

import { useDragContainer } from '../../store';

const TYPE_LABELS: Record<string, string> = {
  'item-popup': 'Popup',
  'item-float': 'Float',
  'item-modal': 'Modal',
  'item-bottom': 'Bottom',
  'item-sidebar': 'Sidebar',
  'item-drawer': 'Drawer',
};

const props = defineProps<{
  item: string;
  containerId: string;
}>();
const { getItemAction } = useDragContainer(props.containerId);
const action = computed(() => getItemAction(props.item));
const title = computed(() => action.value?.title || props.item);
const typeKey = computed(() => action.value?.type || '');
const typeLabel = computed(
  () => TYPE_LABELS[typeKey.value] || typeKey.value || '',
);
</script>
