// libs/map/dataset/src/modules/LayerControl/part/LayerList.vue
<script setup lang="ts">
import { ContextMenu } from '@hungpvq/content-menu';
import type { MapSimple } from '@hungpvq/shared-map';
import {
  BaseButton,
  defaultMapProps,
  useMap,
  WithMapPropType,
} from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import {
  mdiCircleSmall,
  mdiDelete,
  mdiDotsVertical,
  mdiGroup,
  mdiLayers,
  mdiPlus,
} from '@mdi/js';
import {
  computed,
  nextTick,
  onMounted,
  reactive,
  ref,
  VNode,
  watch,
} from 'vue';
import { handleMenuAction } from '../../../extra/menu';
import type { MenuAction } from '../../../interfaces';
import { IGroupListViewUI, IListViewUI, traverseTree } from '../../../model';
import { useUniversalRegistry } from '../../../registry';
import { useMapDataset } from '../../../store';
import { hasMoveLayer } from '../../../utils/check';
import ButtonToggleShowALl from './ButtonToggleAllShow.vue';
import DraggableGroupList from './DraggableList/draggable-list.vue';
import LayerItem from './item/layer-item.vue';

const props = withDefaults(
  defineProps<
    WithMapPropType & {
      disabledDrag?: boolean;
      disabled?: boolean;
      disabledCreateGroup?: boolean;
      disabledDeleteAll?: boolean;
    }
  >(),
  {
    ...defaultMapProps,
    disabledDrag: false,
    disabled: false,
    disabledCreateGroup: false,
    disabledDeleteAll: false,
  },
);

defineSlots<{
  title(): VNode[];
  item(props: {
    item: IListViewUI;
    isSelected: boolean;
    toggleSelect: (item: IListViewUI) => void;
  }): VNode[];
}>();

const path = {
  icon: mdiLayers,
  menu: mdiDotsVertical,
  group: { create: mdiGroup },
  deleteAll: mdiDelete,
  layer: { create: mdiPlus },
};

const { callMap, mapId } = useMap(props);
const { getAllComponentsByType, getDatasetIds, removeComponent } =
  useMapDataset(mapId.value);

const views = ref<Array<IListViewUI>>([]);
const datasetIds = computed(() => {
  return getDatasetIds().value;
});

watch(
  datasetIds,
  () => {
    updateList();
  },
  { deep: true },
);

onMounted(() => {
  updateList();
});

const groupRef = ref<InstanceType<typeof DraggableGroupList> | undefined>(
  undefined,
);
const layers_select = ref<IListViewUI[]>([]);

function updateLayers() {
  callMap((map: MapSimple) => {
    let beforeId: string = '';
    views.value.slice().forEach((view, index, items) => {
      view.index = items.length - index;
      const parent = view.getParent();
      traverseTree(
        parent || view,
        (node) => {
          if (hasMoveLayer(node)) {
            node.moveLayer(map, beforeId);
            beforeId = node.getBeforeId() || '';
          }
        },
        {
          direction: 'rtl',
        },
      );
    });
  });
}

function onRemoveGroupLayer(group: IGroupListViewUI<IListViewUI>) {
  if (
    !group ||
    typeof group === 'string' ||
    !group.children ||
    group.children.length === 0
  ) {
    return;
  }
  group.children.forEach((view: IListViewUI) => {
    removeComponent(view);
  });
}

function onRemoveLayer(view: IListViewUI) {
  if (!view) return;
  removeComponent(view);
  updateList();
}

function updateList() {
  getViewFromStore();
  nextTick(() => {
    updateTree();
  });
}

function updateTree() {
  if (groupRef.value) groupRef.value.update(views.value as any);
}

function getViewFromStore() {
  const viewSource = getAllComponentsByType<IListViewUI>('list');
  views.value = viewSource.sort((a, b) => b.index - a.index) || [];
}

function addNewGroup() {
  if (groupRef.value) groupRef.value.addNewGroup('');
}

function onRemoveAllLayer() {
  if (!views.value || views.value.length === 0) {
    return;
  }
  views.value.forEach((view) => {
    removeComponent(view);
  });
  updateList();
}

const contextMenuRef = ref<
  | {
      open(event: MouseEvent, item: IListViewUI): void;
      close(): void;
    }
  | undefined
>();

const menu_context = reactive<{
  items: MenuAction<IListViewUI>[];
  view: IListViewUI | undefined;
}>({
  items: [],
  view: undefined,
});

function handleContextClick({
  event,
  item,
  actions,
}: {
  event: MouseEvent;
  item: IListViewUI;
  actions: MenuAction<IListViewUI>[];
}) {
  menu_context.items = (actions ? [...actions] : []) as any;
  menu_context.view = item;
  if (contextMenuRef.value) contextMenuRef.value.open(event, item);
}

function closeContextMenu() {
  menu_context.items = [];
  menu_context.view = undefined;
  if (contextMenuRef.value) contextMenuRef.value.close();
}

function onLayerAction({
  event,
  action,
  item,
}: {
  event: MouseEvent;
  action: MenuAction<IListViewUI>;
  item: IListViewUI;
}) {
  handleMenuAction(action, {
    event,
    layer: item,
    mapId: mapId.value,
    value: item,
  });
}

const { getComponent } = useUniversalRegistry(mapId.value);
</script>
<template>
  <div class="layer-control-container">
    <div class="layer-control__header">
      <slot name="title"></slot>
      <div class="v-spacer"></div>
      <ButtonToggleShowALl :items="views" />
      <BaseButton @click="addNewGroup()" v-if="!disabledCreateGroup">
        <SvgIcon size="16" type="mdi" :path="path.group.create" />
      </BaseButton>
      <BaseButton @click="onRemoveAllLayer" v-if="!disabledDeleteAll">
        <SvgIcon size="16" type="mdi" :path="path.deleteAll" />
      </BaseButton>
    </div>
    <div class="layer-control__list">
      <DraggableGroupList
        ref="groupRef"
        v-model:items="views"
        v-model:selected="layers_select"
        :disabled="disabled"
        :disabled-drag="disabledDrag"
        @click-drag:done="updateLayers()"
        @click-group:remove="onRemoveGroupLayer"
      >
        <template #item="{ isSelected, item, toggleSelect }">
          <slot
            name="item"
            :item="item"
            :isSelected="isSelected"
            :toggleSelect="() => toggleSelect(item)"
          >
            <component
              :is="getComponent(item.config?.componentKey, LayerItem)"
              :item="item"
              :is-selected="isSelected"
              @click="toggleSelect(item)"
              @click:remove="onRemoveLayer"
              @click:content-menu="handleContextClick"
              @click:action="onLayerAction"
              :map-id="mapId"
              :readonly="false"
            >
            </component>
          </slot>
        </template>
      </DraggableGroupList>
    </div>
    <ContextMenu ref="contextMenuRef">
      <ul class="layer-context-menu">
        <li
          v-for="(option, index) in menu_context.items"
          :key="index"
          class="layer-context-menu__item"
          :class="[
            option.class,
            option.type === 'divider' ? 'layer-context-menu__divider' : '',
          ]"
          @click.stop="
            if (option.type !== 'divider' && menu_context.view) {
              onLayerAction({
                action: option as any,
                item: menu_context.view,
                event: $event,
              });
            }
            closeContextMenu();
          "
        >
          <!-- Divider -->
          <template v-if="option.type === 'divider'">
            <div class="layer-context-menu__divider-line"></div>
          </template>
          <template v-else-if="'componentKey' in option">
            <!-- item dạng component -->
            <component :is="option.componentKey" />
          </template>
          <!-- Normal item -->
          <template v-else>
            <div class="layer-context-menu__item-icon">
              <SvgIcon
                size="16"
                type="mdi"
                :path="option.icon || mdiCircleSmall"
              />
            </div>
            <span v-html="option.name"></span>
          </template>
        </li>
      </ul>
    </ContextMenu>
  </div>
</template>
<style scoped>
.layer-control__list {
  flex-grow: 1;
  overflow: auto;
  padding: 4px 12px 8px;
}

.layer-control__header {
  display: flex;
  align-items: center;
  padding: 8px;
}

.v-spacer {
  flex: 1 1 auto;
}
</style>

<style lang="scss">
.layer-context-menu {
  min-width: 150px;
  background-color: var(--map-layer-menu-bg, #ecf0f1);
  border-bottom-width: 0px;
  box-shadow: 0 3px 6px 0 rgba(0, 0, 0, 0.2);

  &--active {
    display: block;
  }

  &__item {
    display: flex;
    color: var(--map-layer-menu-text, var(--map-text-primary, #333));
    cursor: pointer;
    padding: 5px 10px;
    align-items: center;
    min-width: 100px;
    min-height: 50px;

    &:hover {
      background-color: var(
        --map-layer-menu-hover-bg,
        var(--map-primary-color, #004e98)
      );
      color: var(--map-layer-menu-hover-text, var(--map-text-inverse, #fff));
    }
  }

  &__item-icon {
    & > * {
      vertical-align: middle;
    }

    display: inline-block;
    padding-right: 5px;
  }

  &__divider {
    box-sizing: content-box;
    height: 2px;
    background-color: currentColor;
    padding: 4px;
    background-clip: content-box;
    pointer-events: none;
    min-height: 2px;
  }
}
</style>

// libs/react/map-dataset/src/modules/LayerControl/LayerList.tsx
import type { MapSimple } from '@hungpvq/map-core';
import type { IListViewUI } from '@hungpvq/map-dataset';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import { LAYER_CONTROL_LOCALE, hasMoveLayer, listListViewGroups, traverseTree } from '@hungpvq/map-dataset';
import { handleMenuAction } from '@hungpvq/map-dataset/menu';
import { ContextMenu, type ContextMenuRef } from '@hungpvq/react-draggable';
import { BaseButton, useLang, useMap } from '@hungpvq/react-map-core';
import { mdiDelete, mdiGroup, mdiLayers, mdiPlus } from '@mdi/js';
import Icon from '@mdi/react';
import { type ReactNode, useEffect, useRef, useState } from 'react';
import { MenuConditionProvider } from '../../extra/menu/condition-context';
import { useMapDataset } from '../../store';
import { ButtonToggleShowAll } from './ButtonToggleShowAll';
import {
  DraggableGroupList,
  type DraggableGroupListRef,
} from './DraggableList/DraggableGroupList';
import type { GroupTree, LayerListItem } from './DraggableList/utils';
import { LayerContextMenuList } from './layer-context-menu-list';
import { LayerItem } from './layer-item';

const HEADER_ICON = '16px';

export function LayerList({
  mapId,
  readonly,
  title,
  disabledCreate,
  disabledCreateGroup,
  disabledDeleteAll,
  disabledDrag,
  disabledMove,
  onCreate,
}: {
  mapId: string;
  readonly?: boolean;
  title?: ReactNode;
  disabledCreate?: boolean;
  disabledCreateGroup?: boolean;
  disabledDeleteAll?: boolean;
  disabledDrag?: boolean;
  disabledMove?: boolean;
  onCreate?: () => void;
}) {
  const { callMap } = useMap({ mapId });
  const { trans, setLocaleDefault } = useLang(mapId);
  const { getAllComponentsByType, removeComponent, datasetVersion } =
    useMapDataset(mapId);
  const [views, setViews] = useState<LayerListItem[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const groupRef = useRef<DraggableGroupListRef>(null);
  const contextMenuRef = useRef<ContextMenuRef>(null);
  const [menuContext, setMenuContext] = useState<{
    items: MenuAction<IListViewUI>[];
    view?: IListViewUI;
  }>({ items: [] });

  useEffect(() => {
    setLocaleDefault(LAYER_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  function refresh() {
    const viewSource = getAllComponentsByType<IListViewUI>('list');
    const next = (viewSource.sort((a, b) => b.index - a.index) ||
      []) as LayerListItem[];
    setViews(next);
    groupRef.current?.update(next);
  }

  useEffect(() => {
    refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [datasetVersion, mapId]);

  function updateLayers(items: LayerListItem[]) {
    callMap((map: MapSimple) => {
      let beforeId = '';
      items.slice().forEach((view, index, arr) => {
        view.index = arr.length - index;
        const parent = view.getParent();
        traverseTree(
          parent || view,
          (node) => {
            if (hasMoveLayer(node)) {
              node.moveLayer(map, beforeId);
              beforeId = node.getBeforeId() || '';
            }
          },
          { direction: 'rtl' },
        );
      });
    });
  }

  function onItemsChange(next: LayerListItem[]) {
    setViews(next);
    updateLayers(next);
  }

  function onRemoveGroupLayer(group: GroupTree) {
    if (!group?.children?.length) return;
    group.children.forEach((view) => removeComponent(view));
  }

  function onRemoveAllLayer() {
    if (!views.length) return;
    views.forEach((view) => removeComponent(view));
    refresh();
  }

  function addNewGroup() {
    groupRef.current?.addNewGroup('');
  }

  function onLayerAction({
    event,
    action,
    item,
  }: {
    event: React.MouseEvent | MouseEvent;
    action: MenuAction<IListViewUI>;
    item: IListViewUI;
  }) {
    const native =
      'nativeEvent' in event ? event.nativeEvent : (event as MouseEvent);
    handleMenuAction(action, {
      event: native,
      layer: item,
      mapId,
      value: item,
    });
  }

  function handleContextClick({
    event,
    item,
    actions,
  }: {
    event: React.MouseEvent;
    item: IListViewUI;
    actions: MenuAction<IListViewUI>[];
  }) {
    setMenuContext({
      items: actions ? [...actions] : [],
      view: item,
    });
    contextMenuRef.current?.open(event);
  }

  function getMenuGroups() {
    const treeGroups = groupRef.current?.getGroups() ?? [];
    return treeGroups.length > 0 ? treeGroups : listListViewGroups(views);
  }

  function closeContextMenu() {
    setMenuContext({ items: [], view: undefined });
    contextMenuRef.current?.close();
  }

  const isEmpty = views.length === 0;
  const showCreate = Boolean(onCreate) && !disabledCreate && !readonly;

  return (
    <MenuConditionProvider
      value={{
        readonly: !!readonly,
        disabledMove: !!disabledMove,
        disabledCreateGroup: !!disabledCreateGroup,
      }}
    >
      <div className="layer-control-container">
        {!isEmpty && (
          <div className="layer-control__header">
            {title}
            <div className="v-spacer" />
            <ButtonToggleShowAll mapId={mapId} items={views} />
            {!disabledCreateGroup && (
              <BaseButton onClick={addNewGroup} aria-label="Create group">
                <Icon path={mdiGroup} size={HEADER_ICON} />
              </BaseButton>
            )}
            {!disabledDeleteAll && (
              <BaseButton
                onClick={onRemoveAllLayer}
                aria-label="Delete all layers"
              >
                <Icon path={mdiDelete} size={HEADER_ICON} />
              </BaseButton>
            )}
          </div>
        )}
        <div className="layer-control__list">
          {isEmpty && (
            <div className="layer-control__empty">
              <Icon
                className="layer-control__empty-icon"
                path={mdiLayers}
                size="36px"
              />
              <div className="layer-control__empty-title">
                {trans('map.layer-control.empty')}
              </div>
              {showCreate && (
                <div className="layer-control__empty-hint">
                  {trans('map.layer-control.empty-hint')}
                </div>
              )}
              {showCreate && (
                <button
                  type="button"
                  className="layer-control__empty-action"
                  onClick={onCreate}
                >
                  <Icon path={mdiPlus} size="14px" />
                  {trans('map.layer-control.create-btn')}
                </button>
              )}
            </div>
          )}
          <div style={isEmpty ? { display: 'none' } : undefined}>
            <DraggableGroupList
              ref={groupRef}
              items={views}
              selected={selected}
              disabledDrag={disabledDrag}
              onSelectedChange={setSelected}
              onItemsChange={onItemsChange}
              onGroupRemove={onRemoveGroupLayer}
              renderItem={({ item, toggleSelect }) => (
                <LayerItem
                  item={item}
                  mapId={mapId}
                  readonly={readonly}
                  disabledMove={disabledMove}
                  disabledCreateGroup={disabledCreateGroup}
                  onTitleClick={toggleSelect}
                  onRemove={(layer) => {
                    removeComponent(layer);
                    refresh();
                  }}
                  onAction={onLayerAction}
                  onContextMenu={handleContextClick}
                />
              )}
            />
          </div>
        </div>
        <ContextMenu ref={contextMenuRef}>
          <LayerContextMenuList
            items={menuContext.items}
            view={menuContext.view}
            mapId={mapId}
            getGroups={getMenuGroups}
            onClose={closeContextMenu}
            onSelect={({ action, event }) => {
              if (menuContext.view) {
                onLayerAction({
                  action,
                  item: menuContext.view,
                  event,
                });
              }
              closeContextMenu();
            }}
          />
        </ContextMenu>
      </div>
    </MenuConditionProvider>
  );
}
