// libs/map/dataset/src/modules/LayerControl/part/item/layer-item.vue
<template>
  <div class="layer-item-container">
    <div class="layer-item__info">
      <div v-if="isHasIcon" class="layer-item__icon">
        <component
          v-if="props.item.icon?.componentKey"
          :is="getComponent(props.item.icon.componentKey)"
          v-bind="props.item.icon.attr"
          :data="item"
          :mapId="mapId"
        ></component>
      </div>
      <span
        class="layer-item__title"
        :title="item.getName()"
        @click="emit('click', item)"
      >
        <span>{{ item.getName() }}</span>
      </span>
      <div class="v-spacer"></div>
      <div class="layer-item__title-action">
        <slot name="pre-btn" :loading="loading" />
        <template v-for="(menu, i) in extra_menus" :key="i">
          <LayerMenu
            :item="menu"
            :data="item"
            :disabled="loading"
            :mapId="mapId"
            @click="onLayerAction(menu)"
          />
        </template>
        <BaseButton
          v-if="!item.config.disabled_delete && !props.readonly"
          :disabled="loading"
          @click.stop="onRemove"
        >
          <SvgIcon size="14" type="mdi" :path="path.delete" />
        </BaseButton>
        <slot name="extra-btn" :loading="loading" />
        <BaseButton
          v-if="content_menus.length > 0"
          :disabled="loading"
          @click.prevent.stop="handleContextClick"
        >
          <SvgIcon size="14" type="mdi" :path="path.menu" />
        </BaseButton>
        <template v-if="!showBottom">
          <template v-for="(menu, i) in extra_bottoms" :key="i">
            <LayerMenu
              :item="menu"
              :data="item"
              :disabled="loading"
              :mapId="mapId"
              @click="onLayerAction(menu)"
            />
          </template>
          <BaseButton @click.stop="onToggleLegend()" v-if="isHasLegend">
            <SvgIcon
              size="14"
              type="mdi"
              :path="legendShow ? path.legendClose : path.legendOpen"
            />
          </BaseButton>
        </template>
      </div>
    </div>
    <div class="layer-item__action" v-if="showBottom">
      <template v-for="(menu, i) in bottoms" :key="i">
        <LayerMenu
          :item="menu"
          :data="item"
          :disabled="loading"
          :mapId="mapId"
          @click="onLayerAction(menu)"
        />
      </template>
      <div class="v-spacer"></div>
      <template v-for="(menu, i) in extra_bottoms" :key="i">
        <LayerMenu
          :item="menu"
          :data="item"
          :disabled="loading"
          :mapId="mapId"
          @click="onLayerAction(menu)"
        />
      </template>
      <BaseButton @click.stop="onToggleChildren()" v-if="isHasChildren">
        <SvgIcon
          size="14"
          type="mdi"
          :path="childrenShow ? path.legendClose : path.legendOpen"
        />
      </BaseButton>
      <BaseButton @click.stop="onToggleLegend()" v-if="isHasLegend">
        <SvgIcon
          size="14"
          type="mdi"
          :path="legendShow ? path.legendClose : path.legendOpen"
        />
      </BaseButton>
    </div>

    <div v-if="isHasLegend && legendShow">
      <component
        v-if="props.item.legend?.componentKey"
        :is="getComponent(props.item.legend.componentKey)"
        :data="item"
        v-bind="props.item.legend.attr"
      ></component>
    </div>
    <div v-if="isHasChildren && childrenShow" class="layer-item__children">
      <LayerSubItem
        v-for="item in children"
        :key="item.id"
        :item="item"
        :mapId="mapId"
      ></LayerSubItem>
    </div>
  </div>
</template>
<script setup lang="ts">
import { BaseButton, useShow } from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import {
  mdiCrosshairsGps,
  mdiDelete,
  mdiDotsVertical,
  mdiLayers,
  mdiLoading,
  mdiMenuDown,
  mdiMenuLeft,
  mdiPencilOutline,
} from '@mdi/js';
import { computed, onMounted, ref } from 'vue';
import type { MenuAction } from '../../../../interfaces';
import type { IListViewUI } from '../../../../model';
import { findAllComponentsByType } from '../../../../model';
import { useUniversalRegistry } from '../../../../registry';
import LayerSubItem from './layer-sub-item.vue';
import LayerMenu from './menu/index.vue';
const { getComponent } = useUniversalRegistry();
const props = defineProps<{
  item: IListViewUI;
  mapId: string;
  readonly: boolean;
}>();
const emit = defineEmits([
  'update:item',
  'click',
  'click:remove',
  'click:action',
  'click:content-menu',
]);
const path = {
  menu: mdiDotsVertical,
  loading: mdiLoading,
  layer: mdiLayers,
  flyTo: mdiCrosshairsGps,
  delete: mdiDelete,
  edit: mdiPencilOutline,
  legendOpen: mdiMenuLeft,
  legendClose: mdiMenuDown,
};
const loading = ref(false);
const onRemove = () => {
  emit('click:remove', props.item);
};
const button_menus = computed<MenuAction<any>[]>(() => {
  if (!props.item) {
    return [];
  }
  return props.item.getMenus() || [];
});
const extra_menus = computed(() => {
  return button_menus.value
    .filter((x) => !x.location || x.location == 'extra')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
const bottoms = computed(() => {
  return button_menus.value
    .filter((x) => x.location == 'prebottom')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
const extra_bottoms = computed(() => {
  return button_menus.value
    .filter((x) => x.location == 'bottom')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
const content_menus = computed(() => {
  return button_menus.value
    .filter((x) => x.location == 'menu')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
const showBottom = computed(() => {
  return (
    !props.readonly &&
    (!props.item.config.disabled_opacity || extra_bottoms.value.length > 0)
  );
});
function onLayerAction(action: MenuAction<IListViewUI>) {
  emit('click:action', { action, item: props.item });
}
function handleContextClick(event: MouseEvent) {
  emit('click:content-menu', {
    event,
    actions: content_menus.value,
    item: props.item,
  });
}

const isHasIcon = computed(() => props.item && props.item.icon);
const isHasLegend = computed(() => props.item && !!props.item.legend);
const [childrenShow, onToggleChildren] = useShow(
  props.item.config.init_show_children ?? false,
);
const [legendShow, onToggleLegend] = useShow(
  props.item.config.init_show_legend ?? false,
);
const isHasChildren = ref(false);
const children = ref<IListViewUI[]>([]);
onMounted(() => {
  const allComponentsOfType = findAllComponentsByType(
    props.item,
    'list-item',
  ) as IListViewUI[];
  isHasChildren.value = allComponentsOfType.length > 0;
  children.value = allComponentsOfType.slice().reverse();
});
</script>

<style scoped>
.spin {
  animation: 2s linear 0s infinite normal none running spin;
}

@keyframes spin {
  100% {
    transform: rotate(360deg);
  }
}

.layer-item-container {
  overflow: hidden;
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.layer-item__info {
  width: 100%;
}

.layer-item__info,
.layer-item__action {
  display: flex;
  align-items: center;
}

.layer-item__action {
  padding-top: 4px;
}

.layer-item__icon {
  flex-grow: 0;
  flex-shrink: 0;
  width: 25px;
  display: flex;
  align-items: center;
}

.layer-item__icon > div {
  display: flex;
  align-items: center;
  justify-content: flex-start;
}

.layer-item__title {
  display: inline-block;
  text-align: left;
  flex-grow: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  font-size: 0.75rem !important;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0.0333333333em !important;
}

.layer-item__title-action {
  display: flex;
  flex-grow: 0;
  align-items: center;
}

.v-spacer {
  flex: 1 1 auto;
}
.layer-item__children {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 0 8px;
  box-sizing: border-box;
}
</style>

// libs/react/map-dataset/src/modules/LayerControl/layer-item.tsx
import type { IListViewUI, MenuAction } from '@hungpvq/map-dataset';
import { findAllComponentsByType } from '@hungpvq/map-dataset';
import { BaseButton, RegistryItem, useShow } from '@hungpvq/react-map-core';
import { mdiDelete, mdiDotsVertical, mdiMenuDown, mdiMenuLeft } from '@mdi/js';
import Icon from '@mdi/react';
import { useEffect, useMemo, useState } from 'react';
import { LayerMenuButton } from './layer-menu-button';
import { LayerSubItem } from './layer-sub-item';

const ICON_SIZE = '14px';

export function LayerItem({
  item,
  mapId,
  readonly,
  onRemove,
  onAction,
  onContextMenu,
  onTitleClick,
}: {
  item: IListViewUI;
  mapId: string;
  readonly?: boolean;
  onRemove?: (item: IListViewUI) => void;
  onAction?: (payload: {
    event: React.MouseEvent;
    action: MenuAction<IListViewUI>;
    item: IListViewUI;
  }) => void;
  onContextMenu?: (payload: {
    event: React.MouseEvent;
    actions: MenuAction<IListViewUI>[];
    item: IListViewUI;
  }) => void;
  onTitleClick?: () => void;
}) {
  const [legendShow, toggleLegend] = useShow(item.config?.init_show_legend ?? false);
  const [childrenShow, toggleChildren] = useShow(
    item.config?.init_show_children ?? false,
  );
  const [children, setChildren] = useState<IListViewUI[]>([]);

  useEffect(() => {
    const childItems =
      (findAllComponentsByType(item, 'list-item') as IListViewUI[]).sort(
        (a, b) => b.index - a.index,
      ) || [];
    setChildren(childItems);
  }, [item]);

  const menus = useMemo(
    () => (item.getMenus?.() || []) as MenuAction<IListViewUI>[],
    [item],
  );
  const extraMenus = menus
    .filter((x) => !x.location || x.location === 'extra')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
  const preBottomMenus = menus
    .filter((x) => x.location === 'prebottom')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
  const bottomMenus = menus
    .filter((x) => x.location === 'bottom')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
  const contentMenus = menus
    .filter((x) => x.location === 'menu')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
  const showBottom =
    !readonly && (!item.config?.disabled_opacity || bottomMenus.length > 0);

  return (
    <div className="layer-item-container">
      <div className="layer-item__info">
        {item.icon?.componentKey && (
          <div className="layer-item__icon">
            <RegistryItem
              componentKey={item.icon.componentKey}
              mapId={mapId}
              {...item.icon.attr}
              data={item}
            />
          </div>
        )}
        <span
          className="layer-item__title"
          title={item.getName()}
          onClick={() => onTitleClick?.()}
        >
          {item.getName()}
        </span>
        <div className="v-spacer" />
        <div className="layer-item__title-action">
          {extraMenus.map((menu, i) => (
            <LayerMenuButton
              key={i}
              menu={menu}
              item={item}
              mapId={mapId}
              onAction={onAction}
            />
          ))}
          {!readonly && !item.config?.disabled_delete && (
            <BaseButton onClick={() => onRemove?.(item)}>
              <Icon path={mdiDelete} size={ICON_SIZE} />
            </BaseButton>
          )}
          {contentMenus.length > 0 && (
            <BaseButton
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                onContextMenu?.({ event, actions: contentMenus, item });
              }}
            >
              <Icon path={mdiDotsVertical} size={ICON_SIZE} />
            </BaseButton>
          )}
          {!showBottom && (
            <>
              {bottomMenus.map((menu, i) => (
                <LayerMenuButton
                  key={i}
                  menu={menu}
                  item={item}
                  mapId={mapId}
                  onAction={onAction}
                />
              ))}
              {item.legend && (
                <BaseButton onClick={() => toggleLegend()}>
                  <Icon
                    path={legendShow ? mdiMenuDown : mdiMenuLeft}
                    size={ICON_SIZE}
                  />
                </BaseButton>
              )}
            </>
          )}
        </div>
      </div>
      {showBottom && (
        <div className="layer-item__action">
          {preBottomMenus.map((menu, i) => (
            <LayerMenuButton
              key={i}
              menu={menu}
              item={item}
              mapId={mapId}
              onAction={onAction}
            />
          ))}
          <div className="v-spacer" />
          {bottomMenus.map((menu, i) => (
            <LayerMenuButton
              key={i}
              menu={menu}
              item={item}
              mapId={mapId}
              onAction={onAction}
            />
          ))}
          {children.length > 0 && (
            <BaseButton onClick={() => toggleChildren()}>
              <Icon
                path={childrenShow ? mdiMenuDown : mdiMenuLeft}
                size={ICON_SIZE}
              />
            </BaseButton>
          )}
          {item.legend && (
            <BaseButton onClick={() => toggleLegend()}>
              <Icon
                path={legendShow ? mdiMenuDown : mdiMenuLeft}
                size={ICON_SIZE}
              />
            </BaseButton>
          )}
        </div>
      )}
      {legendShow && item.legend && (
        <RegistryItem
          componentKey={item.legend.componentKey}
          mapId={mapId}
          data={item}
          {...item.legend.attr}
        />
      )}
      {childrenShow && children.length > 0 && (
        <div className="layer-item__children">
          {children.map((child) => (
            <LayerSubItem
              key={child.id}
              item={child}
              mapId={mapId}
              onAction={onAction}
              onContextMenu={onContextMenu}
            />
          ))}
        </div>
      )}
    </div>
  );
}
