// libs/vue/map-devtools/src/ui/DevtoolsOverlay.vue
<template>
  <div
    ref="shellRef"
    class="devtools-container"
    :class="{
      'devtools-container--mobile': isMobile,
      'devtools-container--open': state.isOpen,
      'devtools-container--dragging': dragging,
      'devtools-container--moved': !!pos,
    }"
    :style="shellStyle"
  >
    <MapControlButton
      v-if="!state.isOpen"
      class="devtools-toggle"
      variant="icon"
      :size="48"
      title="Map Devtools — drag to move"
      aria-label="Map Devtools"
      @pointerdown="onShellPointerDown"
      @click="onToggleClick"
    >
      <SvgIcon :size="22" type="mdi" :path="mdiTools" />
    </MapControlButton>

    <div
      v-else
      class="devtools-panel"
      :class="{ 'devtools-panel--mobile': isMobile }"
    >
      <div
        class="devtools-drag-bar"
        title="Drag to move"
        @pointerdown="onShellPointerDown"
      >
        <span class="devtools-drag-bar__label">Map Devtools</span>
        <span class="devtools-drag-bar__actions">
          <span class="devtools-drag-bar__hint" aria-hidden="true">⠿</span>
          <MapControlButton
            class="devtools-drag-bar__close"
            variant="icon"
            size="small"
            title="Close"
            aria-label="Close Map Devtools"
            @pointerdown.stop
            @click.stop="close"
          >
            <SvgIcon :size="16" type="mdi" :path="mdiClose" />
          </MapControlButton>
        </span>
      </div>
      <DevtoolsPanelBody />
    </div>
  </div>
</template>

<script setup lang="ts">
import { MapControlButton } from '@hungpvq/vue-map-core';
import {
  beginPanelDrag,
  panelPosStyle,
  type PanelPos,
} from '@hungpvq/map-debug';
import { isDevtoolsMobileViewport } from '@hungpvq/map-core/devtools';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiClose, mdiTools } from '@mdi/js';
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { setDevtoolOpen } from '../store';
import { devtoolState } from '../store';
import DevtoolsPanelBody from './DevtoolsPanelBody.vue';

defineProps<{
  containerId?: string;
  mapId?: string;
}>();

const state = devtoolState;
const isMobile = ref(isDevtoolsMobileViewport());
const shellRef = ref<HTMLElement | null>(null);
const pos = ref<PanelPos | null>(null);
const dragging = ref(false);
let dragMoved = false;
let disposeDrag: (() => void) | undefined;

const shellStyle = computed(() => panelPosStyle(pos.value));

function refreshMobile() {
  isMobile.value = isDevtoolsMobileViewport();
}

function open() {
  setDevtoolOpen(true);
}

function close() {
  setDevtoolOpen(false);
}

function onShellPointerDown(e: PointerEvent) {
  if (!shellRef.value) return;
  dragMoved = false;
  disposeDrag?.();
  disposeDrag = beginPanelDrag(shellRef.value, e, {
    onMove: (next) => {
      pos.value = next;
    },
    onDraggingChange: (v) => {
      dragging.value = v;
    },
    onEnd: (moved) => {
      dragMoved = moved;
      disposeDrag = undefined;
    },
  });
}

function onToggleClick(e: MouseEvent) {
  if (dragMoved) {
    e.preventDefault();
    e.stopPropagation();
    dragMoved = false;
    return;
  }
  open();
}

onMounted(() => {
  refreshMobile();
  window.addEventListener('resize', refreshMobile);
});

onUnmounted(() => {
  window.removeEventListener('resize', refreshMobile);
  disposeDrag?.();
});
</script>

// libs/react/map-devtools/src/ui/DevtoolsOverlay.tsx
import { isDevtoolsMobileViewport } from '@hungpvq/map-core/devtools';
import {
  beginPanelDrag,
  panelPosStyle,
  type PanelPos,
} from '@hungpvq/map-debug';
import { MapControlButton } from '@hungpvq/react-map-core';
import { mdiClose, mdiTools } from '@mdi/js';
import Icon from '@mdi/react';
import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type MouseEvent as ReactMouseEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import { setDevtoolOpen } from '../store';
import '../style.css';
import { useDevtoolState } from '../useDevtoolState';
import { DevtoolsPanelBody } from './DevtoolsPanelBody';

export function DevtoolsOverlay({
  containerId: _containerId,
  mapId: _mapId,
}: {
  containerId?: string;
  mapId?: string;
}) {
  const { isOpen, activeTab, logs, errors } = useDevtoolState();
  const logCount = logs.length;
  const errorCount = errors.length;
  const [isMobile, setIsMobile] = useState(isDevtoolsMobileViewport);
  const [pos, setPos] = useState<PanelPos | null>(null);
  const [dragging, setDragging] = useState(false);
  const shellRef = useRef<HTMLDivElement | null>(null);
  const dragMovedRef = useRef(false);
  const disposeDragRef = useRef<(() => void) | undefined>(undefined);

  useEffect(() => {
    const onResize = () => setIsMobile(isDevtoolsMobileViewport());
    onResize();
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  useEffect(
    () => () => {
      disposeDragRef.current?.();
    },
    [],
  );

  const onShellPointerDown = useCallback((e: ReactPointerEvent) => {
    if (!shellRef.current) return;
    dragMovedRef.current = false;
    disposeDragRef.current?.();
    disposeDragRef.current = beginPanelDrag(shellRef.current, e.nativeEvent, {
      onMove: setPos,
      onDraggingChange: setDragging,
      onEnd: (moved) => {
        dragMovedRef.current = moved;
        disposeDragRef.current = undefined;
      },
    });
  }, []);

  const open = () => setDevtoolOpen(true);
  const close = () => setDevtoolOpen(false);

  const onToggleClick = (e: ReactMouseEvent) => {
    if (dragMovedRef.current) {
      e.preventDefault();
      e.stopPropagation();
      dragMovedRef.current = false;
      return;
    }
    open();
  };

  const shellStyle = panelPosStyle(pos) as CSSProperties | undefined;

  const className = [
    'devtools-container',
    isMobile ? 'devtools-container--mobile' : '',
    isOpen ? 'devtools-container--open' : '',
    dragging ? 'devtools-container--dragging' : '',
    pos ? 'devtools-container--moved' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div ref={shellRef} className={className} style={shellStyle}>
      {!isOpen ? (
        <MapControlButton
          className="devtools-toggle"
          variant="icon"
          size={48}
          title="Map Devtools — drag to move"
          aria-label="Map Devtools"
          onPointerDown={onShellPointerDown}
          onClick={onToggleClick}
        >
          <Icon path={mdiTools} size="22px" />
        </MapControlButton>
      ) : (
        <div
          className={`devtools-panel${isMobile ? ' devtools-panel--mobile' : ''}`}
        >
          <div
            className="devtools-drag-bar"
            title="Drag to move"
            onPointerDown={onShellPointerDown}
          >
            <span className="devtools-drag-bar__label">Map Devtools</span>
            <span className="devtools-drag-bar__actions">
              <span className="devtools-drag-bar__hint" aria-hidden="true">
                ⠿
              </span>
              <MapControlButton
                className="devtools-drag-bar__close"
                variant="icon"
                size="small"
                title="Close"
                aria-label="Close Map Devtools"
                onPointerDown={(e) => e.stopPropagation()}
                onClick={(e) => {
                  e.stopPropagation();
                  close();
                }}
              >
                <Icon path={mdiClose} size="16px" />
              </MapControlButton>
            </span>
          </div>
          <DevtoolsPanelBody
            activeTab={activeTab}
            logCount={logCount}
            errorCount={errorCount}
          />
        </div>
      )}
    </div>
  );
}
