// libs/vue/map-devtools/src/ui/TreeItem.vue
<template>
  <div class="tree-item">
    <div class="tree-item__row" @click="toggle">
      <span
        v-if="hasChildren"
        class="tree-item__toggle"
        :class="{ 'tree-item__toggle--open': isOpen }"
      >
        ▶
      </span>
      <span v-else class="tree-item__toggle" />
      <span class="tree-item__key" v-if="label">{{ label }}: </span>
      <span class="tree-item__value" :class="`tree-item__value--${valueType}`">{{
        displayValue
      }}</span>
      <span v-if="hasChildren && !isOpen" class="tree-item__preview">
        {{ previewValue }}
      </span>
    </div>
    <div v-if="isOpen && hasChildren" class="tree-item__children">
      <TreeItem
        v-for="key in childKeys"
        :key="key"
        :label="key"
        :data="data[key]"
        :depth="depth + 1"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  childKeys as getChildKeys,
  displayValue as getDisplayValue,
  getValueType,
  hasChildren as getHasChildren,
  previewValue as getPreviewValue,
} from '@hungpvq/map-debug';
import { computed, ref } from 'vue';

const props = defineProps<{
  label?: string;
  data: any;
  depth?: number;
}>();

const isOpen = ref(false);
const depth = props.depth || 0;

const valueType = computed(() => getValueType(props.data));
const hasChildren = computed(() => getHasChildren(props.data));
const childKeys = computed(() => getChildKeys(props.data));
const displayValue = computed(() => getDisplayValue(props.data));
const previewValue = computed(() => getPreviewValue(props.data));

function toggle() {
  if (hasChildren.value) isOpen.value = !isOpen.value;
}
</script>

// libs/react/map-devtools/src/ui/TreeItem.tsx
import {
  childKeys,
  displayValue,
  getValueType,
  hasChildren,
  previewValue,
} from '@hungpvq/map-debug';
import { useMemo, useState } from 'react';

export interface TreeItemProps {
  label?: string;
  data: unknown;
  depth?: number;
}

export function TreeItem({ label, data, depth = 0 }: TreeItemProps) {
  const [isOpen, setIsOpen] = useState(false);
  const valueType = getValueType(data);
  const canExpand = hasChildren(data);
  const keys = useMemo(() => childKeys(data), [data]);
  const shown = useMemo(() => displayValue(data), [data]);
  const preview = previewValue(data);

  const toggle = () => {
    if (canExpand) setIsOpen((open) => !open);
  };

  return (
    <div className="tree-item">
      <div
        className="tree-item__row"
        onClick={toggle}
      >
        {canExpand ? (
          <span
            className={`tree-item__toggle${isOpen ? ' tree-item__toggle--open' : ''}`}
          >
            ▶
          </span>
        ) : (
          <span className="tree-item__toggle" />
        )}
        {label ? <span className="tree-item__key">{label}: </span> : null}
        <span className={`tree-item__value tree-item__value--${valueType}`}>
          {shown}
        </span>
        {canExpand && !isOpen ? (
          <span className="tree-item__preview">{preview}</span>
        ) : null}
      </div>
      {isOpen && canExpand ? (
        <div className="tree-item__children">
          {keys.map((key) => (
            <TreeItem
              key={`${depth}-${key}`}
              label={key}
              data={(data as Record<string, unknown>)[key]}
              depth={depth + 1}
            />
          ))}
        </div>
      ) : null}
    </div>
  );
}
