// libs/vue/draggable/src/components/ContextMenuItem.vue
<script lang="ts">
export default {
  name: 'ContextMenuItem',
};
</script>
<script setup lang="ts">
defineProps({
  active: { type: Boolean, default: false },
  disabled: { type: Boolean, default: false },
});

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();

function onActivate(event: MouseEvent | KeyboardEvent) {
  emit('click', event as MouseEvent);
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    event.stopPropagation();
    (event.currentTarget as HTMLElement).click();
  }
}
</script>

<template>
  <li
    role="menuitem"
    tabindex="-1"
    class="context-menu__item"
    :class="{
      'is-active': active,
      'is-disabled': disabled,
      clickable: !disabled,
    }"
    :aria-disabled="disabled ? 'true' : undefined"
    :aria-current="active ? 'true' : undefined"
    @click.stop="!disabled && onActivate($event)"
    @keydown="onKeydown"
  >
    <slot />
  </li>
</template>

// libs/react/draggable/src/components/ContextMenuItem.tsx
import type {
  KeyboardEvent as ReactKeyboardEvent,
  MouseEvent as ReactMouseEvent,
  ReactNode,
} from 'react';

export type ContextMenuItemProps = {
  active?: boolean;
  disabled?: boolean;
  className?: string;
  children?: ReactNode;
  onClick?: (event: ReactMouseEvent<HTMLLIElement>) => void;
};

function ContextMenuItem({
  active = false,
  disabled = false,
  className,
  children,
  onClick,
}: ContextMenuItemProps) {
  function handleKeyDown(event: ReactKeyboardEvent<HTMLLIElement>) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      event.stopPropagation();
      event.currentTarget.click();
    }
  }

  function handleClick(event: ReactMouseEvent<HTMLLIElement>) {
    if (disabled) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    onClick?.(event);
  }

  return (
    <li
      role="menuitem"
      tabIndex={-1}
      aria-disabled={disabled || undefined}
      aria-current={active || undefined}
      className={[
        'context-menu__item',
        active ? 'is-active' : '',
        disabled ? 'is-disabled' : 'clickable',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      {children}
    </li>
  );
}

export { ContextMenuItem };
