// libs/vue/map-dataset/src/modules/AttributeTable/AttributeTableGrid.vue
<script lang="ts">
export default { name: 'attribute-table-grid' };
</script>
<script setup lang="ts">
import { convertFeatureToItem } from '@hungpvq/map-dataset';
import {
  type AttributeTableColumn,
  type AttributeTableGridProps,
  type AttributeTableRow,
  getAttributeTableCellRaw,
  resolveAttributeTableComponentRef,
} from '@hungpvq/map-dataset/attribute-table';
import { RegistryItem } from '@hungpvq/vue-map-core';
import { InputText } from '@hungpvq/vue-map-core/fields';
import {
  type Component,
  computed,
  markRaw,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
} from 'vue';

import DatasetMenus from '../../extra/menu/dataset-menus.vue';

const props = defineProps<AttributeTableGridProps>();
const scrollEl = ref<HTMLElement | null>(null);
const lastTop = ref(-1);
const lastHeight = ref(-1);
const focusedRowId = ref<string | null>(null);
let resizeObserver: ResizeObserver | null = null;

function syncScrollMetrics() {
  const el = scrollEl.value;
  if (!el) return;
  const top = el.scrollTop;
  const height = el.clientHeight;
  if (lastTop.value === top && lastHeight.value === height) return;
  lastTop.value = top;
  lastHeight.value = height;
  props.onScrollMetrics(top, height);
}

function bindObserver() {
  resizeObserver?.disconnect();
  resizeObserver = null;
  const el = scrollEl.value;
  if (!el || typeof ResizeObserver === 'undefined') return;
  resizeObserver = new ResizeObserver(() => syncScrollMetrics());
  resizeObserver.observe(el);
}

onMounted(() => {
  nextTick(() => {
    syncScrollMetrics();
    bindObserver();
  });
});

watch(
  () => [props.loading, props.empty] as const,
  () =>
    nextTick(() => {
      syncScrollMetrics();
      bindObserver();
    }),
);

watch(
  () => props.windowedRows.map((r) => r.id).join('\0'),
  () => {
    const ids = props.windowedRows.map((r) => r.id);
    if (!ids.length) {
      focusedRowId.value = null;
      return;
    }
    if (!focusedRowId.value || !ids.includes(focusedRowId.value)) {
      focusedRowId.value = ids[0] ?? null;
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  resizeObserver = null;
});

function sortMark(key: string) {
  const hit = props.sortStates.find((s) => s.key === key);
  if (!hit) return '';
  const idx = props.sortStates.indexOf(hit) + 1;
  return `${hit.dir === 'asc' ? ' ↑' : ' ↓'}${
    props.sortStates.length > 1 ? idx : ''
  }`;
}

function ariaSort(key: string): 'ascending' | 'descending' | 'none' {
  const hit = props.sortStates.find((s) => s.key === key);
  if (!hit) return 'none';
  return hit.dir === 'asc' ? 'ascending' : 'descending';
}

function sortButtonLabel(column: AttributeTableColumn) {
  const state = ariaSort(column.key);
  const stateLabel =
    state === 'ascending'
      ? props.sortedAscLabel
      : state === 'descending'
        ? props.sortedDescLabel
        : props.notSortedLabel;
  return `${column.label}, ${stateLabel}`;
}

function cellTitle(value: string) {
  return value.length > 80 ? value : undefined;
}

function isColumnSortable(column: AttributeTableColumn) {
  return props.sort !== false && column.sortable !== false;
}

function resolveSlot(value: unknown) {
  const resolved = resolveAttributeTableComponentRef(value);
  const defaultComponent = resolved.defaultComponent as Component | undefined;
  return {
    componentKey: resolved.componentKey,
    defaultComponent:
      defaultComponent && typeof defaultComponent === 'object'
        ? markRaw(defaultComponent)
        : defaultComponent,
  };
}

function cellRaw(row: AttributeTableRow, column: AttributeTableColumn) {
  return getAttributeTableCellRaw(row, column);
}

function headerSortMeta(column: AttributeTableColumn) {
  const sortable = isColumnSortable(column);
  if (!sortable) return { sortable: false as const };
  const hit = props.sortStates.find((s) => s.key === column.key);
  const base = hit
    ? {
        sortable: true as const,
        sortDir: hit.dir,
        sortOrder: props.sortStates.indexOf(hit) + 1,
        sortCount: props.sortStates.length,
      }
    : { sortable: true as const };
  const onSort = (append?: boolean) => props.onSortColumn(column.key, !!append);
  return {
    ...base,
    onSort,
  };
}

function selectRowLabel(row: AttributeTableRow) {
  const first = props.columns[0];
  const name = first ? row.cells[first.key] : '';
  return name
    ? `${props.selectRowLabel}: ${name}`
    : `${props.selectRowLabel} ${row.id}`;
}

function focusRowAt(index: number) {
  const rows = props.windowedRows;
  if (!rows.length) return;
  const clamped = Math.max(0, Math.min(index, rows.length - 1));
  focusedRowId.value = rows[clamped]?.id ?? null;
  nextTick(() => {
    const el = scrollEl.value?.querySelector(
      `tr[data-row-id="${CSS.escape(focusedRowId.value ?? '')}"]`,
    ) as HTMLElement | null;
    el?.focus();
  });
}

function onRegionKeydown(event: KeyboardEvent) {
  const rows = props.windowedRows;
  if (!rows.length) return;
  const current = focusedRowId.value
    ? rows.findIndex((r) => r.id === focusedRowId.value)
    : 0;
  const idx = current < 0 ? 0 : current;

  if (event.key === 'ArrowDown') {
    event.preventDefault();
    focusRowAt(idx + 1);
    return;
  }
  if (event.key === 'ArrowUp') {
    event.preventDefault();
    focusRowAt(idx - 1);
    return;
  }
  if (event.key === 'Home') {
    event.preventDefault();
    focusRowAt(0);
    return;
  }
  if (event.key === 'End') {
    event.preventDefault();
    focusRowAt(rows.length - 1);
    return;
  }
  if (event.key === ' ' || event.key === 'Enter') {
    const row = rows[idx];
    if (!row) return;
    // Don't steal Space/Enter from buttons / checkboxes / links.
    const target = event.target as HTMLElement | null;
    if (
      target &&
      (target.closest('button, a, input, select, textarea') ||
        target.isContentEditable)
    ) {
      return;
    }
    event.preventDefault();
    props.onToggleRow(row);
  }
}

const showCheckbox = computed(() => props.checkbox !== false);
const showColumnFilter = computed(() => props.columnFilter !== false);
const colSpan = computed(
  () =>
    props.columns.length +
    (showCheckbox.value ? 1 : 0) +
    (props.itemMenus.length ? 1 : 0),
);

function columnFilterAria(column: AttributeTableColumn) {
  return (props.columnFilterForLabel || 'Filter {column}').replace(
    /\{column\}/g,
    column.label,
  );
}
</script>
<template>
  <div
    v-if="props.loading"
    class="attribute-table__grid"
    role="region"
    :aria-label="props.gridRegionLabel"
    aria-busy="true"
  >
    <div class="attribute-table__status" role="status" aria-live="polite">
      {{ props.loadingLabel }}
    </div>
  </div>
  <div
    v-else-if="props.empty"
    class="attribute-table__grid"
    role="region"
    :aria-label="props.gridRegionLabel"
  >
    <div class="attribute-table__status" role="status" aria-live="polite">
      {{ props.emptyLabel }}
    </div>
  </div>
  <div
    v-else
    class="attribute-table__grid"
    role="region"
    :aria-label="props.gridRegionLabel"
  >
    <div
      ref="scrollEl"
      class="attribute-table__scroll"
      tabindex="0"
      @scroll.passive="syncScrollMetrics"
      @keydown="onRegionKeydown"
    >
      <table class="attribute-table__table" :aria-label="props.tableLabel">
        <thead>
          <tr>
            <th v-if="showCheckbox" class="attribute-table__check" scope="col">
              <input
                type="checkbox"
                :checked="props.allVisibleSelected"
                :aria-label="props.selectAllLabel"
                @change="props.onToggleSelectAll()"
              />
            </th>
            <th
              v-for="column in props.columns"
              :key="column.key"
              scope="col"
              :aria-sort="
                isColumnSortable(column) ? ariaSort(column.key) : undefined
              "
              :class="{
                'is-sortable': isColumnSortable(column),
                'is-sorted':
                  isColumnSortable(column) &&
                  props.sortStates.some((s) => s.key === column.key),
              }"
            >
              <RegistryItem
                v-if="column.headerComponent"
                :mapId="props.mapId"
                :label="column.label"
                :column="column"
                v-bind="{
                  ...resolveSlot(column.headerComponent),
                  ...headerSortMeta(column),
                }"
              />
              <button
                v-else-if="isColumnSortable(column)"
                type="button"
                class="attribute-table__sort-btn"
                :aria-label="sortButtonLabel(column)"
                @click="props.onSortColumn(column.key, $event.shiftKey)"
              >
                {{ column.label }}{{ sortMark(column.key) }}
              </button>
              <template v-else>{{ column.label }}</template>
            </th>
            <th
              v-if="props.itemMenus.length"
              class="attribute-table__actions"
              scope="col"
            >
              <span class="attribute-table__sr-only">{{
                props.actionsColumnLabel
              }}</span>
            </th>
          </tr>
          <tr v-if="showColumnFilter" class="attribute-table__filter-row">
            <th v-if="showCheckbox" class="attribute-table__check" scope="col">
              <span class="attribute-table__sr-only">{{
                props.columnFilterForLabel
              }}</span>
            </th>
            <th
              v-for="column in props.columns"
              :key="'filter-' + column.key"
              scope="col"
              :class="{
                'is-column-filtered': !!(
                  props.columnFilters[column.key] ?? ''
                ).trim(),
              }"
            >
              <InputText
                :model-value="props.columnFilters[column.key] ?? ''"
                :aria-label="columnFilterAria(column)"
                :placeholder="column.label"
                @update:model-value="
                  props.onColumnFilterChange(column.key, String($event ?? ''))
                "
                @click.stop
              />
            </th>
            <th
              v-if="props.itemMenus.length"
              class="attribute-table__actions"
              scope="col"
            />
          </tr>
        </thead>
        <tbody>
          <tr
            v-if="props.virtualWindow.offsetY > 0"
            class="attribute-table__spacer"
            aria-hidden="true"
          >
            <td
              :colspan="colSpan"
              :style="{
                height: props.virtualWindow.offsetY + 'px',
                padding: 0,
                border: 0,
              }"
            />
          </tr>
          <tr
            v-for="row in props.windowedRows"
            :key="row.id"
            :data-row-id="row.id"
            :class="{
              'is-selected': props.selectedIds.has(row.id),
              'is-focused': focusedRowId === row.id,
            }"
            :style="{ height: props.rowHeight + 'px' }"
            :aria-selected="props.selectedIds.has(row.id) ? 'true' : 'false'"
            :tabindex="focusedRowId === row.id ? 0 : -1"
            @click="
              focusedRowId = row.id;
              props.onToggleRow(row);
            "
            @focus="focusedRowId = row.id"
          >
            <td v-if="showCheckbox" class="attribute-table__check" @click.stop>
              <input
                type="checkbox"
                :checked="props.selectedIds.has(row.id)"
                :aria-label="selectRowLabel(row)"
                @change="props.onToggleRow(row)"
              />
            </td>
            <td
              v-for="column in props.columns"
              :key="column.key"
              :title="cellTitle(row.cells[column.key] ?? '')"
            >
              <RegistryItem
                v-if="column.cellComponent"
                v-bind="resolveSlot(column.cellComponent)"
                :mapId="props.mapId"
                :value="row.cells[column.key] ?? ''"
                :raw="cellRaw(row, column)"
                :row="row"
                :column="column"
              />
              <template v-else>{{ row.cells[column.key] }}</template>
            </td>
            <td
              v-if="props.itemMenus.length"
              class="attribute-table__actions"
              @click.stop
            >
              <DatasetMenus
                :menus="props.itemMenus"
                :data="props.itemMenuHost"
                :mapId="props.mapId"
                :value="convertFeatureToItem(row.feature)"
                :locations="['extra', 'menu']"
              />
            </td>
          </tr>
          <tr
            v-if="props.bottomSpacerHeight > 0"
            class="attribute-table__spacer"
            aria-hidden="true"
          >
            <td
              :colspan="colSpan"
              :style="{
                height: props.bottomSpacerHeight + 'px',
                padding: 0,
                border: 0,
              }"
            />
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// libs/react/map-dataset/src/modules/AttributeTable/AttributeTableGrid.tsx
import { convertFeatureToItem } from '@hungpvq/map-dataset';
import {
  type AttributeTableColumn,
  type AttributeTableGridProps,
  type AttributeTableRow,
  getAttributeTableCellRaw,
  resolveAttributeTableComponentRef,
} from '@hungpvq/map-dataset/attribute-table';
import { RegistryItem } from '@hungpvq/react-map-core';
import { InputText } from '@hungpvq/react-map-core/fields';
import type { ComponentType, KeyboardEvent as ReactKeyboardEvent } from 'react';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';

import { DatasetMenus } from '../../extra/menu/dataset-menus';

function isColumnSortable(
  sortEnabled: boolean | undefined,
  column: AttributeTableColumn,
) {
  return sortEnabled !== false && column.sortable !== false;
}

function resolveSlot(value: unknown) {
  const resolved = resolveAttributeTableComponentRef(value);
  return {
    componentKey: resolved.componentKey,
    defaultComponent: resolved.defaultComponent as
      ComponentType<Record<string, unknown>> | undefined,
  };
}

function headerSortMeta(
  sortEnabled: boolean | undefined,
  column: AttributeTableColumn,
  sortStates: AttributeTableGridProps['sortStates'],
  onSortColumn: AttributeTableGridProps['onSortColumn'],
) {
  const sortable = isColumnSortable(sortEnabled, column);
  if (!sortable) {
    return { sortable: false as const };
  }
  const hit = sortStates.find((s) => s.key === column.key);
  const base = hit
    ? {
        sortable: true as const,
        sortDir: hit.dir,
        sortOrder: sortStates.indexOf(hit) + 1,
        sortCount: sortStates.length,
      }
    : { sortable: true as const };
  return {
    ...base,
    onSort: (append?: boolean) => onSortColumn(column.key, !!append),
  };
}

function ariaSortFor(
  key: string,
  sortStates: AttributeTableGridProps['sortStates'],
): 'ascending' | 'descending' | 'none' {
  const hit = sortStates.find((s) => s.key === key);
  if (!hit) return 'none';
  return hit.dir === 'asc' ? 'ascending' : 'descending';
}

export function AttributeTableGrid(props: AttributeTableGridProps) {
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const lastMetricsRef = useRef({ top: -1, height: -1 });
  const onScrollMetricsRef = useRef(props.onScrollMetrics);
  onScrollMetricsRef.current = props.onScrollMetrics;
  const showCheckbox = props.checkbox !== false;
  const showColumnFilter = props.columnFilter !== false;
  const [focusedRowId, setFocusedRowId] = useState<string | null>(null);

  const syncScrollMetrics = () => {
    const el = scrollRef.current;
    if (!el) return;
    const top = el.scrollTop;
    const height = el.clientHeight;
    const last = lastMetricsRef.current;
    if (last.top === top && last.height === height) return;
    lastMetricsRef.current = { top, height };
    onScrollMetricsRef.current(top, height);
  };

  useLayoutEffect(() => {
    if (props.loading || props.empty) return;
    const el = scrollRef.current;
    if (!el) return;
    syncScrollMetrics();
    if (typeof ResizeObserver === 'undefined') return;
    const observer = new ResizeObserver(() => syncScrollMetrics());
    observer.observe(el);
    return () => observer.disconnect();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.loading, props.empty]);

  useEffect(() => {
    const ids = props.windowedRows.map((r) => r.id);
    if (!ids.length) {
      setFocusedRowId(null);
      return;
    }
    setFocusedRowId((prev) =>
      prev && ids.includes(prev) ? prev : (ids[0] ?? null),
    );
  }, [props.windowedRows]);

  function selectRowLabel(row: AttributeTableRow) {
    const first = props.columns[0];
    const name = first ? row.cells[first.key] : '';
    return name
      ? `${props.selectRowLabel}: ${name}`
      : `${props.selectRowLabel} ${row.id}`;
  }

  function columnFilterAria(column: AttributeTableColumn) {
    return (props.columnFilterForLabel || 'Filter {column}').replace(
      /\{column\}/g,
      column.label,
    );
  }

  function sortButtonLabel(column: AttributeTableColumn) {
    const state = ariaSortFor(column.key, props.sortStates);
    const stateLabel =
      state === 'ascending'
        ? props.sortedAscLabel
        : state === 'descending'
          ? props.sortedDescLabel
          : props.notSortedLabel;
    return `${column.label}, ${stateLabel}`;
  }

  function focusRowAt(index: number) {
    const rows = props.windowedRows;
    if (!rows.length) return;
    const clamped = Math.max(0, Math.min(index, rows.length - 1));
    const id = rows[clamped]?.id ?? null;
    setFocusedRowId(id);
    requestAnimationFrame(() => {
      const el = scrollRef.current?.querySelector(
        `tr[data-row-id="${CSS.escape(id ?? '')}"]`,
      ) as HTMLElement | null;
      el?.focus();
    });
  }

  function onRegionKeydown(event: ReactKeyboardEvent<HTMLDivElement>) {
    const rows = props.windowedRows;
    if (!rows.length) return;
    const current = focusedRowId
      ? rows.findIndex((r) => r.id === focusedRowId)
      : 0;
    const idx = current < 0 ? 0 : current;

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      focusRowAt(idx + 1);
      return;
    }
    if (event.key === 'ArrowUp') {
      event.preventDefault();
      focusRowAt(idx - 1);
      return;
    }
    if (event.key === 'Home') {
      event.preventDefault();
      focusRowAt(0);
      return;
    }
    if (event.key === 'End') {
      event.preventDefault();
      focusRowAt(rows.length - 1);
      return;
    }
    if (event.key === ' ' || event.key === 'Enter') {
      const row = rows[idx];
      if (!row) return;
      const target = event.target as HTMLElement | null;
      if (
        target &&
        (target.closest('button, a, input, select, textarea') ||
          target.isContentEditable)
      ) {
        return;
      }
      event.preventDefault();
      props.onToggleRow(row);
    }
  }

  if (props.loading) {
    return (
      <div
        className="attribute-table__grid"
        role="region"
        aria-label={props.gridRegionLabel}
        aria-busy="true"
      >
        <div
          className="attribute-table__status"
          role="status"
          aria-live="polite"
        >
          {props.loadingLabel}
        </div>
      </div>
    );
  }
  if (props.empty) {
    return (
      <div
        className="attribute-table__grid"
        role="region"
        aria-label={props.gridRegionLabel}
      >
        <div
          className="attribute-table__status"
          role="status"
          aria-live="polite"
        >
          {props.emptyLabel}
        </div>
      </div>
    );
  }

  const colSpan =
    props.columns.length +
    (showCheckbox ? 1 : 0) +
    (props.itemMenus.length > 0 ? 1 : 0);

  return (
    <div
      className="attribute-table__grid"
      role="region"
      aria-label={props.gridRegionLabel}
    >
      <div
        className="attribute-table__scroll"
        ref={scrollRef}
        tabIndex={0}
        onScroll={syncScrollMetrics}
        onKeyDown={onRegionKeydown}
      >
        <table
          className="attribute-table__table"
          aria-label={props.tableLabel}
        >
          <thead>
            <tr>
              {showCheckbox ? (
                <th
                  className="attribute-table__check"
                  scope="col"
                >
                  <input
                    type="checkbox"
                    checked={props.allVisibleSelected}
                    aria-label={props.selectAllLabel}
                    onChange={props.onToggleSelectAll}
                  />
                </th>
              ) : null}
              {props.columns.map((column) => {
                const sortable = isColumnSortable(props.sort, column);
                const hit = sortable
                  ? props.sortStates.find((s) => s.key === column.key)
                  : undefined;
                const idx = hit ? props.sortStates.indexOf(hit) + 1 : 0;
                const className = [
                  sortable ? 'is-sortable' : '',
                  hit ? 'is-sorted' : '',
                ]
                  .filter(Boolean)
                  .join(' ');
                const headerSlot = column.headerComponent
                  ? resolveSlot(column.headerComponent)
                  : null;
                return (
                  <th
                    key={column.key}
                    scope="col"
                    className={className || undefined}
                    aria-sort={
                      sortable
                        ? ariaSortFor(column.key, props.sortStates)
                        : undefined
                    }
                  >
                    {headerSlot ? (
                      <RegistryItem
                        componentKey={headerSlot.componentKey}
                        defaultComponent={headerSlot.defaultComponent}
                        mapId={props.mapId}
                        label={column.label}
                        column={column}
                        {...headerSortMeta(
                          props.sort,
                          column,
                          props.sortStates,
                          props.onSortColumn,
                        )}
                      />
                    ) : sortable ? (
                      <button
                        type="button"
                        className="attribute-table__sort-btn"
                        aria-label={sortButtonLabel(column)}
                        onClick={(event) =>
                          props.onSortColumn(column.key, event.shiftKey)
                        }
                      >
                        {column.label}
                        {hit
                          ? `${hit.dir === 'asc' ? ' ↑' : ' ↓'}${
                              props.sortStates.length > 1 ? idx : ''
                            }`
                          : ''}
                      </button>
                    ) : (
                      column.label
                    )}
                  </th>
                );
              })}
              {props.itemMenus.length > 0 ? (
                <th
                  className="attribute-table__actions"
                  scope="col"
                >
                  <span className="attribute-table__sr-only">
                    {props.actionsColumnLabel}
                  </span>
                </th>
              ) : null}
            </tr>
            {showColumnFilter ? (
              <tr className="attribute-table__filter-row">
                {showCheckbox ? (
                  <th
                    className="attribute-table__check"
                    scope="col"
                  >
                    <span className="attribute-table__sr-only">
                      {props.columnFilterForLabel}
                    </span>
                  </th>
                ) : null}
                {props.columns.map((column) => {
                  const active = !!(
                    props.columnFilters[column.key] ?? ''
                  ).trim();
                  return (
                    <th
                      key={`filter-${column.key}`}
                      scope="col"
                      className={active ? 'is-column-filtered' : undefined}
                    >
                      <InputText
                        value={props.columnFilters[column.key] ?? ''}
                        aria-label={columnFilterAria(column)}
                        placeholder={column.label}
                        onChange={(value) =>
                          props.onColumnFilterChange(column.key, value)
                        }
                        onClick={(e) => e.stopPropagation()}
                      />
                    </th>
                  );
                })}
                {props.itemMenus.length > 0 ? (
                  <th
                    className="attribute-table__actions"
                    scope="col"
                  />
                ) : null}
              </tr>
            ) : null}
          </thead>
          <tbody>
            {props.virtualWindow.offsetY > 0 ? (
              <tr
                className="attribute-table__spacer"
                aria-hidden="true"
              >
                <td
                  colSpan={colSpan}
                  style={{
                    height: props.virtualWindow.offsetY,
                    padding: 0,
                    border: 0,
                  }}
                />
              </tr>
            ) : null}
            {props.windowedRows.map((row) => {
              const selected = props.selectedIds.has(row.id);
              const focused = focusedRowId === row.id;
              return (
                <tr
                  key={row.id}
                  data-row-id={row.id}
                  className={[
                    selected ? 'is-selected' : '',
                    focused ? 'is-focused' : '',
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  style={{ height: props.rowHeight }}
                  aria-selected={selected ? 'true' : 'false'}
                  tabIndex={focused ? 0 : -1}
                  onClick={() => {
                    setFocusedRowId(row.id);
                    props.onToggleRow(row);
                  }}
                  onFocus={() => setFocusedRowId(row.id)}
                >
                  {showCheckbox ? (
                    <td
                      className="attribute-table__check"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <input
                        type="checkbox"
                        checked={selected}
                        aria-label={selectRowLabel(row)}
                        onChange={() => props.onToggleRow(row)}
                      />
                    </td>
                  ) : null}
                  {props.columns.map((column) => {
                    const value = row.cells[column.key] ?? '';
                    const cellSlot = column.cellComponent
                      ? resolveSlot(column.cellComponent)
                      : null;
                    return (
                      <td
                        key={column.key}
                        title={value.length > 80 ? value : undefined}
                      >
                        {cellSlot ? (
                          <RegistryItem
                            componentKey={cellSlot.componentKey}
                            defaultComponent={cellSlot.defaultComponent}
                            mapId={props.mapId}
                            value={value}
                            raw={getAttributeTableCellRaw(row, column)}
                            row={row}
                            column={column}
                          />
                        ) : (
                          value
                        )}
                      </td>
                    );
                  })}
                  {props.itemMenus.length > 0 ? (
                    <td
                      className="attribute-table__actions"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <DatasetMenus
                        menus={props.itemMenus}
                        data={props.itemMenuHost}
                        mapId={props.mapId}
                        value={convertFeatureToItem(row.feature)}
                        locations={['extra', 'menu']}
                      />
                    </td>
                  ) : null}
                </tr>
              );
            })}
            {props.bottomSpacerHeight > 0 ? (
              <tr
                className="attribute-table__spacer"
                aria-hidden="true"
              >
                <td
                  colSpan={colSpan}
                  style={{
                    height: props.bottomSpacerHeight,
                    padding: 0,
                    border: 0,
                  }}
                />
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </div>
  );
}
