// libs/react/map-core/src/extra/compare/modules/CompareSettingControl.tsx
import { useEffect } from 'react';
import type { WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiCog } from '@mdi/js';
import { Icon } from '@mdi/react';
import { MapControlButton } from '../../../components/MapControlButton';
import { InputCheckbox } from '../../../field';
import { defaultMapProps, useMap, useShow } from '../../../hooks';
import { ModuleContainer } from '../../../modules/ModuleContainer/ModuleContainer';
import { useLang } from '../../lang';
import { useMapCompareSetting } from '../hooks';

export interface CompareSettingControlProps extends WithMapPropType {
  show?: boolean;
}

export function CompareSettingControl(props: CompareSettingControlProps) {
  const merged = { ...defaultMapProps, ...props };
  const [show, toggleShow] = useShow(props.show);
  const { mapId, moduleContainerProps } = useMap(merged);
  const { trans, setLocaleDefault } = useLang(mapId);
  const { setting, updateSetting } = useMapCompareSetting(mapId);

  useEffect(() => {
    setLocaleDefault({
      map: {
        'setting-control': {
          title: 'Setting',
          field: { split: 'split', sync: 'sync', vertical: 'vertical' },
        },
      },
    });
  }, [setLocaleDefault]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        <MapControlButton
          onClick={(e) => {
            e.stopPropagation();
            toggleShow();
          }}
          title={trans('map.setting-control.title')}
        >
          <Icon path={mdiCog} size={0.75} />
        </MapControlButton>
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => toggleShow(!!v)}
            title={trans('map.setting-control.title')}
            height={200}
            width={280}
            {...bind}
          >
            <div className="map-compare-setting">
              <div className="map-compare-setting__fields">
                <div>
                  <InputCheckbox
                    label={trans('map.setting-control.field.split')}
                    checked={!!setting.split}
                    onChange={(v) => updateSetting({ ...setting, split: v })}
                  />
                </div>
                <div>
                  <InputCheckbox
                    label={trans('map.setting-control.field.vertical')}
                    checked={!!setting.vertical}
                    onChange={(v) => updateSetting({ ...setting, vertical: v })}
                  />
                </div>
                <div>
                  <InputCheckbox
                    label={trans('map.setting-control.field.sync')}
                    checked={!!setting.sync}
                    onChange={(v) => updateSetting({ ...setting, sync: v })}
                  />
                </div>
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

export function CompareSettingCard(props: CompareSettingControlProps) {
  return <CompareSettingControl {...props} />;
}

// libs/map/core/src/extra/compare/modules/CompareSettingControl/CompareSettingControl.vue
<script setup lang="ts">
import { type WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCog } from '@mdi/js';
import MapControlButton from '../../../../components/MapControlButton.vue';
import { InputCheckbox } from '../../../../field';
import {
  defaultMapProps,
  useMap,
  useShow,
  WithShowProps,
} from '../../../../hooks';
import ModuleContainer from '../../../../modules/ModuleContainer/ModuleContainer.vue';
import { useLang } from '../../../lang';
import { useMapCompareSetting } from '../../hooks';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const [show, toggleShow] = useShow(props.show);
const { mapId, moduleContainerProps } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);

setLocaleDefault({
  map: {
    'setting-control': {
      title: 'Setting',
      field: {
        compare: 'compare',
        split: 'split',
        sync: 'sync',
        vertical: 'vertical',
      },
      btn: {
        apply: 'Apply',
      },
    },
  },
});
const { setting, updateSetting } = useMapCompareSetting(mapId.value);
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapControlButton
        @click.stop="toggleShow()"
        :tooltip="trans('map.setting-control.title')"
      >
        <SvgIcon :size="18" type="mdi" :path="mdiCog" />
      </MapControlButton>
    </template>

    <template #draggable="props">
      <DraggableItemPopup
        v-if="show"
        :height="400"
        :width="400"
        v-bind="props"
        v-model:show="show"
        :title="trans('map.setting-control.title')"
      >
        <div class="setting-container">
          <div class="setting-field-container">
            <!-- <div>
              <InputCheckbox
                :label="trans('map.setting-control.field.compare')"
                v-model="setting.compare"
              />
            </div> -->
            <div>
              <InputCheckbox
                :label="trans('map.setting-control.field.split')"
                v-model="setting.split"
                @change="updateSetting()"
              />
            </div>
            <div>
              <InputCheckbox
                :label="trans('map.setting-control.field.vertical')"
                v-model="setting.vertical"
                @change="updateSetting()"
              />
            </div>
            <div>
              <InputCheckbox
                :label="trans('map.setting-control.field.sync')"
                v-model="setting.sync"
                @change="updateSetting()"
              />
            </div>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>
<style>
.setting-container {
  padding: 8px;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: auto;
}
.setting-field-container > div {
  padding: 4px;
}
.setting-container .setting-field-container {
  height: 100%;
  padding: 8px;
  flex-grow: 1;
  overflow: auto;
}
.setting-container .btn-container {
  flex-grow: 0;
  padding: 8px;
}
.setting-center-container {
  display: flex;
}
.setting-center-container > *:not(:last-child) {
  padding-right: 4px;
}
</style>
