// libs/vue/map-dataset/src/modules/List/ListItem.vue
<template>
  <div class="draggale-item" :class="{ 'draggale-item-active': isSelected }">
    <div
      class="draggable-handle"
      v-if="!disabledDrag"
      :style="{
        background:
          item.color ||
          'var(--map-list-item-active-bg, var(--map-primary-color, #1a73e8))',
      }"
    >
      <div class="draggable-handle__icon">
        <SvgIcon size="14" type="mdi" :path="path.draggable" />
      </div>
    </div>
    <div class="draggale-item__info">
      <slot />
    </div>
  </div>
</template>

<script>
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiArrowUpDown } from '@mdi/js';
export default {
  components: { SvgIcon },
  props: {
    isSelected: Boolean,
    disabledDrag: Boolean,
    item: { type: Object, default: () => ({}) },
  },
  computed: {
    path() {
      return { draggable: mdiArrowUpDown };
    },
  },
};
</script>

// libs/react/map-dataset/src/modules/List/ListItem.tsx
import { mdiArrowUpDown } from '@mdi/js';
import { Icon } from '@mdi/react';

const ICON_SIZE = '14px';

export function ListItem({
  children,
  disabledDrag,
  isSelected,
  item,
  className = '',
}: {
  children: React.ReactNode;
  disabledDrag?: boolean;
  isSelected?: boolean;
  item?: { color?: string; id?: string; name?: string };
  className?: string;
}) {
  return (
    <div
      className={`draggale-item ${isSelected ? 'draggale-item-active' : ''} ${className}`.trim()}
    >
      {!disabledDrag && (
        <div
          className="draggable-handle"
          style={{
            background:
              item?.color ||
              'var(--map-list-item-active-bg, var(--map-primary-color, #1a73e8))',
          }}
        >
          <div className="draggable-handle__icon">
            <Icon
              path={mdiArrowUpDown}
              size={ICON_SIZE}
            />
          </div>
        </div>
      )}
      <div className="draggale-item__info">{children}</div>
    </div>
  );
}
