// libs/vue/map-dataset/src/modules/List/RecursiveList.vue
<template>
  <!-- Group Item -->
  <ListGroupItem
    :item="item"
    :disabled-drag="disabledDrag"
    v-if="isGroup(item)"
  >
    <template #extra-data="{ item }">
      <slot name="group-extra-data" :item="item" />
    </template>
    <template #items-list>
      <div class="draggable-group__children">
        <template
          v-for="(child, index) in item.children"
          :key="(child as any).id || index"
        >
          <RecursiveList
            :item="child"
            :disabled-drag="disabledDrag"
            :is-group="isGroup"
            :is-leaf="isLeaf"
          >
            <template #group-extra-data="{ item: groupItem }">
              <slot name="group-extra-data" :item="groupItem" />
            </template>
            <template #leaf="{ item: leafItem }">
              <slot name="leaf" :item="leafItem" />
            </template>
          </RecursiveList>
        </template>
      </div>
    </template>
  </ListGroupItem>

  <ListItem :item="item" :disabled-drag="disabledDrag" v-else>
    <slot name="leaf" :item="item">
      <div class="leaf-item">
        <span class="leaf-item__title" :title="(item as any).name">
          {{ item.name }}
        </span>
      </div>
    </slot>
  </ListItem>
</template>

<script setup lang="ts">
import { GroupTree, Item, TreeItem } from '@hungpvq/map-dataset';
import { VNode } from 'vue';
import ListGroupItem from './ListGroupItem.vue';
import ListItem from './ListItem.vue';

defineOptions({
  name: 'RecursiveList',
});

type IsGroupFn = (item: TreeItem) => boolean;
type IsLeafFn = (item: TreeItem) => boolean;

withDefaults(
  defineProps<{
    item: TreeItem;
    disabledDrag?: boolean;
    isGroup?: IsGroupFn;
    isLeaf?: IsLeafFn;
  }>(),
  {
    disabledDrag: false,
    isGroup: (item: TreeItem): item is GroupTree =>
      Array.isArray(item.children),
    isLeaf: (item: TreeItem): item is Item => !Array.isArray(item.children),
  },
);

defineSlots<{
  group(props: { item: TreeItem }): VNode[];
  leaf(props: { item: Item }): VNode[];
  'group-extra-data'(props: { item: TreeItem }): VNode[];
}>();
</script>

// libs/react/map-dataset/src/modules/List/RecursiveList.tsx
import type { GroupTree, Item, TreeItem } from '@hungpvq/map-dataset';

import { ListGroupItem } from './ListGroupItem';
import { ListItem } from './ListItem';

export function RecursiveList({
  item,
  disabledDrag,
  isGroup = (node: TreeItem): node is GroupTree =>
    Array.isArray((node as GroupTree).children),
  renderLeaf,
}: {
  item: TreeItem;
  disabledDrag?: boolean;
  isGroup?: (item: TreeItem) => item is GroupTree;
  renderLeaf?: (item: Item) => React.ReactNode;
}) {
  if (isGroup(item)) {
    return (
      <ListGroupItem
        item={item}
        disabledDrag={disabledDrag}
      >
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: 8,
            paddingTop: 8,
          }}
        >
          {(item.children || []).map((child, index) => (
            <RecursiveList
              key={(child as Item).id || index}
              item={child}
              disabledDrag={disabledDrag}
              isGroup={isGroup}
              renderLeaf={renderLeaf}
            />
          ))}
        </div>
      </ListGroupItem>
    );
  }
  return (
    <ListItem
      disabledDrag={disabledDrag}
      item={item as Item}
    >
      {renderLeaf ? (
        renderLeaf(item as Item)
      ) : (
        <span>{String((item as Item).name ?? '')}</span>
      )}
    </ListItem>
  );
}
