// libs/map/core/src/modules/GlobeControl/GlobeControl.vue
<script setup lang="ts">
import type { MapSimple } from '@hungpvq/map-core';
import { type WithMapPropType } from '@hungpvq/map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiWeb } from '@mdi/js';
import { ref } from 'vue';
import MapCommonButton from '../../components/MapCommonButton.vue';
import { useLang, useToolbarControl } from '../../extra';
import { defaultMapProps, useMap } from '../../hooks';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';
const props = withDefaults(defineProps<WithMapPropType>(), {
  ...defaultMapProps,
});
const currentProjection = ref<string | undefined>('mercator');

const { callMap, mapId, moduleContainerProps, order } = useMap(
  props,
  onInit,
  onDestroy,
);
const { trans, setLocaleDefault } = useLang(mapId.value);
setLocaleDefault({
  map: {
    'global-control': {
      title: 'Toggle projection',
    },
  },
});
function toggle() {
  callMap((map) => {
    if (currentProjection.value === 'mercator' || !currentProjection.value) {
      map.setProjection({ type: 'globe' });
    } else {
      map.setProjection({ type: 'mercator' });
    }
    currentProjection.value = map.getProjection()?.type as any;
  });
}
let handleMap: any;
function onInit(_map: MapSimple) {
  handleMap = () => {
    currentProjection.value = _map.getProjection()?.type as any;
  };
  _map.on('styledata', handleMap);
}
function onDestroy(_map: MapSimple) {
  if (handleMap) _map.off('styledata', handleMap);
}
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapGlobeControl',
  getState() {
    return {
      visible: true,
      active: currentProjection.value === 'globe',
      title: trans.value('map.global-control.title'),
      order: order.value,
      icon: {
        type: 'mdi',
        path: mdiWeb,
      },
    };
  },
  onClick() {
    toggle();
  },
});
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton v-if="state" :option="state" @click="control.onAction">
      </MapCommonButton>
    </template>
    <slot />
  </ModuleContainer>
</template>

// libs/react/map-core/src/modules/GlobeControl/GlobeControl.tsx
import React, { useState, useCallback, useEffect } from 'react';
import type { MapSimple } from '@hungpvq/map-core';
import { GLOBE_CONTROL_LOCALE, type WithMapPropType } from '@hungpvq/map-core';
import { mdiWeb } from '@mdi/js';
import { MapCommonButton } from '../../components/MapCommonButton';
import { useLang } from '../../extra';
import { defaultMapProps, useMap } from '../../hooks';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';
import type { MapControlButtonUIState } from '@hungpvq/map-core';

function getProjectionType(map: MapSimple): string | undefined {
  const type = map.getProjection()?.type;
  return typeof type === 'string' ? type : undefined;
}

export function GlobeControl(props: WithMapPropType) {
  const mergedProps = { ...defaultMapProps, ...props };
  const [currentProjection, setCurrentProjection] = useState<
    string | undefined
  >('mercator');

  const onInit = useCallback((_map: MapSimple) => {
    const handleMap = () => {
      setCurrentProjection(getProjectionType(_map));
    };
    _map.on('styledata', handleMap);
    return () => {
      _map.off('styledata', handleMap);
    };
  }, []);

  const onDestroy = useCallback((_map: MapSimple) => {
    // Cleanup handled in onInit return
  }, []);

  const { callMap, mapId, moduleContainerProps, order } = useMap(
    mergedProps,
    onInit,
    onDestroy,
  );
  const { trans, setLocaleDefault } = useLang(mapId);

  useEffect(() => {
    setLocaleDefault(GLOBE_CONTROL_LOCALE);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function toggle() {
    callMap((map) => {
      if (currentProjection === 'mercator' || !currentProjection) {
        map.setProjection({ type: 'globe' });
      } else {
        map.setProjection({ type: 'mercator' });
      }
      setCurrentProjection(getProjectionType(map));
    });
  }

  const buttonState: MapControlButtonUIState = {
    visible: true,
    active: currentProjection === 'globe',
    title: trans('map.global-control.title'),
    order: order,
    icon: {
      type: 'mdi',
      path: mdiWeb,
    },
  };

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        <MapCommonButton
          option={buttonState}
          onClick={(e) => {
            e.stopPropagation();
            toggle();
          }}
        />
      }
    />
  );
}
