// libs/react/map-core/src/extra/basemap/modules/BaseMapAddForm.tsx
import {
  type BaseMapItem,
  type BasemapSourceType,
  createCustomBasemapItem,
  validateBasemapSource,
} from '@hungpvq/map-core/basemap';
import { useCallback, useMemo, useState } from 'react';

import { MapControlButton } from '../../../components/MapControlButton';
import { InputSelect, InputText } from '../../../field';
import { useMap } from '../../../hooks/useMap';
import { useLang } from '../../lang/hook';

export interface BaseMapAddFormProps {
  mapId: string;
  thumbnail?: string;
  /** Show the in-form heading (hide when the host popup already titles the panel). */
  showHeading?: boolean;
  onAdded: (item: BaseMapItem) => void;
  onCancel: () => void;
}

export function BaseMapAddForm({
  mapId,
  thumbnail = '',
  showHeading = true,
  onAdded,
  onCancel,
}: BaseMapAddFormProps) {
  const { mapId: resolvedMapId } = useMap({ mapId });
  const { trans } = useLang(resolvedMapId);

  const [title, setTitle] = useState('');
  const [url, setUrl] = useState('');
  const [type, setType] = useState<BasemapSourceType>('raster');
  const [checking, setChecking] = useState(false);
  const [checkOk, setCheckOk] = useState<boolean | null>(null);
  const [statusMessage, setStatusMessage] = useState('');

  const typeItems = useMemo(
    () => [
      { value: 'raster' as const, text: trans('map.basemap.add-type-raster') },
      { value: 'vector' as const, text: trans('map.basemap.add-type-vector') },
    ],
    [trans],
  );

  const urlHint =
    type === 'vector'
      ? trans('map.basemap.add-url-hint-vector')
      : trans('map.basemap.add-url-hint-raster');

  const canCheck = title.trim().length > 0 && url.trim().length > 0;

  const invalidateCheck = useCallback(() => {
    setCheckOk(null);
    setStatusMessage('');
  }, []);

  const onCheck = useCallback(async () => {
    if (!canCheck || checking) return;
    setChecking(true);
    setStatusMessage('');
    setCheckOk(null);
    try {
      const result = await validateBasemapSource({ type, url });
      if (result.ok) {
        setCheckOk(true);
        setStatusMessage(trans('map.basemap.add-check-ok'));
      } else {
        setCheckOk(false);
        setStatusMessage(result.message || trans('map.basemap.add-check-fail'));
      }
    } finally {
      setChecking(false);
    }
  }, [canCheck, checking, type, url, trans]);

  const onSubmit = useCallback(() => {
    if (!checkOk) return;
    const item = createCustomBasemapItem({
      title,
      type,
      url,
      thumbnail,
    });
    onAdded(item);
  }, [checkOk, title, type, url, thumbnail, onAdded]);

  return (
    <div className="base-map-add-form" onClick={(e) => e.stopPropagation()}>
      <div className="base-map-add-form__body">
        {showHeading ? (
          <div className="base-map-add-form__title">
            {trans('map.basemap.add')}
          </div>
        ) : null}
        <InputText
          label={trans('map.basemap.add-title')}
          value={title}
          onChange={(v) => {
            setTitle(v);
            invalidateCheck();
          }}
        />
        <InputSelect
          label={trans('map.basemap.add-type')}
          value={type}
          items={typeItems}
          itemValue="value"
          itemText="text"
          onChange={(v) => {
            setType(String(v) as BasemapSourceType);
            invalidateCheck();
          }}
        />
        <InputText
          label={trans('map.basemap.add-url')}
          value={url}
          placeholder={urlHint}
          onChange={(v) => {
            setUrl(v);
            invalidateCheck();
          }}
        />
        {statusMessage ? (
          <div
            className={`base-map-add-form__status${
              checkOk === true
                ? ' base-map-add-form__status--ok'
                : checkOk === false
                  ? ' base-map-add-form__status--err'
                  : ''
            }`}
          >
            {statusMessage}
          </div>
        ) : null}
      </div>
      <div className="base-map-add-form__actions">
        <MapControlButton
          variant="text"
          size="small"
          disabled={checking || !canCheck}
          onClick={onCheck}
        >
          {checking
            ? trans('map.basemap.add-checking')
            : trans('map.basemap.add-check')}
        </MapControlButton>
        <MapControlButton
          variant="text"
          size="small"
          disabled={!checkOk || checking}
          onClick={onSubmit}
        >
          {trans('map.basemap.add-submit')}
        </MapControlButton>
        <MapControlButton variant="text" size="small" onClick={onCancel}>
          {trans('map.basemap.add-cancel')}
        </MapControlButton>
      </div>
    </div>
  );
}

// libs/vue/map-core/src/extra/basemap/modules/BaseMapAddForm.vue
<template>
  <div class="base-map-add-form" @click.stop>
    <div class="base-map-add-form__body">
      <div v-if="showHeading" class="base-map-add-form__title">
        {{ trans('map.basemap.add') }}
      </div>
      <InputText
        v-model="title"
        :label="trans('map.basemap.add-title')"
        @update:model-value="invalidateCheck"
      />
      <InputSelect
        v-model="type"
        :label="trans('map.basemap.add-type')"
        :items="typeItems"
        item-value="value"
        item-text="text"
        @update:model-value="invalidateCheck"
      />
      <InputText
        v-model="url"
        :label="trans('map.basemap.add-url')"
        :placeholder="urlHint"
        @update:model-value="invalidateCheck"
      />
      <div
        v-if="statusMessage"
        class="base-map-add-form__status"
        :class="{
          'base-map-add-form__status--ok': checkOk,
          'base-map-add-form__status--err': checkOk === false,
        }"
      >
        {{ statusMessage }}
      </div>
    </div>
    <div class="base-map-add-form__actions">
      <MapControlButton
        variant="text"
        size="small"
        :disabled="checking || !canCheck"
        @click="onCheck"
      >
        {{
          checking
            ? trans('map.basemap.add-checking')
            : trans('map.basemap.add-check')
        }}
      </MapControlButton>
      <MapControlButton
        variant="text"
        size="small"
        :disabled="!checkOk || checking"
        @click="onSubmit"
      >
        {{ trans('map.basemap.add-submit') }}
      </MapControlButton>
      <MapControlButton variant="text" size="small" @click="$emit('cancel')">
        {{ trans('map.basemap.add-cancel') }}
      </MapControlButton>
    </div>
  </div>
</template>
<script setup lang="ts">
import {
  type BaseMapItem,
  type BasemapSourceType,
  createCustomBasemapItem,
  validateBasemapSource,
} from '@hungpvq/map-core/basemap';
import { computed, ref } from 'vue';

import MapControlButton from '../../../components/MapControlButton.vue';
import { useLang } from '../../../extra/lang/hook';
import { InputSelect, InputText } from '../../../field';
import { useMap } from '../../../hooks/useMap';

const props = withDefaults(
  defineProps<{
    mapId: string;
    /** Thumbnail for new items (e.g. none basemap thumb). */
    thumbnail?: string;
    /** Show the in-form heading (hide when the host popup already titles the panel). */
    showHeading?: boolean;
  }>(),
  {
    thumbnail: '',
    showHeading: true,
  },
);

const emit = defineEmits<{
  added: [item: BaseMapItem];
  cancel: [];
}>();

const { mapId } = useMap({ mapId: props.mapId });
const { trans } = useLang(mapId.value);

const title = ref('');
const url = ref('');
const type = ref<BasemapSourceType>('raster');
const checking = ref(false);
const checkOk = ref<boolean | null>(null);
const statusMessage = ref('');

const typeItems = computed(() => [
  {
    value: 'raster' as const,
    text: trans.value('map.basemap.add-type-raster'),
  },
  {
    value: 'vector' as const,
    text: trans.value('map.basemap.add-type-vector'),
  },
]);

const urlHint = computed(() =>
  type.value === 'vector'
    ? trans.value('map.basemap.add-url-hint-vector')
    : trans.value('map.basemap.add-url-hint-raster'),
);

const canCheck = computed(
  () => title.value.trim().length > 0 && url.value.trim().length > 0,
);

function invalidateCheck() {
  checkOk.value = null;
  statusMessage.value = '';
}

async function onCheck() {
  if (!canCheck.value || checking.value) return;
  checking.value = true;
  statusMessage.value = '';
  checkOk.value = null;
  try {
    const result = await validateBasemapSource({
      type: type.value,
      url: url.value,
    });
    if (result.ok) {
      checkOk.value = true;
      statusMessage.value = trans.value('map.basemap.add-check-ok');
    } else {
      checkOk.value = false;
      statusMessage.value =
        result.message || trans.value('map.basemap.add-check-fail');
    }
  } finally {
    checking.value = false;
  }
}

function onSubmit() {
  if (!checkOk.value) return;
  const item = createCustomBasemapItem({
    title: title.value,
    type: type.value,
    url: url.value,
    thumbnail: props.thumbnail ?? '',
  });
  emit('added', item);
}
</script>
