// libs/vue/map-core/src/field/input-action-row.vue
<script setup lang="ts">
/**
 * Joined field + action button row (CreateControl Url|Load pattern).
 * Default slot: `.form-group` field. `#action`: MapControlButton (or any button).
 */
withDefaults(
  defineProps<{
    /** Drop top margin (e.g. toolbar / find rows). */
    flush?: boolean;
  }>(),
  { flush: false },
);
</script>

<template>
  <div
    class="input-action-row"
    :class="{ 'input-action-row--flush': flush }"
  >
    <slot />
    <div class="input-action-row__action">
      <slot name="action" />
    </div>
  </div>
</template>

// libs/react/map-core/src/field/input-action-row.tsx
import type { HTMLAttributes, ReactNode } from 'react';

export interface InputActionRowProps extends HTMLAttributes<HTMLDivElement> {
  /** Field content (typically an Input* that renders `.form-group`). */
  children: ReactNode;
  /** Action control (typically MapControlButton). */
  action: ReactNode;
  /** Drop top margin (e.g. toolbar / find rows). */
  flush?: boolean;
}

/**
 * Joined field + action button row (CreateControl Url|Load pattern).
 */
export function InputActionRow({
  children,
  action,
  flush = false,
  className = '',
  ...rest
}: InputActionRowProps) {
  return (
    <div
      {...rest}
      className={[
        'input-action-row',
        flush ? 'input-action-row--flush' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {children}
      <div className="input-action-row__action">{action}</div>
    </div>
  );
}
