// libs/map/core/src/field/input-choose.vue
<script setup>
const model = defineModel({});
defineProps({
  label: String,
  items: {
    type: Array,
    required: true,
  },
});
function onSetValue(item) {
  model.value = item.value;
}
</script>
<template>
  <div class="form-group">
    <label v-if="label">
      {{ label }}
    </label>
    <div class="input-container">
      <div
        v-for="item in items"
        :key="item.value"
        class="item-choose"
        @click.stop="onSetValue(item)"
        :class="{ 'item-choose-active': item.value === model }"
      >
        {{ item.text }}
      </div>
    </div>
  </div>
</template>
<style scoped>
.input-container {
  display: flex;
  border: 1px solid grey;
  border-radius: 15px;
  width: 100%;
}
.item-choose {
  cursor: pointer;
  padding: 15px;
  border-radius: 15px;
  align-items: center;
  height: 22px;
  color: #fff;
  font-weight: 400;
  line-height: 1.25rem;
  letter-spacing: 0.0333333333em;
  font-size: 0.75rem;
  flex-grow: 1;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
}
.item-choose-active {
  color: var(--v-primary-base, #1a73e8);
}
</style>

// libs/react/map-core/src/field/input-choose.tsx
import React from 'react';

export interface ChooseItem<T = unknown> {
  value: T;
  text: string;
}

export interface InputChooseProps<T = unknown> {
  label?: string;
  items: ChooseItem<T>[];
  value?: T;
  onChange?: (value: T) => void;
  className?: string;
}

export function InputChoose<T = unknown>({
  label,
  items,
  value,
  onChange,
  className = '',
}: InputChooseProps<T>) {
  const onSetValue = (item: ChooseItem<T>) => {
    onChange?.(item.value);
  };

  return (
    <div className={`form-group ${className}`.trim()}>
      {label && <label>{label}</label>}
      <div className="input-container">
        {items.map((item) => (
          <div
            key={String(item.value)}
            className={`item-choose ${
              item.value === value ? 'item-choose-active' : ''
            }`}
            onClick={(e) => {
              e.stopPropagation();
              onSetValue(item);
            }}
          >
            {item.text}
          </div>
        ))}
      </div>
    </div>
  );
}
