// libs/vue/map-core/src/field/map-range-slider.vue
<template>
  <input
    class="map-range-slider"
    type="range"
    :value="modelValue"
    :min="min"
    :max="max"
    :step="step"
    :disabled="disabled"
    :style="{ backgroundSize }"
    :aria-label="ariaLabel"
    @input="onInput"
  />
</template>
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    modelValue?: number;
    min?: number;
    max?: number;
    step?: number;
    disabled?: boolean;
    ariaLabel?: string;
  }>(),
  {
    modelValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    disabled: false,
    ariaLabel: undefined,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: number];
}>();

const backgroundSize = computed(() => {
  const span = props.max - props.min;
  if (span <= 0) return '0% 100%';
  return `${((props.modelValue - props.min) * 100) / span}% 100%`;
});

function onInput(event: Event) {
  const value = parseFloat((event.target as HTMLInputElement).value);
  emit('update:modelValue', Number.isFinite(value) ? value : props.min);
}
</script>

// libs/react/map-core/src/field/map-range-slider.tsx
import { type ChangeEvent, useMemo } from 'react';

export interface MapRangeSliderProps {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  className?: string;
  'aria-label'?: string;
  onChange?: (value: number) => void;
}

export function MapRangeSlider({
  value = 0,
  min = 0,
  max = 1,
  step = 0.01,
  disabled = false,
  className = '',
  'aria-label': ariaLabel,
  onChange,
}: MapRangeSliderProps) {
  const backgroundSize = useMemo(() => {
    const span = max - min;
    if (span <= 0) return '0% 100%';
    return `${((value - min) * 100) / span}% 100%`;
  }, [value, min, max]);

  return (
    <input
      type="range"
      className={['map-range-slider', className].filter(Boolean).join(' ')}
      min={min}
      max={max}
      step={step}
      value={value}
      disabled={disabled}
      aria-label={ariaLabel}
      style={{ backgroundSize }}
      onChange={(event: ChangeEvent<HTMLInputElement>) => {
        const next = parseFloat(event.target.value);
        onChange?.(Number.isFinite(next) ? next : min);
      }}
    />
  );
}
