// libs/react/map-core/src/modules/WorkerControl/WorkerLogList.tsx
import { formatWorkerLogTime, type WorkerLogEntry } from '@hungpvq/map-core';
import { memo, useLayoutEffect, useRef } from 'react';

export interface WorkerLogListProps {
  logs: WorkerLogEntry[];
  compact?: boolean;
}

function logsSignature(logs: WorkerLogEntry[]) {
  if (!logs.length) return '0';
  const first = logs[0];
  const last = logs[logs.length - 1];
  return `${logs.length}:${first.id}:${last.id}`;
}

/** Newest-on-top log list — stick to top while following; else keep viewport stable. */
export const WorkerLogList = memo(
  function WorkerLogList({ logs, compact }: WorkerLogListProps) {
    const rootRef = useRef<HTMLDivElement>(null);
    const savedScrollTop = useRef(0);
    const savedScrollHeight = useRef(0);
    const stickToLatest = useRef(true);

    const el = rootRef.current;
    if (el) {
      savedScrollTop.current = el.scrollTop;
      savedScrollHeight.current = el.scrollHeight;
      stickToLatest.current = el.scrollTop <= 8;
    }

    useLayoutEffect(() => {
      const node = rootRef.current;
      if (!node) return;
      if (stickToLatest.current) {
        node.scrollTop = 0;
        return;
      }
      const delta = node.scrollHeight - savedScrollHeight.current;
      node.scrollTop = savedScrollTop.current + Math.max(0, delta);
    });

    return (
      <div
        ref={rootRef}
        className={`map-worker-control__log-list${compact ? ' is-compact' : ''}`}
      >
        {logs.map((entry) => (
          <div
            key={entry.id}
            className="map-worker-control__log"
            data-level={entry.level}
          >
            <span className="map-worker-control__log-time">
              {formatWorkerLogTime(entry.at)}
            </span>
            <span className="map-worker-control__log-level">{entry.level}</span>
            <span className="map-worker-control__log-message">
              {entry.message}
            </span>
          </div>
        ))}
      </div>
    );
  },
  (prev, next) =>
    prev.compact === next.compact &&
    logsSignature(prev.logs) === logsSignature(next.logs),
);

// libs/vue/map-core/src/modules/WorkerControl/WorkerLogList.vue
<script setup lang="ts">
import { formatWorkerLogTime, type WorkerLogEntry } from '@hungpvq/map-core';
import { computed, onBeforeUpdate, onUpdated, ref } from 'vue';

const props = defineProps<{
  logs: WorkerLogEntry[];
  compact?: boolean;
}>();

const root = ref<HTMLElement | null>(null);
let savedScrollTop = 0;
let savedScrollHeight = 0;
let stickToLatest = true;

const memoKey = computed(() => {
  const logs = props.logs;
  if (!logs.length) return '0';
  // Newest is index 0 — include it so live appends invalidate v-memo.
  return `${logs.length}:${logs[0].id}:${logs[logs.length - 1].id}`;
});

// Newest-on-top: stay pinned to top while following; otherwise keep the same lines in view.
onBeforeUpdate(() => {
  const el = root.value;
  savedScrollTop = el?.scrollTop ?? 0;
  savedScrollHeight = el?.scrollHeight ?? 0;
  stickToLatest = savedScrollTop <= 8;
});

onUpdated(() => {
  const el = root.value;
  if (!el) return;
  if (stickToLatest) {
    el.scrollTop = 0;
    return;
  }
  const delta = el.scrollHeight - savedScrollHeight;
  el.scrollTop = savedScrollTop + Math.max(0, delta);
});
</script>

<template>
  <div
    ref="root"
    class="map-worker-control__log-list"
    :class="{ 'is-compact': compact }"
    v-memo="[memoKey, compact]"
  >
    <div
      v-for="entry in logs"
      :key="entry.id"
      class="map-worker-control__log"
      :data-level="entry.level"
    >
      <span class="map-worker-control__log-time">{{
        formatWorkerLogTime(entry.at)
      }}</span>
      <span class="map-worker-control__log-level">{{ entry.level }}</span>
      <span class="map-worker-control__log-message">{{ entry.message }}</span>
    </div>
  </div>
</template>
