// libs/react/map-devtools/src/ui/DevtoolsMapFilter.tsx
import { listMapIds, shortMapId } from '@hungpvq/map-debug';
import { InputSelect } from '@hungpvq/react-map-core/fields';
import { useEffect, useMemo, useState } from 'react';
import { setDevtoolFilterMapId } from '../store';
import { useDevtoolState } from '../useDevtoolState';

const ALL = 'all';

export function DevtoolsMapFilter() {
  const { filterMapId } = useDevtoolState();
  const [mapIds, setMapIds] = useState<string[]>([]);

  useEffect(() => {
    const refresh = () => setMapIds(listMapIds());
    refresh();
    const timer = window.setInterval(refresh, 1000);
    return () => window.clearInterval(timer);
  }, []);

  useEffect(() => {
    if (filterMapId !== ALL && !mapIds.includes(filterMapId)) {
      setDevtoolFilterMapId(ALL);
    }
  }, [filterMapId, mapIds]);

  const items = useMemo(
    () => [
      { value: ALL, text: 'All maps' },
      ...mapIds.map((id) => ({ value: id, text: shortMapId(id) })),
    ],
    [mapIds],
  );

  if (mapIds.length <= 1) return null;

  return (
    <div
      className="devtools-map-filter"
      onPointerDown={(e) => e.stopPropagation()}
    >
      <InputSelect
        aria-label="Filter by mapId"
        value={filterMapId}
        items={items}
        onChange={(value) => setDevtoolFilterMapId(String(value ?? ALL))}
      />
    </div>
  );
}

// libs/vue/map-devtools/src/ui/DevtoolsMapFilter.vue
<template>
  <div
    v-if="mapIds.length > 1"
    class="devtools-map-filter"
    @pointerdown.stop
  >
    <InputSelect
      :model-value="filterMapId"
      :items="items"
      aria-label="Filter by mapId"
      @update:model-value="onChange"
    />
  </div>
</template>

<script setup lang="ts">
import { listMapIds, shortMapId } from '@hungpvq/map-debug';
import { InputSelect } from '@hungpvq/vue-map-core/fields';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { setDevtoolFilterMapId, useDevtoolState } from '../store';

const ALL = 'all';

const { filterMapId } = useDevtoolState();
const mapIds = ref<string[]>([]);

const items = computed(() => [
  { value: ALL, text: 'All maps' },
  ...mapIds.value.map((id) => ({ value: id, text: shortMapId(id) })),
]);

function refresh() {
  mapIds.value = listMapIds();
}

function onChange(value: string | number | boolean | null | undefined) {
  setDevtoolFilterMapId(String(value ?? ALL));
}

watch(mapIds, (ids) => {
  if (filterMapId.value !== ALL && !ids.includes(filterMapId.value)) {
    setDevtoolFilterMapId(ALL);
  }
});

let pollTimer: ReturnType<typeof setInterval> | undefined;

onMounted(() => {
  refresh();
  pollTimer = setInterval(refresh, 1000);
});

onUnmounted(() => {
  if (pollTimer != null) {
    clearInterval(pollTimer);
    pollTimer = undefined;
  }
});
</script>
