// libs/react/map-devtools/src/ui/StoreViewer.tsx
import {
  listMapIds,
  shortMapId,
  snapshotGlobalStore,
  snapshotMapScopedStore,
} from '@hungpvq/map-debug';
import { MapControlButton } from '@hungpvq/react-map-core';
import { InputSelect } from '@hungpvq/react-map-core/fields';
import { useEffect, useMemo, useState } from 'react';
import { TreeItem } from './TreeItem';

const ALL = 'all';

function dumpStore(mapId: string): Record<string, unknown> {
  return mapId === ALL
    ? snapshotGlobalStore()
    : snapshotMapScopedStore(mapId);
}

export function StoreViewer() {
  const [selectedMapId, setSelectedMapId] = useState(ALL);
  const [mapIds, setMapIds] = useState<string[]>([]);
  const [storeState, setStoreState] = useState<Record<string, unknown>>({});

  const mapSelectItems = useMemo(
    () => [
      { value: ALL, text: 'All / global' },
      ...mapIds.map((id) => ({ value: id, text: shortMapId(id) })),
    ],
    [mapIds],
  );

  const refresh = () => {
    const ids = listMapIds();
    setMapIds(ids);
    setSelectedMapId((prev) => {
      const next = prev !== ALL && !ids.includes(prev) ? ALL : prev;
      setStoreState(dumpStore(next));
      return next;
    });
  };

  useEffect(() => {
    refresh();
    const timer = window.setInterval(refresh, 1000);
    return () => window.clearInterval(timer);
  }, []);

  return (
    <div className="store-viewer">
      <div className="store-viewer__toolbar">
        {mapSelectItems.length > 1 ? (
          <InputSelect
            aria-label="Filter by mapId"
            value={selectedMapId}
            items={mapSelectItems}
            onChange={(value) => {
              const next = String(value);
              setSelectedMapId(next);
              setStoreState(dumpStore(next));
            }}
          />
        ) : null}
        <MapControlButton variant="text" size="small" onClick={refresh}>
          Refresh
        </MapControlButton>
      </div>
      <div className="store-viewer__body">
        <TreeItem data={storeState} />
      </div>
    </div>
  );
}

// libs/vue/map-devtools/src/ui/StoreViewer.vue
<template>
  <div class="store-viewer">
    <div class="store-viewer__toolbar">
      <InputSelect
        v-if="mapSelectItems.length > 1"
        v-model="selectedMapId"
        :items="mapSelectItems"
        aria-label="Filter by mapId"
      />
      <MapControlButton variant="text" size="small" @click="refresh">
        Refresh
      </MapControlButton>
    </div>
    <div class="store-viewer__body">
      <TreeItem :data="storeState" />
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  listMapIds,
  shortMapId,
  snapshotGlobalStore,
  snapshotMapScopedStore,
} from '@hungpvq/map-debug';
import { MapControlButton } from '@hungpvq/vue-map-core';
import { InputSelect } from '@hungpvq/vue-map-core/fields';
import { computed, onMounted, onUnmounted, ref, shallowRef, watch } from 'vue';
import TreeItem from './TreeItem.vue';

const ALL = 'all';

const selectedMapId = ref(ALL);
const mapIds = ref<string[]>([]);
const storeState = shallowRef<Record<string, unknown>>({});

const mapSelectItems = computed(() => [
  { value: ALL, text: 'All / global' },
  ...mapIds.value.map((id) => ({ value: id, text: shortMapId(id) })),
]);

const refresh = () => {
  mapIds.value = listMapIds();
  if (
    selectedMapId.value !== ALL &&
    !mapIds.value.includes(selectedMapId.value)
  ) {
    selectedMapId.value = ALL;
  }
  storeState.value =
    selectedMapId.value === ALL
      ? snapshotGlobalStore()
      : snapshotMapScopedStore(selectedMapId.value);
};

watch(selectedMapId, () => {
  storeState.value =
    selectedMapId.value === ALL
      ? snapshotGlobalStore()
      : snapshotMapScopedStore(selectedMapId.value);
});

let pollTimer: ReturnType<typeof setInterval> | undefined;

onMounted(() => {
  refresh();
  pollTimer = setInterval(refresh, 1000);
});

onUnmounted(() => {
  if (pollTimer != null) {
    clearInterval(pollTimer);
    pollTimer = undefined;
  }
});
</script>
