// apps/react/demo-map/src/views/legend.tsx
import './legend.css';

import type { MapSimple } from '@hungpvq/map-core';
import { LayerSimpleMapboxBuild } from '@hungpvq/map-dataset/style';
import {
  BaseMapControl,
  FullScreenControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  Map,
  MouseCoordinatesControl,
  SettingControl,
  useLayerLegend,
  ZoomControl,
} from '@hungpvq/react-map-core';
import { DevtoolsControl } from '@hungpvq/react-map-devtools';
import type { LayerSpecification } from 'maplibre-gl';
import { type ReactNode, useCallback, useState } from 'react';

import { DemoHelpPanel } from '../components/DemoHelpPanel';
import { DemoLanguageControl } from '../components/DemoLanguageControl';
import { MapPageShell } from '../components/MapPageShell';
import { AsideControl } from '../layout/AsideControl';

export function LegendPage() {
  const { getLayerLegendNode } = useLayerLegend();
  const [legends, setLegends] = useState<ReactNode[]>([]);

  const onMapLoaded = useCallback(
    (map: MapSimple) => {
      const layers: LayerSpecification[] = [
        {
          id: 'my-line-layer',
          type: 'line',
          source: 'my-line-source',
          layout: {},
          paint: { 'line-pattern': 'aerialway_11' },
        },
        {
          id: 'my-line-dash-layer',
          type: 'line',
          source: 'my-line-source',
          layout: {},
          paint: {
            'line-color': 'red',
            'line-dasharray': [2, 2],
          },
        },
        {
          id: 'my-fill-layer',
          type: 'fill',
          source: 'my-fill-source',
          layout: {},
          paint: {
            'fill-pattern': 'aerialway_11',
            'fill-color': 'red',
          },
        },
        {
          id: 'points-symbol',
          type: 'symbol',
          source: 'points',
          layout: {
            'icon-image': 'aerialway_11',
            'icon-size': 1.5,
            'text-field': ['get', 'title'],
            'text-offset': [0, 1.2],
            'text-anchor': 'top',
          },
          paint: { 'text-color': '#333' },
        },
        {
          id: 'text-labels',
          type: 'symbol',
          source: 'labels',
          layout: {
            'text-field': ['get', 'name'],
            'text-size': 14,
            'text-offset': [0, 0.5],
            'text-anchor': 'top',
          },
          paint: {
            'text-color': '#ff0000',
            'text-halo-color': '#ffffff',
            'text-halo-width': 2,
          },
        },
        new LayerSimpleMapboxBuild()
          .setStyleType('point')
          .build() as LayerSpecification,
        new LayerSimpleMapboxBuild()
          .setStyleType('line')
          .build() as LayerSpecification,
        new LayerSimpleMapboxBuild()
          .setStyleType('area')
          .build() as LayerSpecification,
      ];
      setLegends(layers.map((layer) => getLayerLegendNode(map, layer)));
    },
    [getLayerLegendNode],
  );

  return (
    <MapPageShell>
      <Map onMapLoaded={onMapLoaded}>
        <DevtoolsControl position="bottom-right" />
        <DemoLanguageControl />
        <AsideControl position="top-left" />
        <GotoControl position="top-right" />
        <GlobeControl />
        <SettingControl />
        <FullScreenControl />
        <ZoomControl />
        <HomeControl />
        <MouseCoordinatesControl />
        <BaseMapControl position="bottom-left" />
        <DemoHelpPanel />
      </Map>
      <div className="legend-control">
        {legends.map((node, index) => (
          <div key={index}>{node}</div>
        ))}
      </div>
    </MapPageShell>
  );
}

// apps/vue/demo-map/src/views/legend.vue
﻿<template lang="">
  <Map ref="mapRef" @mapLoaded="onMapLoaded">
    <DevtoolsControl position="bottom-right" />
    <DemoLanguageControl />
    <AsideControl position="top-left" />
    <GotoControl position="top-right" />
    <GlobeControl />
    <SettingControl />
    <FullScreenControl />
    <ZoomControl />
    <HomeControl />
    <MouseCoordinatesControl />
    <BaseMapControl position="bottom-left" />
    <div class="legend-control">
      <component
        :is="legendVNode"
        v-for="(legendVNode, index) in legends"
        :key="index"
      />
    </div>
    <DemoHelpPanel />
  </Map>
</template>
<script setup lang="ts">
import { MapSimple } from '@hungpvq/map-core';
import { LayerSimpleMapboxBuild } from '@hungpvq/map-dataset/style';
import {
  BaseMapControl,
  FullScreenControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  Map,
  MouseCoordinatesControl,
  SettingControl,
  useLayerLegend,
  ZoomControl,
} from '@hungpvq/vue-map-core';
import { DevtoolsControl } from '@hungpvq/vue-map-devtools';
import { shallowRef } from 'vue';

import DemoHelpPanel from '../components/DemoHelpPanel.vue';
import DemoLanguageControl from '../components/DemoLanguageControl.vue';
import AsideControl from '../layout/aside-control.vue';
const { getLayerLegendVNode } = useLayerLegend();
const legends = shallowRef<any[]>([]);
function onMapLoaded(map: MapSimple) {
  const layers: any[] = [
    {
      id: 'my-line-layer',
      type: 'line',
      source: 'my-line-source',
      layout: {},
      paint: {
        'line-pattern': 'aerialway_11',
      },
    },
    {
      id: 'my-line-dash-layer',
      type: 'line',
      source: 'my-line-source',
      layout: {},
      paint: {
        'line-color': 'red',
        'line-dasharray': [2, 2],
      },
    },
    {
      id: 'my-fill-layer',
      type: 'fill',
      source: 'my-fill-source',
      layout: {},
      paint: {
        'fill-pattern': 'aerialway_11',
        'fill-color': 'red',
      },
    },
    {
      id: 'points-symbol',
      type: 'symbol',
      source: 'points',
      layout: {
        'icon-image': 'aerialway_11', // Biá»ƒu tÆ°á»£ng máº·c Ä‘á»‹nh cá»§a Mapbox
        'icon-size': 1.5,
        'text-field': ['get', 'title'],
        'text-offset': [0, 1.2],
        'text-anchor': 'top',
      },
      paint: {
        'text-color': '#333',
      },
    },
    {
      id: 'text-labels',
      type: 'symbol',
      source: 'labels',
      layout: {
        'text-field': ['get', 'name'], // Láº¥y text tá»« thuá»™c tÃ­nh 'name'
        'text-font': ['Open Sans Bold', 'Arial Unicode MS Bold'],
        'text-size': 14,
        'text-offset': [0, 0.5],
        'text-anchor': 'top',
      },
      paint: {
        'text-color': '#ff0000',
        'text-halo-color': '#ffffff',
        'text-halo-width': 2,
      },
    },
    new LayerSimpleMapboxBuild().setStyleType('point').build(),
    new LayerSimpleMapboxBuild().setStyleType('line').build(),
    new LayerSimpleMapboxBuild().setStyleType('area').build(),
  ];
  legends.value = layers.map((layer) => getLayerLegendVNode(map, layer));
}
</script>
<style>
.legend-control {
  position: fixed;
  top: 10px;
  left: 10px;
  width: 400px;
  z-index: 999;
  background: white;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.legend-item {
  display: flex;
  align-items: center;
}
.legend-item-container {
  display: flex;
  align-items: center;
}
</style>
