// apps/react/demo-map/src/views/toolbar.tsx
import {
  BaseMapControl,
  CrsControl,
  EventManagementControl,
  FullScreenControl,
  GeoLocateControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  LegendControl,
  Map,
  MeasurementControl,
  MouseCoordinatesControl,
  PrintAdvancedControl,
  PrintControl,
  SettingControl,
  ToolbarControl,
  ZoomControl,
} from '@hungpvq/react-map-core';
import { DevtoolsControl } from '@hungpvq/react-map-devtools';

import { DemoHelpPanel } from '../components/DemoHelpPanel';
import { DemoLanguageControl } from '../components/DemoLanguageControl';
import { MapPageShell } from '../components/MapPageShell';
import { AsideControl } from '../layout/AsideControl';

export function ToolbarPage() {
  return (
    <MapPageShell>
      <Map>
        <DevtoolsControl position="bottom-right" />
        <DemoLanguageControl />
        <AsideControl position="top-left" />
        <ToolbarControl position="top-right" />
        <GotoControl
          position="top-right"
          controlLayout="toolbar"
        />
        <MeasurementControl position="top-left" />
        <CrsControl />
        <GlobeControl />
        <SettingControl />
        <FullScreenControl />
        <EventManagementControl />
        <ZoomControl
          controlLayout="toolbar"
          controlOrder={99}
        />
        <HomeControl controlLayout="toolbar" />
        <MouseCoordinatesControl />
        <BaseMapControl position="bottom-left" />
        <GeoLocateControl position="top-right" />
        <LegendControl
          position="top-left"
          controlLayout="toolbar"
          controlOrder={5}
        />
        <PrintControl
          position="top-left"
          controlLayout="toolbar"
        />
        <PrintAdvancedControl
          position="top-left"
          controlLayout="toolbar"
        />
        <DemoHelpPanel />
      </Map>
    </MapPageShell>
  );
}

// apps/vue/demo-map/src/views/toolbar.vue
﻿<template>
  <Map ref="mapRef">
    <DevtoolsControl position="bottom-right" />
    <DemoLanguageControl />
    <AsideControl position="top-left" />
    <ToolbarControl position="top-right" />
    <GotoControl
      position="top-right"
      control-layout="toolbar"
    />
    <MeasurementControl position="top-left" />
    <CrsControl />
    <GlobeControl />
    <SettingControl />
    <FullScreenControl />
    <EventManagementControl />
    <ZoomControl
      control-layout="toolbar"
      control-order="99"
    />
    <HomeControl control-layout="toolbar" />
    <MouseCoordinatesControl />
    <BaseMapControl position="bottom-left" />
    <GeoLocateControl position="top-right" />
    <LegendControl
      position="top-left"
      control-layout="toolbar"
      control-order="5"
    />
    <PrintControl
      position="top-left"
      control-layout="toolbar"
    />
    <PrintAdvancedControl
      position="top-left"
      control-layout="toolbar"
    />
    <DemoHelpPanel />
  </Map>
</template>
<script setup lang="ts">
import { BaseMapControl } from '@hungpvq/vue-map-core';
import {
  CrsControl,
  EventManagementControl,
  FullScreenControl,
  GeoLocateControl,
  GlobeControl,
  GotoControl,
  HomeControl,
  Map,
  MouseCoordinatesControl,
  SettingControl,
  ToolbarControl,
  ZoomControl,
} from '@hungpvq/vue-map-core';
import { LegendControl } from '@hungpvq/vue-map-core';
import { MeasurementControl } from '@hungpvq/vue-map-core';
import { PrintAdvancedControl, PrintControl } from '@hungpvq/vue-map-core';
import { DevtoolsControl } from '@hungpvq/vue-map-devtools';

import DemoHelpPanel from '../components/DemoHelpPanel.vue';
import DemoLanguageControl from '../components/DemoLanguageControl.vue';
import AsideControl from '../layout/aside-control.vue';
</script>
