// libs/react/map-dataset/src/modules/LayerControl/layer-context-menu-list.tsx
import type { IListViewUI } from '@hungpvq/map-dataset';
import type { ListViewGroupOption, MenuAction } from '@hungpvq/map-dataset/menu';
import { createMenuConditionContext, getMenuItemLocation, isMenuItemCustomComponent, isMenuItemDisabled, isMenuItemHidden } from '@hungpvq/map-dataset/menu';
import { RegistryItem } from '@hungpvq/react-map-core';
import { mdiCircleSmall } from '@mdi/js';
import Icon from '@mdi/react';
import { useMenuConditionContext } from '../../extra/menu/condition-context';

export function LayerContextMenuList({
  items,
  view,
  mapId,
  getGroups,
  onSelect,
  onClose,
}: {
  items: MenuAction<IListViewUI>[];
  view?: IListViewUI;
  mapId?: string;
  getGroups?: () => ListViewGroupOption[];
  onSelect: (payload: {
    action: MenuAction<IListViewUI>;
    event: React.MouseEvent;
  }) => void;
  onClose?: () => void;
}) {
  const injectedMenuContext = useMenuConditionContext();
  const conditionCtx = view
    ? createMenuConditionContext(view, {
        mapId,
        context: [injectedMenuContext],
      })
    : undefined;
  const visibleItems = conditionCtx
    ? items.filter((item) => !isMenuItemHidden(item, conditionCtx))
    : items;

  return (
    <ul className="context-menu layer-context-menu">
      {visibleItems.map((option, index) => {
        const key = option.id || String(index);
        const disabled = conditionCtx
          ? isMenuItemDisabled(option, conditionCtx)
          : false;
        if (isMenuItemCustomComponent(option)) {
          return (
            <RegistryItem
              key={key}
              componentKey={option.componentMenuKey}
              item={option}
              data={view}
              mapId={mapId}
              getGroups={getGroups}
              disabled={disabled}
              location={getMenuItemLocation(option)}
              onClose={onClose}
            />
          );
        }
        return (
          <li
            key={key}
            className={[
              'layer-context-menu__item',
              option.type === 'divider' ? 'layer-context-menu__divider' : '',
              disabled ? 'is-disabled' : '',
              option.class || '',
            ]
              .filter(Boolean)
              .join(' ')}
            onClick={(event) => {
              event.stopPropagation();
              if (option.type === 'divider' || disabled) return;
              onSelect({ action: option, event });
            }}
          >
            {option.type === 'divider' ? (
              <div className="layer-context-menu__divider-line" />
            ) : (
              <>
                <div className="layer-context-menu__item-icon">
                  <Icon
                    path={('icon' in option && option.icon) || mdiCircleSmall}
                    size="16px"
                  />
                </div>
                <span>{('name' in option && option.name) || ''}</span>
              </>
            )}
          </li>
        );
      })}
    </ul>
  );
}

// libs/vue/map-dataset/src/modules/LayerControl/part/item/layer-context-menu-list.vue
<template>
  <ul class="context-menu layer-context-menu">
    <template v-for="(option, index) in visibleItems" :key="option.id || index">
      <RegistryItem
        v-if="isMenuItemCustomComponent(option)"
        :componentKey="option.componentMenuKey"
        :item="option"
        :data="view"
        :mapId="mapId"
        :getGroups="getGroups"
        :disabled="isDisabled(option)"
        :location="getMenuItemLocation(option)"
        @close="emit('close')"
      />
      <li
        v-else
        class="layer-context-menu__item"
        :class="[
          option.class,
          option.type === 'divider' ? 'layer-context-menu__divider' : '',
          isDisabled(option) ? 'is-disabled' : '',
        ]"
        @click.stop="onClick(option, $event)"
      >
        <template v-if="option.type === 'divider'">
          <div class="layer-context-menu__divider-line"></div>
        </template>
        <template v-else>
          <div class="layer-context-menu__item-icon">
            <SvgIcon
              size="16"
              type="mdi"
              :path="('icon' in option && option.icon) || mdiCircleSmall"
            />
          </div>
          <span>{{ 'name' in option ? option.name : '' }}</span>
        </template>
      </li>
    </template>
  </ul>
</template>
<script setup lang="ts">
import type { IListViewUI } from '@hungpvq/map-dataset';
import type { ListViewGroupOption, MenuAction } from '@hungpvq/map-dataset/menu';
import { createMenuConditionContext, getMenuItemLocation, isMenuItemCustomComponent, isMenuItemDisabled, isMenuItemHidden } from '@hungpvq/map-dataset/menu';
import { RegistryItem } from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCircleSmall } from '@mdi/js';
import { computed } from 'vue';
import { useMenuConditionSource } from '../../../../extra/menu/condition-context';

defineOptions({ name: 'LayerContextMenuList' });

const props = defineProps<{
  items: MenuAction<IListViewUI>[];
  view?: IListViewUI;
  mapId?: string;
  getGroups?: () => ListViewGroupOption[];
}>();

const emit = defineEmits<{
  select: [payload: { action: MenuAction<IListViewUI>; event: MouseEvent }];
  close: [];
}>();

const injectedMenuContext = useMenuConditionSource();
const conditionCtx = computed(() =>
  props.view
    ? createMenuConditionContext(props.view, {
        mapId: props.mapId,
        context: [injectedMenuContext],
      })
    : undefined,
);

const visibleItems = computed(() => {
  if (!conditionCtx.value) return props.items;
  return props.items.filter((item) => !isMenuItemHidden(item, conditionCtx.value!));
});

function isDisabled(option: MenuAction<IListViewUI>) {
  if (!conditionCtx.value) return false;
  return isMenuItemDisabled(option, conditionCtx.value);
}

function onClick(option: MenuAction<IListViewUI>, event: MouseEvent) {
  if (option.type === 'divider') return;
  if (isDisabled(option)) return;
  emit('select', { action: option, event });
}
</script>
