// libs/vue/map-dataset/src/modules/IdentifyControl/IdentifyResultControl.vue
<script lang="ts">
export default {
  name: 'IdentifyResultControl',
};
</script>

<script setup lang="ts">
import type { WithMapPropType } from '@hungpvq/map-core';
import { createMapDisplayCoordinateFormatter } from '@hungpvq/map-core/crs';
import {
  findSiblingOrNearestLeaf,
  isListView,
  type IListViewUI,
} from '@hungpvq/map-dataset';
import type { IIdentifyView } from '@hungpvq/map-dataset/identify';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import {
  createMenuConditionContext,
  getResolvedMenus,
  handleMenuAction,
  isMenuItemHidden,
  MENU_CONTROL_ID,
} from '@hungpvq/map-dataset/menu';
import {
  IDENTIFY_ALL_LAYERS_VALUE,
  IDENTIFY_CONTROL,
  IDENTIFY_CONTROL_LOCALE,
  IDENTIFY_RESULT_CONTROL,
  type IdentifyResultGrouped,
  type IdentifyResultLayerItem,
  type IdentifyResultUpdatePayload,
} from '@hungpvq/map-dataset/identify';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import {
  defaultMapProps,
  MapControlButton,
  ModuleContainer,
  UniversalRegistry,
  useLang,
  useMap,
  useRegisterMapControl,
} from '@hungpvq/vue-map-core';
import { InputSelect } from '@hungpvq/vue-map-core/fields';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCursorPointer, mdiSelect } from '@mdi/js';
import type { MapMouseEvent } from 'maplibre-gl';
import { computed, reactive, ref } from 'vue';
import { provideMenuConditionContext } from '../../extra/menu/condition-context';
import DatasetMenus from '../../extra/menu/dataset-menus.vue';
import { useMapDataset } from '../../store/dataset-api';

const path = {
  boxSelect: mdiSelect,
  mapClick: mdiCursorPointer,
};

const props = withDefaults(defineProps<WithMapPropType>(), {
  ...defaultMapProps,
});

provideMenuConditionContext(() => ({
  control: MENU_CONTROL_ID.identify,
}));

const { mapId, moduleContainerProps } = useMap(props);
const { trans, registerLocale } = useLang(mapId.value);
const formatCoordinate = createMapDisplayCoordinateFormatter();
const { getAllComponentsByType, getDatasetIds } = useMapDataset(mapId.value);
registerLocale('en', IDENTIFY_CONTROL_LOCALE);

const show = ref(false);
const loading = ref(false);
const errorMessage = ref<string | null>(null);
const items = ref<IdentifyResultGrouped[]>([]);
const origin = reactive({ latitude: 0, longitude: 0 });
const layerItems = ref<IdentifyResultLayerItem[]>([]);
const selectedLayerId = ref(IDENTIFY_ALL_LAYERS_VALUE);
const isEventClickActive = ref(false);
const isEventClickBox = ref(false);
const focusedChildKey = ref<string | null>(null);

const flatChildren = computed(() => {
  const out: Array<{
    key: string;
    child: IdentifyResultGrouped['items'][number];
  }> = [];
  for (const group of items.value) {
    for (const child of group.items) {
      out.push({ key: `${group.id}:${child.id}`, child });
    }
  }
  return out;
});

const currentPoint = computed(() => {
  const point = formatCoordinate(origin);
  return `${point.longitude}, ${point.latitude}`;
});
const hasSelectedPoint = computed(
  () => origin.latitude !== 0 || origin.longitude !== 0,
);

const titleLayer = computed(() => {
  void getDatasetIds().value;
  if (selectedLayerId.value === IDENTIFY_ALL_LAYERS_VALUE) return undefined;
  const identifies =
    getAllComponentsByType<IIdentifyView>('identify') || [];
  const identify = identifies.find((view) => view.id === selectedLayerId.value);
  if (!identify) return undefined;
  return (
    findSiblingOrNearestLeaf<IListViewUI>(identify, isListView) ?? identify
  );
});

const titleMenus = computed(() =>
  titleLayer.value ? getResolvedMenus(titleLayer.value, 'layer') : [],
);

function setShow(value: boolean) {
  show.value = value;
}

function applyUpdate(payload?: IdentifyResultUpdatePayload) {
  if (!payload) return;
  if (payload.show != null) show.value = payload.show;
  if (payload.loading != null) loading.value = payload.loading;
  if (payload.error !== undefined) errorMessage.value = payload.error;
  if (payload.items !== undefined) {
    items.value = payload.items;
    if (!focusedChildKey.value && payload.items.length) {
      const first = payload.items[0]?.items[0];
      if (first) focusedChildKey.value = `${payload.items[0].id}:${first.id}`;
    }
  }
  if (payload.origin) {
    origin.latitude = payload.origin.latitude;
    origin.longitude = payload.origin.longitude;
  }
  if (payload.layerItems) layerItems.value = payload.layerItems;
  if (payload.selectedLayerId != null) {
    selectedLayerId.value = payload.selectedLayerId;
  }
  if (payload.isEventClickActive != null) {
    isEventClickActive.value = payload.isEventClickActive;
  }
  if (payload.isEventClickBox != null) {
    isEventClickBox.value = payload.isEventClickBox;
  }
}

const { panelBind } = useRegisterMapControl(mapId, {
  id: IDENTIFY_RESULT_CONTROL.id,
  panelKind: 'popup',
  title: () => trans.value('map.identify.title'),
  buttonPosition: () => props.position,
  show,
  setShow,
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
  }),
  actions: [
    {
      type: IDENTIFY_RESULT_CONTROL.actionUpdate,
      run: (event) => {
        applyUpdate(event as IdentifyResultUpdatePayload | undefined);
      },
    },
  ],
});

function runIdentifyAction(type: string, event?: unknown) {
  UniversalRegistry.runControlAction(
    mapId.value,
    IDENTIFY_CONTROL.id,
    type,
    event,
  );
}

function onClose() {
  show.value = false;
  runIdentifyAction(IDENTIFY_CONTROL.actionClose);
}

function onUseMapClick() {
  runIdentifyAction(IDENTIFY_CONTROL.actionUseMapClick);
}

function onUseBoxSelect() {
  runIdentifyAction(IDENTIFY_CONTROL.actionUseBoxSelect);
}

function onLayerFilterChange(value: string) {
  selectedLayerId.value = value;
  runIdentifyAction(IDENTIFY_CONTROL.actionSetLayerFilter, {
    identifyId: value === IDENTIFY_ALL_LAYERS_VALUE ? undefined : value,
  });
}

function onMenuAction(
  child: {
    id: string | number;
    data: unknown;
    identify: IIdentifyView;
  },
  menu: MenuAction,
  event?: MapMouseEvent | MouseEvent,
) {
  handleMenuAction(menu, {
    event,
    layer: child.identify,
    mapId: mapId.value,
    value: child.data,
    context: { control: MENU_CONTROL_ID.identify },
  });
}

function getItemMenus(identify: IIdentifyView) {
  const ctx = createMenuConditionContext(identify, { mapId: mapId.value });
  return getResolvedMenus(identify, 'item').filter(
    (menu) => !isMenuItemHidden(menu, ctx),
  );
}

function onResultKeydown(event: KeyboardEvent) {
  if (!flatChildren.value.length) return;
  const keys = flatChildren.value.map((x) => x.key);
  const index = focusedChildKey.value
    ? keys.indexOf(focusedChildKey.value)
    : -1;
  if (event.key === 'ArrowDown') {
    event.preventDefault();
    const next = keys[Math.min(keys.length - 1, Math.max(0, index) + 1)];
    focusedChildKey.value = next;
  } else if (event.key === 'ArrowUp') {
    event.preventDefault();
    const next = keys[Math.max(0, (index < 0 ? 0 : index) - 1)];
    focusedChildKey.value = next;
  } else if (event.key === 'Enter' && focusedChildKey.value) {
    event.preventDefault();
    const hit = flatChildren.value.find((x) => x.key === focusedChildKey.value);
    if (!hit) return;
    const menus = getItemMenus(hit.child.identify);
    if (menus[0]) onMenuAction(hit.child, menus[0]);
  }
}
</script>

<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="p">
      <DraggableItemPopup
        v-if="show"
        v-model:show="show"
        v-bind="{ ...p, ...panelBind }"
        :width="400"
        :height="300"
        @close="onClose"
        :title="trans('map.identify.title')"
      >
        <template v-if="titleLayer" #after-title>
          <DatasetMenus
            :menus="titleMenus"
            :data="titleLayer"
            :mapId="mapId"
            :locations="['title']"
          />
        </template>
        <template #extra-btn>
          <MapControlButton
            @click.stop="onUseMapClick"
            :active="isEventClickActive"
            :disabled="isEventClickActive"
            :title="trans('map.identify.map_click')"
            variant="plain"
          >
            <SvgIcon size="16" type="mdi" :path="path.mapClick" />
          </MapControlButton>
          <MapControlButton
            @click.stop="onUseBoxSelect"
            :active="isEventClickBox"
            :disabled="isEventClickBox"
            :title="trans('map.identify.box_select')"
            variant="plain"
          >
            <SvgIcon size="16" type="mdi" :path="path.boxSelect" />
          </MapControlButton>
        </template>
        <div class="identify-control-container">
          <div class="identify-control-header">
            <div class="identify-control-header__row">
              <b>{{ trans('map.identify.point') }}:</b>
              <span>{{ currentPoint }}</span>
            </div>
            <div
              v-if="layerItems.length > 0"
              class="identify-control-header__layer"
            >
              <InputSelect
                :model-value="selectedLayerId"
                :label="trans('map.identify.layer')"
                :items="layerItems"
                item-value="value"
                item-text="text"
                @update:model-value="onLayerFilterChange(String($event))"
              />
            </div>
          </div>
          <hr class="identify-control-separator" aria-hidden="true" />
          <div
            class="identify-control-body"
            tabindex="0"
            role="region"
            :aria-label="trans('map.identify.title')"
            aria-live="polite"
            @keydown="onResultKeydown"
          >
            <div
              v-if="loading"
              class="identify-control-state"
              role="status"
              aria-live="polite"
            >
              <div class="identify-control-state__content">
                <div
                  class="identify-control-state__loading"
                  aria-hidden="true"
                ></div>
                <span>{{ trans('map.identify.loading') }}</span>
              </div>
            </div>
            <div
              v-else-if="errorMessage"
              class="identify-control-state"
              role="alert"
            >
              <div class="identify-control-state__content">
                <span>{{ errorMessage || trans('map.identify.error') }}</span>
              </div>
            </div>
            <div
              v-else-if="items.length === 0 && !hasSelectedPoint"
              class="identify-control-state"
              role="status"
            >
              <div class="identify-control-state__content">
                <span>{{ trans('map.identify.no_selection') }}</span>
              </div>
            </div>
            <div
              v-else-if="items.length === 0"
              class="identify-control-state"
              role="status"
            >
              <div class="identify-control-state__content">
                <span>{{
                  selectedLayerId !== IDENTIFY_ALL_LAYERS_VALUE
                    ? trans('map.identify.no_data_filtered')
                    : trans('map.identify.no_data')
                }}</span>
              </div>
            </div>
            <div v-else class="identify-control-results" role="status">
              <div
                v-for="item in items"
                :key="item.id"
                class="identify-control-list-item"
              >
                <div class="identify-control-list-item__container">
                  <div
                    class="identify-control-list-item__header"
                    :title="item.name"
                  >
                    {{ item.name || '---' }}
                  </div>
                  <div class="identify-control-list-item__child-container">
                    <div
                      class="identify-control-child-item"
                      v-for="child in item.items"
                      :key="child.id"
                      :title="child.name"
                      role="button"
                      tabindex="0"
                      :class="{
                        'is-focused':
                          focusedChildKey === `${item.id}:${child.id}`,
                      }"
                      @click="focusedChildKey = `${item.id}:${child.id}`"
                      @keydown="
                        ($event) => {
                          if ($event.key !== 'Enter' && $event.key !== ' ')
                            return;
                          $event.preventDefault();
                          focusedChildKey = `${item.id}:${child.id}`;
                        }
                      "
                    >
                      <span class="identify-control-child-item__name">
                        {{ child.name }}
                      </span>
                      <div class="identify-control-child-item__spacer"></div>
                      <div
                        class="identify-control-child-item__action"
                        @click.stop
                      >
                        <DatasetMenus
                          :menus="getItemMenus(child.identify)"
                          :data="child.identify"
                          :mapId="mapId"
                          :value="child.data"
                          :locations="['extra', 'menu']"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
  </ModuleContainer>
</template>

// libs/react/map-dataset/src/modules/IdentifyControl/IdentifyResultControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { createMapDisplayCoordinateFormatter } from '@hungpvq/map-core/crs';
import {
  findSiblingOrNearestLeaf,
  isListView,
  type IListViewUI,
} from '@hungpvq/map-dataset';
import type { IIdentifyView } from '@hungpvq/map-dataset/identify';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import {
  createMenuConditionContext,
  getResolvedMenus,
  handleMenuAction,
  isMenuItemHidden,
  MENU_CONTROL_ID,
} from '@hungpvq/map-dataset/menu';
import {
  IDENTIFY_ALL_LAYERS_VALUE,
  IDENTIFY_CONTROL,
  IDENTIFY_CONTROL_LOCALE,
  IDENTIFY_RESULT_CONTROL,
  type IdentifyResultGrouped,
  type IdentifyResultLayerItem,
  type IdentifyResultUpdatePayload,
} from '@hungpvq/map-dataset/identify';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import {
  defaultMapProps,
  MapControlButton,
  ModuleContainer,
  UniversalRegistry,
  useLang,
  useMap,
  useRegisterMapControl,
  useShow,
} from '@hungpvq/react-map-core';
import { InputSelect } from '@hungpvq/react-map-core/fields';
import { mdiCursorPointer, mdiSelect } from '@mdi/js';
import Icon from '@mdi/react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { MenuConditionProvider } from '../../extra/menu/condition-context';
import { DatasetMenus } from '../../extra/menu/dataset-menus';
import { useMapDataset } from '../../store/dataset-api';

const ICON_SIZE = 16 / 24;
function runIdentifyAction(mapId: string, type: string, event?: unknown) {
  UniversalRegistry.runControlAction(mapId, IDENTIFY_CONTROL.id, type, event);
}

export function IdentifyResultControl(props: WithMapPropType) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps } = useMap({
    ...merged,
    controlId: IDENTIFY_RESULT_CONTROL.id,
  });
  const { trans, registerLocale } = useLang(mapId);
  const formatCoordinate = useMemo(
    () => createMapDisplayCoordinateFormatter(),
    [],
  );
  const { getAllComponentsByType, datasetVersion } = useMapDataset(mapId);
  const [show, toggleShow] = useShow(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [items, setItems] = useState<IdentifyResultGrouped[]>([]);
  const [origin, setOrigin] = useState({ latitude: 0, longitude: 0 });
  const [layerItems, setLayerItems] = useState<IdentifyResultLayerItem[]>([]);
  const [selectedLayerId, setSelectedLayerId] = useState(
    IDENTIFY_ALL_LAYERS_VALUE,
  );
  const [isEventClickActive, setIsEventClickActive] = useState(false);
  const [isEventClickBox, setIsEventClickBox] = useState(false);
  const [focusedChildKey, setFocusedChildKey] = useState<string | null>(null);

  useEffect(() => {
    registerLocale('en', IDENTIFY_CONTROL_LOCALE);
  }, [registerLocale]);

  const flatChildren = useMemo(() => {
    const out: Array<{
      key: string;
      child: IdentifyResultGrouped['items'][number];
    }> = [];
    for (const group of items) {
      for (const child of group.items) {
        out.push({ key: `${group.id}:${child.id}`, child });
      }
    }
    return out;
  }, [items]);

  const applyUpdate = useCallback(
    (payload?: IdentifyResultUpdatePayload) => {
      if (!payload) return;
      if (payload.show != null) toggleShow(payload.show);
      if (payload.loading != null) setLoading(payload.loading);
      if (payload.error !== undefined) setErrorMessage(payload.error);
      if (payload.items !== undefined) {
        setItems(payload.items);
        setFocusedChildKey((prev) => {
          if (prev) return prev;
          const first = payload.items?.[0]?.items[0];
          if (first && payload.items?.[0]) {
            return `${payload.items[0].id}:${first.id}`;
          }
          return prev;
        });
      }
      if (payload.origin) setOrigin(payload.origin);
      if (payload.layerItems) setLayerItems(payload.layerItems);
      if (payload.selectedLayerId != null) {
        setSelectedLayerId(payload.selectedLayerId);
      }
      if (payload.isEventClickActive != null) {
        setIsEventClickActive(payload.isEventClickActive);
      }
      if (payload.isEventClickBox != null) {
        setIsEventClickBox(payload.isEventClickBox);
      }
    },
    [toggleShow],
  );

  const { panelBind } = useRegisterMapControl(mapId, {
    id: IDENTIFY_RESULT_CONTROL.id,
    panelKind: 'popup',
    title: trans('map.identify.title'),
    buttonPosition: merged.position,
    show,
    setShow: toggleShow,
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
    }),
    actions: [
      {
        type: IDENTIFY_RESULT_CONTROL.actionUpdate,
        run: (event) =>
          applyUpdate(event as IdentifyResultUpdatePayload | undefined),
      },
    ],
  });

  const currentPoint = useMemo(() => {
    const point = formatCoordinate(origin);
    return `${point.longitude}, ${point.latitude}`;
  }, [origin, formatCoordinate]);

  const hasSelectedPoint = origin.latitude !== 0 || origin.longitude !== 0;

  const titleLayer = useMemo(() => {
    void datasetVersion;
    if (selectedLayerId === IDENTIFY_ALL_LAYERS_VALUE) return undefined;
    const identifies = getAllComponentsByType<IIdentifyView>('identify') || [];
    const identify = identifies.find((view) => view.id === selectedLayerId);
    if (!identify) return undefined;
    return (
      findSiblingOrNearestLeaf<IListViewUI>(identify, isListView) ?? identify
    );
  }, [selectedLayerId, datasetVersion, getAllComponentsByType]);

  const titleMenus = useMemo(
    () => (titleLayer ? getResolvedMenus(titleLayer, 'layer') : []),
    [titleLayer],
  );

  function onClose() {
    toggleShow(false);
    runIdentifyAction(mapId, IDENTIFY_CONTROL.actionClose);
  }

  function onMenuAction(
    child: {
      id: string | number;
      data: unknown;
      identify: IIdentifyView;
    },
    menu: MenuAction,
    event?: React.MouseEvent | React.KeyboardEvent,
  ) {
    const nativeEvent =
      event && 'nativeEvent' in event ? event.nativeEvent : event;

    handleMenuAction(menu, {
      event: nativeEvent,
      layer: child.identify,
      mapId,
      value: child.data,
    });
  }

  function getItemMenus(identify: IIdentifyView) {
    const ctx = createMenuConditionContext(identify, { mapId });
    return getResolvedMenus(identify, 'item').filter(
      (menu) => !isMenuItemHidden(menu, ctx),
    );
  }

  function onResultKeydown(event: React.KeyboardEvent) {
    if (!flatChildren.length) return;
    const keys = flatChildren.map((x) => x.key);
    const index = focusedChildKey ? keys.indexOf(focusedChildKey) : -1;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      const next = keys[Math.min(keys.length - 1, Math.max(0, index) + 1)];
      setFocusedChildKey(next);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      const next = keys[Math.max(0, (index < 0 ? 0 : index) - 1)];
      setFocusedChildKey(next);
    } else if (event.key === 'Enter' && focusedChildKey) {
      event.preventDefault();
      const hit = flatChildren.find((x) => x.key === focusedChildKey);
      if (!hit) return;
      const menus = getItemMenus(hit.child.identify);
      if (menus[0]) onMenuAction(hit.child, menus[0], event);
    }
  }

  return (
    <MenuConditionProvider value={{ control: MENU_CONTROL_ID.identify }}>
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => {
              if (!v) toggleShow(false);
              else toggleShow(true);
            }}
            onClose={onClose}
            title={trans('map.identify.title')}
            width={400}
            height={300}
            afterTitle={
              titleLayer ? (
                <DatasetMenus
                  menus={titleMenus}
                  data={titleLayer}
                  mapId={mapId}
                  locations={['title']}
                />
              ) : undefined
            }
            extraBtn={
              <>
                <MapControlButton
                  variant="plain"
                  active={isEventClickActive}
                  disabled={isEventClickActive}
                  title={trans('map.identify.map_click')}
                  onClick={(e) => {
                    e.stopPropagation();
                    runIdentifyAction(
                      mapId,
                      IDENTIFY_CONTROL.actionUseMapClick,
                    );
                  }}
                >
                  <Icon path={mdiCursorPointer} size={ICON_SIZE} />
                </MapControlButton>
                <MapControlButton
                  variant="plain"
                  active={isEventClickBox}
                  disabled={isEventClickBox}
                  title={trans('map.identify.box_select')}
                  onClick={(e) => {
                    e.stopPropagation();
                    runIdentifyAction(
                      mapId,
                      IDENTIFY_CONTROL.actionUseBoxSelect,
                    );
                  }}
                >
                  <Icon path={mdiSelect} size={ICON_SIZE} />
                </MapControlButton>
              </>
            }
            {...bind}
            {...panelBind}
          >
            <div className="identify-control-container">
              <div className="identify-control-header">
                <div className="identify-control-header__row">
                  <b>{trans('map.identify.point')}:</b>
                  <span>{currentPoint}</span>
                </div>
                {layerItems.length > 0 ? (
                  <div className="identify-control-header__layer">
                    <InputSelect
                      label={trans('map.identify.layer')}
                      items={layerItems}
                      value={selectedLayerId}
                      onChange={(value) => {
                        const next = String(value);
                        setSelectedLayerId(next);
                        runIdentifyAction(
                          mapId,
                          IDENTIFY_CONTROL.actionSetLayerFilter,
                          {
                            identifyId:
                              next === IDENTIFY_ALL_LAYERS_VALUE
                                ? undefined
                                : next,
                          },
                        );
                      }}
                    />
                  </div>
                ) : null}
              </div>
              <hr className="identify-control-separator" aria-hidden="true" />
              <div
                className="identify-control-body"
                tabIndex={0}
                role="region"
                aria-label={trans('map.identify.title')}
                onKeyDown={onResultKeydown}
              >
                {loading ? (
                  <div
                    className="identify-control-state"
                    role="status"
                    aria-live="polite"
                  >
                    <div className="identify-control-state__content">
                      <div
                        className="identify-control-state__loading"
                        aria-hidden="true"
                      />
                      <span>{trans('map.identify.loading')}</span>
                    </div>
                  </div>
                ) : errorMessage ? (
                  <div className="identify-control-state" role="alert">
                    <div className="identify-control-state__content">
                      <span>
                        {errorMessage || trans('map.identify.error')}
                      </span>
                    </div>
                  </div>
                ) : items.length === 0 && !hasSelectedPoint ? (
                  <div className="identify-control-state">
                    <div className="identify-control-state__content">
                      <span>{trans('map.identify.no_selection')}</span>
                    </div>
                  </div>
                ) : items.length === 0 ? (
                  <div className="identify-control-state">
                    <div className="identify-control-state__content">
                      <span>
                        {selectedLayerId !== IDENTIFY_ALL_LAYERS_VALUE
                          ? trans('map.identify.no_data_filtered')
                          : trans('map.identify.no_data')}
                      </span>
                    </div>
                  </div>
                ) : (
                  items.map((item) => (
                    <div key={item.id} className="identify-control-list-item">
                      <div className="identify-control-list-item__container">
                        <div
                          className="identify-control-list-item__header"
                          title={item.name}
                        >
                          {item.name || '---'}
                        </div>
                        <div className="identify-control-list-item__child-container">
                          {item.items.map((child) => {
                            const childKey = `${item.id}:${child.id}`;
                            return (
                              <div
                                key={String(child.id)}
                                className={`identify-control-child-item${
                                  focusedChildKey === childKey
                                    ? ' is-focused'
                                    : ''
                                }`}
                                title={child.name || String(child.id)}
                                role="button"
                                tabIndex={0}
                                onClick={() => setFocusedChildKey(childKey)}
                              >
                                <span className="identify-control-child-item__name">
                                  {child.name || String(child.id) || '---'}
                                </span>
                                <div className="identify-control-child-item__spacer" />
                                <div
                                  className="identify-control-child-item__action"
                                  onClick={(e) => e.stopPropagation()}
                                >
                                  <DatasetMenus
                                    menus={getItemMenus(child.identify)}
                                    data={child.identify}
                                    mapId={mapId}
                                    value={child.data}
                                    locations={['extra', 'menu']}
                                  />
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
    </MenuConditionProvider>
  );
}
