// libs/react/map-core/src/modules/ZoomControl/ZoomControl.tsx
import React, {
  useState,
  useCallback,
  useRef,
  useEffect,
  useMemo,
} from 'react';
import type { MapSimple } from '@hungpvq/map-core';
import type { WithMapPropType } from '@hungpvq/map-core';
import { mdiMinus, mdiPlus } from '@mdi/js';
import { MapCommonButton } from '../../components/MapCommonButton';
import { MapControlGroupButton } from '../../components/MapControlGroupButton';
import { useLang, useToolbarControl } from '../../extra';
import { defaultMapProps, useMap } from '../../hooks';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

export interface ZoomControlProps extends WithMapPropType {
  showCompass?: boolean;
  showZoom?: boolean;
}

export function ZoomControl({
  showCompass = true,
  showZoom = true,
  ...props
}: ZoomControlProps) {
  const mergedProps = { ...defaultMapProps, ...props };
  const [transform, setTransform] = useState('rotate(0deg)');
  const bindSyncRotateRef = useRef<(() => void) | null>(null);

  function syncRotate(_map: MapSimple) {
    const angle = _map.getBearing() * -1;
    setTransform(`rotate(${angle}deg)`);
  }

  const onInit = useCallback((_map: MapSimple) => {
    bindSyncRotateRef.current = () => syncRotate(_map);
    if (bindSyncRotateRef.current) {
      _map.on('rotate', bindSyncRotateRef.current);
    }
  }, []);

  const onDestroy = useCallback((_map: MapSimple) => {
    if (bindSyncRotateRef.current) {
      _map.off('rotate', bindSyncRotateRef.current);
      bindSyncRotateRef.current = null;
    }
  }, []);

  const { callMap, mapId, moduleContainerProps, order } = useMap(
    mergedProps,
    onInit,
    onDestroy,
  );
  const { trans, setLocaleDefault } = useLang(mapId);

  useEffect(() => {
    setLocaleDefault({
      map: {
        action: {
          'navigation-control-zoom-in': 'Zoom in',
          'navigation-control-zoom-out': 'Zoom out',
          'navigation-control-reset-bearing': 'Reset bearing to north',
        },
      },
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function onZoomIn(e: React.MouseEvent) {
    callMap((map) => {
      map.zoomIn({}, { originalEvent: e.nativeEvent });
    });
  }

  function onZoomOut(e: React.MouseEvent) {
    callMap((map) => {
      map.zoomOut({}, { originalEvent: e.nativeEvent });
    });
  }

  function onResetBearing() {
    callMap((map) => {
      map.easeTo({ bearing: 0, pitch: 0 });
    });
  }

  const compassButton = useMemo(
    () => ({
      id: 'mapCompass',
      getState: () => ({
        visible: showCompass,
        title: trans('map.action.navigation-control-reset-bearing'),
        icon: {
          type: 'compass',
          transform: transform,
        },
      }),
      onClick: () => onResetBearing(),
    }),
    [showCompass, trans, transform, onResetBearing],
  );

  const zoomInButton = useMemo(
    () => ({
      id: 'mapZoomIn',
      getState: () => ({
        visible: showZoom,
        title: trans('map.action.navigation-control-zoom-in'),
        icon: { path: mdiPlus, type: 'mdi' },
      }),
      onClick: (e?: React.MouseEvent) => onZoomIn(e!),
    }),
    [showZoom, trans, onZoomIn],
  );

  const zoomOutButton = useMemo(
    () => ({
      id: 'mapZoomOut',
      getState: () => ({
        visible: showZoom,
        title: trans('map.action.navigation-control-zoom-out'),
        icon: { path: mdiMinus, type: 'mdi' },
      }),
      onClick: (e?: React.MouseEvent) => onZoomOut(e!),
    }),
    [showZoom, trans, onZoomOut],
  );

  const toolbarConfig = useMemo(
    () => ({
      kind: 'module' as const,
      moduleId: 'mapNavigationControl',
      moduleOrder: order,
      buttons: [compassButton, zoomInButton, zoomOutButton],
    }),
    [order, compassButton, zoomInButton, zoomOutButton],
  );

  const { state, control } = useToolbarControl(
    mapId,
    mergedProps,
    toolbarConfig,
  );

  const compassState = showCompass ? compassButton.getState() : null;
  const zoomInState = showZoom ? zoomInButton.getState() : null;
  const zoomOutState = showZoom ? zoomOutButton.getState() : null;

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        <MapControlGroupButton>
          {compassState && (
            <MapCommonButton
              option={compassState}
              onClick={(e) => {
                e.stopPropagation();
                compassButton.onClick?.();
                control.sync();
              }}
            />
          )}
          {zoomInState && (
            <MapCommonButton
              option={zoomInState}
              onClick={(e) => {
                e.stopPropagation();
                zoomInButton.onClick?.(e);
                control.sync();
              }}
            />
          )}
          {zoomOutState && (
            <MapCommonButton
              option={zoomOutState}
              onClick={(e) => {
                e.stopPropagation();
                zoomOutButton.onClick?.(e);
                control.sync();
              }}
            />
          )}
        </MapControlGroupButton>
      }
    />
  );
}

// libs/map-core/src/modules/ZoomControl/ZoomControl.vue
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapControlGroupButton>
        <MapControlButton
          v-if="showCompass"
          @click="onResetBearing"
          :title="trans('map.action.navigation-control-reset-bearing')"
        >
          <svg
            height="22"
            :style="{ transform: transform }"
            viewBox="0 0 24 24"
            width="22"
            xmlns="http://www.w3.org/2000/svg"
          >
            <g fill="none" fill-rule="evenodd">
              <path d="M0 0h24v24H0z"></path>
              <path d="M12 3l4 8H8z" fill="#f44336"></path>
              <path d="M12 21l-4-8h8z" fill="#9E9E9E"></path>
            </g>
          </svg>
        </MapControlButton>
        <MapControlButton
          v-if="showZoom"
          @click="onZoomIn"
          :title="trans('map.action.navigation-control-zoom-in')"
        >
          <SvgIcon :size="18" type="mdi" :path="path.plus" />
        </MapControlButton>
        <MapControlButton
          v-if="showZoom"
          @click="onZoomOut"
          :title="trans('map.action.navigation-control-zoom-out')"
        >
          <SvgIcon :size="18" type="mdi" :path="path.minus" />
        </MapControlButton>
      </MapControlGroupButton>
    </template>
    <slot />
  </ModuleContainer>
</template>

<script setup>
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiMinus, mdiPlus } from '@mdi/js';
import { ref } from 'vue';
import MapControlButton from '../../components/MapControlButton.vue';
import MapControlGroupButton from '../../components/MapControlGroupButton.vue';
import { useMap, withMapProps } from '../../hooks';
import { useLang } from '../../extra';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';
const path = {
  plus: mdiPlus,
  minus: mdiMinus,
};
const props = defineProps({
  ...withMapProps,
  showCompass: { type: Boolean, default: true },
  showZoom: { type: Boolean, default: true },
});
const transform = ref('rotate(0deg)');
const { callMap, mapId, moduleContainerProps } = useMap(
  props,
  onInit,
  onDestroy
);
const { trans, setLocale } = useLang(mapId.value);
setLocale({
  map: {
    action: {
      'navigation-control-zoom-in': 'Zoom in',
      'navigation-control-zoom-out': 'Zoom out',
      'navigation-control-reset-bearing': 'Reset bearing to north',
    },
  },
});
let bindSyncRotate = null;
function onInit(_map) {
  bindSyncRotate = syncRotate.bind(null, _map);
  _map.on('rotate', bindSyncRotate);
}
function onDestroy(_map) {
  _map.off('rotate', bindSyncRotate);
}
function onZoomIn(e) {
  callMap((map) => {
    map.zoomIn({}, { originalEvent: e });
  });
}
function onZoomOut(e) {
  callMap((map) => {
    map.zoomOut({}, { originalEvent: e });
  });
}
function onResetBearing() {
  callMap((map) => {
    map.easeTo({ bearing: 0, pitch: 0 });
  });
}
function syncRotate(_map) {
  const angle = _map.getBearing() * -1;
  transform.value = `rotate(${angle}deg)`;
}
</script>
