// libs/react/map-core/src/modules/MapContextMenuControl/MapContextMenuControl.tsx
import { type WithMapPropType } from '@hungpvq/map-core';
import { EventContextMenu } from '@hungpvq/map-core/event';
import {
  copyMapPointCoords,
  createDefaultMapContextMenuItems,
  createMapMenuItemProps,
  filterVisibleMapMenuItems,
  formatMapContextCoords,
  handleMapMenuAction,
  resolveMapMenuCondition,
  type MapContextMenuItem,
  type MapContextMenuTarget,
} from '@hungpvq/map-core/menu';
import { ContextMenu, type ContextMenuRef } from '@hungpvq/react-draggable';
import { mdiChevronRight, mdiMapMarkerOutline } from '@mdi/js';
import { Icon } from '@mdi/react';
import type { MapMouseEvent } from 'maplibre-gl';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useEventMap } from '../../extra/event/hook/useEvent';
import { defaultMapProps, useMap } from '../../hooks/useMap';

export type MapContextMenuControlProps = WithMapPropType & {
  items?: MapContextMenuItem[];
  include?: string[];
  exclude?: string[];
  extra?: MapContextMenuItem[];
  prepend?: MapContextMenuItem[];
  showCoords?: boolean;
  enabled?: boolean;
  zoomDelta?: number;
  onOpen?: (target: MapContextMenuTarget) => void;
  onClose?: () => void;
  onSelect?: (payload: {
    item: MapContextMenuItem;
    target: MapContextMenuTarget;
  }) => void;
};

export function MapContextMenuControl(props: MapContextMenuControlProps) {
  const merged = {
    ...defaultMapProps,
    showCoords: true,
    enabled: true,
    zoomDelta: 2,
    ...props,
  };
  const { mapId } = useMap(merged);
  const menuRef = useRef<ContextMenuRef>(null);
  const [target, setTarget] = useState<MapContextMenuTarget>();
  const onContextMenuRef = useRef<(e: MapMouseEvent) => void>(() => undefined);
  const pendingOpenRef = useRef<MouseEvent | null>(null);

  const event = useMemo(
    () =>
      new EventContextMenu().setHandler((e: MapMouseEvent) => {
        onContextMenuRef.current(e);
      }),
    [],
  );
  const { add, remove } = useEventMap(mapId, event, false);

  useEffect(() => {
    if (merged.enabled) add();
    else remove();
    return () => remove();
  }, [merged.enabled, add, remove]);

  useEffect(() => {
    const ev = pendingOpenRef.current;
    if (!target || !ev) return;
    pendingOpenRef.current = null;
    menuRef.current?.open(ev);
  }, [target]);

  const sourceItems = useMemo(() => {
    if (merged.items?.length) {
      return [
        ...(merged.prepend ?? []),
        ...merged.items,
        ...(merged.extra ?? []),
      ];
    }
    return createDefaultMapContextMenuItems({
      include: merged.include,
      exclude: merged.exclude,
      extra: merged.extra,
      prepend: merged.prepend,
      zoomDelta: merged.zoomDelta,
      mapId,
    });
  }, [
    merged.items,
    merged.prepend,
    merged.extra,
    merged.include,
    merged.exclude,
    merged.zoomDelta,
    mapId,
  ]);

  const visibleItems = useMemo(() => {
    if (!target) return sourceItems;
    return filterVisibleMapMenuItems(sourceItems, target);
  }, [sourceItems, target]);

  onContextMenuRef.current = (e: MapMouseEvent) => {
    const next: MapContextMenuTarget = {
      lngLat: { lng: e.lngLat.lng, lat: e.lngLat.lat },
      point: { x: e.point.x, y: e.point.y },
      mapId,
    };
    setTarget(next);
    merged.onOpen?.(next);
    const original = e.originalEvent;
    if (original instanceof MouseEvent) {
      pendingOpenRef.current = original;
    }
  };

  function onSelect(item: MapContextMenuItem, event: React.MouseEvent) {
    event.stopPropagation();
    if (!target || item.type !== 'item') return;
    if (resolveMapMenuCondition(item.disabled, target)) return;
    handleMapMenuAction(
      item,
      createMapMenuItemProps(target, event.nativeEvent),
    );
    merged.onSelect?.({ item, target });
    if (!item.children?.length) {
      menuRef.current?.close();
      merged.onClose?.();
    }
  }

  function isDisabled(item: MapContextMenuItem) {
    if (!target || item.type !== 'item') return false;
    return resolveMapMenuCondition(item.disabled, target);
  }

  const coordsLabel = target
    ? formatMapContextCoords(target.lngLat.lng, target.lngLat.lat)
    : '';

  return (
    <ContextMenu ref={menuRef}>
      {target ? (
        <ul className="context-menu map-context-menu">
          {merged.showCoords ? (
            <li
              className="map-context-menu__coords"
              onClick={(e) => {
                e.stopPropagation();
                void copyMapPointCoords(target);
              }}
            >
              <div className="map-context-menu__coords-icon">
                <Icon path={mdiMapMarkerOutline} size="16px" />
              </div>
              <span className="map-context-menu__label">{coordsLabel}</span>
            </li>
          ) : null}
          {visibleItems.map((item, index) => {
            const key = item.id || String(index);
            if (item.type === 'header') {
              return (
                <li key={key} className="map-context-menu__header">
                  {item.name}
                </li>
              );
            }
            if (item.type === 'divider') {
              return (
                <li key={key} className="map-context-menu__divider">
                  <div className="map-context-menu__divider-line" />
                </li>
              );
            }
            return (
              <li
                key={key}
                className={[
                  'map-context-menu__item',
                  isDisabled(item) ? 'is-disabled' : '',
                  item.children?.length
                    ? 'map-context-menu__item--has-children'
                    : '',
                ]
                  .filter(Boolean)
                  .join(' ')}
                onClick={(event) => onSelect(item, event)}
              >
                <div className="map-context-menu__item-icon">
                  {item.icon ? <Icon path={item.icon} size="16px" /> : null}
                </div>
                <span className="map-context-menu__label">{item.name}</span>
                {item.children?.length ? (
                  <div className="map-context-menu__chevron">
                    <Icon path={mdiChevronRight} size="16px" />
                  </div>
                ) : null}
                {item.children?.length ? (
                  <ul className="context-menu map-context-menu map-context-menu__submenu">
                    {item.children.map((child, childIndex) => {
                      const childKey = child.id || String(childIndex);
                      if (child.type === 'header') {
                        return (
                          <li
                            key={childKey}
                            className="map-context-menu__header"
                          >
                            {child.name}
                          </li>
                        );
                      }
                      if (child.type === 'divider') {
                        return (
                          <li
                            key={childKey}
                            className="map-context-menu__divider"
                          >
                            <div className="map-context-menu__divider-line" />
                          </li>
                        );
                      }
                      return (
                        <li
                          key={childKey}
                          className={[
                            'map-context-menu__item',
                            isDisabled(child) ? 'is-disabled' : '',
                          ]
                            .filter(Boolean)
                            .join(' ')}
                          onClick={(event) => onSelect(child, event)}
                        >
                          <div className="map-context-menu__item-icon">
                            {child.icon ? (
                              <Icon path={child.icon} size="16px" />
                            ) : null}
                          </div>
                          <span className="map-context-menu__label">
                            {child.name}
                          </span>
                        </li>
                      );
                    })}
                  </ul>
                ) : null}
              </li>
            );
          })}
        </ul>
      ) : null}
    </ContextMenu>
  );
}

// libs/vue/map-core/src/modules/MapContextMenuControl/MapContextMenuControl.vue
<script lang="ts">
export default {
  name: 'MapContextMenuControl',
};
</script>
<script setup lang="ts">
import { type WithMapPropType } from '@hungpvq/map-core';
import { EventContextMenu } from '@hungpvq/map-core/event';
import {
  copyMapPointCoords,
  createDefaultMapContextMenuItems,
  createMapMenuItemProps,
  filterVisibleMapMenuItems,
  formatMapContextCoords,
  handleMapMenuAction,
  type MapContextMenuItem,
  type MapContextMenuTarget,
  resolveMapMenuCondition,
} from '@hungpvq/map-core/menu';
import { ContextMenu } from '@hungpvq/vue-draggable';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiChevronRight, mdiMapMarkerOutline } from '@mdi/js';
import type { MapMouseEvent } from 'maplibre-gl';
import { computed, ref, watch } from 'vue';

import { useEventMap } from '../../extra/event/hook/useEvent';
import { defaultMapProps, useMap } from '../../hooks/useMap';

const props = withDefaults(
  defineProps<
    WithMapPropType & {
      items?: MapContextMenuItem[];
      include?: string[];
      exclude?: string[];
      extra?: MapContextMenuItem[];
      prepend?: MapContextMenuItem[];
      showCoords?: boolean;
      enabled?: boolean;
      zoomDelta?: number;
    }
  >(),
  {
    ...defaultMapProps,
    showCoords: true,
    enabled: true,
    zoomDelta: 2,
  },
);

const emit = defineEmits<{
  open: [target: MapContextMenuTarget];
  close: [];
  select: [payload: { item: MapContextMenuItem; target: MapContextMenuTarget }];
}>();

const { mapId } = useMap(props);
const menuRef = ref<{ open: (event: MouseEvent) => void; close: () => void }>();
const target = ref<MapContextMenuTarget>();

const event = new EventContextMenu().setHandler(onContextMenu);
const { add, remove } = useEventMap(mapId.value, event, false);

watch(
  () => props.enabled,
  (enabled) => {
    if (enabled) add();
    else remove();
  },
  { immediate: true },
);

const sourceItems = computed(() => {
  void target.value;
  if (props.items?.length) {
    return [...(props.prepend ?? []), ...props.items, ...(props.extra ?? [])];
  }
  return createDefaultMapContextMenuItems({
    include: props.include,
    exclude: props.exclude,
    extra: props.extra,
    prepend: props.prepend,
    zoomDelta: props.zoomDelta,
    mapId: mapId.value,
  });
});

const visibleItems = computed(() => {
  if (!target.value) return sourceItems.value;
  return filterVisibleMapMenuItems(sourceItems.value, target.value);
});

const coordsLabel = computed(() => {
  if (!target.value) return '';
  return formatMapContextCoords(
    target.value.lngLat.lng,
    target.value.lngLat.lat,
  );
});

function onContextMenu(e: MapMouseEvent) {
  const next: MapContextMenuTarget = {
    lngLat: { lng: e.lngLat.lng, lat: e.lngLat.lat },
    point: { x: e.point.x, y: e.point.y },
    mapId: mapId.value,
  };
  target.value = next;
  emit('open', next);
  const mouse = e.originalEvent;
  if (mouse instanceof MouseEvent) {
    menuRef.value?.open(mouse);
  }
}

function onCopyCoords() {
  if (!target.value) return;
  void copyMapPointCoords(target.value);
}

function onSelect(item: MapContextMenuItem, event: MouseEvent) {
  if (!target.value || item.type !== 'item') return;
  if (resolveMapMenuCondition(item.disabled, target.value)) return;
  handleMapMenuAction(item, createMapMenuItemProps(target.value, event));
  emit('select', { item, target: target.value });
  if (!item.children?.length) {
    menuRef.value?.close();
    emit('close');
  }
}

function isDisabled(item: MapContextMenuItem) {
  if (!target.value || item.type !== 'item') return false;
  return resolveMapMenuCondition(item.disabled, target.value);
}
</script>

<template>
  <ContextMenu ref="menuRef">
    <ul class="context-menu map-context-menu" v-if="target">
      <li
        v-if="showCoords"
        class="map-context-menu__coords"
        @click.stop="onCopyCoords"
      >
        <div class="map-context-menu__coords-icon">
          <SvgIcon :size="16" type="mdi" :path="mdiMapMarkerOutline" />
        </div>
        <span class="map-context-menu__label">{{ coordsLabel }}</span>
      </li>
      <template v-for="(item, index) in visibleItems" :key="item.id || index">
        <li v-if="item.type === 'header'" class="map-context-menu__header">
          {{ item.name }}
        </li>
        <li
          v-else-if="item.type === 'divider'"
          class="map-context-menu__divider"
        >
          <div class="map-context-menu__divider-line" />
        </li>
        <li
          v-else
          class="map-context-menu__item"
          :class="{
            'is-disabled': isDisabled(item),
            'map-context-menu__item--has-children': !!item.children?.length,
          }"
          @click.stop="onSelect(item, $event)"
        >
          <div class="map-context-menu__item-icon">
            <SvgIcon v-if="item.icon" :size="16" type="mdi" :path="item.icon" />
          </div>
          <span class="map-context-menu__label">{{ item.name }}</span>
          <div v-if="item.children?.length" class="map-context-menu__chevron">
            <SvgIcon :size="16" type="mdi" :path="mdiChevronRight" />
          </div>
          <ul
            v-if="item.children?.length"
            class="context-menu map-context-menu map-context-menu__submenu"
          >
            <template
              v-for="(child, childIndex) in item.children"
              :key="child.id || childIndex"
            >
              <li
                v-if="child.type === 'header'"
                class="map-context-menu__header"
              >
                {{ child.name }}
              </li>
              <li
                v-else-if="child.type === 'divider'"
                class="map-context-menu__divider"
              >
                <div class="map-context-menu__divider-line" />
              </li>
              <li
                v-else
                class="map-context-menu__item"
                :class="{ 'is-disabled': isDisabled(child) }"
                @click.stop="onSelect(child, $event)"
              >
                <div class="map-context-menu__item-icon">
                  <SvgIcon
                    v-if="'icon' in child && child.icon"
                    :size="16"
                    type="mdi"
                    :path="child.icon"
                  />
                </div>
                <span v-if="'name' in child" class="map-context-menu__label">{{
                  child.name
                }}</span>
              </li>
            </template>
          </ul>
        </li>
      </template>
    </ul>
  </ContextMenu>
</template>
