// libs/react/map-core/src/modules/GotoControl/GotoControl.tsx
import { GOTO_CONTROL_LOCALE, type WithMapPropType } from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiMapMarkerOutline } from '@mdi/js';
import { useEffect, useState } from 'react';
import { MapCommonButton } from '../../components/MapCommonButton';
import { useLang, useRegisterMapControl } from '../../extra';
import { useToolbarControl } from '../../extra/toolbar';
import { BaseButton, InputText } from '../../field';
import { defaultMapProps, useMap, useShow } from '../../hooks';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

export interface GotoControlProps extends WithMapPropType {
  show?: boolean;
}

export function GotoControl(props: GotoControlProps) {
  const mergedProps = { ...defaultMapProps, ...props };
  const { callMap, mapId, moduleContainerProps, order } = useMap({ ...mergedProps, controlId: 'mapGotoControl' });
  const { trans, setLocaleDefault } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);
  const [setting, setSetting] = useState<{
    zoom?: number;
    center: [number, number];
  }>({ center: [0, 0] });

  useEffect(() => {
    setLocaleDefault(GOTO_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  function loadCurrentView() {
    callMap((map) => {
      setSetting({
        zoom: map.getZoom(),
        center: [
          +map.getCenter().lng.toFixed(6),
          +map.getCenter().lat.toFixed(6),
        ],
      });
    });
  }

  function handleToggle() {
    const nextShow = !show;
    toggleShow(nextShow);
    if (nextShow) {
      loadCurrentView();
    }
  }

  const { panelBind } = useRegisterMapControl(mapId, {
    id: 'mapGotoControl',
    panelKind: 'popup',
    title: trans('map.goto-control.title'),
    buttonPosition: mergedProps.position,
    show,
    setShow: toggleShow,
    getProps: () => ({
      position: mergedProps.position,
      controlLayout: mergedProps.controlLayout,
    }),
    actions: [{ type: 'mapGotoControl', run: () => handleToggle() }],
  });

  function onSetSetting() {
    callMap((map) => {
      if (setting.zoom != null) map.setZoom(setting.zoom);
      if (setting.center) map.setCenter(setting.center);
    });
  }

  const { state, control } = useToolbarControl(mapId, mergedProps, {
    kind: 'single',
    id: 'mapGotoControl',
    getState: () =>
      mdiButtonState(mdiMapMarkerOutline, {
        visible: true,
        title: trans('map.goto-control.title'),
        order,
      }),
    onClick: () => handleToggle(),
  });

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => toggleShow(!!v)}
            title={trans('map.goto-control.title')}
            height={300}
            width={400}
            {...bind}
            {...panelBind}
          >
            <div className="map-goto-control">
              <div className="map-goto-control__fields">
                <div>
                  <label className="map-goto-control__center-label">
                    {trans('map.goto-control.field.center')}
                  </label>
                  <div className="map-goto-control__center">
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[0])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [Number(v), prev.center[1]],
                        }))
                      }
                    />
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[1])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [prev.center[0], Number(v)],
                        }))
                      }
                    />
                  </div>
                </div>
                <div>
                  <InputText
                    label={trans('map.goto-control.field.zoom')}
                    type="number"
                    min={0}
                    max={24}
                    value={setting.zoom != null ? String(setting.zoom) : ''}
                    onChange={(v) =>
                      setSetting((prev) => ({
                        ...prev,
                        zoom: v === '' ? undefined : Number(v),
                      }))
                    }
                  />
                </div>
              </div>
              <BaseButton className="map-goto-control__btn" onClick={onSetSetting}>
                {trans('map.goto-control.btn.apply')}
              </BaseButton>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

// libs/map/core/src/modules/GotoControl/GotoControl.vue
<script setup lang="ts">
import { type WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { mdiMapMarkerOutline } from '@mdi/js';
import { ref } from 'vue';
import MapCommonButton from '../../components/MapCommonButton.vue';
import { useLang, useToolbarControl } from '../../extra';
import { BaseButton, InputText } from '../../field';
import { defaultMapProps, useMap, useShow, WithShowProps } from '../../hooks';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const [show, setShow] = useShow(props.show);
const { callMap, mapId, moduleContainerProps, order } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);

setLocaleDefault({
  map: {
    'goto-control': {
      title: 'Go to',
      field: {
        zoom: 'Zoom',
        center: 'Center',
      },
      btn: {
        apply: 'Go to',
      },
    },
  },
});
function onToggleShow() {
  setShow(!show.value);
  if (show.value) {
    callMap((_map) => {
      setting.value.zoom = _map.getZoom();
      setting.value.center = [
        +_map.getCenter().lng.toFixed(6),
        +_map.getCenter().lat.toFixed(6),
      ];
    });
  }
}
const setting = ref<{
  zoom?: number;
  center: [number, number];
}>({ center: [0, 0] });
const onSetSetting = () => {
  callMap((map) => {
    if (setting.value.zoom) map.setZoom(setting.value.zoom);
    if (setting.value.center) map.setCenter(setting.value.center);
  });
};
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapGotoControl',
  getState() {
    return {
      visible: true,
      title: trans.value('map.goto-control.title'),
      order: order.value,
      icon: {
        type: 'mdi',
        path: mdiMapMarkerOutline,
      },
    };
  },
  onClick() {
    onToggleShow();
  },
});
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton v-if="state" :option="state" @click="control.onAction">
      </MapCommonButton>
    </template>

    <template #draggable="props">
      <DraggableItemPopup
        v-if="show"
        :height="300"
        :width="400"
        v-bind="props"
        v-model:show="show"
        :title="trans('map.goto-control.title')"
      >
        <div class="setting-container">
          <div class="setting-field-container">
            <div>
              <label>
                {{ trans('map.goto-control.field.center') }}
              </label>
              <div class="setting-center-container">
                <InputText
                  v-model="setting.center[0]"
                  type="number"
                  step="0.0000001"
                />
                <InputText
                  v-model="setting.center[1]"
                  type="number"
                  step="0.0000001"
                />
              </div>
            </div>
            <div>
              <InputText
                :label="trans('map.goto-control.field.zoom')"
                v-model="setting.zoom"
                type="number"
                min="0"
                max="24"
              />
            </div>
          </div>

          <base-button class="btn-container" @click="onSetSetting()">
            {{ trans('map.goto-control.btn.apply') }}
          </base-button>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>
<style>
.setting-container {
  padding: 8px;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: auto;
}
.setting-field-container > div {
  padding: 4px;
}
.setting-container .setting-field-container {
  height: 100%;
  padding: 8px;
  flex-grow: 1;
  overflow: auto;
}
.setting-container .btn-container {
  flex-grow: 0;
  padding: 8px;
}
.setting-center-container {
  display: flex;
}
.setting-center-container > *:not(:last-child) {
  padding-right: 4px;
}
</style>
