// libs/react/map-core/src/extra/basemap/modules/BaseMapControl.tsx
import type { BaseMapItem } from '@hungpvq/map-core';
import {
  INIT_BASEMAPS,
  logHelper,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiLayersOutline } from '@mdi/js';
import { Icon } from '@mdi/react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  MapCard,
  MapControlButton,
  MapIcon,
  MapImage,
} from '../../../components';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { ModuleContainer } from '../../../modules';
import type { BindPosition } from '../../../modules/ModuleContainer/ModuleContainer';
import { useLang } from '../../useLang';
import { useToolbarControl } from '../../useToolbarControl';
import { useBaseMap } from '../hooks';
import { logger } from '../logger';

const SIZE_BASE_MAP = 70;

export interface BaseMapControlProps extends WithMapPropType {
  baseMaps?: BaseMapItem[];
  title?: string;
  defaultBaseMap?: string;
  controlIcon?: string;
}

export function BaseMapControl({
  baseMaps = INIT_BASEMAPS,
  title = '',
  defaultBaseMap = 'Open Street Map',
  controlIcon = '',
  ...mapProps
}: BaseMapControlProps) {
  const props = {
    ...defaultMapProps,
    ...mapProps,
    baseMaps,
    title,
    defaultBaseMap,
    controlIcon,
  };
  const { mapId, moduleContainerProps, order } = useMap(props);
  const { trans, setLocaleDefault } = useLang(mapId);
  const {
    setBaseMaps,
    baseMaps: c_baseMaps,
    setDefaultBaseMap,
    setCurrent,
    currentBaseMap: current_baseMaps,
    remove,
    init,
  } = useBaseMap(mapId);

  useEffect(() => {
    setBaseMaps(props.baseMaps as BaseMapItem[]);
  }, [props.baseMaps, setBaseMaps]);

  useEffect(() => {
    setDefaultBaseMap(props.defaultBaseMap);
  }, [props.defaultBaseMap, setDefaultBaseMap]);

  useEffect(() => {
    setLocaleDefault({
      map: {
        basemap: {
          title: 'Map basemap',
          setting: 'Setting',
        },
      },
    });
  }, [setLocaleDefault]);

  const [show, setShow] = useState(false);

  const onClick = useCallback(
    (baseMap: BaseMapItem) => {
      logHelper(logger, mapId, 'control', 'BaseMapControl').debug(
        'onClick',
        baseMap,
      );
      setCurrent(baseMap);
    },
    [mapId, setCurrent],
  );

  const onToggleList = useCallback(() => {
    setShow((s) => !s);
  }, []);

  useEffect(() => {
    init(props.baseMaps as BaseMapItem[], props.defaultBaseMap);
    return () => remove();
  }, []);

  useToolbarControl(mapId, props, {
    id: 'mapBaseMapControl',
    getState: () => ({
      visible: true,
      order,
      title: title || trans('map.basemap.title'),
      icon: {
        type: 'mdi',
        path: mdiLayersOutline,
      },
    }),
    onClick: onToggleList,
  });

  const draggableContent = useCallback(
    (bindDrag: BindPosition) => (
      <DraggableItemPopup
        show={show}
        onUpdateShow={setShow}
        title={trans('map.basemap.setting')}
        width={SIZE_BASE_MAP * 3 + 24}
        height={
          SIZE_BASE_MAP * (Math.floor(c_baseMaps.length / 3) + 1) + 48 + 10
        }
        sticks={[]}
        disabledExpand
        {...bindDrag}
      >
        <div className="base-map-control-setting">
          {c_baseMaps.map((baseMap) => (
            <div
              key={baseMap.id}
              className={`clickable base-map-control-setting-item ${
                current_baseMaps && baseMap.id === current_baseMaps.id
                  ? 'base-map-control-setting-item__active'
                  : ''
              }`}
              style={{ width: SIZE_BASE_MAP + 'px' }}
              title={baseMap.title}
              onClick={() => onClick(baseMap)}
            >
              <div
                style={{
                  width: SIZE_BASE_MAP - 34 + 'px',
                  height: SIZE_BASE_MAP - 34 + 'px',
                }}
              >
                <MapImage src={baseMap.thumbnail} />
              </div>
              <div className="base-map-control-setting-item__title">
                {baseMap.title}
              </div>
            </div>
          ))}
        </div>
      </DraggableItemPopup>
    ),
    [show, c_baseMaps, current_baseMaps, trans, onClick],
  );

  // Logic mặc định: lấy map thỏa mãn defaultBaseMap (b.default hoặc b.title === defaultBaseMap), nếu không thì lấy phần tử đầu
  const getDefaultBaseMap = (maps: BaseMapItem[]) =>
    maps.find((b) => b.default || b.title === props.defaultBaseMap) ?? maps[0];

  const baseMapsSource =
    c_baseMaps.length > 0 ? c_baseMaps : (props.baseMaps as BaseMapItem[]);
  const displayBaseMap = current_baseMaps ?? getDefaultBaseMap(baseMapsSource);
  const btnContent = (
    <MapControlButton tooltip={title} onClick={onToggleList} size={70}>
      <MapCard
        className="clickable base-map-button__container"
        height="70px"
        width="70px"
      >
        <div className="base-map-button__content">
          <MapImage src={displayBaseMap.thumbnail}>
            <div className="base-map-button__title">
              {controlIcon ? (
                <MapIcon>{controlIcon}</MapIcon>
              ) : (
                <Icon path={mdiLayersOutline} size={1} />
              )}
              <div>{title || trans('map.basemap.title')}</div>
            </div>
          </MapImage>
        </div>
      </MapCard>
    </MapControlButton>
  );

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btnWidth={70}
      btn={btnContent}
      draggable={draggableContent}
    ></ModuleContainer>
  );
}

// libs/map/core/src/extra/basemap/modules/BaseMapControl.vue
<template>
  <ModuleContainer v-bind="moduleContainerProps" :btnWidth="70">
    <template #btn>
      <MapControlButton v-if="current_baseMaps" :tooltip="title">
        <template #content>
          <map-card
            class="clickable base-map-button__container"
            height="70px"
            width="70px"
            @click="onToggleList"
          >
            <div class="base-map-button__content">
              <map-image :src="current_baseMaps.thumbnail">
                <div class="base-map-button__title">
                  <map-icon v-if="controlIcon">
                    {{ controlIcon }}
                  </map-icon>
                  <SvgIcon type="mdi" :path="path.layer" v-else />
                  <div class="">
                    {{ title || trans('map.basemap.title') }}
                  </div>
                </div>
              </map-image>
            </div>
          </map-card>
        </template>
      </MapControlButton>

      <div v-else></div>
    </template>
    <template #draggable="props">
      <DraggableItemPopup
        v-if="show"
        v-bind="props"
        :height="
          sizeBaseMap * (Math.floor(c_baseMaps.length / 3) + 1) + 48 + 10
        "
        v-model:show="show"
        :is-resizable="false"
        :title="trans('map.basemap.setting')"
        :width="sizeBaseMap * 3 + 24"
      >
        <div class="base-map-control-setting">
          <div
            v-for="baseMap in c_baseMaps"
            :key="baseMap.id"
            class="clickable base-map-control-setting-item"
            :style="{ width: sizeBaseMap + 'px' }"
            :title="baseMap.title"
            @click="onClick(baseMap)"
          >
            <div
              :style="{
                width: sizeBaseMap - 34 + 'px',
                height: sizeBaseMap - 34 + 'px',
              }"
            >
              <map-image :src="baseMap.thumbnail"> </map-image>
            </div>
            <div
              class="base-map-control-setting-item__title"
              :class="{
                'base-map-control-setting-item__active':
                  current_baseMaps && baseMap.id == current_baseMaps.id,
              }"
              style="font-size: 14px"
            >
              {{ baseMap.title }}
            </div>
          </div>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>
<script lang="ts" setup>
import type { BaseMapItem } from '@hungpvq/map-core';
import {
  INIT_BASEMAPS,
  logHelper,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiLayersOutline } from '@mdi/js';
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  MapCard,
  MapControlButton,
  MapIcon,
  MapImage,
} from '../../../components';
import { useLang } from '../../../extra/lang';
import { useToolbarControl } from '../../../extra/toolbar';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { ModuleContainer } from '../../../modules';
import { useBaseMap } from '../hooks';
import { logger } from '../logger';
const props = withDefaults(
  defineProps<
    WithMapPropType & {
      baseMaps?: BaseMapItem[]; // hoặc cụ thể hơn nếu có kiểu
      title?: string;
      defaultBaseMap?: string;
      controlIcon?: string;
    }
  >(),
  {
    ...defaultMapProps,
    baseMaps: () => INIT_BASEMAPS,
    title: '',
    defaultBaseMap: 'Open Street Map',
    controlIcon: '',
  },
);
const { mapId, moduleContainerProps, order } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);
const {
  setBaseMaps,
  baseMaps: c_baseMaps,
  setDefaultBaseMap,
  setCurrent,
  currentBaseMap: current_baseMaps,
  remove,
  init,
} = useBaseMap(mapId.value);
watch(
  () => props.baseMaps as BaseMapItem[],
  (value: BaseMapItem[]) => {
    setBaseMaps(value);
  },
);
watch(
  () => props.defaultBaseMap,
  (value) => {
    setDefaultBaseMap(value);
  },
);
setLocaleDefault({
  map: {
    basemap: {
      title: 'Map basemap',
      setting: 'Setting',
    },
  },
});
const sizeBaseMap = computed(() => {
  return 70;
});
const path = {
  layer: mdiLayersOutline,
};
const show = ref(false);
function onClick(baseMap: BaseMapItem) {
  logHelper(logger, mapId.value, 'control', 'BaseMapControl').debug(
    'onClick',
    baseMap,
  );
  setCurrent(baseMap);
}
function onToggleList() {
  show.value = !show.value;
}
onMounted(() => {
  init(props.baseMaps as BaseMapItem[], props.defaultBaseMap);
});
onBeforeUnmount(() => {
  remove();
});
useToolbarControl(mapId.value, props, {
  id: 'mapBaseMapControl',
  getState() {
    return {
      visible: true,
      order: order.value,
      title: props.title || trans.value('map.basemap.title'),
      icon: {
        type: 'mdi',
        path: path.layer,
      },
    };
  },
  onClick() {
    onToggleList();
  },
});
</script>
