// libs/react/map-dataset/src/modules/StyleControl/style/SingleStyle.tsx
import {
  applyStyleTabValue,
  applyStyleZoom,
  convertTabWithDefaultConfig,
  DEFAULT_VALUE,
  type Tab,
  type TabConfig,
  TABS,
} from '@hungpvq/map-dataset/style';
import { BaseCollapse, InputSlider } from '@hungpvq/react-map-core/fields';
import type { LayerSpecification } from 'maplibre-gl';
import { useEffect, useMemo, useState } from 'react';

import { TabContent } from '../component/TabContent';
import { TabItem } from '../component/TabItem';
import { CONFIG_TABS } from './type/default';
import type { TransFn } from './type/tab-utils';

function getTabValue(layer: LayerSpecification, tab: Tab): unknown {
  if (tab.type === 'divider' || !('key' in tab) || !tab.key) return undefined;
  const part = tab.part || 'paint';
  const bag = layer[part] as Record<string, unknown> | undefined;
  return bag?.[String(tab.key)];
}

function getDefaultTabValue(layerType: string, tab: Tab): unknown {
  if (tab.type === 'divider' || !('key' in tab) || !tab.key) return undefined;
  const defaults = DEFAULT_VALUE[layerType];
  const part = tab.part || 'paint';
  const bag = defaults?.[part] as Record<string, unknown> | undefined;
  return bag?.[String(tab.key)];
}

export function SingleStyle({
  value,
  trans,
  mapId,
  onUpdateStyle,
}: {
  value?: LayerSpecification;
  trans: TransFn;
  mapId: string;
  onUpdateStyle?: (layer: LayerSpecification) => void;
}) {
  const layer = value;
  const tabs_format = useMemo<TabConfig[]>(() => {
    if (!layer) return [];
    const tab = TABS[layer.type];
    if (!tab) return [];
    if (tab.type === 'multi') {
      return tab.tabs.map((x) => ({
        ...x,
        items: convertTabWithDefaultConfig(x.items, CONFIG_TABS),
      }));
    }
    return [
      {
        type: 'single',
        text: 'style',
        items: convertTabWithDefaultConfig(tab.items, CONFIG_TABS),
      },
    ];
  }, [layer]);

  const [tabGroup, setTabGroup] = useState<TabConfig | undefined>();
  const [tab, setTab] = useState<Tab | undefined>();

  useEffect(() => {
    if (tabs_format[0]) {
      onSelectTabGroup(tabs_format[0]);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tabs_format]);

  function onSelectTab(item: Tab) {
    const next = { ...item } as Tab & {
      menu?: {
        text?: string;
        subtitle?: string;
        text_trans?: string;
        subtitle_trans?: string;
      }[];
    };
    if (next.menu) {
      next.menu = next.menu.map((x) => ({
        ...x,
        text: x.text || trans(x.text_trans || '') || '',
        subtitle: x.subtitle || trans(x.subtitle_trans || '') || '',
      }));
    }
    setTab(next);
  }

  function onSelectTabGroup(group: TabConfig) {
    setTabGroup(group);
    if (group.items?.[0]) onSelectTab(group.items[0]);
  }

  function emitLayer(next: LayerSpecification) {
    onUpdateStyle?.(next);
  }

  function emitInput(
    raw: unknown,
    currentTab: Tab,
    currentLayer: LayerSpecification,
  ) {
    emitLayer(applyStyleTabValue(currentLayer, currentTab, raw));
  }

  function onChangeMinZoom(zoom: number, currentLayer: LayerSpecification) {
    emitLayer(applyStyleZoom(currentLayer, 'min-zoom', zoom));
  }

  function onChangeMaxZoom(zoom: number, currentLayer: LayerSpecification) {
    emitLayer(applyStyleZoom(currentLayer, 'max-zoom', zoom));
  }

  if (!layer) return null;

  const layerZoom = layer as LayerSpecification & {
    'min-zoom'?: number;
    'max-zoom'?: number;
  };

  return (
    <div className="style-edit-container">
      <BaseCollapse header={trans('map.style-control.layer.title')}>
        <div className="label-config-container">
          <div className="label-config-item">
            <div className="label-config-item__label">
              {trans('map.style-control.layer.id')}
            </div>
            <div className="label-config-item__input">{layer.id}</div>
          </div>
          <div className="label-config-item">
            <div className="label-config-item__label">
              {trans('map.style-control.layer.type')}
            </div>
            <div className="label-config-item__input">{layer.type}</div>
          </div>
          <div className="label-config-item">
            <div className="label-config-item__label">
              {trans('map.style-control.layer.min-zoom')}
            </div>
            <div className="label-config-item__input">
              <InputSlider
                value={
                  layerZoom['min-zoom'] != null ? layerZoom['min-zoom'] : 0
                }
                onChange={(v) => onChangeMinZoom(v, layer)}
                min={0}
                max={24}
                step={1}
              />
            </div>
          </div>
          <div className="label-config-item">
            <div className="label-config-item__label">
              {trans('map.style-control.layer.max-zoom')}
            </div>
            <div className="label-config-item__input">
              <InputSlider
                value={
                  layerZoom['max-zoom'] != null ? layerZoom['max-zoom'] : 24
                }
                onChange={(v) => onChangeMaxZoom(v, layer)}
                min={0}
                max={24}
                step={1}
              />
            </div>
          </div>
        </div>
      </BaseCollapse>

      <BaseCollapse header={trans('map.style-control.style.title')}>
        {tabs_format.length > 1 && (
          <div className="tab-group-label">
            {tabs_format.map((item, i) => (
              <div
                key={item.trans || item.text || i}
                className={`tab clickable${
                  tabGroup && tabGroup.trans === item.trans ? ' tab-active' : ''
                }`}
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectTabGroup(item);
                }}
              >
                {item.text || (item.trans ? trans(item.trans) : '')}
              </div>
            ))}
          </div>
        )}
        <div className="tab-group-container">
          <div className="label-container">
            {tabGroup &&
              tabGroup.items.map((item, i) => (
                <div
                  key={'key' in item ? String(item.key) : `divider-${i}`}
                  className="clickable"
                  onClick={(e) => {
                    e.stopPropagation();
                    onSelectTab(item);
                  }}
                >
                  {item.type === 'divider' ? (
                    <div className="tab-divider" />
                  ) : (
                    <TabItem
                      value={getTabValue(layer, item)}
                      item={item}
                      text={item.text || (item.trans ? trans(item.trans) : '')}
                      default_value={getDefaultTabValue(layer.type, item)}
                      active={
                        !!tab &&
                        'key' in tab &&
                        'key' in item &&
                        tab.key === item.key
                      }
                      disabled={item.disabled?.(layer)}
                    />
                  )}
                </div>
              ))}
          </div>
          <div className="value-container">
            <div>
              {tab && tab.type !== 'divider' && (
                <>
                  <div className="value-container__label">
                    {tab.text || (tab.trans ? trans(tab.trans) : '')}
                  </div>
                  <TabContent
                    item={tab}
                    value={getTabValue(layer, tab)}
                    onInput={(v) => emitInput(v, tab, layer)}
                    default_value={getDefaultTabValue(layer.type, tab)}
                    trans={trans}
                    mapId={mapId}
                  />
                </>
              )}
            </div>
          </div>
        </div>
      </BaseCollapse>
    </div>
  );
}

// libs/vue/map-dataset/src/modules/StyleControl/style/single-style.vue
<script setup lang="ts">
import {
  applyStyleTabValue,
  applyStyleZoom,
  convertTabWithDefaultConfig,
  DEFAULT_VALUE,
  type Tab,
  type TabConfig,
  TABS,
} from '@hungpvq/map-dataset/style';
import { Collapse, InputSlider } from '@hungpvq/vue-map-core/fields';
import { LayerSpecification } from 'maplibre-gl';
import { computed, onMounted, ref } from 'vue';

import TabContent from '../component/tab-content.vue';
import TabItem from '../component/tab-item.vue';
import { CONFIG_TABS } from './type/default';
const props = defineProps({
  trans: {
    required: true,
  },
  mapId: {
    required: true,
  },
});
const emit = defineEmits(['input', 'update-style']);
const layer = defineModel<LayerSpecification>({ required: true });
const tabs_format = computed<TabConfig[]>(() => {
  const tab = TABS[layer.value.type];
  if (tab.type === 'multi') {
    return tab.tabs.map((x) => ({
      ...x,
      items: convertTabWithDefaultConfig(x.items, CONFIG_TABS),
    }));
  }
  return [
    {
      type: 'single',
      text: 'style',
      items: convertTabWithDefaultConfig(tab.items, CONFIG_TABS),
    },
  ];
});
const default_value = computed(() => DEFAULT_VALUE[layer.value.type]);
const tab_group = ref<TabConfig | undefined>(undefined);
const tab = ref<Tab | undefined>(undefined);
const onSelectTab = (item: Tab) => {
  tab.value = item;
  if (tab.value && (tab.value as any).menu) {
    (tab.value as any).menu = (tab.value as any).menu.map((x: any) => ({
      ...x,
      text: x.text || (props.trans as any)(x.text_trans || '') || '',
      subtitle:
        x.subtitle || (props.trans as any)(x.subtitle_trans || '') || '',
    }));
  }
};
const onSelectTabGroup = (group: TabConfig) => {
  tab_group.value = group;
  if (tab_group.value && tab_group.value.items)
    onSelectTab(tab_group.value.items[0]);
};
const emitInput = (value: unknown, currentTab: Tab) => {
  layer.value = applyStyleTabValue(layer.value, currentTab, value);
  emit('update-style', layer.value);
};
onMounted(() => {
  if (tabs_format.value) onSelectTabGroup(tabs_format.value[0]);
});
const onChangeMinZoom = (zoom: number) => {
  layer.value = applyStyleZoom(layer.value, 'min-zoom', zoom);
  emit('update-style', layer.value);
};
const onChangeMaxZoom = (zoom: number) => {
  layer.value = applyStyleZoom(layer.value, 'max-zoom', zoom);
  emit('update-style', layer.value);
};
</script>
<template lang="">
  <div class="style-edit-container">
    <Collapse>
      <template #header>
        {{ trans('map.style-control.layer.title') }}
      </template>
      <div class="label-config-container">
        <div class="label-config-item">
          <div class="label-config-item__label">
            {{ trans('map.style-control.layer.id') }}
          </div>
          <div class="label-config-item__input">{{ layer.id }}</div>
        </div>
        <div class="label-config-item">
          <div class="label-config-item__label">
            {{ trans('map.style-control.layer.type') }}
          </div>
          <div class="label-config-item__input">{{ layer.type }}</div>
        </div>
        <div class="label-config-item">
          <div class="label-config-item__label">
            {{ trans('map.style-control.layer.min-zoom') }}
          </div>
          <div class="label-config-item__input">
            <InputSlider
              :modelValue="layer['min-zoom'] != null ? layer['min-zoom'] : 0"
              @update:modelValue="onChangeMinZoom($event)"
              min="0"
              max="24"
              step="1"
            />
          </div>
        </div>
        <div class="label-config-item">
          <div class="label-config-item__label">
            {{ trans('map.style-control.layer.max-zoom') }}
          </div>
          <div class="label-config-item__input">
            <InputSlider
              :modelValue="layer['max-zoom'] != null ? layer['max-zoom'] : 24"
              @update:modelValue="onChangeMaxZoom($event)"
              min="0"
              max="24"
              step="1"
            />
          </div>
        </div>
      </div>
    </Collapse>

    <Collapse>
      <template #header>
        {{ trans('map.style-control.style.title') }}
      </template>
      <div class="tab-group-label" v-if="tabs_format && tabs_format.length > 1">
        <div
          v-for="item in tabs_format"
          :key="item.key"
          class="tab clickable"
          :class="{ 'tab-active': tab_group && tab_group.trans == item.trans }"
          @click.stop="onSelectTabGroup(item)"
        >
          {{ item.text || trans(item.trans) }}
        </div>
      </div>
      <div class="tab-group-container">
        <div class="label-container">
          <div v-if="tab_group">
            <div
              v-for="item in tab_group.items"
              :key="item.key"
              class="clickable"
              @click.stop="onSelectTab(item)"
            >
              <div v-if="item.type === 'divider'" class="tab-divider"></div>
              <TabItem
                v-else
                :value="layer[item.part || 'paint'][item.key]"
                :item="item"
                :text="item.text || trans(item.trans)"
                :default_value="default_value[item.part || 'paint'][item.key]"
                :active="tab && tab.key === item.key"
                :disabled="item.disabled && item.disabled(layer)"
              >
              </TabItem>
            </div>
          </div>
        </div>
        <div class="value-container">
          <div>
            <div class="value-container__label" v-if="tab">
              {{ tab.text || trans(tab.trans) }}
            </div>
            <TabContent
              v-if="tab"
              :item="tab"
              :value="layer[tab.part || 'paint'][tab.key]"
              @input="emitInput($event, tab)"
              :default_value="default_value[tab.part || 'paint'][tab.key]"
              :trans="trans"
              :mapId="mapId"
            >
            </TabContent>
          </div>
        </div>
      </div>
    </Collapse>
  </div>
</template>
