// libs/react/map-core/src/components/MapControlGroupButton.tsx
import React, { useMemo } from 'react';
import { MapButton } from './MapButton';
import { MapControlButtonGroupContext } from './MapControlButton';
import { MapIcon } from './MapIcon';

export interface ButtonItem {
  title: string;
  icon: string;
  onClick: (e: React.MouseEvent) => void;
}

export interface MapControlGroupButtonProps extends React.HTMLAttributes<HTMLDivElement> {
  items?: ButtonItem[];
  row?: boolean;
  size?: number | string;
  children?: React.ReactNode;
}

export function MapControlGroupButton({
  items = [],
  row = false,
  size = 32,
  children,
  className = '',
  style,
  ...props
}: MapControlGroupButtonProps) {
  const sizeNum = typeof size === 'string' ? parseInt(size, 10) : size;

  const containerStyle = useMemo(
    () => ({
      width: !row ? `${sizeNum}px` : undefined,
      height: row ? `${sizeNum}px` : undefined,
      ...style,
    }),
    [row, sizeNum, style],
  );

  const classes = [
    'button-container',
    'button-group-container',
    row ? 'button-group-row-container' : 'button-group-column-container',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <MapControlButtonGroupContext.Provider
      value={{ isGroup: true, groupSize: sizeNum }}
    >
      <div className={classes} style={containerStyle} {...props}>
        <div
          className={`button-group-sheet ${
            !row ? 'button-group-sheet-column' : ''
          }`}
          style={{ borderRadius: '150px' }}
        >
          {items.map((item, i) => (
            <MapButton
              key={i}
              height={sizeNum}
              width={sizeNum}
              title={item.title}
              onClick={item.onClick}
            >
              <MapIcon>{item.icon}</MapIcon>
            </MapButton>
          ))}
          {children}
        </div>
      </div>
    </MapControlButtonGroupContext.Provider>
  );
}

// libs/map/core/src/components/MapControlGroupButton.vue
<template>
  <div
    class="button-container button-group-container"
    :class="{
      'button-group-row-container': row,
      'button-group-column-container': !row,
    }"
    :style="containerStyle"
  >
    <div
      class="button-group-sheet"
      :class="{ 'button-group-sheet-column': !row }"
      style="border-radius: 150px"
    >
      <MapButton
        v-for="(item, i) in items"
        :key="i"
        :height="Number(size)"
        :width="Number(size)"
        text
        :title="item.title"
        @click="item.onClick"
      >
        <MapIcon>
          {{ item.icon }}
        </MapIcon>
      </MapButton>
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import type { PropType } from 'vue';
import MapButton from './MapButton.vue';
import MapIcon from './MapIcon.vue';
interface ButtonItem {
  title: string;
  icon: string;
  onClick: (e: MouseEvent) => void;
}
export default {
  name: 'MapControlGroupButton',
  components: { MapButton, MapIcon },
  props: {
    // {title:string,icon:string,onClick:(e)=>{}}
    items: {
      type: Array as PropType<ButtonItem[]>,
      default: () => [],
    },
    row: Boolean,
    size: { type: [Number, String], default: 32 },
  },
  provide() {
    return {
      isGroup: true,
      size: this.size,
    };
  },
  computed: {
    containerStyle(): Record<string, string | undefined> {
      return {
        width: !this.row ? `${this.size}px` : undefined,
        height: this.row ? `${this.size}px` : undefined,
      };
    },
  },
};
</script>

<style scoped>
.button-group-container ::deep(.map-control-button) {
  background-color: unset !important;
}
.button-group-row-container ::deep(.map-control-button:not(:last-child)) {
  border-right: thin solid rgba(0, 0, 0, 0.12);
}
.button-group-column-container ::deep(.map-control-button:not(:first-child)) {
  border-top: thin solid rgba(0, 0, 0, 0.12);
}
.button-group-sheet {
  background-color: #ffffff;
  border-color: #ffffff;
  color: rgba(0, 0, 0, 0.87);
  display: flex;
}
.button-group-sheet-column {
  flex-direction: column;
}
</style>
