// libs/vue/map-dataset/src/modules/HighlightPointer/HighlightPointer.vue
<script setup lang="ts">
import type { HighlightStyle } from '@hungpvq/map-dataset/highlight';
import { destroyHighlightController } from '@hungpvq/map-dataset/highlight';
import { useMap } from '@hungpvq/vue-map-core';
import { onMounted, onUnmounted, watch } from 'vue';
import { useMapHighlight } from '../../store/highlight';

const props = withDefaults(
  defineProps<{
    enableClick?: boolean;
    enableHover?: boolean;
    color?: string;
    durationMs?: number;
  }>(),
  {
    enableClick: false,
    enableHover: false,
  },
);

const { mapId } = useMap();
const hl = useMapHighlight(mapId.value);
let unbind: (() => void) | undefined;

function applyDefaults() {
  const style: HighlightStyle = {};
  if (props.color) style.color = props.color;
  if (props.durationMs != null) style.durationMs = props.durationMs;
  if (Object.keys(style).length) hl.setDefaultStyle(style);
}

onMounted(() => {
  applyDefaults();
  unbind = hl.bindPointer({
    click: props.enableClick,
    hover: props.enableHover,
  });
});

watch(
  () =>
    [props.enableClick, props.enableHover, props.color, props.durationMs] as const,
  () => {
    applyDefaults();
    unbind?.();
    unbind = hl.bindPointer({
      click: props.enableClick,
      hover: props.enableHover,
    });
  },
);

onUnmounted(() => {
  unbind?.();
  destroyHighlightController(mapId.value);
});
</script>

// libs/react/map-dataset/src/modules/HighlightPointer/HighlightPointer.tsx
import type { HighlightStyle } from '@hungpvq/map-dataset/highlight';
import { destroyHighlightController } from '@hungpvq/map-dataset/highlight';
import { useMap } from '@hungpvq/react-map-core';
import { useEffect } from 'react';
import { useMapHighlight } from '../../store/highlight';

export type HighlightPointerProps = {
  enableClick?: boolean;
  enableHover?: boolean;
  color?: string;
  durationMs?: number;
};

/** Bind map pointer to highlight controller (click / hover sources). */
export function HighlightPointer({
  enableClick = false,
  enableHover = false,
  color,
  durationMs,
}: HighlightPointerProps) {
  const { mapId } = useMap();
  const hl = useMapHighlight(mapId);

  useEffect(() => {
    const style: HighlightStyle = {};
    if (color) style.color = color;
    if (durationMs != null) style.durationMs = durationMs;
    if (Object.keys(style).length) hl.setDefaultStyle(style);
    const unbind = hl.bindPointer({ click: enableClick, hover: enableHover });
    return () => {
      unbind();
      destroyHighlightController(mapId);
    };
  }, [hl, mapId, enableClick, enableHover, color, durationMs]);

  return null;
}
