// libs/react/map-core/src/components/MapCopyButton.tsx
import { createCopyFeedback, type MapButtonSize, type MapButtonVariant } from '@hungpvq/map-core';
import { mdiCheck, mdiContentCopy } from '@mdi/js';
import { Icon } from '@mdi/react';
import React, { useEffect, useRef, useState, type MouseEvent } from 'react';
import { MapControlButton } from './MapControlButton';

export interface MapCopyButtonProps
  extends Omit<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    'value' | 'children' | 'onClick' | 'title'
  > {
  /** Text copied to the clipboard. */
  value?: string | number | null;
  title?: string;
  copiedTitle?: string;
  variant?: MapButtonVariant;
  size?: MapButtonSize | string;
  disabled?: boolean;
  /** Icon size in px (passed to @mdi/react as `${iconSize}px`). Dense rows: 14. */
  iconSize?: number;
  className?: string;
}

/**
 * Shared copy action button: clipboard + mdiContentCopy → mdiCheck feedback
 * (~1.5s). Prefer this over ad-hoc MapControlButton + createCopyFeedback.
 */
export function MapCopyButton({
  value = '',
  title = 'Copy',
  copiedTitle = 'Copied',
  variant = 'plain',
  size = 'small',
  disabled = false,
  iconSize = 14,
  className,
  ...props
}: MapCopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const copyFeedbackRef = useRef(
    createCopyFeedback({
      onChange: (key) => setCopied(key === 'copy'),
    }),
  );

  useEffect(() => () => copyFeedbackRef.current.dispose(), []);

  const text = value == null ? '' : String(value);
  const trimmed = text.trim();
  const isDisabled = disabled || !trimmed || trimmed === '—';
  const label = copied ? copiedTitle : title;

  function onClick(e: MouseEvent<HTMLButtonElement>) {
    e.stopPropagation();
    void copyFeedbackRef.current.copy('copy', text);
  }

  return (
    <MapControlButton
      {...props}
      className={className}
      variant={variant}
      size={size}
      disabled={isDisabled}
      title={label}
      aria-label={label}
      onClick={onClick}
    >
      <Icon
        path={copied ? mdiCheck : mdiContentCopy}
        size={`${iconSize}px`}
      />
    </MapControlButton>
  );
}

// libs/vue/map-core/src/components/MapCopyButton.vue
<template>
  <MapControlButton
    v-bind="$attrs"
    :variant="variant"
    :size="size"
    :disabled="isDisabled"
    :title="copied ? copiedTitle : title"
    :aria-label="copied ? copiedTitle : title"
    @click.stop="onCopy"
  >
    <SvgIcon
      :size="iconSize"
      type="mdi"
      :path="copied ? mdiCheck : mdiContentCopy"
    />
  </MapControlButton>
</template>

<script setup lang="ts">
import {
  createCopyFeedback,
  type MapButtonSize,
  type MapButtonVariant,
} from '@hungpvq/map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCheck, mdiContentCopy } from '@mdi/js';
import { computed, onBeforeUnmount, ref } from 'vue';
import MapControlButton from './MapControlButton.vue';

/**
 * Shared copy action button: clipboard + mdiContentCopy → mdiCheck feedback
 * (~1.5s). Prefer this over ad-hoc MapControlButton + createCopyFeedback.
 */

defineOptions({
  name: 'MapCopyButton',
  inheritAttrs: false,
});

const props = withDefaults(
  defineProps<{
    value?: string | number | null;
    title?: string;
    copiedTitle?: string;
    variant?: MapButtonVariant;
    size?: MapButtonSize | string;
    disabled?: boolean;
    /** SvgIcon size (px). Dense rows usually 14. */
    iconSize?: string | number;
  }>(),
  {
    value: '',
    title: 'Copy',
    copiedTitle: 'Copied',
    variant: 'plain',
    size: 'small',
    disabled: false,
    iconSize: 14,
  },
);

const copied = ref(false);
const copyFeedback = createCopyFeedback({
  onChange: (key) => {
    copied.value = key === 'copy';
  },
});

onBeforeUnmount(() => copyFeedback.dispose());

const text = computed(() =>
  props.value == null ? '' : String(props.value),
);

const isDisabled = computed(() => {
  if (props.disabled) return true;
  const t = text.value.trim();
  return !t || t === '—';
});

function onCopy() {
  void copyFeedback.copy('copy', text.value);
}
</script>
