// libs/react/map-core/src/components/MapControlGroupButton.tsx
import { type MapButtonSize, resolveMapButtonSizePx } from '@hungpvq/map-core';
import React, { useMemo } from 'react';

import { MapButton } from './MapButton';
import { MapControlButtonGroupContext } from './MapControlButton';
import { MapIcon } from './MapIcon';

export interface ButtonItem {
  title: string;
  icon: string;
  onClick: (e: React.MouseEvent) => void;
}

export interface MapControlGroupButtonProps extends React.HTMLAttributes<HTMLDivElement> {
  items?: ButtonItem[];
  row?: boolean;
  /** small | medium | large | number (px) */
  size?: MapButtonSize | string;
  children?: React.ReactNode;
}

export function MapControlGroupButton({
  items = [],
  row = false,
  size = 'medium',
  children,
  className = '',
  style,
  ...props
}: MapControlGroupButtonProps) {
  const sizePx = resolveMapButtonSizePx(size);

  const containerStyle = useMemo(
    () => ({
      width: !row ? `${sizePx}px` : undefined,
      height: row ? `${sizePx}px` : undefined,
      ...style,
    }),
    [row, sizePx, style],
  );

  const classes = [
    'button-container',
    'button-group-container',
    row ? 'button-group-row-container' : 'button-group-column-container',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <MapControlButtonGroupContext.Provider
      value={{ isGroup: true, groupSize: sizePx }}
    >
      <div
        className={classes}
        style={containerStyle}
        {...props}
      >
        <div
          className={`button-group-sheet ${
            !row ? 'button-group-sheet-column' : ''
          }`}
          style={{ borderRadius: '150px' }}
        >
          {items.map((item, i) => (
            <MapButton
              key={i}
              size={sizePx}
              title={item.title}
              onClick={item.onClick}
            >
              <MapIcon>{item.icon}</MapIcon>
            </MapButton>
          ))}
          {children}
        </div>
      </div>
    </MapControlButtonGroupContext.Provider>
  );
}

// libs/vue/map-core/src/components/MapControlGroupButton.vue
<template>
  <div
    class="button-container button-group-container"
    :class="[
      {
        'button-group-row-container': row,
        'button-group-column-container': !row,
      },
      attrsClass,
    ]"
    :style="containerStyle"
  >
    <div
      class="button-group-sheet"
      :class="{ 'button-group-sheet-column': !row }"
      style="border-radius: 150px"
    >
      <MapButton
        v-for="(item, i) in items"
        :key="i"
        :size="resolvedSizePx"
        :title="item.title"
        @click="item.onClick"
      >
        <MapIcon>
          {{ item.icon }}
        </MapIcon>
      </MapButton>
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import type { PropType } from 'vue';
import MapButton from './MapButton.vue';
import MapIcon from './MapIcon.vue';
import {
  isMapButtonSize,
  resolveMapButtonSizePx,
  type MapButtonSize,
} from '@hungpvq/map-core';

interface ButtonItem {
  title: string;
  icon: string;
  onClick: (e: MouseEvent) => void;
}
export default {
  name: 'MapControlGroupButton',
  components: { MapButton, MapIcon },
  inheritAttrs: false,
  props: {
    items: {
      type: Array as PropType<ButtonItem[]>,
      default: () => [],
    },
    row: Boolean,
    /** small | medium | large | number (px) */
    size: {
      type: [Number, String] as PropType<MapButtonSize | string>,
      default: 'medium',
      validator: (v: unknown) => isMapButtonSize(v),
    },
  },
  provide() {
    return {
      isGroup: true,
      size: this.resolvedSizePx,
    };
  },
  computed: {
    resolvedSizePx(): number {
      return resolveMapButtonSizePx(this.size);
    },
    attrsClass(): unknown {
      return this.$attrs.class;
    },
    containerStyle(): Record<string, string | undefined> {
      return {
        width: !this.row ? `${this.resolvedSizePx}px` : undefined,
        height: this.row ? `${this.resolvedSizePx}px` : undefined,
      };
    },
  },
};
</script>
