// apps/react/demo-map/src/layout/AsideControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemSideBar } from '@hungpvq/react-draggable';
import {
  defaultMapProps,
  MapCommonButton,
  ModuleContainer,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import { mdiMenu } from '@mdi/js';
import { useEffect } from 'react';
import { Link } from 'react-router';
import './demo-nav.css';

const NAV_ITEMS = [
  { to: '/', label: 'Home (All Map)' },
  { to: '/map-core', label: 'Map - Core' },
  { to: '/language', label: 'Language' },
  { to: '/minimal', label: 'Minimal starter' },
  { to: '/map-dataset', label: 'Map - Dataset (all)' },
  { to: '/worker-sample', label: 'Worker - Sample' },
  { to: '/toolbar', label: 'Map - Toolbar' },
  { to: '/mobile-menu', label: 'Map - Mobile menu' },
  { to: '/basemap', label: 'BaseMap' },
  { to: '/basemap-error', label: 'Basemap error' },
  { to: '/multi-map', label: 'Multi-map' },
  { to: '/measurement', label: 'Measurement' },
  { to: '/dataset-highlight', label: 'Dataset - Highlight' },
  { to: '/dataset-identify', label: 'Dataset - Identify' },
  { to: '/dataset-identify-present', label: 'Dataset - Identify present' },
  { to: '/dataset-menu', label: 'Dataset - Menu' },
  { to: '/dataset-list', label: 'Dataset - List' },
  { to: '/registry-control', label: 'UniversalRegistry - Controls' },
  { to: '/dataset-data-management', label: 'Dataset - Data management' },
  { to: '/dataset-attribute-table', label: 'Dataset - Attribute table' },
  { to: '/dataset-geo-export', label: 'Dataset - Geo export' },
  { to: '/story-telling', label: 'Story telling' },
  { to: '/story-telling-gps', label: 'Story telling GPS' },
  { to: '/legend', label: 'Legend' },
  { to: '/draw', label: 'Draw' },
];

export function AsideControl(props: WithMapPropType & { show?: boolean }) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps } = useMap({ ...merged, controlId: 'asideControl' });
  const { trans, registerLocale } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);

  useEffect(() => {
    registerLocale('en', { map: { 'aside-control': { title: 'Aside Control' } } });
  }, [registerLocale]);

  const { state, control } = useToolbarControl(mapId, merged, {
    kind: 'single',
    id: 'asideControl',
    getState: () => ({
      visible: true,
      active: show,
      title: trans('map.aside-control.title'),
      icon: { type: 'mdi' as const, path: mdiMenu },
    }),
    onClick: () => toggleShow(),
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) => (
        <DraggableItemSideBar
          show={show}
          onUpdateShow={(v) => toggleShow(!!v)}
          title={trans('map.aside-control.title')}
          titleNode={
            <span className="aside-control__title">
              {trans('map.aside-control.title')}
            </span>
          }
          containerId={bind.containerId}
        >
          <ul className="v-list">
            {NAV_ITEMS.map((item) => (
              <li key={item.to} className="v-list-item">
                <Link to={item.to} onClick={() => toggleShow(false)}>
                  {item.label}
                </Link>
              </li>
            ))}
          </ul>
        </DraggableItemSideBar>
      )}
    />
  );
}

// apps/vue/demo-map/src/layout/aside-control.vue
<template lang="">
  <ModuleContainer v-bind="moduleContainerProps" :active="show">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>

    <template #draggable="props">
      <DraggableItemSideBar
        :containerId="props.containerId"
        v-model:show="show"
        :title="trans('map.aside-control.title')"
      >
        <template #title>
          <span class="aside-control__title">
            {{ trans('map.aside-control.title') }}
          </span>
        </template>
        <v-list>
          <v-list-item>
            <RouterLink to="/">Home </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/map-core">Map - Core </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/language">Language </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/minimal">Minimal starter </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/worker-sample">Worker - Sample </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/toolbar">Map - Toolbar </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/mobile-menu">Map - Mobile menu </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/legend">Legend </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/story-telling">Story telling </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/story-telling-gps">Story telling GPS </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/basemap">BaseMap </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/basemap-error">Basemap error </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/multi-map">Multi-map </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/measurement">Measurement </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-highlight"
              >Dataset - Highlight
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-identify">Dataset - Identify </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-identify-present"
              >Dataset - Identify present
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-menu">Dataset - Menu </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-list">Dataset - List </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/registry-control"
              >UniversalRegistry - Controls
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-data-management"
              >Dataset - Data management
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-attribute-table"
              >Dataset - Attribute table
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-geo-export"
              >Dataset - Geo export
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/draw">Draw </RouterLink>
          </v-list-item>
        </v-list>
      </DraggableItemSideBar>
    </template>
  </ModuleContainer>
</template>
<script>
import { VList, VListItem } from '@hungpvq/ui-core';
import { DraggableItemSideBar } from '@hungpvq/vue-draggable';
import {
  makeShowProps,
  MapCommonButton,
  ModuleContainer,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
  withMapProps,
} from '@hungpvq/vue-map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { mdiMenu } from '@mdi/js';
import { RouterLink } from 'vue-router';
export default {
  name: 'AsideControl',
  components: {
    VList,
    DraggableItemSideBar,
    ModuleContainer,
    VListItem,
    RouterLink,
    MapCommonButton,
  },
  props: {
    ...withMapProps,
    ...makeShowProps({ show: false }),
  },
  setup(props) {
    const path = {
      icon: mdiMenu,
    };
    const [show, toggleShow] = useShow(props.show);
    const { mapId, moduleContainerProps } = useMap({
      ...props,
      controlId: 'asideControl',
    });
    const { trans, registerLocale } = useLang(mapId.value);

    registerLocale('en', {
      map: {
        'aside-control': {
          title: 'Aside Control',
        },
      },
    });

    const { state, control } = useToolbarControl(mapId.value, props, {
      id: 'asideControl',
      getState() {
        return mdiButtonState(path.icon, {
          visible: true,
          title: trans.value('map.aside-control.title'),
        });
      },
      onClick() {
        toggleShow();
      },
    });
    return {
      state,
      control,
      show,
      toggleShow,
      moduleContainerProps,
      trans,
      path,
    };
  },
};
</script>
<style lang=""></style>
