// libs/vue/map-core/src/extra/measurement/modules/MeasurementSettingPopup.vue
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="slotProps">
      <DraggableItemPopup
        v-bind="{ ...slotProps, ...popUpPosition, ...panelBind }"
        v-if="c_show"
        v-model:show="c_show"
        :title="trans('map.measurement.setting.title')"
      >
        <div class="map-measurement-setting">
          <MeasurementSettingFields :fields="fields" />
          <CrsDisplaySettings v-if="measurementType === 'point'" />
          <FieldGeometry
            @update:modelValue="setValue"
            :modelValue="model"
            :maxLength="maxLength"
            @click:fillbound="onFlyTo"
            :title="trans('map.measurement.setting.field.data')"
            :titleActionDownload="trans('map.measurement.action.download')"
            :titleActionFillBound="trans('map.measurement.action.fly-to')"
            :titleActionAddPoint="trans('map.measurement.action.add-point')"
          />
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>

<script setup lang="ts">
import {
  type CoordinatesNumber,
  type DraftCoordinatesNumber,
  fitBounds,
  toCoordinatesNumberList,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { IViewSettingField } from '@hungpvq/map-core/measurement';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import type { Feature, FeatureCollection, Geometry } from 'geojson';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import ModuleContainer from '../../../modules/ModuleContainer/ModuleContainer.vue';
import { useLang } from '../../lang/hook';
import { useRegisterMapControl } from '../../registry/useRegisterMapControl';
import FieldGeometry from './setting/field-geometry.vue';
import MeasurementSettingFields from './setting/fields-show.vue';
import CrsDisplaySettings from '../../crs/modules/CrsDisplaySettings/CrsDisplaySettings.vue';
const props = withDefaults(
  defineProps<
    WithMapPropType & {
      maxLength?: number;
      fields?: IViewSettingField[];
      measurementType?: string;
      popUpPosition?: {
        top: number;
        right: number;
        width: number;
        height: number;
      };
    }
  >(),
  {
    ...defaultMapProps,
    maxLength: 0,
    fields: () => [{ text: 'Status', value: 'waiting...' }],
    popUpPosition: () => ({
      top: 50,
      right: 40,
      width: 350,
      height: 300,
    }),
  },
);
const { callMap, moduleContainerProps, mapId } = useMap(props);
const { trans } = useLang(mapId.value);
const model = defineModel<CoordinatesNumber[]>({
  default: () => [],
});
const c_show = defineModel('show', { default: false });
const { panelBind } = useRegisterMapControl(mapId, {
  id: 'mapMeasurementSetting',
  panelKind: 'popup',
  title: () => trans.value('map.measurement.setting.title'),
  buttonPosition: () => props.position,
  show: c_show,
  setShow: (value) => {
    c_show.value = value;
  },
  initialPanelPosition: {
    top: props.popUpPosition.top,
    right: props.popUpPosition.right,
  },
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
    maxLength: props.maxLength,
    measurementType: props.measurementType,
  }),
  actions: [
    {
      type: 'mapMeasurementSetting',
      run: () => {
        c_show.value = !c_show.value;
      },
    },
  ],
});
const onFlyTo = (geometry: Geometry | Feature | FeatureCollection) => {
  callMap((map) => {
    fitBounds(map, geometry);
  });
};
function setValue(value: DraftCoordinatesNumber[]) {
  model.value = toCoordinatesNumberList(value);
}
</script>

// libs/react/map-core/src/extra/measurement/modules/MeasurementSettingPopup.tsx
import {
  type CoordinatesNumber,
  type DraftCoordinatesNumber,
  fitBounds,
  toCoordinatesNumberList,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { type IViewSettingField } from '@hungpvq/map-core/measurement';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import type { Feature, FeatureCollection, Geometry } from 'geojson';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { ModuleContainer } from '../../../modules/ModuleContainer/ModuleContainer';
import { useLang } from '../../lang/hook';
import { useRegisterMapControl } from '../../registry/useRegisterMapControl';
import { FieldGeometry } from './setting/field-geometry';
import { MeasurementSettingFields } from './setting/fields-show';
import { CrsDisplaySettings } from '../../crs/CrsDisplaySettings';

type Coord = DraftCoordinatesNumber;

export interface MeasurementSettingPopupProps extends WithMapPropType {
  show?: boolean;
  onUpdateShow?: (show: boolean) => void;
  value?: Coord[];
  onChange?: (value: CoordinatesNumber[]) => void;
  maxLength?: number;
  fields?: IViewSettingField[];
  measurementType?: string;
  popUpPosition?: {
    top?: number;
    right?: number;
    width?: number;
    height?: number;
  };
}

export function MeasurementSettingPopup({
  show = false,
  onUpdateShow,
  value = [],
  onChange,
  maxLength = 0,
  fields = [{ text: 'Status', value: 'waiting...' }],
  measurementType,
  popUpPosition = { top: 50, right: 40, width: 350, height: 300 },
  ...mapProps
}: MeasurementSettingPopupProps) {
  const merged = { ...defaultMapProps, ...mapProps };
  const { callMap, moduleContainerProps, mapId } = useMap({ ...merged, controlId: 'mapMeasurementSetting' });
  const { trans } = useLang(mapId);
  const { panelBind } = useRegisterMapControl(mapId, {
    id: 'mapMeasurementSetting',
    panelKind: 'popup',
    title: trans('map.measurement.setting.title'),
    buttonPosition: merged.position,
    show,
    setShow: (v) => onUpdateShow?.(v),
    initialPanelPosition: {
      top: popUpPosition.top,
      right: popUpPosition.right,
    },
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
      measurementType,
    }),
    actions: [
      {
        type: 'mapMeasurementSetting',
        run: () => onUpdateShow?.(!show),
      },
    ],
  });

  function onFlyTo(geometry: Geometry | Feature | FeatureCollection) {
    callMap((map) => {
      fitBounds(map, geometry);
    });
  }

  function setValue(next: Coord[]) {
    onChange?.(toCoordinatesNumberList(next));
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            {...bind}
            {...popUpPosition}
            {...panelBind}
            show={show}
            onUpdateShow={(v) => onUpdateShow?.(!!v)}
            title={trans('map.measurement.setting.title')}
            width={popUpPosition.width ?? 350}
            height={popUpPosition.height ?? 300}
          >
            <div className="map-measurement-setting">
              <MeasurementSettingFields fields={fields} />
              {measurementType === 'point' ? <CrsDisplaySettings /> : null}
              <FieldGeometry
                value={value}
                maxLength={maxLength}
                onChange={setValue}
                onClickFillBound={onFlyTo}
                title={trans('map.measurement.setting.field.data')}
                titleActionDownload={trans('map.measurement.action.download')}
                titleActionFillBound={trans('map.measurement.action.fly-to')}
                titleActionAddPoint={trans('map.measurement.action.add-point')}
              />
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}
