// libs/react/map-core/src/modules/SettingControl/SettingControl.tsx
import {
  SETTING_CONTROL_LOCALE,
  type WithMapPropType,
} from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiCog } from '@mdi/js';
import type { SpriteSpecification } from 'maplibre-gl';
import { useEffect, useState } from 'react';
import { MapCommonButton } from '../../components/MapCommonButton';
import { useLang, useRegisterMapControl } from '../../extra';
import { useToolbarControl } from '../../extra/toolbar';
import { BaseButton, InputText } from '../../field';
import { defaultMapProps, useMap, useShow } from '../../hooks';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

export interface SettingControlProps extends WithMapPropType {
  show?: boolean;
}

type SettingState = {
  zoom?: number;
  center: [number, number];
  sprite?: string;
  glyphs?: string;
};

function spriteToInput(sprite?: SpriteSpecification): string {
  if (sprite == null) return '';
  return typeof sprite === 'string' ? sprite : JSON.stringify(sprite);
}

function inputToSprite(value?: string): SpriteSpecification | undefined {
  if (!value?.trim()) return undefined;
  try {
    const parsed = JSON.parse(value);
    if (typeof parsed === 'object' && parsed !== null) {
      return parsed as SpriteSpecification;
    }
  } catch {
    // keep as url string
  }
  return value;
}

export function SettingControl(props: SettingControlProps) {
  const mergedProps = { ...defaultMapProps, ...props };
  const { callMap, mapId, moduleContainerProps, order } = useMap({ ...mergedProps, controlId: 'mapSettingControl' });
  const { trans, setLocaleDefault } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);
  const [setting, setSetting] = useState<SettingState>({
    zoom: undefined,
    center: [0, 0],
    sprite: undefined,
    glyphs: undefined,
  });

  useEffect(() => {
    setLocaleDefault(SETTING_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  function loadCurrentView() {
    callMap((map) => {
      const style = map.getStyle();
      setSetting({
        zoom: map.getZoom(),
        center: [
          +map.getCenter().lng.toFixed(6),
          +map.getCenter().lat.toFixed(6),
        ],
        sprite: spriteToInput(style.sprite),
        glyphs: style.glyphs,
      });
    });
  }

  function handleToggle() {
    const nextShow = !show;
    toggleShow(nextShow);
    if (nextShow) {
      loadCurrentView();
    }
  }

  const { panelBind } = useRegisterMapControl(mapId, {
    id: 'mapSettingControl',
    panelKind: 'popup',
    title: trans('map.setting-control.title'),
    buttonPosition: mergedProps.position,
    show,
    setShow: toggleShow,
    getProps: () => ({
      position: mergedProps.position,
      controlLayout: mergedProps.controlLayout,
    }),
    actions: [{ type: 'mapSettingControl', run: () => handleToggle() }],
  });

  function onSetSetting() {
    callMap((map) => {
      if (setting.zoom) map.setZoom(setting.zoom);
      if (setting.center) map.setCenter(setting.center);
      const style = map.getStyle();
      const sprite = inputToSprite(setting.sprite);
      if (sprite) {
        style.sprite = sprite;
      }
      if (setting.glyphs) {
        style.glyphs = setting.glyphs;
      }
      map.setStyle(style);
    });
  }

  const { state, control } = useToolbarControl(mapId, mergedProps, {
    kind: 'single',
    id: 'mapSettingControl',
    getState: () => ({
      visible: true,
      title: trans('map.setting-control.title'),
      order,
      icon: { type: 'mdi' as const, path: mdiCog },
    }),
    onClick: () => handleToggle(),
  });

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => toggleShow(!!v)}
            title={trans('map.setting-control.title')}
            height={400}
            width={400}
            {...bind}
            {...panelBind}
          >
            <div className="map-setting-control">
              <div className="map-setting-control__fields">
                <div>
                  <label className="map-setting-control__center-label">
                    {trans('map.setting-control.field.center')}
                  </label>
                  <div className="map-setting-control__center">
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[0])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [Number(v), prev.center[1]],
                        }))
                      }
                    />
                    <InputText
                      type="number"
                      step="0.0000001"
                      value={String(setting.center[1])}
                      onChange={(v) =>
                        setSetting((prev) => ({
                          ...prev,
                          center: [prev.center[0], Number(v)],
                        }))
                      }
                    />
                  </div>
                </div>
                <div>
                  <InputText
                    label={trans('map.setting-control.field.zoom')}
                    value={setting.zoom != null ? String(setting.zoom) : ''}
                    onChange={(v) =>
                      setSetting((prev) => ({
                        ...prev,
                        zoom: v === '' ? undefined : Number(v),
                      }))
                    }
                  />
                </div>
                <div>
                  <InputText
                    label={trans('map.setting-control.field.sprite')}
                    value={setting.sprite ?? ''}
                    onChange={(v) =>
                      setSetting((prev) => ({ ...prev, sprite: v }))
                    }
                  />
                </div>
                <div>
                  <InputText
                    label={trans('map.setting-control.field.glyphs')}
                    value={setting.glyphs ?? ''}
                    onChange={(v) =>
                      setSetting((prev) => ({ ...prev, glyphs: v }))
                    }
                  />
                </div>
              </div>
              <BaseButton
                className="map-setting-control__apply"
                onClick={onSetSetting}
              >
                {trans('map.setting-control.btn.apply')}
              </BaseButton>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}

// libs/map/core/src/modules/SettingControl/SettingControl.vue
<script setup lang="ts">
import { type WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { mdiCog } from '@mdi/js';
import type { SpriteSpecification } from 'maplibre-gl';
import { ref } from 'vue';
import MapCommonButton from '../../components/MapCommonButton.vue';
import { useLang, useToolbarControl } from '../../extra';
import { BaseButton, InputText } from '../../field';
import { defaultMapProps, useMap, useShow, WithShowProps } from '../../hooks';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const [show, setShow] = useShow(props.show);
const { callMap, mapId, moduleContainerProps, order } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);

setLocaleDefault({
  map: {
    'setting-control': {
      title: 'Setting',
      field: {
        zoom: 'Zoom',
        center: 'Center',
        sprite: 'Sprite url',
        glyphs: 'Glyphs url',
      },
      btn: {
        apply: 'Apply',
      },
    },
  },
});
function onToggleShow() {
  setShow(!show.value);
  if (show.value) {
    callMap((_map) => {
      setting.value.zoom = _map.getZoom();
      setting.value.center = [
        +_map.getCenter().lng.toFixed(6),
        +_map.getCenter().lat.toFixed(6),
      ];
      setting.value.sprite = _map.getStyle().sprite;
      setting.value.glyphs = _map.getStyle().glyphs;
    });
  }
}
const setting = ref<{
  zoom?: number;
  center: [number, number];
  sprite?: SpriteSpecification;
  glyphs?: string;
}>({
  zoom: undefined,
  center: [0, 0],
  sprite: undefined,
  glyphs: undefined,
});
const onSetSetting = () => {
  callMap((map) => {
    if (setting.value.zoom) map.setZoom(setting.value.zoom);
    if (setting.value.center) map.setCenter(setting.value.center);
    const style = map.getStyle();
    if (setting.value.sprite) {
      style.sprite = setting.value.sprite;
    }
    if (setting.value.glyphs) {
      style.glyphs = setting.value.glyphs;
    }
    map.setStyle(style);
  });
};
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapSettingControl',
  getState() {
    return {
      visible: true,
      title: trans.value('map.setting-control.title'),
      order: order.value,
      icon: {
        type: 'mdi',
        path: mdiCog,
      },
    };
  },
  onClick() {
    onToggleShow();
  },
});
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton v-if="state" :option="state" @click="control.onAction">
      </MapCommonButton>
    </template>

    <template #draggable="props">
      <DraggableItemPopup
        v-if="show"
        :height="400"
        :width="400"
        v-bind="props"
        v-model:show="show"
        :title="trans('map.setting-control.title')"
      >
        <div class="setting-container">
          <div class="setting-field-container">
            <div>
              <label>
                {{ trans('map.setting-control.field.center') }}
              </label>
              <div class="setting-center-container">
                <InputText
                  v-model="setting.center[0]"
                  type="number"
                  step="0.0000001"
                />
                <InputText
                  v-model="setting.center[1]"
                  type="number"
                  step="0.0000001"
                />
              </div>
            </div>
            <div>
              <InputText
                :label="trans('map.setting-control.field.zoom')"
                v-model="setting.zoom"
              />
            </div>
            <div>
              <InputText
                :label="trans('map.setting-control.field.sprite')"
                v-model="setting.sprite"
              />
            </div>
            <div>
              <InputText
                :label="trans('map.setting-control.field.glyphs')"
                v-model="setting.glyphs"
              />
            </div>
          </div>

          <base-button class="btn-container" @click="onSetSetting()">
            {{ trans('map.setting-control.btn.apply') }}
          </base-button>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>
<style>
.setting-container {
  padding: 8px;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: auto;
}
.setting-field-container > div {
  padding: 4px;
}
.setting-container .setting-field-container {
  height: 100%;
  padding: 8px;
  flex-grow: 1;
  overflow: auto;
}
.setting-container .btn-container {
  flex-grow: 0;
  padding: 8px;
}
.setting-center-container {
  display: flex;
}
.setting-center-container > *:not(:last-child) {
  padding-right: 4px;
}
</style>
