// libs/vue/map-dataset/src/extra/menu/dataset-menus.vue
<template>
  <div
    v-if="hasAnything"
    class="dataset-menus"
    :class="rootClass"
  >
    <DatasetMenuButton
      v-for="(menu, i) in inlineMenus"
      :key="menu.id || `inline-${i}`"
      :item="menu"
      :data="data"
      :mapId="mapId"
      :disabled="disabled || isDisabled(menu)"
      @click="onInlineClick(menu, $event)"
    />
    <MapControlButton
      v-if="overflowMenus.length > 0"
      variant="plain"
      size="small"
      :disabled="disabled"
      aria-label="Open menu"
      aria-haspopup="menu"
      @click.prevent.stop="openOverflow"
    >
      <SvgIcon size="14" type="mdi" :path="mdiDotsVertical" />
    </MapControlButton>
    <ContextMenu ref="contextMenuRef">
      <ul class="context-menu layer-context-menu dataset-menus__context">
        <template
          v-for="(option, index) in overflowMenus"
          :key="option.id || index"
        >
          <RegistryItem
            v-if="isMenuItemCustomComponent(option)"
            :componentKey="option.componentMenuKey"
            :item="option"
            :data="data"
            :mapId="mapId"
            :getGroups="getGroups"
            :disabled="disabled || isDisabled(option)"
            :location="getMenuItemLocation(option)"
            @close="closeOverflow"
          />
          <li
            v-else
            class="layer-context-menu__item"
            :class="[
              option.class,
              option.type === 'divider' ? 'layer-context-menu__divider' : '',
              isDisabled(option) ? 'is-disabled' : '',
            ]"
            @click.stop="onOverflowClick(option, $event)"
          >
            <template v-if="option.type === 'divider'">
              <div class="layer-context-menu__divider-line" />
            </template>
            <template v-else>
              <div class="layer-context-menu__item-icon">
                <SvgIcon
                  size="16"
                  type="mdi"
                  :path="('icon' in option && option.icon) || mdiCircleSmall"
                />
              </div>
              <span>{{ 'name' in option ? option.name : '' }}</span>
            </template>
          </li>
        </template>
      </ul>
    </ContextMenu>
  </div>
</template>

<script setup lang="ts">
import type { IDataset } from '@hungpvq/map-dataset';
import type {
  ListViewGroupOption,
  MenuAction,
  MenuActionLocation,
  MenuContextSource,
} from '@hungpvq/map-dataset/menu';
import {
  createMenuConditionContext,
  getMenuItemLocation,
  handleMenuAction,
  isMenuItemCustomComponent,
  isMenuItemDisabled,
  partitionMenuActions,
} from '@hungpvq/map-dataset/menu';
import { MapControlButton, RegistryItem } from '@hungpvq/vue-map-core';
import { ContextMenu } from '@hungpvq/vue-draggable';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiCircleSmall, mdiDotsVertical } from '@mdi/js';
import { computed, ref } from 'vue';
import { useMenuConditionSource } from './condition-context';
import DatasetMenuButton from './dataset-menu-button.vue';

defineOptions({ name: 'DatasetMenus' });

const props = withDefaults(
  defineProps<{
    menus: MenuAction[];
    data: IDataset;
    mapId?: string;
    value?: unknown;
    /** Which locations to show after partition. Default: extra + menu (row). */
    locations?: MenuActionLocation[];
    disabled?: boolean;
    class?: string;
    getGroups?: () => ListViewGroupOption[];
    /** Extra condition context merged with inject (e.g. readonly flags). */
    menuContext?: MenuContextSource | MenuContextSource[];
  }>(),
  {
    locations: () => ['extra', 'menu'],
  },
);

const injectedMenuContext = useMenuConditionSource();
const conditionCtx = computed(() =>
  createMenuConditionContext(props.data, {
    mapId: props.mapId,
    context: [
      injectedMenuContext,
      ...(Array.isArray(props.menuContext)
        ? props.menuContext
        : props.menuContext
          ? [props.menuContext]
          : []),
    ],
  }),
);

const partitioned = computed(() =>
  partitionMenuActions(props.menus, conditionCtx.value),
);

const locationSet = computed(() => new Set(props.locations));

const inlineMenus = computed(() => {
  const list: MenuAction[] = [];
  for (const loc of props.locations) {
    if (loc === 'menu') continue;
    list.push(...partitioned.value[loc]);
  }
  return list;
});

const overflowMenus = computed(() =>
  locationSet.value.has('menu') ? partitioned.value.menu : [],
);

const hasAnything = computed(
  () => inlineMenus.value.length > 0 || overflowMenus.value.length > 0,
);

const rootClass = computed(() => props.class);

const contextMenuRef = ref<{
  open: () => void;
  close: () => void;
} | null>(null);

function isDisabled(option: MenuAction) {
  return isMenuItemDisabled(option, conditionCtx.value);
}

function runAction(menu: MenuAction, event: MouseEvent) {
  if (menu.type === 'divider') return;
  if (props.disabled || isDisabled(menu)) return;
  handleMenuAction(menu, {
    event,
    layer: props.data,
    mapId: props.mapId,
    value: props.value,
  });
}

function onInlineClick(menu: MenuAction, event: MouseEvent) {
  runAction(menu, event);
}

function openOverflow(event: MouseEvent) {
  contextMenuRef.value?.open(event);
}

function closeOverflow() {
  contextMenuRef.value?.close();
}

function onOverflowClick(menu: MenuAction, event: MouseEvent) {
  runAction(menu, event);
  closeOverflow();
}
</script>

// libs/react/map-dataset/src/extra/menu/dataset-menus.tsx
import type { IDataset } from '@hungpvq/map-dataset';
import type {
  ListViewGroupOption,
  MenuAction,
  MenuActionLocation,
  MenuContextSource,
} from '@hungpvq/map-dataset/menu';
import {
  createMenuConditionContext,
  getMenuItemLocation,
  handleMenuAction,
  isMenuItemCustomComponent,
  isMenuItemDisabled,
  partitionMenuActions,
} from '@hungpvq/map-dataset/menu';
import { ContextMenu, type ContextMenuRef } from '@hungpvq/react-draggable';
import { MapControlButton, RegistryItem } from '@hungpvq/react-map-core';
import { mdiCircleSmall, mdiDotsVertical } from '@mdi/js';
import { Icon } from '@mdi/react';
import { useMemo, useRef } from 'react';

import { useMenuConditionContext } from './condition-context';
import { DatasetMenuButton } from './dataset-menu-button';

const ICON_SIZE = '14px';

export function DatasetMenus<T extends IDataset = IDataset>({
  menus,
  data,
  mapId,
  value,
  locations = ['extra', 'menu'],
  disabled,
  className,
  getGroups,
  menuContext,
}: {
  /** Prefer `MenuAction[]`; `any` avoids variance friction with typed list menus. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  menus: MenuAction<any>[];
  data: T;
  mapId?: string;
  value?: unknown;
  locations?: MenuActionLocation[];
  disabled?: boolean;
  className?: string;
  getGroups?: () => ListViewGroupOption[];
  menuContext?: MenuContextSource | MenuContextSource[];
}) {
  const injectedMenuContext = useMenuConditionContext();
  const conditionCtx = useMemo(
    () =>
      createMenuConditionContext(data, {
        mapId,
        context: [
          injectedMenuContext as MenuContextSource,
          ...(Array.isArray(menuContext)
            ? menuContext
            : menuContext
              ? [menuContext]
              : []),
        ],
      }),
    [data, mapId, injectedMenuContext, menuContext],
  );

  const partitioned = useMemo(
    () => partitionMenuActions(menus as MenuAction[], conditionCtx),
    [menus, conditionCtx],
  );

  const locationSet = useMemo(() => new Set(locations), [locations]);

  const inlineMenus = useMemo(() => {
    const list: MenuAction[] = [];
    for (const loc of locations) {
      if (loc === 'menu') continue;
      list.push(...partitioned[loc]);
    }
    return list;
  }, [locations, partitioned]);

  const overflowMenus = useMemo(
    () => (locationSet.has('menu') ? partitioned.menu : []),
    [locationSet, partitioned],
  );

  const contextMenuRef = useRef<ContextMenuRef>(null);

  if (inlineMenus.length === 0 && overflowMenus.length === 0) {
    return null;
  }

  function isDisabled(option: MenuAction) {
    return isMenuItemDisabled(option, conditionCtx);
  }

  function runAction(menu: MenuAction, event: React.MouseEvent) {
    if (menu.type === 'divider') return;
    if (disabled || isDisabled(menu)) return;
    handleMenuAction(menu, {
      event: event.nativeEvent,
      layer: data,
      mapId: mapId ?? '',
      value,
      context: conditionCtx.context,
    });
  }

  return (
    <div className={['dataset-menus', className].filter(Boolean).join(' ')}>
      {inlineMenus.map((menu, i) => (
        <DatasetMenuButton
          key={menu.id || `inline-${i}`}
          menu={menu as MenuAction<T>}
          item={data}
          mapId={mapId}
          disabled={disabled || isDisabled(menu)}
          onAction={({ event, action }) =>
            runAction(action as MenuAction, event)
          }
        />
      ))}
      {overflowMenus.length > 0 && (
        <>
          <MapControlButton
            variant="plain"
            size="small"
            disabled={disabled}
            aria-label="Open menu"
            aria-haspopup="menu"
            onClick={(event) => {
              event.preventDefault();
              event.stopPropagation();
              contextMenuRef.current?.open(event);
            }}
          >
            <Icon
              path={mdiDotsVertical}
              size={ICON_SIZE}
            />
          </MapControlButton>
          <ContextMenu ref={contextMenuRef}>
            <ul className="context-menu layer-context-menu dataset-menus__context">
              {overflowMenus.map((option, index) => {
                const key = option.id || String(index);
                const itemDisabled = disabled || isDisabled(option);
                if (isMenuItemCustomComponent(option)) {
                  return (
                    <RegistryItem
                      key={key}
                      componentKey={option.componentMenuKey}
                      item={option}
                      data={data}
                      mapId={mapId}
                      getGroups={getGroups}
                      disabled={itemDisabled}
                      location={getMenuItemLocation(option)}
                      onClose={() => contextMenuRef.current?.close()}
                    />
                  );
                }
                return (
                  <li
                    key={key}
                    className={[
                      'layer-context-menu__item',
                      option.type === 'divider'
                        ? 'layer-context-menu__divider'
                        : '',
                      itemDisabled ? 'is-disabled' : '',
                      option.class || '',
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    onClick={(event) => {
                      event.stopPropagation();
                      if (option.type === 'divider' || itemDisabled) return;
                      runAction(option, event);
                      contextMenuRef.current?.close();
                    }}
                  >
                    {option.type === 'divider' ? (
                      <div className="layer-context-menu__divider-line" />
                    ) : (
                      <>
                        <div className="layer-context-menu__item-icon">
                          <Icon
                            path={
                              ('icon' in option && option.icon) ||
                              mdiCircleSmall
                            }
                            size="16px"
                          />
                        </div>
                        <span>{('name' in option && option.name) || ''}</span>
                      </>
                    )}
                  </li>
                );
              })}
            </ul>
          </ContextMenu>
        </>
      )}
    </div>
  );
}
