// libs/vue/map-dataset/src/extra/menu/dataset-menu-button.vue
<template>
  <component
    :is="component"
    :item="item"
    :data="data"
    :mapId="mapId"
    :location="itemLocation"
    :disabled="disabled"
    v-bind="$attrs"
  />
</template>
<script setup lang="ts">
import type { IDataset } from '@hungpvq/map-dataset';
import type { MenuAction } from '@hungpvq/map-dataset/menu';
import { getMenuItemLocation } from '@hungpvq/map-dataset/menu';
import { useUniversalRegistry } from '@hungpvq/vue-map-core';
import { computed } from 'vue';
import DatasetMenuDivider from './dataset-menu-divider.vue';
import DatasetMenuItem from './dataset-menu-item.vue';

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  item: MenuAction;
  data?: IDataset;
  mapId?: string;
  disabled?: boolean;
}>();

const { getComponent } = useUniversalRegistry(props.mapId);
const itemLocation = computed(() => getMenuItemLocation(props.item));
const component = computed(() => {
  if (props.item.type === 'divider') return DatasetMenuDivider;
  if (props.item.type === 'item' && 'componentKey' in props.item && props.mapId) {
    return getComponent(props.item.componentKey) || DatasetMenuItem;
  }
  return DatasetMenuItem;
});
</script>

// libs/react/map-dataset/src/extra/menu/dataset-menu-button.tsx
import type { IDataset, MenuAction } from '@hungpvq/map-dataset';
import { getMenuItemLocation } from '@hungpvq/map-dataset';
import { BaseButton, RegistryItem } from '@hungpvq/react-map-core';
import Icon from '@mdi/react';

const ICON_SIZE = '14px';

export function DatasetMenuButton<T extends IDataset = IDataset>({
  menu,
  item,
  mapId,
  disabled,
  onClick,
  onAction,
}: {
  menu: MenuAction<T>;
  item?: T;
  mapId?: string;
  disabled?: boolean;
  onClick?: (event: React.MouseEvent) => void;
  onAction?: (payload: {
    event: React.MouseEvent;
    action: MenuAction<T>;
    item: T;
  }) => void;
}) {
  if (menu.type === 'divider') {
    return <div className="menu-divider" />;
  }

  if (menu.type === 'item' && 'componentKey' in menu && mapId) {
    return (
      <RegistryItem
        componentKey={menu.componentKey}
        mapId={mapId}
        item={menu}
        data={item}
        disabled={disabled}
        location={getMenuItemLocation(menu)}
      />
    );
  }

  const title = 'name' in menu ? menu.name : '';
  const icon = 'icon' in menu ? menu.icon : undefined;

  return (
    <BaseButton
      className="menu-item"
      disabled={disabled}
      title={title}
      onClick={(event) => {
        if (disabled) return;
        onClick?.(event);
        if (item) {
          onAction?.({ event, action: menu, item });
        }
      }}
    >
      {icon ? <Icon path={icon} size={ICON_SIZE} /> : title}
    </BaseButton>
  );
}
