// libs/vue/map-core/src/extra/legend/modules/LegendControl/LegendControl.vue
<script setup lang="ts">
import type { MapSimple, WithMapPropType } from '@hungpvq/map-core';
import {
  getLegendName,
  isSupportGenLayerLegend,
  LEGEND_CONTROL_LOCALE,
} from '@hungpvq/map-core/legend';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { mdiMapLegend } from '@mdi/js';
import { ref, shallowRef, watch } from 'vue';
import { MapCommonButton } from '../../../../components';
import { useEventListener } from '../../../../extra/event/hook/useEvent';
import { useLang } from '../../../../extra/lang/hook';
import { useRegisterMapControl } from '../../../../extra/registry/useRegisterMapControl';
import { useToolbarControl } from '../../../../extra/toolbar/helper';
import { InputCheckbox } from '../../../../field';
import { defaultMapProps, useMap } from '../../../../hooks/useMap';
import { useShow } from '../../../../hooks/useShow';
import ModuleContainer from '../../../../modules/ModuleContainer/ModuleContainer.vue';
import { useLayerLegend } from '../../lib/useLayerLegend';
const props = withDefaults(defineProps<WithMapPropType>(), {
  ...defaultMapProps,
});
const [show, setShow] = useShow(false);
const { callMap, mapId, moduleContainerProps, order } = useMap(props);
const { trans, setLocaleDefault } = useLang(mapId.value);
const { getLayerLegendVNode } = useLayerLegend();

setLocaleDefault(LEGEND_CONTROL_LOCALE);
function onToggleShow() {
  setShow(!show.value);
}
const { panelBind } = useRegisterMapControl(mapId, {
  id: 'mapLegendControl',
  panelKind: 'popup',
  title: () => trans.value('map.legend-control.title'),
  buttonPosition: () => props.position,
  show,
  setShow,
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
  }),
  actions: [
    {
      type: 'mapLegendControl',
      run: () => onToggleShow(),
    },
  ],
});
const onlyRender = ref(false);
const legends = shallowRef<{ icon: any; name: string }[]>([]);
function updateLegend(map: MapSimple) {
  let layers = map?.getStyle().layers;
  let visibleLayers: Set<string> | null = null;
  if (onlyRender.value) {
    visibleLayers = new Set(); // Dùng Set để tránh trùng lặp

    // Lấy các feature đang render trong viewport
    const features = map.queryRenderedFeatures();
    for (const feature of features) {
      visibleLayers.add(feature.layer.id);
    }
  }
  legends.value = layers
    .slice()
    .reverse()
    .filter(
      (layer) =>
        (!visibleLayers || (visibleLayers && visibleLayers.has(layer.id))) &&
        isSupportGenLayerLegend(layer),
    )
    .map((layer) => ({
      icon: getLayerLegendVNode(map, layer as any),
      name: getLegendName(layer as any),
    }));
}
useEventListener(mapId.value, 'styledata', updateLegend);
const { add, remove } = useEventListener(
  mapId.value,
  'moveend',
  updateLegend,
  false,
);
watch(onlyRender, (newValue) => {
  if (newValue) {
    add();
    callMap((map) => {
      updateLegend(map);
    });
  } else {
    remove();
  }
});
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapLegendControl',
  getState() {
    return mdiButtonState(mdiMapLegend, {
      visible: true,
      title: trans.value('map.legend-control.title'),
      order: order.value,
    });
  },
  onClick() {
    onToggleShow();
  },
});
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>

    <template #draggable="slotProps">
      <DraggableItemPopup
        v-if="show"
        :height="400"
        :width="400"
        v-bind="{ ...slotProps, ...panelBind }"
        v-model:show="show"
        :title="trans('map.legend-control.title')"
      >
        <div class="map-legend-control">
          <div class="map-legend-control__list">
            <div
              v-for="(legendVNode, index) in legends"
              :key="index"
              class="map-legend-control__item"
            >
              <div class="map-legend-control__icon">
                <component :is="legendVNode.icon" />
              </div>
              <span>{{ legendVNode.name }}</span>
            </div>
          </div>
          <div class="map-legend-control__action">
            <InputCheckbox
              :label="trans('map.legend-control.onlyRendered')"
              v-model="onlyRender"
            />
          </div>
        </div>
      </DraggableItemPopup>
    </template>
    <slot />
  </ModuleContainer>
</template>

// libs/react/map-core/src/extra/legend/modules/LegendControl.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import type { MapSimple, WithMapPropType } from '@hungpvq/map-core';
import {
  LEGEND_CONTROL_LOCALE,
  getLegendName,
  isSupportGenLayerLegend,
  type LegendLayerSpecification,
} from '@hungpvq/map-core/legend';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import { mdiMapLegend } from '@mdi/js';
import type { ReactNode } from 'react';
import { MapCommonButton } from '../../../components/MapCommonButton';
import { InputCheckbox } from '../../../field';
import { defaultMapProps, useMap } from '../../../hooks/useMap';
import { useShow } from '../../../hooks/useShow';
import { ModuleContainer } from '../../../modules/ModuleContainer/ModuleContainer';
import { useEventListener } from '../../event/hook/useEvent';
import { useLang } from '../../lang/hook';
import { useRegisterMapControl } from '../../registry/useRegisterMapControl';
import { useToolbarControl } from '../../toolbar/helper';
import { useLayerLegend } from '../lib/useLayerLegend';

export function LegendControl(props: WithMapPropType) {
  const merged = { ...defaultMapProps, ...props };
  const [show, setShow] = useShow(false);
  const { callMap, mapId, moduleContainerProps, order } = useMap({ ...merged, controlId: 'mapLegendControl' });
  const { trans, setLocaleDefault } = useLang(mapId);
  const { panelBind } = useRegisterMapControl(mapId, {
    id: 'mapLegendControl',
    panelKind: 'popup',
    title: trans('map.legend-control.title'),
    buttonPosition: merged.position,
    show,
    setShow,
    getProps: () => ({
      position: merged.position,
      controlLayout: merged.controlLayout,
    }),
    actions: [{ type: 'mapLegendControl', run: () => setShow(!show) }],
  });
  const { getLayerLegendNode } = useLayerLegend();
  const [onlyRender, setOnlyRender] = useState(false);
  const [legends, setLegends] = useState<{ icon: ReactNode; name: string }[]>(
    [],
  );
  const onlyRenderRef = useRef(onlyRender);
  onlyRenderRef.current = onlyRender;

  useEffect(() => {
    setLocaleDefault(LEGEND_CONTROL_LOCALE);
  }, [setLocaleDefault]);

  const updateLegend = useCallback(
    (map: MapSimple) => {
      const layers = map?.getStyle().layers || [];
      let visibleLayers: Set<string> | null = null;
      if (onlyRenderRef.current) {
        visibleLayers = new Set();
        for (const feature of map.queryRenderedFeatures()) {
          visibleLayers.add(feature.layer.id);
        }
      }
      setLegends(
        layers
          .slice()
          .reverse()
          .filter(
            (layer): layer is LegendLayerSpecification =>
              (!visibleLayers || visibleLayers.has(layer.id)) &&
              isSupportGenLayerLegend(layer),
          )
          .map((layer) => ({
            icon: getLayerLegendNode(map, layer),
            name: getLegendName(layer),
          })),
      );
    },
    [getLayerLegendNode],
  );

  useEventListener(mapId, 'styledata', updateLegend);
  const { add, remove } = useEventListener(
    mapId,
    'moveend',
    updateLegend,
    false,
  );

  const addMoveEndRef = useRef(add);
  const removeMoveEndRef = useRef(remove);
  const callMapRef = useRef(callMap);
  const updateLegendRef = useRef(updateLegend);
  addMoveEndRef.current = add;
  removeMoveEndRef.current = remove;
  callMapRef.current = callMap;
  updateLegendRef.current = updateLegend;

  useEffect(() => {
    if (onlyRender) {
      addMoveEndRef.current();
      callMapRef.current((map) => updateLegendRef.current(map));
    } else {
      removeMoveEndRef.current();
    }
  }, [onlyRender]);

  const { state, control } = useToolbarControl(mapId, merged, {
    kind: 'single',
    id: 'mapLegendControl',
    getState: () =>
      mdiButtonState(mdiMapLegend, {
        visible: true,
        title: trans('map.legend-control.title'),
        order,
      }),
    onClick: () => setShow(!show),
  });

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) =>
        show ? (
          <DraggableItemPopup
            show={show}
            onUpdateShow={(v) => setShow(!!v)}
            title={trans('map.legend-control.title')}
            width={400}
            height={400}
            {...bind}
            {...panelBind}
          >
            <div className="map-legend-control">
              <div className="map-legend-control__list">
                {legends.map((item, i) => (
                  <div key={i} className="map-legend-control__item">
                    <div className="map-legend-control__icon">{item.icon}</div>
                    <span>{item.name}</span>
                  </div>
                ))}
              </div>
              <div className="map-legend-control__action">
                <InputCheckbox
                  label={trans('map.legend-control.onlyRendered')}
                  checked={onlyRender}
                  onChange={(v) => setOnlyRender(!!v)}
                />
              </div>
            </div>
          </DraggableItemPopup>
        ) : null
      }
    />
  );
}
