// libs/react/map-dataset/src/modules/StyleControl/style/field/InputMultiple.tsx
import { MapControlButton } from '@hungpvq/react-map-core';
import { InputText } from '@hungpvq/react-map-core/fields';
import { mdiDelete } from '@mdi/js';
import { Icon } from '@mdi/react';

export function InputMultiple({
  value = [0, 0],
  onChange,
}: {
  value?: number[];
  onChange?: (value: number[]) => void;
  mapId?: string;
}) {
  const form = value.length ? value : [0, 0];

  function onSetValue(next: number, index: number) {
    const copy = [...form];
    copy[index] = next;
    onChange?.(copy);
  }

  function onRemove(index: number) {
    if (form.length <= 2) return;
    onChange?.(form.filter((_, i) => i !== index));
  }

  function onAdd() {
    onChange?.([...form, 0]);
  }

  return (
    <div className="input-array-index">
      {form.map((arr, index) => (
        <div className="input-array-item" key={`array_${index}`}>
          <InputText
            value={String(arr ?? '')}
            type="number"
            onChange={(v) => onSetValue(+v, index)}
          />
          <div className="input-array-item__action">
            {form.length > 2 && (
              <MapControlButton variant="text" onClick={() => onRemove(index)}>
                <Icon path={mdiDelete} size="16px" />
              </MapControlButton>
            )}
          </div>
        </div>
      ))}
      <MapControlButton onClick={onAdd} variant="text">
        {' '}
        Add
      </MapControlButton>
    </div>
  );
}

// libs/vue/map-dataset/src/modules/StyleControl/style/field/InputMultiple.vue
<template lang="">
  import { MapControlButton } from '@hungpvq/vue-map-core';
  <div v-bind="$attrs" class="input-array-index">
    <div
      class="input-array-item"
      v-for="(arr, index) in form"
      :key="`array_${index}`"
    >
      <InputText
        :modelValue="form[index]"
        :type="arr.type"
        @change="onSetValue(+$event.target.value, index)"
      />
      <div class="input-array-item__action">
        <map-control-button
          @click="onRemove(form, index)"
          v-if="form.length > 2"
          variant="text"
        >
          <SvgIcon size="16" type="mdi" :path="path.delete" />
        </map-control-button>
      </div>
    </div>
    <map-control-button @click="onAdd()" variant="text">
      Add</map-control-button
    >
  </div>
</template>
<script setup lang="ts">
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiDelete } from '@mdi/js';
const form = defineModel<number[]>({ default: () => [0, 0] });
const emit = defineEmits(['update:modelValue']);

const path = {
  delete: mdiDelete,
};
defineProps({
  mapId: {
    type: String,
    required: true,
  },
});
function onSetValue(value: number, index: number) {
  form.value[index] = value;
  emit('update:modelValue', form.value);
}
function onRemove(array: number[], index: number) {
  if (array) array.splice(index, 1);
  form.value = array;
  emit('update:modelValue', array);
}
function onAdd() {
  form.value.push(0);
  emit('update:modelValue', form.value);
}
</script>
