// libs/react/map-dataset/src/modules/StyleControl/style/field/InputImage.tsx
import { useMapImages } from '@hungpvq/react-map-core';
import { InputText } from '@hungpvq/react-map-core/fields';

export function InputImage({
  value,
  onChange,
  mapId = '',
}: {
  value?: string;
  onChange?: (value: string | undefined) => void;
  mapId?: string;
}) {
  const { images, toDataURL } = useMapImages(mapId);

  function onSetValue(next: string) {
    onChange?.(next === value ? undefined : next);
  }

  return (
    <div className="input-image">
      <div>
        <InputText
          value={value || ''}
          onChange={(v) => onSetValue(v)}
        />
      </div>
      <div className="fill-canvas">
        {Object.entries(images).map(([name, styleImage]) => (
          <div
            key={name}
            className={`item-icon${name === value ? ' item-icon-active' : ''}`}
          >
            <div className="item-image">
              <img
                src={toDataURL(name, styleImage)}
                alt={name}
                onClick={() => onSetValue(name)}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// libs/vue/map-dataset/src/modules/StyleControl/style/field/InputImage.vue
<template lang="">
  <div v-bind="$attrs" class="input-image">
    <div>
      <InputText :modelValue="form" @change="onSetValue($event.target.value)" />
    </div>
    <div class="fill-canvas">
      <div
        v-for="(styleImage, name) in images"
        :key="name"
        class="item-icon"
        :class="{ 'item-icon-active': name == form }"
      >
        <div class="item-image">
          <img
            :src="toDataURL(name, styleImage)"
            alt="Map image"
            @click="onSetValue(name)"
          />
        </div>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { useMapImages } from '@hungpvq/vue-map-core';
import { InputText } from '@hungpvq/vue-map-core/fields';
const form = defineModel<string | undefined>({ default: undefined });
const emit = defineEmits(['update:modelValue']);

const props = defineProps({
  mapId: {
    type: String,
    required: true,
  },
});
const { images, toDataURL } = useMapImages(props.mapId);
function onSetValue(value: string) {
  emit('update:modelValue', value == form.value ? undefined : value);
}
</script>
