// apps/demo-map/src/layout/aside-control.vue
<template lang="">
  <ModuleContainer v-bind="moduleContainerProps" :active="show">
    <template #btn>
      <MapControlButton
        @click.stop="toggleShow()"
        :tooltip="trans('map.aside-control.title')"
      >
        <SvgIcon size="16" type="mdi" :path="path.icon" />
      </MapControlButton>
    </template>

    <template #draggable="props">
      <DraggableItemSideBar
        :containerId="props.containerId"
        v-model:show="show"
        :title="trans('map.aside-control.title')"
      >
        <template #title>
          <span class="aside-control__title">
            {{ trans('map.aside-control.title') }}
          </span>
        </template>
        <v-list>
          <v-list-item>
            <RouterLink to="/">Home </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/toolbar">Map - Toolbar </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/compare">Compare </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/story-telling">Story telling </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/story-telling-gps">Story telling GPS </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/basemap">BaseMap </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/measurement">measurement </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-highlight"
              >Dataset - Highlight
            </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-identify">Dataset - Identify </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-menu">Dataset - Menu </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-list">Dataset - List </RouterLink>
          </v-list-item>
          <v-list-item>
            <RouterLink to="/dataset-data-management"
              >Dataset - Data management
            </RouterLink>
          </v-list-item>
        </v-list>
      </DraggableItemSideBar>
    </template>
  </ModuleContainer>
</template>
<script>
import { VList, VListItem } from '@hungpvq/ui-core';
import { DraggableItemSideBar } from '@hungpvq/vue-draggable';
import {
  makeShowProps,
  MapControlButton,
  ModuleContainer,
  useLang,
  useMap,
  useShow,
  withMapProps,
} from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiMenu } from '@mdi/js';
import { RouterLink } from 'vue-router';
export default {
  name: 'AsideControl',
  components: {
    VList,
    DraggableItemSideBar,
    MapControlButton,
    ModuleContainer,
    SvgIcon,
    VListItem,
    RouterLink,
  },
  props: {
    ...withMapProps,
    ...makeShowProps({ show: false }),
  },
  setup(props) {
    const path = {
      icon: mdiMenu,
    };
    const [show, toggleShow] = useShow(props.show);
    const { mapId, moduleContainerProps } = useMap(props);
    const { trans, setLocale } = useLang(mapId.value);

    setLocale({
      map: {
        'aside-control': {
          title: 'Aside Control',
        },
      },
    });
    return {
      show,
      toggleShow,
      moduleContainerProps,
      trans,
      path,
    };
  },
};
</script>
<style lang=""></style>

// apps/react/demo-map/src/layout/AsideControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { DraggableItemSideBar } from '@hungpvq/react-draggable';
import {
  defaultMapProps,
  MapCommonButton,
  ModuleContainer,
  useLang,
  useMap,
  useShow,
  useToolbarControl,
} from '@hungpvq/react-map-core';
import { mdiMenu } from '@mdi/js';
import { useEffect } from 'react';
import { Link } from 'react-router';
import './demo-nav.css';

const NAV_ITEMS = [
  { to: '/', label: 'Home (All Map)' },
  { to: '/map-core', label: 'Map - Core' },
  { to: '/toolbar', label: 'Map - Toolbar' },
  { to: '/basemap', label: 'BaseMap' },
  { to: '/measurement', label: 'Measurement' },
  { to: '/dataset-highlight', label: 'Dataset - Highlight' },
  { to: '/dataset-identify', label: 'Dataset - Identify' },
  { to: '/dataset-menu', label: 'Dataset - Menu' },
  { to: '/dataset-list', label: 'Dataset - List' },
  { to: '/dataset-data-management', label: 'Dataset - Data management' },
  { to: '/story-telling', label: 'Story telling' },
];

export function AsideControl(props: WithMapPropType & { show?: boolean }) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps } = useMap(merged);
  const { trans, setLocaleDefault } = useLang(mapId);
  const [show, toggleShow] = useShow(props.show);

  useEffect(() => {
    setLocaleDefault({ map: { 'aside-control': { title: 'Aside Control' } } });
  }, [setLocaleDefault]);

  const { state, control } = useToolbarControl(mapId, merged, {
    kind: 'single',
    id: 'asideControl',
    getState: () => ({
      visible: true,
      active: show,
      title: trans('map.aside-control.title'),
      icon: { type: 'mdi' as const, path: mdiMenu },
    }),
    onClick: () => toggleShow(),
  });

  useEffect(() => {
    control.sync();
  }, [show, control]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        state ? (
          <MapCommonButton
            option={state}
            onClick={(e) => {
              e.stopPropagation();
              control.onAction(e.nativeEvent);
            }}
          />
        ) : null
      }
      draggable={(bind) => (
        <DraggableItemSideBar
          show={show}
          onUpdateShow={(v) => toggleShow(!!v)}
          title={trans('map.aside-control.title')}
          titleNode={
            <span className="aside-control__title">
              {trans('map.aside-control.title')}
            </span>
          }
          containerId={bind.containerId}
        >
          <ul className="v-list">
            {NAV_ITEMS.map((item) => (
              <li key={item.to} className="v-list-item">
                <Link to={item.to} onClick={() => toggleShow(false)}>
                  {item.label}
                </Link>
              </li>
            ))}
          </ul>
        </DraggableItemSideBar>
      )}
    />
  );
}
