// libs/vue/map-dataset/src/modules/StyleControl/style/multi-style.vue
<script setup lang="ts">
import { LayerSimpleMapboxBuild } from '@hungpvq/map-dataset/style';
import { MapControlButton, useShow } from '@hungpvq/vue-map-core';
import { InputSelect } from '@hungpvq/vue-map-core/fields';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiClose, mdiDelete, mdiPlus } from '@mdi/js';
import { LayerSpecification } from 'maplibre-gl';
import { computed, nextTick, ref, watch } from 'vue';

import SingleStyle from './single-style.vue';
defineExpose({
  SvgIcon,
  SingleStyle,
  MapControlButton,
  InputSelect,
});
defineProps({
  trans: {
    required: true,
  },
  mapId: {
    required: true,
  },
});
const emit = defineEmits(['input', 'update-style', 'close']);
const layers = defineModel<LayerSpecification[]>({
  required: true,
  default: () => [],
});
watch(layers, () => {
  if (!tab.value && layers.value.length > 0) {
    tab.value = layers.value[layers.value.length - 1].id;
  }
});
const onSelectTab = (layer_id: string) => {
  tab.value = undefined;
  nextTick(() => {
    tab.value = layer_id;
  });
};
const onUpdateStyleLayer = (layer: LayerSpecification, layer_id: string) => {
  emit('update-style', {
    type: 'update-one-layer',
    layer,
    index: layers.value.findIndex((x) => x.id === layer_id),
  });
};
const onAddStyleLayer = (type: string) => {
  tab.value = undefined;
  emit('update-style', {
    type: 'add-one-layer',
    layer: new LayerSimpleMapboxBuild()
      .setStyleType(type as any)
      .setColor('#fff')
      .build(),
  });
  onShowAddStyle(false);
};
const onRemoveStyleLayer = (layer_id: string) => {
  let index = layers.value.findIndex((x) => x.id === layer_id);
  if (!layers.value[index]) {
    return;
  }
  tab.value = undefined;
  emit('update-style', {
    type: 'remove-one-layer',
    index,
    layer: layers.value[index],
  });
  layers.value.splice(index, 1);
  if (layers.value.length === 0) {
    tab.value = undefined;
    onShowAddStyle(true);
  } else {
    tab.value = layers.value[layers.value.length - 1]?.id; // Nếu tab hiện tại là layer bị xóa, chọn lại layer đầu tiên còn lại
  }
  if (layers.value[0]) onSelectTab(layers.value[0].id);
};
const tab = ref<string | undefined>(layers.value[0].id);
const tabs = computed(() => {
  return layers.value.map((x, i) => {
    return { text: `#${i + 1}`, value: x.id };
  });
});
const current_layer = computed(() => {
  return layers.value.find((x) => x.id === tab.value);
});
const path = {
  delete: mdiDelete,
  create: mdiPlus,
  close: mdiClose,
};
const [showAdd, setShowAdd] = useShow(false);
const onShowAddStyle = (value: boolean) => {
  setShowAdd(value);
};
</script>
<template lang="">
  <div class="multi-style-edit-container">
    <div class="tab-container">
      <div class="tab-item">
        <InputSelect
          :modelValue="tab"
          @update:modelValue="onSelectTab"
          :items="tabs"
        ></InputSelect>
      </div>
      <MapControlButton
        class="tab-item tab-add clickable"
        @click="onRemoveStyleLayer(tab)"
        :disabled="!tab"
        variant="text"
      >
        <SvgIcon size="14" type="mdi" :path="path.delete" :disabled="!tab" />
      </MapControlButton>
      <MapControlButton
        class="tab-item tab-add clickable"
        @click="onShowAddStyle(!showAdd)"
        variant="text"
      >
        <SvgIcon
          size="14"
          type="mdi"
          :path="!showAdd ? path.create : path.close"
        />
      </MapControlButton>
    </div>
    <div class="style-container" v-if="showAdd">
      <div class="add-style-container">
        <map-control-button @click="onAddStyleLayer('area')" variant="text">
          {{ trans('map.style-control.add.area') }}
        </map-control-button>
        <map-control-button @click="onAddStyleLayer('line')" variant="text">
          {{ trans('map.style-control.add.line') }}
        </map-control-button>
        <map-control-button @click="onAddStyleLayer('point')" variant="text">
          {{ trans('map.style-control.add.point') }}
        </map-control-button>
        <map-control-button @click="onAddStyleLayer('symbol')" variant="text">
          {{ trans('map.style-control.add.symbol') }}
        </map-control-button>
      </div>
    </div>
    <div class="style-container" v-else-if="tab">
      <SingleStyle
        :modelValue="current_layer"
        :trans="trans"
        :mapId="mapId"
        :key="tab"
        @update-style="onUpdateStyleLayer($event, tab)"
      />
    </div>
  </div>
</template>

// libs/react/map-dataset/src/modules/StyleControl/style/MultiStyle.tsx
import { LayerSimpleMapboxBuild } from '@hungpvq/map-dataset/style';
import { MapControlButton, useShow } from '@hungpvq/react-map-core';
import { InputSelect } from '@hungpvq/react-map-core/fields';
import Icon from '@mdi/react';
import { mdiClose, mdiDelete, mdiPlus } from '@mdi/js';
import type { LayerSpecification } from 'maplibre-gl';
import { useEffect, useMemo, useState } from 'react';
import type { TransFn } from './type/tab-utils';
import { SingleStyle } from './SingleStyle';

export function MultiStyle({
  value = [],
  trans,
  mapId,
  onUpdateStyle,
}: {
  value?: LayerSpecification[];
  trans: TransFn;
  mapId: string;
  onUpdateStyle?: (payload: {
    type: string;
    layer?: LayerSpecification;
    index?: number;
  }) => void;
}) {
  const layers = value;
  const [tab, setTab] = useState<string | undefined>(layers[0]?.id);
  const [showAdd, setShowAdd] = useShow(false);

  useEffect(() => {
    if (!tab && layers.length > 0) {
      setTab(layers[layers.length - 1].id);
    }
  }, [layers, tab]);

  const tabs = useMemo(
    () => layers.map((x, i) => ({ text: `#${i + 1}`, value: x.id })),
    [layers],
  );
  const current_layer = useMemo(
    () => layers.find((x) => x.id === tab),
    [layers, tab],
  );

  function onSelectTab(layer_id: string) {
    setTab(undefined);
    requestAnimationFrame(() => setTab(layer_id));
  }

  function onUpdateStyleLayer(layer: LayerSpecification, layer_id: string) {
    onUpdateStyle?.({
      type: 'update-one-layer',
      layer,
      index: layers.findIndex((x) => x.id === layer_id),
    });
  }

  function onAddStyleLayer(type: string) {
    setTab(undefined);
    onUpdateStyle?.({
      type: 'add-one-layer',
      layer: new LayerSimpleMapboxBuild()
        .setStyleType(type as 'point' | 'line' | 'area' | 'symbol')
        .setColor('#fff')
        .build() as LayerSpecification,
    });
    setShowAdd(false);
  }

  function onRemoveStyleLayer(layer_id?: string) {
    if (!layer_id) return;
    const index = layers.findIndex((x) => x.id === layer_id);
    if (!layers[index]) return;
    setTab(undefined);
    onUpdateStyle?.({
      type: 'remove-one-layer',
      index,
      layer: layers[index],
    });
    const next = layers.filter((_, i) => i !== index);
    if (next.length === 0) {
      setShowAdd(true);
    } else {
      onSelectTab(next[next.length - 1]?.id || next[0].id);
    }
  }

  return (
    <div className="multi-style-edit-container">
      <div className="tab-container">
        <div className="tab-item">
          <InputSelect
            value={tab}
            onChange={(v) => onSelectTab(String(v))}
            items={tabs}
          />
        </div>
        <MapControlButton variant="text"
          className="tab-item tab-add clickable"
          onClick={() => onRemoveStyleLayer(tab)}
          disabled={!tab}
        >
          <Icon path={mdiDelete} size="14px" />
        </MapControlButton>
        <MapControlButton variant="text"
          className="tab-item tab-add clickable"
          onClick={() => setShowAdd(!showAdd)}
        >
          <Icon path={!showAdd ? mdiPlus : mdiClose} size="14px" />
        </MapControlButton>
      </div>
      {showAdd ? (
        <div className="style-container">
          <div className="add-style-container">
            <MapControlButton variant="text" onClick={() => onAddStyleLayer('area')}>
              {trans('map.style-control.add.area')}
            </MapControlButton>
            <MapControlButton variant="text" onClick={() => onAddStyleLayer('line')}>
              {trans('map.style-control.add.line')}
            </MapControlButton>
            <MapControlButton variant="text" onClick={() => onAddStyleLayer('point')}>
              {trans('map.style-control.add.point')}
            </MapControlButton>
            <MapControlButton variant="text" onClick={() => onAddStyleLayer('symbol')}>
              {trans('map.style-control.add.symbol')}
            </MapControlButton>
          </div>
        </div>
      ) : (
        tab &&
        current_layer && (
          <div className="style-container">
            <SingleStyle
              key={tab}
              value={current_layer}
              trans={trans}
              mapId={mapId}
              onUpdateStyle={(layer) => onUpdateStyleLayer(layer, tab)}
            />
          </div>
        )
      )}
    </div>
  );
}
