// libs/react/map-dataset/src/modules/LayerControl/layer-sub-item.tsx
import type { IListViewUI, MenuAction } from '@hungpvq/map-dataset';
import {
  createMenuConditionContext,
  isMenuItemDisabled,
  isMenuItemHidden,
} from '@hungpvq/map-dataset';
import { BaseButton, RegistryItem } from '@hungpvq/react-map-core';
import { mdiDotsVertical } from '@mdi/js';
import Icon from '@mdi/react';
import { useMemo } from 'react';
import { useMenuConditionContext } from '../../extra/menu/condition-context';
import { LayerMenuButton } from './layer-menu-button';

const ICON_SIZE = '14px';

export function LayerSubItem({
  item,
  mapId,
  readonly,
  disabledMove,
  disabledCreateGroup,
  onAction,
  onContextMenu,
}: {
  item: IListViewUI;
  mapId: string;
  readonly?: boolean;
  disabledMove?: boolean;
  disabledCreateGroup?: boolean;
  onAction?: (payload: {
    event: React.MouseEvent;
    action: MenuAction<IListViewUI>;
    item: IListViewUI;
  }) => void;
  onContextMenu?: (payload: {
    event: React.MouseEvent;
    actions: MenuAction<IListViewUI>[];
    item: IListViewUI;
  }) => void;
}) {
  const injectedMenuContext = useMenuConditionContext();
  const conditionCtx = createMenuConditionContext(item, {
    mapId,
    context: [
      {
        readonly,
        disabledMove,
        disabledCreateGroup,
      },
      injectedMenuContext,
    ],
  });
  const menus = useMemo(
    () => (item.getMenus?.() || []) as MenuAction<IListViewUI>[],
    [item],
  );
  const extraMenus = menus
    .filter((x) => !x.location || x.location === 'extra')
    .filter((x) => !isMenuItemHidden(x, conditionCtx))
    .sort((a, b) => (a.order || 0) - (b.order || 0));
  const contentMenus = menus
    .filter((x) => x.location === 'menu')
    .filter((x) => !isMenuItemHidden(x, conditionCtx))
    .sort((a, b) => (a.order || 0) - (b.order || 0));

  return (
    <div className="layer-sub-item-container">
      <div className="layer-sub-item__info">
        {item.icon?.componentKey && (
          <div className="layer-sub-item__icon">
            <RegistryItem
              componentKey={item.icon.componentKey}
              mapId={mapId}
              {...item.icon.attr}
              data={item}
            />
          </div>
        )}
        <span className="layer-sub-item__title" title={item.getName()}>
          <span>{item.getName()}</span>
        </span>
        <div className="layer-sub-item__title-action">
          {extraMenus.map((menu, i) => (
            <LayerMenuButton
              key={i}
              menu={menu}
              item={item}
              mapId={mapId}
              disabled={isMenuItemDisabled(menu, conditionCtx)}
              onAction={onAction}
            />
          ))}
          {contentMenus.length > 0 && (
            <BaseButton
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                onContextMenu?.({ event, actions: contentMenus, item });
              }}
            >
              <Icon path={mdiDotsVertical} size={ICON_SIZE} />
            </BaseButton>
          )}
        </div>
      </div>
    </div>
  );
}

// libs/map/dataset/src/modules/LayerControl/part/item/layer-sub-item.vue
<template lang="">
  <div class="layer-sub-item-container">
    <div class="layer-sub-item__info">
      <div v-if="isHasIcon" class="layer-sub-item__icon">
        <component
          v-if="props.item.icon?.componentKey"
          :is="getComponent(props.item.icon.componentKey)"
          v-bind="props.item.icon.attr"
          :data="item"
          :mapId="mapId"
        ></component>
      </div>
      <span class="layer-sub-item__title" :title="item.getName()">
        <span>{{ item.getName() }}</span>
      </span>
      <div class="layer-sub-item__title-action">
        <slot name="pre-btn" />
        <template v-for="(menu, i) in extra_menus" :key="i">
          <LayerMenu
            :item="menu"
            :data="item"
            :mapId="mapId"
            @click="onLayerAction(menu)"
          />
        </template>
        <BaseButton
          v-if="content_menus.length > 0"
          @click.prevent.stop="handleContextClick"
        >
          <SvgIcon size="14" type="mdi" :path="path.menu" />
        </BaseButton>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { BaseButton } from '@hungpvq/vue-map-core';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiDotsVertical } from '@mdi/js';
import { computed } from 'vue';
import type { MenuAction } from '../../../../interfaces';
import type { IListViewUI } from '../../../../model';
import { useUniversalRegistry } from '../../../../registry';
import LayerMenu from './menu/index.vue';

const path = {
  menu: mdiDotsVertical,
};
const props = defineProps<{
  item: IListViewUI;
  mapId: string;
}>();
const { getComponent } = useUniversalRegistry(props.mapId);
const isHasIcon = computed(() => props.item && props.item.icon);
const emit = defineEmits(['click:action', 'click:content-menu']);
const button_menus = computed<MenuAction<any>[]>(() => {
  if (!props.item) {
    return [];
  }
  return props.item.getMenus() || [];
});
const extra_menus = computed(() => {
  return button_menus.value
    .filter((x) => x.location !== 'menu')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
const content_menus = computed(() => {
  return button_menus.value
    .filter((x) => x.location == 'menu')
    .sort((a, b) => (a.order || 0) - (b.order || 0));
});
function onLayerAction(action: MenuAction<IListViewUI>) {
  emit('click:action', { action, item: props.item });
}
function handleContextClick(event: MouseEvent) {
  emit('click:content-menu', {
    event,
    actions: content_menus.value,
    item: props.item,
  });
}
</script>
<style lang="scss" scoped>
.layer-sub-item {
  &__info {
    width: 100%;
    display: flex;
    align-items: center;
  }
  &__icon {
    flex-grow: 0;
    flex-shrink: 0;
    width: 25px;
    display: flex;
    align-items: center;
  }
  &__title {
    display: inline-block;
    text-align: left;
    flex-grow: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    font-size: 0.75rem !important;
    font-weight: 400;
    line-height: 1.25rem;
    letter-spacing: 0.0333333333em !important;
  }
  &__title-action {
    display: flex;
    flex: 0;
    align-items: center;
  }
}
</style>
