// apps/vue/demo-draggable/src/components/custom-cards/LocalHeader.vue
<template>
  <div class="custom-header custom-header--local">
    <hr class="map-divider" />
    <div class="draggable-header">
      <div class="draggable-header__content">
        <slot name="pre-title" />
        <div class="draggable-header__title">
          <slot name="title" />
        </div>
        <div class="map-spacer" />
        <slot name="extra-btn" />
      </div>
    </div>
    <hr class="map-divider" />
  </div>
</template>

// apps/react/demo-draggable/src/components/custom-cards/LocalHeader.tsx
import type { ReactNode } from 'react';

export interface LocalHeaderProps {
  children?: ReactNode;
  preTitle?: ReactNode;
  title?: ReactNode;
  extraBtn?: ReactNode;
}

export function LocalHeader({ preTitle, title, extraBtn }: LocalHeaderProps) {
  return (
    <div className="custom-header custom-header--local">
      <hr className="map-divider" />
      <div className="draggable-header">
        <div className="draggable-header__content">
          {preTitle}
          <div className="draggable-header__title">{title}</div>
          <div className="map-spacer" />
          {extraBtn}
        </div>
      </div>
      <hr className="map-divider" />
    </div>
  );
}
