// libs/vue/map-core/src/modules/ModuleContainer/ModuleContainer.vue
<template>
  <div class="module__container">
    <Teleport
      v-if="controlVisible && hasCornerChrome && showCornerChrome"
      :to="btnTo"
    >
      <div
        v-if="hasBtnContent"
        :class="btnModuleClass"
        :style="{ order: controlOrder }"
        :data-map-control-id="resolvedControlId || undefined"
      >
        <slot
          v-if="hasSlotBtn"
          name="btn"
        />
        <MapAutoHostButtons
          v-else-if="autoButtonEntry && autoButtonState != null"
          :state="autoButtonState"
          :position="position"
          :on-action="onAutoAction"
        />
      </div>
      <slot name="btnOutside" />
    </Teleport>
    <slot />
    <Teleport
      :to="draggableTo"
      v-if="c_containerId && hasSlotDraggable"
    >
      <slot
        v-bind="bindDrag"
        name="draggable"
      />
    </Teleport>
  </div>
</template>
<script lang="ts">
export default {
  name: 'ModuleContainer',
};
</script>
<script setup lang="ts">
import {
  buildModuleBindPosition,
  getControlAutoButton,
  isModuleCornerChromeVisible,
  MAP_MODULE_CONTROL_ID_KEY,
  moduleBtnContainerClassName,
  moduleCornerHostSelector,
  moduleDraggableHostSelector,
  subscribeControlAutoButton,
} from '@hungpvq/map-core';
import { computed, inject, onUnmounted, ref, useSlots } from 'vue';

import { defineProps } from 'vue';
import MapAutoHostButtons from '../../components/MapAutoHostButtons.vue';

const slots = useSlots();
const props = defineProps({
  mapId: { type: String, default: '' },
  dragId: { type: String, default: '' },
  btnWidth: { type: Number, default: 40 },
  controlOrder: { type: Number, default: 0 },
  controlId: { type: String, default: '' },
  position: {
    type: String,
    default: 'bottom-right',
    validator(value: string) {
      return (
        ['top-left', 'top-right', 'bottom-left', 'bottom-right'].indexOf(
          value,
        ) !== -1
      );
    },
  },
  controlVisible: {
    type: Boolean,
    default: true,
  },
  controlLayout: {
    type: String,
    default: 'standalone',
    validator(value: string) {
      return ['toolbar', 'standalone', 'button', 'menu'].indexOf(value) !== -1;
    },
  },
});
const hasSlotBtn = computed(() => !!slots['btn']);
const hasSlotBtnOutside = computed(() => !!slots['btnOutside']);
const autoBtnTick = ref(0);
const i_map_id = inject<string>('$map.id');
const injectedControlId = inject<string | undefined>(
  MAP_MODULE_CONTROL_ID_KEY,
  undefined,
);
const resolvedControlId = computed(
  () => props.controlId || injectedControlId || '',
);
const c_mapId = computed<string>(() => {
  return props.mapId || i_map_id!;
});

const autoButtonEntry = computed(() => {
  autoBtnTick.value;
  if (hasSlotBtn.value) return undefined;
  const mid = c_mapId.value;
  const cid = resolvedControlId.value;
  if (!mid || !cid) return undefined;
  return getControlAutoButton(mid, cid);
});

const autoButtonState = computed(() => {
  autoBtnTick.value;
  const entry = autoButtonEntry.value;
  if (!entry) return undefined;
  return entry.getUiState();
});

const hasAutoBtn = computed(
  () => !!autoButtonEntry.value && autoButtonState.value != null,
);
const hasBtnContent = computed(() => hasSlotBtn.value || hasAutoBtn.value);
const hasCornerChrome = computed(
  () => hasBtnContent.value || hasSlotBtnOutside.value,
);
const showCornerChrome = computed(() =>
  isModuleCornerChromeVisible(
    props.controlLayout as 'toolbar' | 'standalone' | 'button' | 'menu',
  ),
);
const hasSlotDraggable = computed(() => !!slots['draggable']);
const i_dragId = inject<string>('$map.dragId');
const btnModuleClass = computed(() =>
  moduleBtnContainerClassName(resolvedControlId.value),
);
const c_containerId = computed<string>(() => {
  return props.dragId || i_dragId!;
});

const stopAutoBtn = subscribeControlAutoButton((mid, controlId) => {
  if (
    mid === c_mapId.value &&
    (controlId === resolvedControlId.value || controlId === '*')
  ) {
    autoBtnTick.value++;
  }
});
onUnmounted(() => stopAutoBtn());

function onAutoAction(...args: unknown[]) {
  autoButtonEntry.value?.onAction(...args);
}

const draggableTo = computed(() => moduleDraggableHostSelector(c_mapId.value));
const btnTo = computed(() =>
  moduleCornerHostSelector(
    props.position as 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right',
    c_mapId.value,
  ),
);

const bindDrag = computed(() =>
  buildModuleBindPosition({
    position: props.position as
      | 'top-left'
      | 'top-right'
      | 'bottom-left'
      | 'bottom-right',
    btnWidth: props.btnWidth,
    containerId: c_containerId.value,
  }),
);
</script>

// libs/react/map-core/src/modules/ModuleContainer/ModuleContainer.tsx
import {
  buildModuleBindPosition,
  getControlAutoButton,
  isModuleCornerChromeVisible,
  moduleBtnContainerClassName,
  moduleCornerHostSelector,
  moduleDraggableHostSelector,
  type Position,
  queryModuleHostElement,
  subscribeControlAutoButton,
} from '@hungpvq/map-core';
import React, { useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';

import { MapAutoHostButtons } from '../../components/MapAutoHostButtons';
import { useMapContext } from '../../context/MapContext';

export interface ModuleContainerProps {
  mapId?: string;
  dragId?: string;
  btnWidth?: number;
  controlOrder?: number;
  /** Control id → class `{controlId}-btn-module-container` */
  controlId?: string;
  position?: Position;
  controlVisible?: boolean;
  controlLayout?: 'toolbar' | 'standalone' | 'button' | 'menu';
  btn?: React.ReactNode;
  /**
   * Teleported to the same corner host as `btn`, sibling outside
   * `.btn-module-container` (absolute panels pin to the map corner).
   */
  btnOutside?: React.ReactNode;
  draggable?: (bindDrag: BindPosition) => React.ReactNode;
  children?: React.ReactNode;
}

export interface BindPosition {
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
  containerId: string;
}

function useModuleHostElement(selector: string | null): HTMLElement | null {
  const [host, setHost] = useState<HTMLElement | null>(() =>
    selector ? queryModuleHostElement(selector) : null,
  );

  useLayoutEffect(() => {
    if (!selector) {
      setHost(null);
      return;
    }

    const found = queryModuleHostElement(selector);
    if (found) {
      setHost(found);
      return;
    }

    setHost(null);
    if (
      typeof document === 'undefined' ||
      typeof MutationObserver === 'undefined'
    ) {
      return;
    }

    const observer = new MutationObserver(() => {
      const el = queryModuleHostElement(selector);
      if (el) {
        setHost(el);
        observer.disconnect();
      }
    });
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [selector]);

  return host;
}

export function ModuleContainer({
  mapId: propsMapId,
  dragId: propsDragId,
  btnWidth = 40,
  controlOrder = 0,
  controlId = '',
  position = 'bottom-right',
  controlVisible = true,
  controlLayout = 'standalone',
  btn,
  btnOutside,
  draggable,
  children,
}: ModuleContainerProps) {
  const context = useMapContext();
  const mapId = propsMapId || context.mapId;
  const dragId = propsDragId || context.dragId;

  const [autoTick, setAutoTick] = useState(0);
  useEffect(() => {
    return subscribeControlAutoButton((mid, cid) => {
      if (mid === mapId && (cid === controlId || cid === '*')) {
        setAutoTick((t) => t + 1);
      }
    });
  }, [mapId, controlId]);

  const autoEntry = useMemo(() => {
    void autoTick;
    if (btn || !mapId || !controlId) return undefined;
    return getControlAutoButton(mapId, controlId);
  }, [autoTick, btn, mapId, controlId]);

  const autoState = useMemo(() => {
    void autoTick;
    return autoEntry?.getUiState();
  }, [autoTick, autoEntry]);

  const hasBtn = !!btn;
  const hasAutoBtn = !hasBtn && !!autoEntry && autoState != null;
  const hasBtnOutside = !!btnOutside;
  const hasCornerChrome = hasBtn || hasAutoBtn || hasBtnOutside;
  const showCornerChrome = isModuleCornerChromeVisible(controlLayout);
  const hasDraggable = !!draggable;

  const containerId = useMemo(() => dragId, [dragId]);

  const btnSelector = useMemo(
    () => (mapId ? moduleCornerHostSelector(position, mapId) : null),
    [position, mapId],
  );
  const draggableSelector = useMemo(
    () => (mapId ? moduleDraggableHostSelector(mapId) : null),
    [mapId],
  );

  const bindDrag = useMemo<BindPosition>(
    () =>
      buildModuleBindPosition({
        position,
        btnWidth,
        containerId,
      }),
    [containerId, btnWidth, position],
  );

  const needBtnHost =
    controlVisible && hasCornerChrome && showCornerChrome && !!btnSelector;
  const needDragHost = !!containerId && hasDraggable && !!draggableSelector;

  const btnPortalTarget = useModuleHostElement(
    needBtnHost ? btnSelector : null,
  );
  const draggablePortalTarget = useModuleHostElement(
    needDragHost ? draggableSelector : null,
  );

  const btnClassName = moduleBtnContainerClassName(controlId);

  const btnContent = hasBtn ? (
    btn
  ) : hasAutoBtn ? (
    <MapAutoHostButtons
      state={autoState}
      position={position}
      onAction={(...args) => autoEntry?.onAction(...args)}
    />
  ) : null;

  return (
    <div className="module__container">
      {needBtnHost && btnPortalTarget
        ? createPortal(
            <>
              {btnContent ? (
                <div
                  className={btnClassName}
                  style={{ order: controlOrder }}
                  data-map-control-id={controlId || undefined}
                >
                  {btnContent}
                </div>
              ) : null}
              {btnOutside}
            </>,
            btnPortalTarget,
          )
        : null}
      {children}
      {needDragHost && draggablePortalTarget && draggable
        ? createPortal(draggable(bindDrag), draggablePortalTarget)
        : null}
    </div>
  );
}
