// libs/react/map-dataset/src/modules/DatasetControl/DatasetDetail.tsx
import type { MapPopupProps } from '@hungpvq/map-core';
import type { IDataset } from '@hungpvq/map-dataset';
import { traverseTree } from '@hungpvq/map-dataset';
import { DraggableItemPopup } from '@hungpvq/react-draggable';
import {
  ModuleContainer,
  useMap,
  useMapControl,
  useShow,
} from '@hungpvq/react-map-core';

export function DatasetDetail({
  dataset,
  onClose,
  mapId: propsMapId,
  popupProps,
}: {
  dataset: IDataset;
  onClose?: () => void;
  mapId?: string;
  popupProps?: MapPopupProps;
}) {
  const { mapId } = useMap({
    mapId: propsMapId,
    controlId: 'mapDatasetDetail',
  });
  const [show, toggleShow] = useShow(true);
  const { panelBind, moduleContainerProps } = useMapControl(mapId, {
    id: 'mapDatasetDetail',
    panelKind: 'popup',
    title: dataset.getName(),
    from: { popupProps },
    show,
    setShow: (v) => {
      toggleShow(v);
      if (!v) onClose?.();
    },
    actions: [
      {
        type: 'mapDatasetDetail',
        run: () => toggleShow(),
      },
    ],
  });
  const items: { level: number; path: number[]; node: IDataset }[] = [];
  traverseTree(dataset, (node, level, path) => {
    items.push({ node, level, path });
  });

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) => (
        <DraggableItemPopup
          show={show}
          title={dataset.getName()}
          onUpdateShow={(v) => {
            toggleShow(!!v);
            if (!v) onClose?.();
          }}
          width={400}
          height={400}
          {...bind}
          {...panelBind}
        >
          <ul className="dataset-list">
            {items.map((item, index) => (
              <li
                key={index}
                className="dataset-list-item"
                style={{ paddingLeft: `${item.level * 0.5}rem` }}
              >
                <span>{item.path.join('.')}</span>
                <span>({item.node.type})</span>
                <span>{item.node.getName()}</span>
              </li>
            ))}
          </ul>
        </DraggableItemPopup>
      )}
    />
  );
}

// libs/vue/map-dataset/src/modules/DatasetControl/DatasetDetail.vue
<script lang="ts">
export default {
  name: 'detail-dataset-info',
};
</script>

<script setup lang="ts">
import type { MapPopupProps } from '@hungpvq/map-core';
import type { IDataset } from '@hungpvq/map-dataset';
import { traverseTree } from '@hungpvq/map-dataset';
import { DraggableItemPopup } from '@hungpvq/vue-draggable';
import { ModuleContainer, useMap, useMapControl } from '@hungpvq/vue-map-core';
import { ref, shallowRef, watch } from 'vue';
const props = defineProps<{
  dataset: IDataset;
  popupProps?: MapPopupProps;
}>();
const emit = defineEmits(['close']);
const { mapId } = useMap();
const show = ref(true);
function onUpdateShow(val: boolean) {
  show.value = val;
  if (!val) {
    emit('close');
  }
}
const { panelBind, moduleContainerProps } = useMapControl(mapId, {
  id: 'mapDatasetDetail',
  panelKind: 'popup',
  title: () => props.dataset?.getName?.(),
  from: () => ({ popupProps: props.popupProps }),
  show,
  setShow: (value) => {
    show.value = value;
    if (!value) emit('close');
  },
  actions: [
    {
      type: 'mapDatasetDetail',
      run: () => {
        show.value = !show.value;
        if (!show.value) emit('close');
      },
    },
  ],
});
const items = shallowRef<{ level: number; path: number[]; node: IDataset }[]>(
  [],
);
watch(
  () => props.dataset,
  (newVal) => {
    items.value = [];
    traverseTree(newVal, (node, level, path) => {
      items.value.push({
        node,
        level,
        path,
      });
    });
  },
  { immediate: true },
);
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #draggable="slotProps">
      <DraggableItemPopup
        v-bind="{ ...slotProps, ...panelBind }"
        :show="show"
        @update:show="onUpdateShow"
        :title="dataset.getName()"
        :width="400"
        :height="400"
      >
        <ul class="dataset-list">
          <li
            v-for="(item, index) in items"
            :key="index"
            class="dataset-list-item"
            :style="{ paddingLeft: `${item.level * 0.5}rem` }"
          >
            <span>{{ item.path.join('.') }}</span>
            <span>({{ item.node.type }})</span>
            <span>{{ item.node.getName() }}</span>
          </li>
        </ul>
      </DraggableItemPopup>
    </template>
  </ModuleContainer>
</template>
