// libs/react/map-dataset/src/modules/DatasetControl/DatasetControl.tsx
import type { WithMapPropType } from '@hungpvq/map-core';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import type { IDataset } from '@hungpvq/map-dataset';
import {
  createMenuClickAddComponentBuilder,
  createMenuClickBuilder,
  handleMenuActionClick,
  LIST_VIEW_MENU_COMPONENT_KEY,
  LIST_VIEW_MENU_ID,
} from '@hungpvq/map-dataset/menu';
import { DraggableItemSideBar } from '@hungpvq/react-draggable';
import {
  defaultMapProps,
  MapControlButton,
  ModuleContainer,
  useLang,
  useMap,
  useMapControl,
  useShow,
} from '@hungpvq/react-map-core';
import { mdiDatabaseOutline, mdiDelete, mdiInformation } from '@mdi/js';
import { Icon } from '@mdi/react';
import { useEffect, useState } from 'react';

import { useMapDataset } from '../../store/dataset-api';

const ICON_SIZE = 16 / 24;

export function DatasetControl(props: WithMapPropType & { show?: boolean }) {
  const merged = { ...defaultMapProps, ...props };
  const { mapId, order } = useMap(merged);
  const { trans } = useLang(mapId);
  const [show, setShow] = useShow(props.show);
  const { getDatasets, removeDataset, datasetVersion } = useMapDataset(mapId);
  const [views, setViews] = useState<IDataset[]>([]);

  useEffect(() => {
    const next = getDatasets();
    setViews((prev) => {
      if (
        prev.length === next.length &&
        prev.every((view, index) => view === next[index])
      ) {
        return prev;
      }
      return next;
    });
  }, [datasetVersion, mapId, getDatasets]);

  const singleButton = {
    kind: 'single' as const,
    getState: () =>
      mdiButtonState(mdiDatabaseOutline, {
        active: show,
        title: trans('map.dataset-control.title'),
        order,
      }),
    onClick: () => setShow(),
  };

  const { moduleContainerProps, panelPosition, control } = useMapControl(
    mapId,
    {
      id: 'mapDatasetControl',
      panelKind: 'sidebar',
      title: trans('map.dataset-control.title'),
      from: merged,
      order,
      show,
      setShow,
      initialPanelPosition: { location: 'left' },
      actions: [{ type: 'mapDatasetControl', run: () => setShow() }],
      host: { button: singleButton },
      toolbar: singleButton,
    },
  );

  useEffect(() => {
    control.sync();
  }, [show, control]);

  function onShowDetail(view: IDataset) {
    handleMenuActionClick(
      createMenuClickBuilder()
        .addTupleStatic(LIST_VIEW_MENU_ID.addComponent, {
          value: createMenuClickAddComponentBuilder()
            .setComponentKey(LIST_VIEW_MENU_COMPONENT_KEY.datasetDetail)
            .setAttr({ dataset: view })
            .setCheck('detail-dataset')
            .build(),
        })
        .build(),
      { layer: view, mapId, value: view },
    );
  }

  return (
    <ModuleContainer
      {...moduleContainerProps}
      draggable={(bind) => (
        <DraggableItemSideBar
          show={show}
          onUpdateShow={(v) => setShow(!!v)}
          title={trans('map.dataset-control.title')}
          containerId={bind.containerId}
          location={panelPosition.location || 'left'}
        >
          <div className="dataset-control">
            {views.map((view) => (
              <div
                key={view.id}
                className="dataset-item"
              >
                <span className="dataset-item__title">{view.getName()}</span>
                <div className="dataset-item__title-action">
                  <MapControlButton
                    variant="plain"
                    onClick={(e) => {
                      e.stopPropagation();
                      onShowDetail(view);
                    }}
                  >
                    <Icon
                      path={mdiInformation}
                      size={ICON_SIZE}
                    />
                  </MapControlButton>
                  <MapControlButton
                    variant="plain"
                    onClick={(e) => {
                      e.stopPropagation();
                      removeDataset(view);
                    }}
                  >
                    <Icon
                      path={mdiDelete}
                      size={ICON_SIZE}
                    />
                  </MapControlButton>
                </div>
              </div>
            ))}
          </div>
        </DraggableItemSideBar>
      )}
    />
  );
}

// libs/vue/map-dataset/src/modules/DatasetControl/DatasetControl.vue
<script lang="ts">
export default {
  name: 'dataset-control',
};
</script>

<script setup lang="ts">

import { type WithMapPropType } from '@hungpvq/map-core';
import type { IDataset } from '@hungpvq/map-dataset';

import {
  createMenuClickAddComponentBuilder,
  createMenuClickBuilder,
  handleMenuActionClick,
  LIST_VIEW_MENU_COMPONENT_KEY,
  LIST_VIEW_MENU_ID,
} from '@hungpvq/map-dataset/menu';
import { DraggableItemSideBar } from '@hungpvq/vue-draggable';
import {
  defaultMapProps,
  MapCommonButton,
  MapControlButton,
  ModuleContainer,
  useLang,
  useMap,
  useRegisterMapControl,
  useShow,
  useToolbarControl,
  type WithShowProps,
} from '@hungpvq/vue-map-core';

import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import SvgIcon from '@jamescoyle/vue-icon';
import { mdiDatabaseOutline, mdiDelete, mdiInformation } from '@mdi/js';
import { shallowRef, watch } from 'vue';
import { useMapDataset } from '../../store/dataset-api';
const props = withDefaults(defineProps<WithMapPropType & WithShowProps>(), {
  ...defaultMapProps,
});
const { mapId, moduleContainerProps, order } = useMap(props);
const { trans } = useLang(mapId.value);
const path = {
  icon: mdiDatabaseOutline,
  detail: mdiInformation,
  delete: mdiDelete,
};
const [show, setShow] = useShow(props.show);
const { panelPosition } = useRegisterMapControl(mapId, {
  id: 'mapDatasetControl',
  panelKind: 'sidebar',
  title: () => trans.value('map.dataset-control.title'),
  buttonPosition: () => props.position,
  show,
  setShow,
  initialPanelPosition: { location: 'left' },
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
  }),
  actions: [
    {
      type: 'mapDatasetControl',
      run: () => setShow(),
    },
  ],
});
const { getDatasets, removeDataset, datasetVersion } = useMapDataset(mapId);
const views = shallowRef<Array<IDataset>>([]);
function getViewFromStore() {
  views.value = getDatasets();
}
function updateList() {
  getViewFromStore();
}
watch([datasetVersion, mapId], () => updateList(), { immediate: true });
function onShowDetail(view: IDataset) {
  handleMenuActionClick(
    createMenuClickBuilder()
      .addTupleStatic(LIST_VIEW_MENU_ID.addComponent, {
        value: createMenuClickAddComponentBuilder()
          .setComponentKey(LIST_VIEW_MENU_COMPONENT_KEY.datasetDetail)
          .setAttr({
            dataset: view,
          })
          .setCheck('detail-dataset')
          .build(),
      })
      .build(),
    { layer: view, mapId: mapId.value, value: view },
  );
}
function onRemove(view: IDataset) {
  removeDataset(view);
}
defineSlots<{
  item(props: { item: IDataset }): any;
  default(): any;
}>();
const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapDatasetControl',
  getState() {
    return mdiButtonState(path.icon, {
      active: show.value,
      title: trans.value('map.dataset-control.title'),
      order: order.value,
    });
  },
  onClick() {
    setShow();
  },
});
watch(show, () => control.sync());
</script>
<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapCommonButton
        v-if="state"
        :option="state"
        @click.stop="control.onAction"
      >
      </MapCommonButton>
    </template>

    <template #draggable="props">
      <DraggableItemSideBar
        :containerId="props.containerId"
        v-model:show="show"
        :title="trans('map.dataset-control.title')"
        :location="panelPosition.location || 'left'"
      >
        <div class="dataset-control">
          <template v-for="view in views" :key="view.id">
            <slot name="item" :item="view">
              <div class="dataset-item">
                <span class="dataset-item__title">{{ view.getName() }}</span>
                <div class="dataset-item__title-action">
                  <MapControlButton
                    @click.stop="onShowDetail(view)"
                    variant="plain"
                  >
                    <SvgIcon size="16" type="mdi" :path="path.detail" />
                  </MapControlButton>

                  <MapControlButton
                    @click.stop="onRemove(view)"
                    variant="plain"
                  >
                    <SvgIcon size="16" type="mdi" :path="path.delete" />
                  </MapControlButton>
                </div>
              </div>
            </slot>
          </template>
        </div>
      </DraggableItemSideBar>
    </template>
    <slot />
  </ModuleContainer>
</template>
