// libs/vue/draggable/src/components/parts/DragSidebarToggle.vue
<script lang="ts">
export default {
  name: 'DragSidebarToggle',
};
</script>
<script setup lang="ts">
import { useIcon } from '../../hook';

const { SidebarExpandedIcon, SidebarCloseExpandedIcon } = useIcon();
defineProps({
  location: String,
  expand: Boolean,
});
</script>

<template>
  <button type="button">
    <SidebarExpandedIcon v-if="expand" :size="16" />
    <SidebarCloseExpandedIcon v-else :size="16" />
  </button>
</template>

// libs/react/draggable/src/components/parts/DragSidebarToggle.tsx
import { useIcon } from '../../hook';

export interface DragSidebarToggleProps {
  location?: string;
  expand?: boolean;
  onClick?: () => void;
  'aria-controls'?: string;
  'aria-label'?: string;
  'aria-expanded'?: boolean | 'true' | 'false';
  role?: string;
}

export function DragSidebarToggle({
  expand = false,
  onClick,
  ...props
}: DragSidebarToggleProps) {
  const { SidebarExpandedIcon, SidebarCloseExpandedIcon } = useIcon();

  return (
    <button
      type="button"
      onClick={onClick}
      {...props}
    >
      {expand ? (
        <SidebarExpandedIcon size={'16px'} />
      ) : (
        <SidebarCloseExpandedIcon size={'16px'} />
      )}
    </button>
  );
}
