// libs/vue/draggable/src/components/parts/DragHeader.vue
<script lang="ts">
export default {
  name: 'DragHeader',
};
</script>
<script setup lang="ts"></script>

<template>
  <hr class="map-divider" aria-hidden="true" />
  <div class="draggable-header">
    <div class="draggable-header__content">
      <slot name="pre-title"> </slot>
      <div class="draggable-header__title">
        <slot name="title"> </slot>
      </div>
      <div class="map-spacer"></div>
      <slot name="extra-btn"></slot>
    </div>
  </div>
  <hr class="map-divider" aria-hidden="true" />
</template>

// libs/react/draggable/src/components/parts/DragHeader.tsx
import type { ReactNode } from 'react';

export type DragHeaderProps = {
  children?: ReactNode;
  preTitle?: ReactNode;
  title?: ReactNode;
  extraBtn?: ReactNode;
};

function DragHeader({ preTitle, title, extraBtn }: DragHeaderProps) {
  return (
    <>
      <hr className="map-divider" aria-hidden="true" />
      <div className="draggable-header">
        <div className="draggable-header__content">
          {preTitle}
          <div className="draggable-header__title">{title}</div>
          <div className="map-spacer"></div>
          {extraBtn}
        </div>
      </div>
      <hr className="map-divider" aria-hidden="true" />
    </>
  );
}

export { DragHeader };
