// libs/vue/draggable/src/components/parts/MapCard.vue
<template>
  <div
    :style="cardStyle"
    v-bind="$attrs"
    :class="{ 'hungpvq-draggable-card': true, highlight }"
  >
    <div class="card-container">
      <slot />
    </div>
    <div class="card-arrow">
      <div class="card-arrow-top-left"></div>
      <div class="card-arrow-top-right"></div>
      <div class="card-arrow-bottom-left"></div>
      <div class="card-arrow-bottom-right"></div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    height: {},
    width: {},
    highlight: {
      type: Boolean,
      default: false,
    },
  },
  name: 'MapCard',
  data: () => ({}),
  computed: {
    cardStyle() {
      return { height: this.height, width: this.width };
    },
  },
  methods: {},
};
</script>

// libs/react/draggable/src/components/parts/MapCard.tsx
import { useMemo, type HTMLAttributes, type ReactNode } from 'react';

export type MapCardProps = {
  height?: string | number;
  width?: string | number;
  highlight?: boolean;
  children?: ReactNode;
} & HTMLAttributes<HTMLDivElement>;

function MapCard({
  height,
  width,
  highlight = false,
  children,
  className = '',
  style,
  ...props
}: MapCardProps) {
  const cardStyle = useMemo(
    () => ({
      height:
        height !== undefined
          ? typeof height === 'number'
            ? `${height}px`
            : height
          : undefined,
      width:
        width !== undefined
          ? typeof width === 'number'
            ? `${width}px`
            : width
          : undefined,
      ...style,
    }),
    [height, width, style],
  );

  const classes = [
    'hungpvq-draggable-card',
    highlight ? 'highlight' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} style={cardStyle} {...props}>
      <div className="card-container">{children}</div>
      <div className="card-arrow">
        <div className="card-arrow-top-left"></div>
        <div className="card-arrow-top-right"></div>
        <div className="card-arrow-bottom-left"></div>
        <div className="card-arrow-bottom-right"></div>
      </div>
    </div>
  );
}

export { MapCard };
