// libs/react/map-dataset/src/modules/StyleControl/style/label/text-after.tsx
import type { Tab } from '@hungpvq/map-dataset/style';

export function TextAfter({
  value,
  default_value,
  tab,
}: {
  value?: unknown;
  default_value?: unknown;
  tab?: Tab & { unit?: string };
}) {
  return (
    <div>
      {String(value ?? default_value ?? '0')} {tab?.unit || ''}
    </div>
  );
}

// libs/vue/map-dataset/src/modules/StyleControl/style/label/text-after.vue
<template>
  <div>{{ value || default_value || '0' }} {{ tab.unit || '' }}</div>
</template>

<script>
export default {
  props: {
    value: {},
    default_value: {},
    tab: {
      default: () => ({}),
    },
  },
  data: () => ({}),
  computed: {},
  methods: {},
};
</script>

<style scoped></style>
