// libs/react/map-core/src/field/input-choose.tsx
import React from 'react';

export interface ChooseItem<T = unknown> {
  value: T;
  text: string;
}

export interface InputChooseProps<T = unknown> {
  label?: string;
  items: ChooseItem<T>[];
  value?: T;
  onChange?: (value: T) => void;
  className?: string;
}

export function InputChoose<T = unknown>({
  label,
  items,
  value,
  onChange,
  className = '',
}: InputChooseProps<T>) {
  const onSetValue = (item: ChooseItem<T>) => {
    onChange?.(item.value);
  };

  return (
    <div className={`form-group ${className}`.trim()}>
      {label && <label>{label}</label>}
      <div className="input-container">
        {items.map((item) => (
          <div
            key={String(item.value)}
            className={`item-choose ${
              item.value === value ? 'item-choose-active' : ''
            }`}
            onClick={(e) => {
              e.stopPropagation();
              onSetValue(item);
            }}
          >
            {item.text}
          </div>
        ))}
      </div>
    </div>
  );
}

// libs/vue/map-core/src/field/input-choose.vue
<script setup>
const model = defineModel({});
defineProps({
  label: String,
  items: {
    type: Array,
    required: true,
  },
});
function onSetValue(item) {
  model.value = item.value;
}
</script>
<template>
  <div class="form-group">
    <label v-if="label">
      {{ label }}
    </label>
    <div class="input-container">
      <div
        v-for="item in items"
        :key="item.value"
        class="item-choose"
        @click.stop="onSetValue(item)"
        :class="{ 'item-choose-active': item.value === model }"
      >
        {{ item.text }}
      </div>
    </div>
  </div>
</template>
