// libs/react/map-core/src/field/input-text.tsx
import React from 'react';

export interface InputTextProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'value'> {
  label?: string;
  disabled?: boolean;
  value?: string;
  onChange?: (value: string) => void;
}

export function InputText({
  label,
  disabled = false,
  value,
  onChange,
  className = '',
  ...props
}: InputTextProps) {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onChange?.(e.target.value);
  };

  return (
    <div className="form-group">
      {label && <label>{label}</label>}
      <div className="input-container">
        <input
          {...props}
          value={value}
          onChange={handleChange}
          disabled={disabled}
          className={className}
        />
      </div>
    </div>
  );
}

// libs/vue/map-core/src/field/input-text.vue
<script lang="ts">
export default {
  name: 'InputText',
};
</script>
<script setup lang="ts">
const model = defineModel();
defineProps({
  label: String,
  disabled: Boolean,
});
</script>
<template>
  <div class="form-group">
    <label v-if="label">
      {{ label }}
    </label>
    <div class="input-container">
      <input v-bind="$attrs" v-model="model" :disabled="disabled" />
    </div>
  </div>
</template>
