// libs/react/map-core/src/field/input-colorPicker.tsx
import React from 'react';
import { SketchPicker, ColorResult } from 'react-color';
import './input-colorPicker.css';

export interface InputColorPickerProps {
  label?: string;
  disabled?: boolean;
  value?: string;
  onChange?: (value: string) => void;
  onColorChange?: (color: ColorResult) => void;
}

export function InputColorPicker({
  label,
  disabled = false,
  value = '#000000',
  onChange,
  onColorChange,
  className = '',
}: InputColorPickerProps) {
  const onSetValue = (color: ColorResult) => {
    onChange?.(color.hex);
    onColorChange?.(color);
  };

  return (
    <div className="form-group">
      {label && <label>{label}</label>}
      <div className="input-container">
        <SketchPicker color={value} onChange={onSetValue} disabled={disabled} />
      </div>
    </div>
  );
}

// libs/vue/map-core/src/field/input-colorPicker.vue
<template>
  <div class="form-group">
    <label v-if="label">
      {{ label }}
    </label>
    <div class="input-container">
      <Sketch
        :modelValue="form"
        v-bind="$attrs"
        @update:modelValue="onSetValue"
        :disabled="disabled"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Sketch } from '@ckpack/vue-color';
const form = defineModel({ default: '#000000' });
defineProps({
  label: String,
  disabled: Boolean,
});
const emit = defineEmits(['change']);
function onSetValue({ hex }: { hex: string }) {
  form.value = hex;
  emit('change', hex);
}
</script>
