// libs/react/map-core/src/field/input-textarea.tsx
import React from 'react';

export interface InputTextareaProps extends Omit<
  React.TextareaHTMLAttributes<HTMLTextAreaElement>,
  'onChange' | 'value'
> {
  label?: string;
  value?: string;
  onChange?: (value: string) => void;
}

export function InputTextarea({
  label,
  value,
  onChange,
  className = '',
  ...props
}: InputTextareaProps) {
  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(e.target.value);
  };

  return (
    <div className="form-group">
      {label && <label>{label}</label>}
      <div className="input-container">
        <textarea
          {...props}
          value={value}
          onChange={handleChange}
          className={className}
        />
      </div>
    </div>
  );
}

// libs/vue/map-core/src/field/input-textarea.vue
<script setup lang="ts">
const model = defineModel<string>();
defineProps({
  label: String,
});
</script>
<template>
  <div class="form-group">
    <label v-if="label">
      {{ label }}
    </label>
    <div class="input-container">
      <textarea
        v-bind="$attrs"
        v-model="model"
      />
    </div>
  </div>
</template>
