// libs/react/map-dataset/src/modules/Legend/parts/linear-gradient.tsx
export function LayerLegendLinearGradient({
  value,
}: {
  value?: {
    text: string;
    items: { color: string; value: string }[];
  };
}) {
  const item = value || {
    text: '',
    items: [] as { color: string; value: string }[],
  };
  const items = item.items || [];
  const colors = items.map((x) => x.color);
  return (
    <div className="legend-item legend-item--column">
      <div className="legend-text">{item.text}:</div>
      <div className="legend-value-container">
        {items.map((entry, i) => (
          <div className="legend-value" key={i}>
            {entry.value}
          </div>
        ))}
      </div>
      <div>
        <div
          className="legend-item-color"
          style={{
            background: `linear-gradient(to right,${colors.join(',')})`,
          }}
        />
      </div>
    </div>
  );
}

// libs/vue/map-dataset/src/modules/Legend/parts/linear-gradient.vue
<template>
  <div class="legend-item legend-item--column">
    <div class="legend-text">{{ item.text }}:</div>
    <div class="legend-value-container">
      <div
        class="legend-value"
        v-for="(item, i) in items"
        :key="i"
      >
        {{ item.value }}
      </div>
    </div>
    <div>
      <div
        :style="{
          background: `linear-gradient(to right,${colors.join(',')})`,
        }"
        class="legend-item-color"
      ></div>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    value: { type: Object, default: () => ({}) },
  },
  computed: {
    item() {
      return this.value;
    },
    items() {
      return this.value.items || [];
    },
    colors() {
      return this.items.map((x) => x.color);
    },
  },
};
</script>
