// libs/vue/draggable/src/components/ManagementControl/ShowStatusSideBar.vue
<template>
  <div class="mgmt-groups">
    <div
      v-for="(state, side) in filledSides"
      :key="side"
      class="mgmt-group"
    >
      <div class="mgmt-group__title">
        <span>{{ capitalize(side) }}</span>
        <span class="mgmt__count">{{ state.items.length }}</span>
      </div>
      <ItemList
        :items="state.items"
        :show="state.show"
        :containerId="containerId"
      >
        <template #extra="{ item, show }">
          <map-button
            @click.stop="onOpen(item)"
            v-if="!show"
            title="Show"
            aria-label="Show"
          >
            <ShowIcon :size="16" />
          </map-button>
        </template>
      </ItemList>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useIcon } from '../../hook';
import { useDragContainer } from '../../store';
import { LocationSideBar, SidebarConfig } from '../../types';
import MapButton from '../parts/MapButton.vue';
import ItemList from './ItemList.vue';

const props = defineProps<{
  items: Record<LocationSideBar, SidebarConfig>;
  containerId: string;
}>();

const { ShowIcon } = useIcon();
function capitalize(text: string) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}
const filledSides = computed(() => {
  const result = {} as Record<string, SidebarConfig>;
  for (const [side, state] of Object.entries(props.items || {})) {
    if (state?.items?.length) result[side] = state;
  }
  return result;
});
const { getItemAction } = useDragContainer(props.containerId);
function onOpen(id: string) {
  getItemAction(id).open?.();
}
</script>

// libs/react/draggable/src/components/ManagementControl/ShowStatusSideBar.tsx
import { useIcon } from '../../hook';
import { useDragContainer } from '../../store';
import { LocationSideBar, SidebarConfig } from '../../types';
import { MapButton } from '../parts/MapButton';
import { ItemList } from './ItemList';

export interface ShowStatusSideBarProps {
  items: Record<LocationSideBar, SidebarConfig>;
  containerId: string;
}

function capitalize(text: string) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export function ShowStatusSideBar({
  items,
  containerId,
}: ShowStatusSideBarProps) {
  const { ShowIcon } = useIcon();
  const { getItemAction } = useDragContainer(containerId);

  function onOpen(id: string) {
    getItemAction(id)?.open?.();
  }

  const filled = (
    Object.entries(items) as [LocationSideBar, SidebarConfig][]
  ).filter(([, state]) => (state?.items?.length || 0) > 0);

  if (!filled.length) return null;

  return (
    <div className="mgmt-groups">
      {filled.map(([side, state]) => (
        <div key={side} className="mgmt-group">
          <div className="mgmt-group__title">
            <span>{capitalize(side)}</span>
            <span className="mgmt__count">{state.items.length}</span>
          </div>
          <ItemList
            items={state.items}
            show={state.show}
            containerId={containerId}
            renderExtra={(item, show) =>
              !show ? (
                <MapButton onClick={() => onOpen(item)} title="Show" aria-label="Show">
                  <ShowIcon size={16} />
                </MapButton>
              ) : null
            }
          />
        </div>
      ))}
    </div>
  );
}
