// libs/react/map-dataset/src/extra/component/set-opacity.tsx
import type { MapSimple } from '@hungpvq/map-core';
import type { IDataset, IListViewUI, WithSetOpacity } from '@hungpvq/map-dataset';
import { isHasSetOpacity, runAllComponentsWithCheck } from '@hungpvq/map-dataset';
import { useMap } from '@hungpvq/react-map-core';
import { useEffect, useState } from 'react';
import { LayerItemSlider } from './layer-item-slider';
import type { WithLayerItemActionType } from './types';

export function SetOpacity(props: WithLayerItemActionType) {
  const { callMap } = useMap(props);
  const [opacityValue, setOpacityValue] = useState(props.data.opacity ?? 1);

  useEffect(() => {
    const onChange = (e: { opacity: number }) => setOpacityValue(e.opacity);
    props.data.on('changeOpacity', onChange);
    return () => props.data.off('changeOpacity', onChange);
  }, [props.data]);

  function onSetOpacity(view: IListViewUI, opacity: number) {
    const parent = view.getParent() || view;
    callMap((map: MapSimple) => {
      runAllComponentsWithCheck(
        parent,
        (dataset): dataset is IDataset & WithSetOpacity => isHasSetOpacity(dataset),
        [(dataset) => dataset.setOpacity(map, opacity)],
      );
    });
  }

  return (
    <div className="layer-item__opacity">
      <LayerItemSlider
        value={opacityValue}
        min={0}
        max={1}
        step={0.01}
        disabled={props.disabled}
        onChange={(v) => {
          setOpacityValue(v);
          onSetOpacity(props.data, v);
        }}
      />
    </div>
  );
}

// libs/vue/map-dataset/src/extra/component/set-opacity.vue
<template>
  <div class="layer-item__opacity">
    <LayerItemSlider
      v-bind="$attrs"
      :model-value="opacityValue"
      @update:modelValue="onUpdateValue"
    />
  </div>
</template>
<script lang="ts" setup>
import type { MapSimple } from '@hungpvq/map-core';
import type { IDataset } from '@hungpvq/map-dataset';
import {
  isHasSetOpacity,
  runAllComponentsWithCheck,
  WithSetOpacity,
  type IListViewUI,
} from '@hungpvq/map-dataset';
import { useMap } from '@hungpvq/vue-map-core';
import { onMounted, onUnmounted, ref } from 'vue';
import LayerItemSlider from './layer-item-slider.vue';
import type { WithLayerItemActionType } from './types';

const props = defineProps<WithLayerItemActionType>();
const { callMap } = useMap(props);
const opacityValue = ref(props.data.opacity);
function onUpdateValue(opacity: number) {
  opacityValue.value = opacity;
  onSetOpacity(props.data, opacity);
}
function onSetOpacity(view: IListViewUI, opacity: number) {
  const parent = view.getParent() || view;
  callMap((map: MapSimple) => {
    runAllComponentsWithCheck(
      parent,
      (dataset): dataset is IDataset & WithSetOpacity =>
        isHasSetOpacity(dataset),
      [
        (dataset) => {
          dataset.setOpacity(map, opacity);
        },
      ],
    );
  });
}
function updateValue(e: { opacity: number }) {
  const { opacity } = e;
  opacityValue.value = opacity;
}
onMounted(() => {
  props.data.on('changeOpacity', updateValue);
});
onUnmounted(() => {
  props.data.off('changeOpacity', updateValue);
});
</script>
