// libs/react/map-core/src/modules/ThemeControl/ThemeControl.tsx
import { type WithMapPropType, subscribeMapReady } from '@hungpvq/map-core';
import {
  MAP_THEME_COLOR_SCHEME,
  MAP_THEME_MODES,
  THEME_CONTROL_LOCALE,
  applyMapTheme,
  getMapThemeLocaleKey,
  getPrefersDark,
  getStoredMapThemeMode,
  normalizeMapThemeModes,
  resolveMapTheme,
  setStoredMapThemeMode,
  subscribePrefersContrastMore,
  toggleMapThemeLightDark,
  type MapThemeMode,
  type MapThemeScope,
} from '@hungpvq/map-core/theme';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import {
  mdiCircleHalfFull,
  mdiPalette,
  mdiPineTree,
  mdiThemeLightDark,
  mdiWater,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeatherSunset,
} from '@mdi/js';
import { useEffect, useMemo, useState } from 'react';
import { MapCommonButton } from '../../components/MapCommonButton';
import { MapControlGroupButton } from '../../components/MapControlGroupButton';
import { useLang } from '../../extra/lang/hook';
import { useRegisterMapControl } from '../../extra/registry/useRegisterMapControl';
import { useToolbarControl } from '../../extra/toolbar/helper';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import { ModuleContainer } from '../ModuleContainer/ModuleContainer';

const MODE_ICONS: Record<MapThemeMode, string> = {
  auto: mdiThemeLightDark,
  light: mdiWeatherSunny,
  dark: mdiWeatherNight,
  vibrant: mdiPalette,
  ocean: mdiWater,
  forest: mdiPineTree,
  sunset: mdiWeatherSunset,
  slate: mdiCircleHalfFull,
};

export type ThemeControlProps = WithMapPropType & {
  themes?: MapThemeMode[];
  /**
   * `document` (default): `html` + mirror on this map shell (page-wide chrome).
   * `map`: only `.map-container[data-map-id]` + per-map localStorage.
   */
  scope?: MapThemeScope;
};

export function ThemeControl({
  themes,
  scope = 'document',
  ...props
}: ThemeControlProps) {
  const mergedProps = { ...defaultMapProps, ...props };
  const { mapId, moduleContainerProps, order } = useMap({
    ...mergedProps,
    controlId: 'mapThemeControl',
  });
  const { trans, registerLocale } = useLang(mapId);
  const storageOpts = scope === 'map' ? { mapId } : undefined;
  const [mode, setMode] = useState<MapThemeMode>(() =>
    getStoredMapThemeMode('auto', storageOpts),
  );
  const [prefersDark, setPrefersDark] = useState(() => getPrefersDark());

  const themeModes = useMemo(
    () => normalizeMapThemeModes(themes ?? MAP_THEME_MODES),
    [themes],
  );

  const resolved = useMemo(
    () => resolveMapTheme(mode, prefersDark),
    [mode, prefersDark],
  );
  const toggleTarget = useMemo(
    () => toggleMapThemeLightDark(resolved),
    [resolved],
  );
  const toggleIcon =
    MAP_THEME_COLOR_SCHEME[resolved] === 'dark'
      ? mdiWeatherSunny
      : mdiWeatherNight;

  useEffect(() => {
    registerLocale('en', THEME_CONTROL_LOCALE);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    setMode(getStoredMapThemeMode('auto', storageOpts));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scope, mapId]);

  useEffect(() => {
    applyMapTheme(resolveMapTheme(mode, prefersDark), { scope, mapId });
  }, [mode, prefersDark, scope, mapId]);

  useEffect(() => {
    if (scope !== 'map') return;
    return subscribeMapReady(mapId, () => {
      applyMapTheme(resolveMapTheme(mode, prefersDark), { scope, mapId });
    });
  }, [scope, mapId, mode, prefersDark]);

  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    const onChange = (event: MediaQueryListEvent) => {
      setPrefersDark(event.matches);
    };
    setPrefersDark(mediaQuery.matches);
    mediaQuery.addEventListener('change', onChange);
    return () => mediaQuery.removeEventListener('change', onChange);
  }, []);

  useEffect(
    () =>
      subscribePrefersContrastMore(() => {
        applyMapTheme(resolveMapTheme(mode, prefersDark), { scope, mapId });
      }),
    [mode, prefersDark, scope, mapId],
  );

  function applyMode(next: MapThemeMode) {
    setMode(next);
    setStoredMapThemeMode(next, storageOpts);
  }

  function toggleTheme() {
    applyMode(toggleTarget);
  }

  useRegisterMapControl(mapId, {
    id: 'mapThemeControl',
    panelKind: 'button',
    buttonPosition: mergedProps.position,
    getProps: () => ({
      position: mergedProps.position,
      controlLayout: mergedProps.controlLayout,
      themes: themeModes,
      scope,
    }),
    actions: [
      {
        type: 'mapThemeControl',
        run: () => toggleTheme(),
      },
    ],
  });

  const titleKey = getMapThemeLocaleKey(toggleTarget);

  const { state, control } = useToolbarControl(mapId, mergedProps, {
    kind: 'single',
    id: 'mapThemeControl',
    getState: () =>
      mdiButtonState(toggleIcon, {
        visible: true,
        order,
        title: trans(titleKey),
      }),
    onClick: () => toggleTheme(),
  });

  useEffect(() => {
    control.sync();
  }, [mode, prefersDark, toggleIcon, titleKey, control]);

  return (
    <ModuleContainer
      {...moduleContainerProps}
      btn={
        <MapControlGroupButton
          row
          className="map-theme-control-group button-group-hover-expand"
        >
          {state ? (
            <MapCommonButton
              option={state}
              onClick={(e) => {
                e.stopPropagation();
                control.onAction(e);
              }}
            />
          ) : null}
          {themeModes.map((themeId) => (
            <MapCommonButton
              key={themeId}
              option={{
                visible: true,
                active: mode === themeId,
                title: trans(getMapThemeLocaleKey(themeId)),
                icon: { type: 'mdi', path: MODE_ICONS[themeId] },
              }}
              onClick={(e) => {
                e.stopPropagation();
                applyMode(themeId);
              }}
            />
          ))}
        </MapControlGroupButton>
      }
    />
  );
}

// libs/vue/map-core/src/modules/ThemeControl/ThemeControl.vue
<script setup lang="ts">
import { type WithMapPropType, subscribeMapReady } from '@hungpvq/map-core';
import {
  MAP_THEME_COLOR_SCHEME,
  MAP_THEME_MODES,
  THEME_CONTROL_LOCALE,
  applyMapTheme,
  getMapThemeLocaleKey,
  getPrefersDark,
  getStoredMapThemeMode,
  normalizeMapThemeModes,
  resolveMapTheme,
  setStoredMapThemeMode,
  subscribePrefersContrastMore,
  toggleMapThemeLightDark,
  type MapThemeMode,
  type MapThemeScope,
} from '@hungpvq/map-core/theme';
import { mdiButtonState } from '@hungpvq/map-core/toolbar';
import {
  mdiCircleHalfFull,
  mdiPalette,
  mdiPineTree,
  mdiThemeLightDark,
  mdiWater,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeatherSunset,
} from '@mdi/js';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import MapCommonButton from '../../components/MapCommonButton.vue';
import MapControlGroupButton from '../../components/MapControlGroupButton.vue';
import { useLang } from '../../extra/lang/hook';
import { useRegisterMapControl } from '../../extra/registry/useRegisterMapControl';
import { useToolbarControl } from '../../extra/toolbar/helper';
import { defaultMapProps, useMap } from '../../hooks/useMap';
import ModuleContainer from '../ModuleContainer/ModuleContainer.vue';

const MODE_ICONS: Record<MapThemeMode, string> = {
  auto: mdiThemeLightDark,
  light: mdiWeatherSunny,
  dark: mdiWeatherNight,
  vibrant: mdiPalette,
  ocean: mdiWater,
  forest: mdiPineTree,
  sunset: mdiWeatherSunset,
  slate: mdiCircleHalfFull,
};

const props = withDefaults(
  defineProps<
    WithMapPropType & {
      themes?: MapThemeMode[];
      /**
       * `document` (default): `html` + mirror on this map shell (page-wide chrome).
       * `map`: only `.map-container[data-map-id]` + per-map localStorage.
       */
      scope?: MapThemeScope;
    }
  >(),
  {
    ...defaultMapProps,
    themes: () => [...MAP_THEME_MODES],
    scope: 'document',
  },
);

const { mapId, moduleContainerProps, order } = useMap(props);
const { trans, registerLocale } = useLang(mapId.value);
registerLocale('en', THEME_CONTROL_LOCALE);

const storageOpts = computed(() =>
  props.scope === 'map' ? { mapId: mapId.value } : undefined,
);

const mode = ref<MapThemeMode>(
  getStoredMapThemeMode('auto', storageOpts.value),
);
const prefersDark = ref(getPrefersDark());

const themeModes = computed(() => normalizeMapThemeModes(props.themes));

const resolved = computed(() =>
  resolveMapTheme(mode.value, prefersDark.value),
);

const toggleTarget = computed(() => toggleMapThemeLightDark(resolved.value));

const toggleIcon = computed(() =>
  MAP_THEME_COLOR_SCHEME[resolved.value] === 'dark'
    ? mdiWeatherSunny
    : mdiWeatherNight,
);

function applyCurrentTheme() {
  applyMapTheme(resolveMapTheme(mode.value, prefersDark.value), {
    scope: props.scope,
    mapId: mapId.value,
  });
}

function setMode(next: MapThemeMode) {
  mode.value = next;
  setStoredMapThemeMode(next, storageOpts.value);
  applyCurrentTheme();
}

function toggleTheme() {
  setMode(toggleTarget.value);
}

const titleKey = computed(() => getMapThemeLocaleKey(toggleTarget.value));

useRegisterMapControl(mapId, {
  id: 'mapThemeControl',
  panelKind: 'button',
  buttonPosition: () => props.position,
  getProps: () => ({
    position: props.position,
    controlLayout: props.controlLayout,
    themes: themeModes.value,
    scope: props.scope,
  }),
  actions: [
    {
      type: 'mapThemeControl',
      run: () => toggleTheme(),
    },
  ],
});

const { state, control } = useToolbarControl(mapId.value, props, {
  id: 'mapThemeControl',
  getState() {
    return mdiButtonState(toggleIcon.value, {
      visible: true,
      order: order.value,
      title: trans.value(titleKey.value),
    });
  },
  onClick() {
    toggleTheme();
  },
});

watch(mode, () => control.sync());
watch(prefersDark, () => {
  if (mode.value === 'auto') {
    applyCurrentTheme();
    control.sync();
  }
});
watch(toggleIcon, () => control.sync());
watch(
  () => [props.scope, mapId.value] as const,
  () => {
    mode.value = getStoredMapThemeMode('auto', storageOpts.value);
    applyCurrentTheme();
  },
);

let mediaQuery: MediaQueryList | undefined;
let unsubContrast: (() => void) | undefined;
let unsubReady: (() => void) | undefined;
function onMediaChange(event: MediaQueryListEvent) {
  prefersDark.value = event.matches;
}

onMounted(() => {
  applyCurrentTheme();
  if (props.scope === 'map') {
    unsubReady = subscribeMapReady(mapId.value, () => {
      applyCurrentTheme();
    });
  }
  if (typeof window !== 'undefined' && window.matchMedia) {
    mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    prefersDark.value = mediaQuery.matches;
    mediaQuery.addEventListener('change', onMediaChange);
  }
  unsubContrast = subscribePrefersContrastMore(() => {
    applyCurrentTheme();
  });
});

onUnmounted(() => {
  if (mediaQuery) mediaQuery.removeEventListener('change', onMediaChange);
  unsubContrast?.();
  unsubReady?.();
});
</script>

<template>
  <ModuleContainer v-bind="moduleContainerProps">
    <template #btn>
      <MapControlGroupButton
        row
        class="map-theme-control-group button-group-hover-expand"
      >
        <MapCommonButton
          v-if="state"
          :option="state"
          @click.stop="control.onAction"
        />
        <MapCommonButton
          v-for="themeId in themeModes"
          :key="themeId"
          :option="
            mdiButtonState(MODE_ICONS[themeId], {
              visible: true,
              active: mode === themeId,
              title: trans(getMapThemeLocaleKey(themeId)),
            })
          "
          @click.stop="setMode(themeId)"
        />
      </MapControlGroupButton>
    </template>
    <slot />
  </ModuleContainer>
</template>
