// libs/react/draggable/src/components/parts/MapButton.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';

export type MapButtonProps = {
  height?: number;
  width?: number;
  disabled?: boolean;
  children?: ReactNode;
} & ButtonHTMLAttributes<HTMLButtonElement>;

function MapButton({
  height = 32,
  width = 32,
  disabled = false,
  children,
  className = '',
  style,
  ...props
}: MapButtonProps) {
  const bindStyle = {
    width: `${width}px`,
    height: `${height}px`,
    ...style,
  };

  const classes = [
    'hungpvq-draggable-button',
    disabled ? 'hungpvq-draggable-button--disabled' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button
      type="button"
      className={classes}
      style={bindStyle}
      disabled={disabled}
      {...props}
    >
      <span className="hungpvq-draggable-button__content">{children}</span>
    </button>
  );
}

export { MapButton };

// libs/vue/draggable/src/components/parts/MapButton.vue
<template>
  <button
    type="button"
    class="hungpvq-draggable-button"
    v-bind="$attrs"
    :style="bindStyle"
    :class="bindClass"
  >
    <span class="hungpvq-draggable-button__content">
      <slot />
    </span>
  </button>
</template>

<script>
export default {
  name: 'MapButton',
  props: { height: { default: 32 }, width: { default: 32 }, disabled: Boolean },
  computed: {
    bindStyle() {
      return { width: `${this.width}px`, height: `${this.height}px` };
    },
    bindClass() {
      return { 'hungpvq-draggable-button--disabled': this.disabled };
    },
  },
};
</script>
