// libs/react/draggable/src/components/parts/MapSidebarToggle.tsx
import { useIcon } from '../../hook';

export interface MapSidebarToggleProps {
  location?: string;
  expand?: boolean;
  onClick?: () => void;
  'aria-controls'?: string;
  'aria-label'?: string;
  role?: string;
}

export function MapSidebarToggle({
  expand = false,
  onClick,
  ...props
}: MapSidebarToggleProps) {
  const { SidebarExpandedIcon, SidebarCloseExpandedIcon } = useIcon();

  return (
    <button type="button" onClick={onClick} {...props}>
      {expand ? (
        <SidebarExpandedIcon size={'16px'} />
      ) : (
        <SidebarCloseExpandedIcon size={'16px'} />
      )}
    </button>
  );
}

// libs/vue/draggable/src/components/parts/MapSidebarToggle.vue
<script lang="ts">
export default {
  name: 'MapSidebarToggle',
};
</script>
<script setup lang="ts">
import { useIcon } from '../../hook';

const { SidebarExpandedIcon, SidebarCloseExpandedIcon } = useIcon();
defineProps({
  location: String,
  expand: Boolean,
});
</script>

<template>
  <button type="button">
    <SidebarExpandedIcon v-if="expand" :size="16" />
    <SidebarCloseExpandedIcon v-else :size="16" />
  </button>
</template>
