// libs/vue/map-dataset/src/modules/StyleControl/style/field/InputArrayIndex.vue
<template lang="">
  <div v-bind="$attrs" class="input-array-index">
    <div
      class="input-array-item"
      v-for="(arr, index) in items"
      :key="`array_${index}`"
    >
      <span> {{ arr.text }}: </span>
      <InputText
        :modelValue="form[index]"
        :type="arr.type"
        @change="onSetValue(+$event.target.value, index)"
      />
    </div>
  </div>
</template>
<script setup lang="ts">
import { InputText } from '@hungpvq/vue-map-core/fields';
const form = defineModel<number[]>({ default: () => [] });
const emit = defineEmits(['update:modelValue']);

defineProps({
  mapId: {
    type: String,
    required: true,
  },
  items: {
    type: Array,
    required: true,
    default: () => [],
  },
});
function onSetValue(value: number, index: number) {
  form.value[index] = value;
  emit('update:modelValue', form.value);
}
</script>

// libs/react/map-dataset/src/modules/StyleControl/style/field/InputArrayIndex.tsx
import { InputText } from '@hungpvq/react-map-core/fields';

export function InputArrayIndex({
  value = [],
  items = [],
  onChange,
}: {
  value?: number[];
  items?: { text: string; type?: string; value?: number }[];
  onChange?: (value: number[]) => void;
  mapId?: string;
}) {
  const form = value.length ? value : items.map(() => 0);

  function onSetValue(next: number, index: number) {
    const copy = [...form];
    copy[index] = next;
    onChange?.(copy);
  }

  return (
    <div className="input-array-index">
      {items.map((arr, index) => (
        <div
          className="input-array-item"
          key={`array_${index}`}
        >
          <span> {arr.text}: </span>
          <InputText
            value={String(form[index] ?? '')}
            type={arr.type || 'number'}
            onChange={(v) => onSetValue(+v, index)}
          />
        </div>
      ))}
    </div>
  );
}
